{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-ktx",
    "version": "2.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-alpha05.aar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-alpha05.aar",
          "size": 4036,
          "sha512": "58ab720bd5280bc508dfe8e218c2dcda3325e9f8e2efb0ca1940859b2403a3d7f1ec713f774288952faee5fee950b669b47ee6ad2697acd34b68ad2490c645d4",
          "sha256": "f66050049d020300f38a1dc6a833f75f835dc2348f1909913c06403ba43dceef",
          "sha1": "f7b646d821baaaf205ca9835fd0e87418e45ee30",
          "md5": "787f0a1827b3026ce08b8085626c5547"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-alpha05.aar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-alpha05.aar",
          "size": 4036,
          "sha512": "58ab720bd5280bc508dfe8e218c2dcda3325e9f8e2efb0ca1940859b2403a3d7f1ec713f774288952faee5fee950b669b47ee6ad2697acd34b68ad2490c645d4",
          "sha256": "f66050049d020300f38a1dc6a833f75f835dc2348f1909913c06403ba43dceef",
          "sha1": "f7b646d821baaaf205ca9835fd0e87418e45ee30",
          "md5": "787f0a1827b3026ce08b8085626c5547"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-alpha05-sources.jar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-alpha05-sources.jar",
          "size": 1410,
          "sha512": "bfe6372c5910f626e7b41bb6468d62612d1f1bde9b3c767caaa7eb7c07e93cf00d047d8e909b7c47f2985f42ffa554a82888f83e712473cee8756407fcc09548",
          "sha256": "8af8f2ac694742fe8ae133067dfdec6a193a738f46ba80c59b3e8a4ab36703f3",
          "sha1": "a900dc99643d8638beb02bd809a495f772d457e7",
          "md5": "43d89db66da712ab2560a41753632946"
        }
      ]
    }
  ]
}