{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-compose-samples",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-alpha01.aar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-alpha01.aar",
          "size": 10204,
          "sha512": "feeedef1b0cd6c9b79ab5f88de23d184a535cee80fa5a1e8aaf1a0283f567f81f5a353e55a0ac403e7713b2d992d61e3bdb2373f55630a31949c33a52b11ff79",
          "sha256": "06168339242cc54b2eee41c0cb36cfe7eefff5fcfbd6c720b8e291aabbb0eb8f",
          "sha1": "bbfffaa104bffe97b25a68343f824080df1c3864",
          "md5": "8266d11937f2bb69c702f53347690e15"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-alpha01.aar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-alpha01.aar",
          "size": 10204,
          "sha512": "feeedef1b0cd6c9b79ab5f88de23d184a535cee80fa5a1e8aaf1a0283f567f81f5a353e55a0ac403e7713b2d992d61e3bdb2373f55630a31949c33a52b11ff79",
          "sha256": "06168339242cc54b2eee41c0cb36cfe7eefff5fcfbd6c720b8e291aabbb0eb8f",
          "sha1": "bbfffaa104bffe97b25a68343f824080df1c3864",
          "md5": "8266d11937f2bb69c702f53347690e15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-alpha01-sources.jar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-alpha01-sources.jar",
          "size": 1731,
          "sha512": "f32a32a12973855c0eab98d590f8ab6a0043e7640f01f32e0d6d4278252fd89bbbf9cdbfc9674ac086eecde7c1d93a8262e0ee334bbd0e78c2cabf952dd36f52",
          "sha256": "ef6d4ceecbf1088ff696b4a6d673133df23ab41f025fb27f881b62ab43d15d6c",
          "sha1": "9f69512e7023d6927160997f98484e79c8694fc5",
          "md5": "9515fd8b08da901770d198ce6eb0b15a"
        }
      ]
    }
  ]
}