{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.6.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.6.0-alpha03.aar",
          "url": "activity-1.6.0-alpha03.aar",
          "size": 108208,
          "sha512": "71cb95762945d4228b0fba64d1a01f652f46ef549dac14edc00b50365f744fc53592d82f4e93df096533df57cc382f394a61b59408c8597a1fff5d0deaf15131",
          "sha256": "dd1452aa1fe29afe188ec76be19b0f77b4f6387023abf490bb2a83c25df910ba",
          "sha1": "15274f67080aaebabad87ac0f685a47cbaa0f591",
          "md5": "1d237efcdcdebcf587d33cc7c67b9032"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.6.0-alpha03.aar",
          "url": "activity-1.6.0-alpha03.aar",
          "size": 108208,
          "sha512": "71cb95762945d4228b0fba64d1a01f652f46ef549dac14edc00b50365f744fc53592d82f4e93df096533df57cc382f394a61b59408c8597a1fff5d0deaf15131",
          "sha256": "dd1452aa1fe29afe188ec76be19b0f77b4f6387023abf490bb2a83c25df910ba",
          "sha1": "15274f67080aaebabad87ac0f685a47cbaa0f591",
          "md5": "1d237efcdcdebcf587d33cc7c67b9032"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.6.0-alpha03-sources.jar",
          "url": "activity-1.6.0-alpha03-sources.jar",
          "size": 42961,
          "sha512": "a1de15d472e6b15518ab98bc01b78ab9b6815359b08660bb49a3d6e217c39e6b731dcff26aa9a4f7d860c82fb585042d8ff65c2406b1a00cb0f3530a1b926b1b",
          "sha256": "2de6978449dd58c3a2929a7844c2f91c8f98bff207815bf1c61a986c5e98156d",
          "sha1": "8b0d6ef147636e41473bfafb9306ea9432f4f1e0",
          "md5": "5d59c62634f230e9da6ff4052c39a1d4"
        }
      ]
    }
  ]
}