{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.4.0-alpha02.aar",
          "url": "lifecycle-livedata-2.4.0-alpha02.aar",
          "size": 11227,
          "sha512": "8a57002f84bc959018d4ceae1508c7297a11121c1ad35a1d943c1ccc35cc395c95565082d4c1a2eb0e9f02472dc57efcf6147a32b447d24f13cc95320ffb4d80",
          "sha256": "5bdbaeb1eaa70fd4a752e062a6868057d3bbd89112a20b5d449882984b4929af",
          "sha1": "2eb5693f55ddd74dcf6ac570e074e50bab7b070f",
          "md5": "e66076230f198c86f19f0c17699570fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.4.0-alpha02.aar",
          "url": "lifecycle-livedata-2.4.0-alpha02.aar",
          "size": 11227,
          "sha512": "8a57002f84bc959018d4ceae1508c7297a11121c1ad35a1d943c1ccc35cc395c95565082d4c1a2eb0e9f02472dc57efcf6147a32b447d24f13cc95320ffb4d80",
          "sha256": "5bdbaeb1eaa70fd4a752e062a6868057d3bbd89112a20b5d449882984b4929af",
          "sha1": "2eb5693f55ddd74dcf6ac570e074e50bab7b070f",
          "md5": "e66076230f198c86f19f0c17699570fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.4.0-alpha02-sources.jar",
          "url": "lifecycle-livedata-2.4.0-alpha02-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
