{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.5.0-beta01.aar",
          "url": "lifecycle-viewmodel-2.5.0-beta01.aar",
          "size": 34733,
          "sha512": "7c79fe1e71eb273c68c68371fc694c1698c6f6a67fb8a9a7c9a9af9179f4a481d80e404bb8a54a0737727dd390acc4e2cee57037d5c77b77fadc080a0288207f",
          "sha256": "25050dd12973f68bcbb44f706d3a6bdd8c9ffc7dace6664615e59b1f5a37d222",
          "sha1": "b02c3b792d6dc6deb6dec938e90e47bfc8d08202",
          "md5": "bc0a60897129a7319f00315d2065efc3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.5.0-beta01.aar",
          "url": "lifecycle-viewmodel-2.5.0-beta01.aar",
          "size": 34733,
          "sha512": "7c79fe1e71eb273c68c68371fc694c1698c6f6a67fb8a9a7c9a9af9179f4a481d80e404bb8a54a0737727dd390acc4e2cee57037d5c77b77fadc080a0288207f",
          "sha256": "25050dd12973f68bcbb44f706d3a6bdd8c9ffc7dace6664615e59b1f5a37d222",
          "sha1": "b02c3b792d6dc6deb6dec938e90e47bfc8d08202",
          "md5": "bc0a60897129a7319f00315d2065efc3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-2.5.0-beta01-sources.jar",
          "url": "lifecycle-viewmodel-2.5.0-beta01-sources.jar",
          "size": 17218,
          "sha512": "d5732c2880bdeb97a35f567a476e94faca936d492f912827ba8d427d5e4874b7b314f8374f6f9ef74d2fd58ef3f1379aa0b2c1242b80741e9d9ffa02e6b13ad7",
          "sha256": "36f2f1851c2b8368bd5716003e893684bcc368b26df529cd310e0d3b0fa3e2d5",
          "sha1": "5b3fa761abf3169bc953609ea7e5f0c2abb0f6a5",
          "md5": "053cecbaa6b38dc80f3ea8bed0f1ca72"
        }
      ]
    }
  ]
}