{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-ktx",
    "version": "2.5.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.5.0-alpha04.aar",
          "url": "lifecycle-livedata-ktx-2.5.0-alpha04.aar",
          "size": 40776,
          "sha512": "44b368740d9dfe104a49e1777413e0bdb7be58a2a6c6389c696c954985de1cba68bea8c23840749592502de80f7315afe883a86bb3ffc9d4a90f361ea22a7fa6",
          "sha256": "82b514d12e80b5f9b7dc877be9ebf053e71c30c492d6064687deccd7352e4bac",
          "sha1": "dce2a1f4c931ead5bb9d0aa37c9087cf599362ed",
          "md5": "161bee5100a3af618b29d7e04498d1af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.5.0-alpha04.aar",
          "url": "lifecycle-livedata-ktx-2.5.0-alpha04.aar",
          "size": 40776,
          "sha512": "44b368740d9dfe104a49e1777413e0bdb7be58a2a6c6389c696c954985de1cba68bea8c23840749592502de80f7315afe883a86bb3ffc9d4a90f361ea22a7fa6",
          "sha256": "82b514d12e80b5f9b7dc877be9ebf053e71c30c492d6064687deccd7352e4bac",
          "sha1": "dce2a1f4c931ead5bb9d0aa37c9087cf599362ed",
          "md5": "161bee5100a3af618b29d7e04498d1af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.5.0-alpha04-sources.jar",
          "url": "lifecycle-livedata-ktx-2.5.0-alpha04-sources.jar",
          "size": 8725,
          "sha512": "821c6091de18f97dcb9e34631e9fa9f04886992595f01391ffe88a30401bafe2c26d03f6c6514a86d38f722ec3d6448d71275075753e6deb1e7999f63b33d89e",
          "sha256": "93b88aed20951cf9ffdc604ae665414bca0811c069986c339d0d1991861fa956",
          "sha1": "9017d4f6a545e0fd90d4a40bef15b517fa32fbcb",
          "md5": "edf93d3aa22eb5d1ac37890a66fb05a6"
        }
      ]
    }
  ]
}
