{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-compiler",
    "version": "2.6.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.6.0-alpha03.jar",
          "url": "lifecycle-compiler-2.6.0-alpha03.jar",
          "size": 49477,
          "sha512": "f61bafa6f2ec26922ec4f626199c729ee874e67178df5717015803104f1ded81595205df68249c11811e0c8320110f2ac5cc9c0eeb9a9f6d24cd7f39dee0ac7a",
          "sha256": "441ccaa1ac4d897d9bd42397e9629f4e493c1ad14da9c093e72abd6cf1d6e271",
          "sha1": "76bca0984a6f00174c1685bf84d32f0ce0129d13",
          "md5": "7c46ce51b212509716c2c7be8590a892"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha03"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-compiler-2.6.0-alpha03.jar",
          "url": "lifecycle-compiler-2.6.0-alpha03.jar",
          "size": 49477,
          "sha512": "f61bafa6f2ec26922ec4f626199c729ee874e67178df5717015803104f1ded81595205df68249c11811e0c8320110f2ac5cc9c0eeb9a9f6d24cd7f39dee0ac7a",
          "sha256": "441ccaa1ac4d897d9bd42397e9629f4e493c1ad14da9c093e72abd6cf1d6e271",
          "sha1": "76bca0984a6f00174c1685bf84d32f0ce0129d13",
          "md5": "7c46ce51b212509716c2c7be8590a892"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.6.0-alpha03-sources.jar",
          "url": "lifecycle-compiler-2.6.0-alpha03-sources.jar",
          "size": 18983,
          "sha512": "ca17efe01b105646b8c4e6ab80a94aa11e08d9a0294813b4d8b4c237368fe3340f2ead7a1daaaff4311e97e7109a4155e65b308686570d1d2bb6f782fa341cf8",
          "sha256": "cbf9618ee4cb0170a7030bffd2480507261af831552bacd101db3bce319622d2",
          "sha1": "aa8485e5b4ed1777938edf2ff3d96b89ba07c51c",
          "md5": "787146ee536af428776a9fa21a83fa4a"
        }
      ]
    }
  ]
}