{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.5.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha04.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha04.aar",
          "size": 10086,
          "sha512": "8a7f2f340207f3fb766648cc6694ad7de780bde2d30130525cbc60a4d5b8af602de0910351006d0cf29aefc0d5c1544233fb537ec8ca3b1bbd9dea328a38ab99",
          "sha256": "9494830a484e51b01309fb2fb9a292272544ebf6fef2038f4eea9421765f5c8a",
          "sha1": "af92b9d9e28fa0859492d8e88fd2424976cd93a8",
          "md5": "0ffed4d94d839c51cbb7d4064a9ccf50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha04.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha04.aar",
          "size": 10086,
          "sha512": "8a7f2f340207f3fb766648cc6694ad7de780bde2d30130525cbc60a4d5b8af602de0910351006d0cf29aefc0d5c1544233fb537ec8ca3b1bbd9dea328a38ab99",
          "sha256": "9494830a484e51b01309fb2fb9a292272544ebf6fef2038f4eea9421765f5c8a",
          "sha1": "af92b9d9e28fa0859492d8e88fd2424976cd93a8",
          "md5": "0ffed4d94d839c51cbb7d4064a9ccf50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha04-sources.jar",
          "url": "lifecycle-livedata-core-2.5.0-alpha04-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}
