{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.6.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.6.0-alpha04.aar",
          "url": "lifecycle-livedata-2.6.0-alpha04.aar",
          "size": 12466,
          "sha512": "7506f3809f6e5b5a42913fc818f93ed94363b344186dcbfb936951a09cab69a5467005050429e93a6f44dcd7060d580208f176dd7da9c2e3c235784c0b5c7432",
          "sha256": "161b8f47f4b6cee7befb2c13dc5d97343c45506f5a10fb5e4777469243c25941",
          "sha1": "a9dae05104f5179ac466d89552d5a5a1e074d1c6",
          "md5": "e588d1120bb3de8d8b9d8afb2c49f01c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.6.0-alpha04.aar",
          "url": "lifecycle-livedata-2.6.0-alpha04.aar",
          "size": 12466,
          "sha512": "7506f3809f6e5b5a42913fc818f93ed94363b344186dcbfb936951a09cab69a5467005050429e93a6f44dcd7060d580208f176dd7da9c2e3c235784c0b5c7432",
          "sha256": "161b8f47f4b6cee7befb2c13dc5d97343c45506f5a10fb5e4777469243c25941",
          "sha1": "a9dae05104f5179ac466d89552d5a5a1e074d1c6",
          "md5": "e588d1120bb3de8d8b9d8afb2c49f01c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.6.0-alpha04-sources.jar",
          "url": "lifecycle-livedata-2.6.0-alpha04-sources.jar",
          "size": 6759,
          "sha512": "72eaea1780da25282d6e286bcc37f191daead45e09f50ea1f321fee6ab1a8c843c113df4e013d6d8a7d71f4f91ad87ea2d4bcd625c18ea9b56ef93616eaa48c8",
          "sha256": "6bca2d3e9c3764861f120d6201d02964b70ff1c5f0e29988805e7d983690a5b5",
          "sha1": "7dc362e5f2fb149179d8baeaa36a15a7ce0db561",
          "md5": "4f5cb01d85a32a555877de4200fadd72"
        }
      ]
    }
  ]
}