{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha01.aar",
          "url": "lifecycle-service-2.5.0-alpha01.aar",
          "size": 4332,
          "sha512": "2bf265eecf739e01944514e2a7b22849f93f6e15defdcb9d6b78d470e3886880aca57f86734c240c0a2d1e4a3d221c32889afd7d2791ba0502972124c02f38db",
          "sha256": "23623cd313332dd99ddfbb855a1c13650c6c632558035e7f644c574683de9489",
          "sha1": "d490895d72fd33c5cbc69c7401113f610c0c8831",
          "md5": "bce475fa18c02bbc7cb41b73d2556c77"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha01.aar",
          "url": "lifecycle-service-2.5.0-alpha01.aar",
          "size": 4332,
          "sha512": "2bf265eecf739e01944514e2a7b22849f93f6e15defdcb9d6b78d470e3886880aca57f86734c240c0a2d1e4a3d221c32889afd7d2791ba0502972124c02f38db",
          "sha256": "23623cd313332dd99ddfbb855a1c13650c6c632558035e7f644c574683de9489",
          "sha1": "d490895d72fd33c5cbc69c7401113f610c0c8831",
          "md5": "bce475fa18c02bbc7cb41b73d2556c77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha01-sources.jar",
          "url": "lifecycle-service-2.5.0-alpha01-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
