{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-beta01.aar",
          "url": "lifecycle-livedata-core-2.5.0-beta01.aar",
          "size": 10085,
          "sha512": "22a7995187eb6bb23ce6cab34d755df6dd34d0a27f0da4054ba90fc1a802e885129924c8424354edded9844bc9987b10bc544f515e4360fe32ea68383c8a5a98",
          "sha256": "f17709ea27a0d722abdb1fa670e25f8bc369c0b142cc2e7ed5907973740028cb",
          "sha1": "6faac7fc697909b68555669c79a80d95df08a307",
          "md5": "911a43e46b027ea284571570d2d0bb55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-beta01.aar",
          "url": "lifecycle-livedata-core-2.5.0-beta01.aar",
          "size": 10085,
          "sha512": "22a7995187eb6bb23ce6cab34d755df6dd34d0a27f0da4054ba90fc1a802e885129924c8424354edded9844bc9987b10bc544f515e4360fe32ea68383c8a5a98",
          "sha256": "f17709ea27a0d722abdb1fa670e25f8bc369c0b142cc2e7ed5907973740028cb",
          "sha1": "6faac7fc697909b68555669c79a80d95df08a307",
          "md5": "911a43e46b027ea284571570d2d0bb55"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-beta01-sources.jar",
          "url": "lifecycle-livedata-core-2.5.0-beta01-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}