{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220518001855+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.0-alpha05"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-rc01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.6.0-alpha05.aar",
          "url": "activity-ktx-1.6.0-alpha05.aar",
          "size": 31946,
          "sha512": "606c26b4765b9c14295fd4b87958c7b458bb609e79a75b0e092c6ede072d7eec8d95a82f0b6c9c646a2cb762614cb32e6546023b7ed1c59cbe29583e06832520",
          "sha256": "fa99d42f50ceb27c3f405674d5a8e2b7f9fae98d14f61798b16417e4e8343ee6",
          "sha1": "359898d161ab665e80b806de0d9fd2985f77bf3b",
          "md5": "2c1b47ad4e794e3199fc42d06dafa25a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.0-alpha05"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-rc01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.6.0-alpha05.aar",
          "url": "activity-ktx-1.6.0-alpha05.aar",
          "size": 31946,
          "sha512": "606c26b4765b9c14295fd4b87958c7b458bb609e79a75b0e092c6ede072d7eec8d95a82f0b6c9c646a2cb762614cb32e6546023b7ed1c59cbe29583e06832520",
          "sha256": "fa99d42f50ceb27c3f405674d5a8e2b7f9fae98d14f61798b16417e4e8343ee6",
          "sha1": "359898d161ab665e80b806de0d9fd2985f77bf3b",
          "md5": "2c1b47ad4e794e3199fc42d06dafa25a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.6.0-alpha05-sources.jar",
          "url": "activity-ktx-1.6.0-alpha05-sources.jar",
          "size": 7896,
          "sha512": "410bbd1a10f608fdc92ce2597cac6d8e8bc24c7c2a3de296016e04106298d0df3108cc767b661b869d7160403664b806051b2023a4359afa72f5de366d6660ae",
          "sha256": "89dd07b2ecd1e7678fcee8a3cde667ae51f251c88b3bce5ea8298662c118c909",
          "sha1": "919ce22f7ced37bb707da496c1852fa8a30b6571",
          "md5": "2086f53f293836c195e19cf368e671f1"
        }
      ]
    }
  ]
}