{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams",
    "version": "2.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.6.0-alpha05.aar",
          "url": "lifecycle-reactivestreams-2.6.0-alpha05.aar",
          "size": 10622,
          "sha512": "bfabad90580c5fa41ec35335de00469849fbc3be2e6405a9d6e93172b1e4fb3101ef97bd518e638433d120961e1613964ff9bc0e183aa42f0678548066e60bcb",
          "sha256": "4c7150db8ab0225f4dac021428959af35d18487e99c8631486fe0fd6f3fdb51a",
          "sha1": "f68890563ee04fb88b1366598407a95cfd8a54c8",
          "md5": "7c369fa9160b00c704a47b05316d16af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.6.0-alpha05.aar",
          "url": "lifecycle-reactivestreams-2.6.0-alpha05.aar",
          "size": 10622,
          "sha512": "bfabad90580c5fa41ec35335de00469849fbc3be2e6405a9d6e93172b1e4fb3101ef97bd518e638433d120961e1613964ff9bc0e183aa42f0678548066e60bcb",
          "sha256": "4c7150db8ab0225f4dac021428959af35d18487e99c8631486fe0fd6f3fdb51a",
          "sha1": "f68890563ee04fb88b1366598407a95cfd8a54c8",
          "md5": "7c369fa9160b00c704a47b05316d16af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.6.0-alpha05-sources.jar",
          "url": "lifecycle-reactivestreams-2.6.0-alpha05-sources.jar",
          "size": 2983,
          "sha512": "d43b08153b4771c3968ed4cdc55ba889dc68e05cd3fcd2c6fac9d6590467a04d4a31bf4329df12ac4749cbf53ef1e696a8ecc0a75c884bfa5b463c5ab3ad529a",
          "sha256": "7f288db7a573f6d85834a866e7e030dae402f2f3bbc75bec4f25ddb99bb37ca2",
          "sha1": "c5df382970fda2d842f5094c0ac14487f7668da9",
          "md5": "bba20ab9a61ede23fb2f45739cedecae"
        }
      ]
    }
  ]
}