{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-ktx",
    "version": "2.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6860046"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.3.0-beta01.aar",
          "url": "lifecycle-runtime-ktx-2.3.0-beta01.aar",
          "size": 53064,
          "sha512": "b68a36404e50b6c0bb7ec8b2e67c720f498fe38987e1e01a342e454f22ec3c0127028befad7bf7892ec2b4c083ba843dc04d44b5f30c7e7791cde3efa5d4c9d3",
          "sha256": "e3dc8b64f2d98bb97430565b1314ef732e2209a215d02af61a5816b9845b61cf",
          "sha1": "e091d6a45443baded84117c6c6bf05f5bf548a76",
          "md5": "b1352bbc313f3f87ff1a87bdd345feee"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.3.0-beta01.aar",
          "url": "lifecycle-runtime-ktx-2.3.0-beta01.aar",
          "size": 53064,
          "sha512": "b68a36404e50b6c0bb7ec8b2e67c720f498fe38987e1e01a342e454f22ec3c0127028befad7bf7892ec2b4c083ba843dc04d44b5f30c7e7791cde3efa5d4c9d3",
          "sha256": "e3dc8b64f2d98bb97430565b1314ef732e2209a215d02af61a5816b9845b61cf",
          "sha1": "e091d6a45443baded84117c6c6bf05f5bf548a76",
          "md5": "b1352bbc313f3f87ff1a87bdd345feee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.3.0-beta01-sources.jar",
          "url": "lifecycle-runtime-ktx-2.3.0-beta01-sources.jar",
          "size": 10171,
          "sha512": "1080b3c5bdf4f624b5caea16db973f09252ca9245e15d03965b158d2742a86c9d323c7f7453da657dc719a3b1322f5dde16a7db6c0ac91bdc45df1f6d441d928",
          "sha256": "8ca44c6ed51302972bcdbc00e642285b26d91e7632bd472b33b30dda9cd6701f",
          "sha1": "65f30d664378f04a5d789b3c1a6b9cd4d54b04f8",
          "md5": "33bca9a66e03d266444d85877bf37634"
        }
      ]
    }
  ]
}
