{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-ktx",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.6.0-alpha01.aar",
          "url": "lifecycle-livedata-ktx-2.6.0-alpha01.aar",
          "size": 41270,
          "sha512": "31120e1cba098489e83db80c9373b801775244c012a60e72e5aa93e8eab12acde9c81458f0d4fdadfe8f65c0b1b72e7972ccbb7fc6c394fd89c8e9a0f5fed033",
          "sha256": "237bac8b0656ca1d1a39aa021761241552740993383d9fff2408e58436c72a43",
          "sha1": "765d16c7f378e2e93b480fa41e4650177a7f61c2",
          "md5": "9b7f3cf8f3cf2d28aad63cc2e586d4b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.6.0-alpha01.aar",
          "url": "lifecycle-livedata-ktx-2.6.0-alpha01.aar",
          "size": 41270,
          "sha512": "31120e1cba098489e83db80c9373b801775244c012a60e72e5aa93e8eab12acde9c81458f0d4fdadfe8f65c0b1b72e7972ccbb7fc6c394fd89c8e9a0f5fed033",
          "sha256": "237bac8b0656ca1d1a39aa021761241552740993383d9fff2408e58436c72a43",
          "sha1": "765d16c7f378e2e93b480fa41e4650177a7f61c2",
          "md5": "9b7f3cf8f3cf2d28aad63cc2e586d4b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.6.0-alpha01-sources.jar",
          "url": "lifecycle-livedata-ktx-2.6.0-alpha01-sources.jar",
          "size": 8725,
          "sha512": "821c6091de18f97dcb9e34631e9fa9f04886992595f01391ffe88a30401bafe2c26d03f6c6514a86d38f722ec3d6448d71275075753e6deb1e7999f63b33d89e",
          "sha256": "93b88aed20951cf9ffdc604ae665414bca0811c069986c339d0d1991861fa956",
          "sha1": "9017d4f6a545e0fd90d4a40bef15b517fa32fbcb",
          "md5": "edf93d3aa22eb5d1ac37890a66fb05a6"
        }
      ]
    }
  ]
}