{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "2.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.4.0-rc01.aar",
          "url": "lifecycle-viewmodel-compose-2.4.0-rc01.aar",
          "size": 6688,
          "sha512": "73ca83b79942332e2c0a188787c9f6a6513dcb9bbe1395442a71fd60e0f69413095744398bca394739441333904f812edf3da3fc473418381b5f92d011718d45",
          "sha256": "c046693936a3cd1c74feb8c7c08427c981d63a80b5da1d253de32db6a980555f",
          "sha1": "4aa390b790598500b73246c5104a35ef1dd3b5d2",
          "md5": "ac704080694c0dd7df3b4b18039b61cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.4.0-rc01.aar",
          "url": "lifecycle-viewmodel-compose-2.4.0-rc01.aar",
          "size": 6688,
          "sha512": "73ca83b79942332e2c0a188787c9f6a6513dcb9bbe1395442a71fd60e0f69413095744398bca394739441333904f812edf3da3fc473418381b5f92d011718d45",
          "sha256": "c046693936a3cd1c74feb8c7c08427c981d63a80b5da1d253de32db6a980555f",
          "sha1": "4aa390b790598500b73246c5104a35ef1dd3b5d2",
          "md5": "ac704080694c0dd7df3b4b18039b61cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.4.0-rc01-sources.jar",
          "url": "lifecycle-viewmodel-compose-2.4.0-rc01-sources.jar",
          "size": 3092,
          "sha512": "f8b3c8d7c01ef63b5c496edc99325227d3925b6a35bef2d68c84b831100eba76eeeb1664f08e6e7c748923a3921503d690d2bab215e203f9d9f65422fead14fc",
          "sha256": "6608531b0526640b945335b3502a40cfd316fae0cc8d40f24bac787bdc943fcd",
          "sha1": "c9b120561f7ae26405f8a8731d5f1c23190b587d",
          "md5": "6aecbfdf78b3f09f2b4a25d5527f6fe8"
        }
      ]
    }
  ]
}
