{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.5.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha04.aar",
          "url": "lifecycle-service-2.5.0-alpha04.aar",
          "size": 4366,
          "sha512": "660b33a3a5ccb2d857ac48d614c7641a3db1842a25246460d67f3d49fc41171ac64fa22bf35e656f92649c2496bf2fd031a3530d871e390e5f10def5d32d498f",
          "sha256": "d2f3e2842892615661ad72fd3a7a2b73ed8c9d1ab22a34b4bc2117384eb2a2b5",
          "sha1": "c7098a3c11ea56751751c029c5c4f9392bf0a017",
          "md5": "b22afe9c1fbfe97522e8ba069a5d0b17"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha04.aar",
          "url": "lifecycle-service-2.5.0-alpha04.aar",
          "size": 4366,
          "sha512": "660b33a3a5ccb2d857ac48d614c7641a3db1842a25246460d67f3d49fc41171ac64fa22bf35e656f92649c2496bf2fd031a3530d871e390e5f10def5d32d498f",
          "sha256": "d2f3e2842892615661ad72fd3a7a2b73ed8c9d1ab22a34b4bc2117384eb2a2b5",
          "sha1": "c7098a3c11ea56751751c029c5c4f9392bf0a017",
          "md5": "b22afe9c1fbfe97522e8ba069a5d0b17"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha04-sources.jar",
          "url": "lifecycle-service-2.5.0-alpha04-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
