{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-alpha01.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-alpha01.aar",
          "size": 2904,
          "sha512": "96c8234e4b549ffa61a85282ee5ece3f2474c8f8a07b3c92772fa18314804ae5e0ba013084c644625c20f9e7e63ebb2d7cb30d97415c0ced610f6bc1742e2afc",
          "sha256": "818d718ccd6d80bb44ee76a1d75b74fbc9537aee5522d72aa3dccfd7b27aeef7",
          "sha1": "32d8e8c5437e63853b46b72dc935a3850bb1a062",
          "md5": "013247cdf7ac2f8b2b98171ba3eab7ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-alpha01.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-alpha01.aar",
          "size": 2904,
          "sha512": "96c8234e4b549ffa61a85282ee5ece3f2474c8f8a07b3c92772fa18314804ae5e0ba013084c644625c20f9e7e63ebb2d7cb30d97415c0ced610f6bc1742e2afc",
          "sha256": "818d718ccd6d80bb44ee76a1d75b74fbc9537aee5522d72aa3dccfd7b27aeef7",
          "sha1": "32d8e8c5437e63853b46b72dc935a3850bb1a062",
          "md5": "013247cdf7ac2f8b2b98171ba3eab7ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-alpha01-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-alpha01-sources.jar",
          "size": 1261,
          "sha512": "bb0f402ed24247b2fd8e5ecbfec147427d84a8f18bf21cb5857c1fee5746e2a97febac326c894484fe6e86a515fe1bfd05c3b1538eb3f0f1cce712f280a76861",
          "sha256": "c50b9f047a5b5d5ee5d330b3e2dc45f4ae8deca41f607d1d495792c89e731048",
          "sha1": "23c53fd2626cac61baac62c95dec1c49046e0261",
          "md5": "5d68075becef226fa5ce3a00a8721ea7"
        }
      ]
    }
  ]
}
