{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-compiler",
    "version": "2.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.4.0-alpha02.jar",
          "url": "lifecycle-compiler-2.4.0-alpha02.jar",
          "size": 49568,
          "sha512": "a81aee28180ec7c942fd8eabd5863ff2b7aa80319efe5f8e0d463feb4cb2d72bd8c19c6edac7c7d908d94258f3ebe51f0dab18d952ced4925a27559673a4847f",
          "sha256": "86ddd62b38827adaaf24314a8d812aa1c6ac18067caf7330c523bf132426f19b",
          "sha1": "9784d3fdf5763648ded768268251d9c281e8e341",
          "md5": "a799db96d4d3ecc32a5425e786621a47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-compiler-2.4.0-alpha02.jar",
          "url": "lifecycle-compiler-2.4.0-alpha02.jar",
          "size": 49568,
          "sha512": "a81aee28180ec7c942fd8eabd5863ff2b7aa80319efe5f8e0d463feb4cb2d72bd8c19c6edac7c7d908d94258f3ebe51f0dab18d952ced4925a27559673a4847f",
          "sha256": "86ddd62b38827adaaf24314a8d812aa1c6ac18067caf7330c523bf132426f19b",
          "sha1": "9784d3fdf5763648ded768268251d9c281e8e341",
          "md5": "a799db96d4d3ecc32a5425e786621a47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.4.0-alpha02-sources.jar",
          "url": "lifecycle-compiler-2.4.0-alpha02-sources.jar",
          "size": 18945,
          "sha512": "b98b5c854261d05e0a835e6b22e64d4335c47955d6813c565b2c241227e35594f9ffb95d8f108c33863f02fda6004cfa46ffb9d1df2d749a4edac60a50f82bd5",
          "sha256": "6f5dbfbca2596359127a69e76041db82244e364771e7e41bd28d1ef9d6fdcbdd",
          "sha1": "d677635574a41614848015dd8be201db36321879",
          "md5": "838e6095ded0e64250795dfcd49368df"
        }
      ]
    }
  ]
}
