{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate",
    "version": "2.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.5.0-alpha02.aar",
          "url": "lifecycle-viewmodel-savedstate-2.5.0-alpha02.aar",
          "size": 31348,
          "sha512": "3c851f8dddfcc2a04db1b3205f503822375a8600835d91b552bc07a1ec60582528448966eb39fc2a129dc12ffebd6173225b71c4b6df5706564dd7fff57fc860",
          "sha256": "664493f40f407d6d63d639be60030e47f5740074df1d44bc1e061760fa20d16b",
          "sha1": "501680eb480b811205954a346fc053567cb4625b",
          "md5": "07c6499e27e3f0b4f7b002e3bf7ab35f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.5.0-alpha02.aar",
          "url": "lifecycle-viewmodel-savedstate-2.5.0-alpha02.aar",
          "size": 31348,
          "sha512": "3c851f8dddfcc2a04db1b3205f503822375a8600835d91b552bc07a1ec60582528448966eb39fc2a129dc12ffebd6173225b71c4b6df5706564dd7fff57fc860",
          "sha256": "664493f40f407d6d63d639be60030e47f5740074df1d44bc1e061760fa20d16b",
          "sha1": "501680eb480b811205954a346fc053567cb4625b",
          "md5": "07c6499e27e3f0b4f7b002e3bf7ab35f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.5.0-alpha02-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-2.5.0-alpha02-sources.jar",
          "size": 14319,
          "sha512": "443de5ce1319210f1fc1d1f1ab1fc48a1ce450f77e250c94ae574db73ba9a12f5a83bb1da2c6540ab11f62dec746ec500135b8dc33bd3d3452143082cb155c4b",
          "sha256": "ae898ed332b4acaa8fa7be41fa06b83f856b529b6e6e2a85b8cf37820f32a790",
          "sha1": "024a925ed82a45bdc7f20897067d2d7df3e61109",
          "md5": "c9bd950bdb54af9303792c5f0eea7eff"
        }
      ]
    }
  ]
}
