{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7201951"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.3.1.aar",
          "url": "lifecycle-reactivestreams-2.3.1.aar",
          "size": 8531,
          "sha512": "68941903046db50cc7bec89843803b4611ef44cfcdcff0cf9ddf8f29bf3ad2893603f4f8d013e7ae19e9690a4b85d4e31966591d72c5973cbcb7342f59297daa",
          "sha256": "a5600258465fe03a96a5d6891e08cbb5bd8ce8d9af89ed54af9d3d8ccf801bdc",
          "sha1": "05edcc548686b9545212bcde12d969cd6ab6d591",
          "md5": "4a9e625ee7e729de78ad0908fb27dced"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.3.1.aar",
          "url": "lifecycle-reactivestreams-2.3.1.aar",
          "size": 8531,
          "sha512": "68941903046db50cc7bec89843803b4611ef44cfcdcff0cf9ddf8f29bf3ad2893603f4f8d013e7ae19e9690a4b85d4e31966591d72c5973cbcb7342f59297daa",
          "sha256": "a5600258465fe03a96a5d6891e08cbb5bd8ce8d9af89ed54af9d3d8ccf801bdc",
          "sha1": "05edcc548686b9545212bcde12d969cd6ab6d591",
          "md5": "4a9e625ee7e729de78ad0908fb27dced"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.3.1-sources.jar",
          "url": "lifecycle-reactivestreams-2.3.1-sources.jar",
          "size": 3248,
          "sha512": "a6b65d83c8f4d40f76f171140950c3e44745058afe510b3f89b883ae47fe9f1a14c6ab03929077e43c584df3430c28437a32e8d0fba537d5ec6381ff4e6ec7eb",
          "sha256": "25c60c1e6301781e80787118a26d2e3c011187df8356ab427078c18c7e349585",
          "sha1": "31df3402f1e5e287cb5b0e7d9568f100871588f3",
          "md5": "aa8ca57584eb4039b356b2ab8d5a2ae1"
        }
      ]
    }
  ]
}
