{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-ktx",
    "version": "2.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.6.0-alpha05.aar",
          "url": "lifecycle-runtime-ktx-2.6.0-alpha05.aar",
          "size": 82371,
          "sha512": "fdffc8f04b7525ad36cf6b9a754ffbe1daf20b063a2c6c0c685d65716f47fd3f7474e19bae506d70b2ec1bf60d3138e5f40d9cd7d89b76e280458f7b5636ee82",
          "sha256": "3d68b724a669827e03d851f79732ca3a919d9c2485eb2f789d314beb82ba487b",
          "sha1": "32703a55b2c4c1eefe62edc79fe64ffd2447c135",
          "md5": "1114fb8602c40c85bec892f1eb2ed1f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.6.0-alpha05.aar",
          "url": "lifecycle-runtime-ktx-2.6.0-alpha05.aar",
          "size": 82371,
          "sha512": "fdffc8f04b7525ad36cf6b9a754ffbe1daf20b063a2c6c0c685d65716f47fd3f7474e19bae506d70b2ec1bf60d3138e5f40d9cd7d89b76e280458f7b5636ee82",
          "sha256": "3d68b724a669827e03d851f79732ca3a919d9c2485eb2f789d314beb82ba487b",
          "sha1": "32703a55b2c4c1eefe62edc79fe64ffd2447c135",
          "md5": "1114fb8602c40c85bec892f1eb2ed1f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.6.0-alpha05-sources.jar",
          "url": "lifecycle-runtime-ktx-2.6.0-alpha05-sources.jar",
          "size": 15137,
          "sha512": "9abb6768450f9c114b9d30d4b4f49f35c2a9de0ccfb777b2cfb6784f7b0bd0aa03b4df75479cddd16d333af1942b4683bab098cab630f9b308d178b45bfdf97d",
          "sha256": "fcf8b2c8046d5b1a879532c4cf286e4a6047a6eeba505a381053d9e13fa6a30f",
          "sha1": "1692f07132f885b44450431a28d5fbaddd95eb4b",
          "md5": "db49516591017f500764df728fe7433c"
        }
      ]
    }
  ]
}