{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7262094"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-alpha06.aar",
          "url": "activity-1.3.0-alpha06.aar",
          "size": 68060,
          "sha512": "e68f7817a49e10afa00075d573dbdf065498dbf377c2278b6e64bbe4a5b3dc8c86ba30d72401cbff9c71ebc8d57ff716ef728ce150ab28d60a8642166a45c152",
          "sha256": "5e110ae39fc3ee9ecea94c1c86dd936f026dccc91e145e516fd31838777cbce4",
          "sha1": "8a6054b7291282cfdb58fe64654b2172e76b55c3",
          "md5": "30d23c0880b906bea959c27d4bef8992"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-alpha06.aar",
          "url": "activity-1.3.0-alpha06.aar",
          "size": 68060,
          "sha512": "e68f7817a49e10afa00075d573dbdf065498dbf377c2278b6e64bbe4a5b3dc8c86ba30d72401cbff9c71ebc8d57ff716ef728ce150ab28d60a8642166a45c152",
          "sha256": "5e110ae39fc3ee9ecea94c1c86dd936f026dccc91e145e516fd31838777cbce4",
          "sha1": "8a6054b7291282cfdb58fe64654b2172e76b55c3",
          "md5": "30d23c0880b906bea959c27d4bef8992"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.3.0-alpha06-sources.jar",
          "url": "activity-1.3.0-alpha06-sources.jar",
          "size": 35608,
          "sha512": "53d529ca53db82f838aae1c6bb84069e973424350a94cb7602b70e7155281088d39a57564eee4842f97416286f9fc5a76ce058b034bc502eadc7f1ab6d983249",
          "sha256": "0cffd6a421f6c3a172b256dac2a597093b96ac7224157d0c62057610bcd5ba2b",
          "sha1": "8b49edd0e1494eafb504f24514f943fa3937d3bf",
          "md5": "79e13286c89746869b88fa2194bb75b0"
        }
      ]
    }
  ]
}
