{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-ktx",
    "version": "2.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-rc01.aar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-rc01.aar",
          "size": 4029,
          "sha512": "7c4e24afc365622425e43e1f29b7e4308a34a5ee278688787142f66f5edd6c6f6696250f7caf66bfbac06adcfe375ad879f94aff782e5f1b49fac35b85e3c6bd",
          "sha256": "cc80578750d201370b875b33c8ac37f0fa61beafac9f5687f3e8d29ebb79879d",
          "sha1": "8d26b8524eef518d4184c39c097ab0030e1e5dcf",
          "md5": "794088af1cacd1d223f4bd10ffbb829a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-rc01.aar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-rc01.aar",
          "size": 4029,
          "sha512": "7c4e24afc365622425e43e1f29b7e4308a34a5ee278688787142f66f5edd6c6f6696250f7caf66bfbac06adcfe375ad879f94aff782e5f1b49fac35b85e3c6bd",
          "sha256": "cc80578750d201370b875b33c8ac37f0fa61beafac9f5687f3e8d29ebb79879d",
          "sha1": "8d26b8524eef518d4184c39c097ab0030e1e5dcf",
          "md5": "794088af1cacd1d223f4bd10ffbb829a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-rc01-sources.jar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-rc01-sources.jar",
          "size": 1410,
          "sha512": "bfe6372c5910f626e7b41bb6468d62612d1f1bde9b3c767caaa7eb7c07e93cf00d047d8e909b7c47f2985f42ffa554a82888f83e712473cee8756407fcc09548",
          "sha256": "8af8f2ac694742fe8ae133067dfdec6a193a738f46ba80c59b3e8a4ab36703f3",
          "sha1": "a900dc99643d8638beb02bd809a495f772d457e7",
          "md5": "43d89db66da712ab2560a41753632946"
        }
      ]
    }
  ]
}