{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-ktx",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.5.0-beta01.aar",
          "url": "lifecycle-runtime-ktx-2.5.0-beta01.aar",
          "size": 79847,
          "sha512": "ea093234fe9d33b2501525150ef49783c137eed48b7d07afcde03e061eea12e6894e885aa20d0ac3a937e68e2e94c2e353bb8f6c569d0df79cf6ea923a3b2973",
          "sha256": "263384479424ad64004c8d05fa4c61fef1aaba6252472a09a112e2948755aff9",
          "sha1": "3060dd8e6b629ddcc90013c79b7be6b2a77b6465",
          "md5": "45ce8169bf248fce6634c9c9207c98bc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.5.0-beta01.aar",
          "url": "lifecycle-runtime-ktx-2.5.0-beta01.aar",
          "size": 79847,
          "sha512": "ea093234fe9d33b2501525150ef49783c137eed48b7d07afcde03e061eea12e6894e885aa20d0ac3a937e68e2e94c2e353bb8f6c569d0df79cf6ea923a3b2973",
          "sha256": "263384479424ad64004c8d05fa4c61fef1aaba6252472a09a112e2948755aff9",
          "sha1": "3060dd8e6b629ddcc90013c79b7be6b2a77b6465",
          "md5": "45ce8169bf248fce6634c9c9207c98bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.5.0-beta01-sources.jar",
          "url": "lifecycle-runtime-ktx-2.5.0-beta01-sources.jar",
          "size": 14828,
          "sha512": "e970319d029eab328f11c9cf9f263f8aae0b958f2be8a6c6ee5fdc8e785a1ef8caf4de5e5a42e32394437d77605ebfa74d9018acba18287ecf12cdf5da809802",
          "sha256": "9c1d28b751c500263b5d4d81caf6bd541944d91e295df85273b09e7b7d0baed3",
          "sha1": "6d338022f8fa82c24121d5d249fe5daeeb297742",
          "md5": "6bd895cc45fa4ff72bfb62dfa2cc7602"
        }
      ]
    }
  ]
}