{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha05.aar",
          "url": "lifecycle-livedata-2.5.0-alpha05.aar",
          "size": 11471,
          "sha512": "1105b1b37fe6241f9aae0ebb75f10a64abddaec1addc893f17479f972e91129cb9084d414bed97c1b381a2da510ff2b02912e6b83a76023307f5b9992d93d60e",
          "sha256": "bcb80a55e5d61708d156ea8b0927d43adbc4f46781ef61f0bb18833c79bd619a",
          "sha1": "2e46a471992edf9e5707906f86bf44bf4c99358e",
          "md5": "ebf24bfe03430362f495f5451fc2ec71"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha05.aar",
          "url": "lifecycle-livedata-2.5.0-alpha05.aar",
          "size": 11471,
          "sha512": "1105b1b37fe6241f9aae0ebb75f10a64abddaec1addc893f17479f972e91129cb9084d414bed97c1b381a2da510ff2b02912e6b83a76023307f5b9992d93d60e",
          "sha256": "bcb80a55e5d61708d156ea8b0927d43adbc4f46781ef61f0bb18833c79bd619a",
          "sha1": "2e46a471992edf9e5707906f86bf44bf4c99358e",
          "md5": "ebf24bfe03430362f495f5451fc2ec71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha05-sources.jar",
          "url": "lifecycle-livedata-2.5.0-alpha05-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}