{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-process",
    "version": "2.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.4.0-rc01.aar",
          "url": "lifecycle-process-2.4.0-rc01.aar",
          "size": 9003,
          "sha512": "aef40512b2da5fd434da923ba000a7d7d0b0aa4ec4b0651038b17f25acbb9ab4778f1be775c8bc43f9e30ab8d8222a985585d435c44fa5c8619bccdb653b7bba",
          "sha256": "cdccfb7d7b38ac3b52a5b85b1509534f77964f972f293ac40d785fe5db7a9141",
          "sha1": "1ac5226c1f45622b9ba663c6f98747c3fe410763",
          "md5": "9a94db7ee4592d88a42b7dace5140ffa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.4.0-rc01.aar",
          "url": "lifecycle-process-2.4.0-rc01.aar",
          "size": 9003,
          "sha512": "aef40512b2da5fd434da923ba000a7d7d0b0aa4ec4b0651038b17f25acbb9ab4778f1be775c8bc43f9e30ab8d8222a985585d435c44fa5c8619bccdb653b7bba",
          "sha256": "cdccfb7d7b38ac3b52a5b85b1509534f77964f972f293ac40d785fe5db7a9141",
          "sha1": "1ac5226c1f45622b9ba663c6f98747c3fe410763",
          "md5": "9a94db7ee4592d88a42b7dace5140ffa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-process-2.4.0-rc01-sources.jar",
          "url": "lifecycle-process-2.4.0-rc01-sources.jar",
          "size": 5598,
          "sha512": "71e5eea7788ea36a96775d6f5c84c31890b6596879b5a4d5e13fb00334630ba545c87bcb4b3dd2b48b4e23e267b1a2d6db05400ccd0822e6d774fd5971ba7cd5",
          "sha256": "9686b6a4e755a7f834f9ba6dc4913d2ba597576bd755caed9acdf62662980bd8",
          "sha1": "30f942ae82287047dd2dc7410060672ca44c1942",
          "md5": "17160aece18716bf94ce4125b8ba501a"
        }
      ]
    }
  ]
}
