{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7104547"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0.aar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0.aar",
          "size": 2357,
          "sha512": "483f914ec2ade18fce3634a83cfa5a20d485cc586c214c7611a14cbe31b6a409fd2cd63174ffd66a8dcdf59e6c9871adff8fdc9ff5fc986d864a4cbc3650c13a",
          "sha256": "9690588231b05ee2c368a269050c4a8e0448ce6131d31e0c0065d04b2d7a76f1",
          "sha1": "e548da2fb3d5ad7fe70242ed931852008de274fa",
          "md5": "5afa851ce96c3570a772eee41fd595b8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0.aar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0.aar",
          "size": 2357,
          "sha512": "483f914ec2ade18fce3634a83cfa5a20d485cc586c214c7611a14cbe31b6a409fd2cd63174ffd66a8dcdf59e6c9871adff8fdc9ff5fc986d864a4cbc3650c13a",
          "sha256": "9690588231b05ee2c368a269050c4a8e0448ce6131d31e0c0065d04b2d7a76f1",
          "sha1": "e548da2fb3d5ad7fe70242ed931852008de274fa",
          "md5": "5afa851ce96c3570a772eee41fd595b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-sources.jar",
          "size": 1261,
          "sha512": "bb0f402ed24247b2fd8e5ecbfec147427d84a8f18bf21cb5857c1fee5746e2a97febac326c894484fe6e86a515fe1bfd05c3b1538eb3f0f1cce712f280a76861",
          "sha256": "c50b9f047a5b5d5ee5d330b3e2dc45f4ae8deca41f607d1d495792c89e731048",
          "sha1": "23c53fd2626cac61baac62c95dec1c49046e0261",
          "md5": "5d68075becef226fa5ce3a00a8721ea7"
        }
      ]
    }
  ]
}
