{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.3.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-rc02.aar",
          "url": "activity-1.3.0-rc02.aar",
          "size": 70685,
          "sha512": "86259a8710e575ba8eab1a443cea4aae19de9ef712a191bb0cc96d382d992f5328101b59555fa78aedc6a43cf56e65f5919ff9422803d3f23d9b09494189feef",
          "sha256": "9513b5b502804a930c4baefaecec3c11669d4221fc063176c27c12d124fdd0c0",
          "sha1": "9c4d9cf312dc12a112ebc841ebcca40a48d766ff",
          "md5": "c09153b3d87c8355434e9132b1afc940"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-rc02.aar",
          "url": "activity-1.3.0-rc02.aar",
          "size": 70685,
          "sha512": "86259a8710e575ba8eab1a443cea4aae19de9ef712a191bb0cc96d382d992f5328101b59555fa78aedc6a43cf56e65f5919ff9422803d3f23d9b09494189feef",
          "sha256": "9513b5b502804a930c4baefaecec3c11669d4221fc063176c27c12d124fdd0c0",
          "sha1": "9c4d9cf312dc12a112ebc841ebcca40a48d766ff",
          "md5": "c09153b3d87c8355434e9132b1afc940"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.3.0-rc02-sources.jar",
          "url": "activity-1.3.0-rc02-sources.jar",
          "size": 36246,
          "sha512": "78061bf7ade5845cd1788d748f88f1bea4a549dae61dffd671c66779c492bc38c2d8f8cdc0e3db29b78f87d8e32cee40044ff2230b61c2feb189d7d046517efe",
          "sha256": "d7469ea3b7ac2aee586ce36ebc31ab37af10dbb235ddc0b90071190465af251e",
          "sha1": "47b35d483b15e1738de81d26b51ccfc6e2e7b5f8",
          "md5": "a1e27a556fa0408f58894817c3e06d05"
        }
      ]
    }
  ]
}
