{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-rc01.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-rc01.aar",
          "size": 19630,
          "sha512": "ec7089cc5a42a6b3d520e9052d027b6329c201d8e9b7f5acf5ab055509647f2ab1f8c065a88bc5ced6d8f8bc6fac134068fe3bfa520a20933daecd41f47077d7",
          "sha256": "87f3533c32e0f22975934db2b50e85556ce37531d436b324ca0b0697c585a3af",
          "sha1": "44f2b3dacbb4304094d4dd33ed64eb505993d131",
          "md5": "e93638cdd36e812421ad15eb0c541960"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-rc01.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-rc01.aar",
          "size": 19630,
          "sha512": "ec7089cc5a42a6b3d520e9052d027b6329c201d8e9b7f5acf5ab055509647f2ab1f8c065a88bc5ced6d8f8bc6fac134068fe3bfa520a20933daecd41f47077d7",
          "sha256": "87f3533c32e0f22975934db2b50e85556ce37531d436b324ca0b0697c585a3af",
          "sha1": "44f2b3dacbb4304094d4dd33ed64eb505993d131",
          "md5": "e93638cdd36e812421ad15eb0c541960"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-rc01-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-rc01-sources.jar",
          "size": 1631,
          "sha512": "aec27370748b879276405755e63a377e08307bfe2f370687ee18fa5c43cb5e203fe5e3bcc9cda40390c872bf279e96bc2bae2f0a9e2ee631f861b2ad0e54c0ae",
          "sha256": "b7a2a7c66a58440b0ba30c68abe17074836f217123fb6ea728279834641a7c77",
          "sha1": "0ec507705520b7ddccce7da52bbf5abd9ecd1808",
          "md5": "c552138cfc58a3f4d73c8acbb66e4a86"
        }
      ]
    }
  ]
}