{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-ktx",
    "version": "2.3.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7017154"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.3.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.3.0-rc01.aar",
          "url": "lifecycle-livedata-ktx-2.3.0-rc01.aar",
          "size": 39862,
          "sha512": "da70328b16bcfb466e2e9eb32b50a150e68ed9ff5b526cb2c864d00a8abb1ab2a1879a1dfc823abd32971348da54a7a49632388ed51040dcc3e1b7094dc32b9e",
          "sha256": "f259d0951d63082688f4d9dbce01f3e097e8cccc442d4de7ada197f8b35414de",
          "sha1": "b0625e49385f259b4812661e75e19ef177784d93",
          "md5": "b0088de5daba57b690720a00fd6c9d04"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.3.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.3.0-rc01.aar",
          "url": "lifecycle-livedata-ktx-2.3.0-rc01.aar",
          "size": 39862,
          "sha512": "da70328b16bcfb466e2e9eb32b50a150e68ed9ff5b526cb2c864d00a8abb1ab2a1879a1dfc823abd32971348da54a7a49632388ed51040dcc3e1b7094dc32b9e",
          "sha256": "f259d0951d63082688f4d9dbce01f3e097e8cccc442d4de7ada197f8b35414de",
          "sha1": "b0625e49385f259b4812661e75e19ef177784d93",
          "md5": "b0088de5daba57b690720a00fd6c9d04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.3.0-rc01-sources.jar",
          "url": "lifecycle-livedata-ktx-2.3.0-rc01-sources.jar",
          "size": 8580,
          "sha512": "8199d2f1df3ba53fd8c90e2f2b92288803d7bfc289fbce7014cd899d253d567ef2af6c19667814f711aafffcce72a911c45fca413e287a70c6700b83a8fe75ff",
          "sha256": "108c76911f2f7614234456e011a65b8e20d3635a9b3a3a6b896c3fbebdfaed46",
          "sha1": "086ef44d2dab57d278e18eaff5ce09c816685cd1",
          "md5": "9a22cbca7503671ff17c6ec980f0f770"
        }
      ]
    }
  ]
}
