{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6860046"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.3.0-beta01.aar",
          "url": "lifecycle-livedata-core-ktx-2.3.0-beta01.aar",
          "size": 13715,
          "sha512": "e055dfaec69b8b90e22cfeede7743823ad261e5279d415104b75c3485fef15133fa86028b8049163869271c06507987c1abc7a324e77f600612e8e0c4e181d34",
          "sha256": "7abd1e34a76fb75ea06cce779c2db40a6936af2b372fa70b0784a83fbe778f3a",
          "sha1": "aae7b85e43532f42fab99dc1609098066d928683",
          "md5": "1444e452de07a610120fa3f7bdb03af7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.3.0-beta01.aar",
          "url": "lifecycle-livedata-core-ktx-2.3.0-beta01.aar",
          "size": 13715,
          "sha512": "e055dfaec69b8b90e22cfeede7743823ad261e5279d415104b75c3485fef15133fa86028b8049163869271c06507987c1abc7a324e77f600612e8e0c4e181d34",
          "sha256": "7abd1e34a76fb75ea06cce779c2db40a6936af2b372fa70b0784a83fbe778f3a",
          "sha1": "aae7b85e43532f42fab99dc1609098066d928683",
          "md5": "1444e452de07a610120fa3f7bdb03af7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.3.0-beta01-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.3.0-beta01-sources.jar",
          "size": 1626,
          "sha512": "58b54e58debc06935e122a11d3df02a4cd4e57de0bd9e97d6be3e58a61eed2758ab71e1e3bcb646c820450f782ca3b3d5475688e70a0e9fcf4d063ee4bb20a92",
          "sha256": "bed4c43a34850937f741247cdc8e5bd31e8980b702994016c7d42c101caeb8db",
          "sha1": "e5b6db67283a46d4f6ad8bd431f0b8e1933564e0",
          "md5": "734a9975b112d11cf90845f199ee3405"
        }
      ]
    }
  ]
}
