{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose-samples",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.4.1.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.4.1.aar",
          "size": 1761,
          "sha512": "6028d21dff01072f75becd9cd4295452ef3846200516ab7c895c558516df2f32f2af17d4efacf4300bb55855532cf3e354c306a5ee8bbf2cef56d85f970bb056",
          "sha256": "2232409adfe01a5d1d2424545ab7a8eb467a234c02a844f1b09103f52c4e7a6a",
          "sha1": "cd63a74c178f641709edf5685b572185734fa302",
          "md5": "e74e6d6a8e60f914d4a0130a732a1b16"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.4.1.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.4.1.aar",
          "size": 1761,
          "sha512": "6028d21dff01072f75becd9cd4295452ef3846200516ab7c895c558516df2f32f2af17d4efacf4300bb55855532cf3e354c306a5ee8bbf2cef56d85f970bb056",
          "sha256": "2232409adfe01a5d1d2424545ab7a8eb467a234c02a844f1b09103f52c4e7a6a",
          "sha1": "cd63a74c178f641709edf5685b572185734fa302",
          "md5": "e74e6d6a8e60f914d4a0130a732a1b16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.4.1-sources.jar",
          "url": "lifecycle-viewmodel-compose-samples-2.4.1-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
