{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.4.0-alpha03.aar",
          "url": "lifecycle-livedata-core-ktx-2.4.0-alpha03.aar",
          "size": 16271,
          "sha512": "3304e9ce6b332fde65e5aa1645215e52e23a9561b583a6fc86e365373637bb7422d231583ced92152913241da3ebf41c9111d83296f44771f6dd503959307253",
          "sha256": "2c9f5ea20caa15e521c8b9dbb2c64fe77bc53c1a12482a4ed254d8acfe47204c",
          "sha1": "72ffe13c9b5c8411bb62b503f371ed65a6d8d38a",
          "md5": "44ca9e3eac36f443509a41947c0413e5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.4.0-alpha03.aar",
          "url": "lifecycle-livedata-core-ktx-2.4.0-alpha03.aar",
          "size": 16271,
          "sha512": "3304e9ce6b332fde65e5aa1645215e52e23a9561b583a6fc86e365373637bb7422d231583ced92152913241da3ebf41c9111d83296f44771f6dd503959307253",
          "sha256": "2c9f5ea20caa15e521c8b9dbb2c64fe77bc53c1a12482a4ed254d8acfe47204c",
          "sha1": "72ffe13c9b5c8411bb62b503f371ed65a6d8d38a",
          "md5": "44ca9e3eac36f443509a41947c0413e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.4.0-alpha03-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.4.0-alpha03-sources.jar",
          "size": 1631,
          "sha512": "aec27370748b879276405755e63a377e08307bfe2f370687ee18fa5c43cb5e203fe5e3bcc9cda40390c872bf279e96bc2bae2f0a9e2ee631f861b2ad0e54c0ae",
          "sha256": "b7a2a7c66a58440b0ba30c68abe17074836f217123fb6ea728279834641a7c77",
          "sha1": "0ec507705520b7ddccce7da52bbf5abd9ecd1808",
          "md5": "c552138cfc58a3f4d73c8acbb66e4a86"
        }
      ]
    }
  ]
}
