{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-beta01.aar",
          "url": "lifecycle-runtime-2.5.0-beta01.aar",
          "size": 12295,
          "sha512": "87eb2446bedfc301524027570205387d668b71a137b3ae91a62c4efbb4ad5ca831f6690ac0e9de27f337ec81d1f332003c995b4a57ab56905e574953200eb52a",
          "sha256": "e9512fc5facfcdb939617221be80e850b16b7eb53bd703a14afafe4f2c71d378",
          "sha1": "4f0d83a7da2923b6964390616021e58fdbdc0d66",
          "md5": "33ad5441d3782bd95d9e5e4d94e34799"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-beta01.aar",
          "url": "lifecycle-runtime-2.5.0-beta01.aar",
          "size": 12295,
          "sha512": "87eb2446bedfc301524027570205387d668b71a137b3ae91a62c4efbb4ad5ca831f6690ac0e9de27f337ec81d1f332003c995b4a57ab56905e574953200eb52a",
          "sha256": "e9512fc5facfcdb939617221be80e850b16b7eb53bd703a14afafe4f2c71d378",
          "sha1": "4f0d83a7da2923b6964390616021e58fdbdc0d66",
          "md5": "33ad5441d3782bd95d9e5e4d94e34799"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-beta01-sources.jar",
          "url": "lifecycle-runtime-2.5.0-beta01-sources.jar",
          "size": 8970,
          "sha512": "2009c123e8c19a76eb578ab4a999257a8a815e0f576678921cb327ace677502a07c117cd74a3d88e9cc901591f3e993420a60fc7177abe2e3b08532eddb5a4cf",
          "sha256": "7dd944be47d1245d17aae7cc656880f1d91695501955da5256c8659c6964e656",
          "sha1": "0d255b447102736e536a28b97671c6a736c801b7",
          "md5": "bc3ece2ea0121fea9bc2ba8334f1e80e"
        }
      ]
    }
  ]
}