{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-ktx",
    "version": "2.3.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6558100"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.3.0-alpha04.aar",
          "url": "lifecycle-runtime-ktx-2.3.0-alpha04.aar",
          "size": 42513,
          "sha512": "cd636df748177cd6bd325eece7d0a947957e43bfdbd18f09f142d5dbaa9ca286a7091d07e4f5e765cf0879f8f3f95d3f979a8ef966fbcaef5d452822f410b454",
          "sha256": "781aa34eb250b902dddd7e0a8a4bde5e4dbe80404ac3bff7a4b07a6d5146cb24",
          "sha1": "dc65007c22a8471011a3d72b02d694dcd326cd4a",
          "md5": "8f301b97c839d4701d585fa655b4154a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.3.0-alpha04.aar",
          "url": "lifecycle-runtime-ktx-2.3.0-alpha04.aar",
          "size": 42513,
          "sha512": "cd636df748177cd6bd325eece7d0a947957e43bfdbd18f09f142d5dbaa9ca286a7091d07e4f5e765cf0879f8f3f95d3f979a8ef966fbcaef5d452822f410b454",
          "sha256": "781aa34eb250b902dddd7e0a8a4bde5e4dbe80404ac3bff7a4b07a6d5146cb24",
          "sha1": "dc65007c22a8471011a3d72b02d694dcd326cd4a",
          "md5": "8f301b97c839d4701d585fa655b4154a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.3.0-alpha04-sources.jar",
          "url": "lifecycle-runtime-ktx-2.3.0-alpha04-sources.jar",
          "size": 8290,
          "sha512": "d0a232c31e1256a7591a3f179314297d4d25696e5cd9dca926aee0a6c6e47b825f06f3953c5935e9b6b77623ca91331615971df2b7d2fc59a0b802bc5988fca7",
          "sha256": "caf1119a13b148e5b5225e487956104f9832b4919061823e5f1d8a6c8eac3158",
          "sha1": "9ee179ce9a5a85cc9d93ab052bc96464deb452bf",
          "md5": "d6044ccf258952a4a1099ad769b38fd3"
        }
      ]
    }
  ]
}
