{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7104547"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0.aar",
          "url": "lifecycle-runtime-testing-2.3.0.aar",
          "size": 7731,
          "sha512": "710c06508d76de9f03a52aa76fdb039f0d52d163afef37f9c9aba3cfa27cd4d730cd20af779a7fc557d70e2b26586db55f1c9313ecfd999adecc1d09333e3eed",
          "sha256": "104b8cc81b4be7e68f63d16a97b89fb871049d6454868a5a34d4a39a098af628",
          "sha1": "c58493bd41c31e1035e329898a4a6cdad847f9f4",
          "md5": "bd613ac4d2aeefd16d6e6a0f0c92c5e0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0.aar",
          "url": "lifecycle-runtime-testing-2.3.0.aar",
          "size": 7731,
          "sha512": "710c06508d76de9f03a52aa76fdb039f0d52d163afef37f9c9aba3cfa27cd4d730cd20af779a7fc557d70e2b26586db55f1c9313ecfd999adecc1d09333e3eed",
          "sha256": "104b8cc81b4be7e68f63d16a97b89fb871049d6454868a5a34d4a39a098af628",
          "sha1": "c58493bd41c31e1035e329898a4a6cdad847f9f4",
          "md5": "bd613ac4d2aeefd16d6e6a0f0c92c5e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-sources.jar",
          "url": "lifecycle-runtime-testing-2.3.0-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}
