{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-alpha01.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-alpha01.aar",
          "size": 16157,
          "sha512": "dd1d9b04231fffe3defc6c70870e73b958d9248c8a59b27008270d370274c8e7be2c7532f94d8af135fc1f66055c0ed510fa376dc85344b16813b89b779e9a78",
          "sha256": "8fa2d59068f0fda2405c63ceaedaa4d009e6960ab93911850774e2d3b3fdc23d",
          "sha1": "75fd6fb008c9631b40b4735f5e4efa2491b51f0b",
          "md5": "c33e6f191513319416f56c877844b1fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-alpha01.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-alpha01.aar",
          "size": 16157,
          "sha512": "dd1d9b04231fffe3defc6c70870e73b958d9248c8a59b27008270d370274c8e7be2c7532f94d8af135fc1f66055c0ed510fa376dc85344b16813b89b779e9a78",
          "sha256": "8fa2d59068f0fda2405c63ceaedaa4d009e6960ab93911850774e2d3b3fdc23d",
          "sha1": "75fd6fb008c9631b40b4735f5e4efa2491b51f0b",
          "md5": "c33e6f191513319416f56c877844b1fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-alpha01-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-alpha01-sources.jar",
          "size": 1631,
          "sha512": "aec27370748b879276405755e63a377e08307bfe2f370687ee18fa5c43cb5e203fe5e3bcc9cda40390c872bf279e96bc2bae2f0a9e2ee631f861b2ad0e54c0ae",
          "sha256": "b7a2a7c66a58440b0ba30c68abe17074836f217123fb6ea728279834641a7c77",
          "sha1": "0ec507705520b7ddccce7da52bbf5abd9ecd1808",
          "md5": "c552138cfc58a3f4d73c8acbb66e4a86"
        }
      ]
    }
  ]
}
