{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.5.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha04.aar",
          "url": "lifecycle-livedata-2.5.0-alpha04.aar",
          "size": 11472,
          "sha512": "c4f529635dc7b93b22577edda4a044a27b2571551e10e8dd1b4b713d6b2d0b1b93cd962d157ba89a4772de03cca942739051c12815ad33279b028ec93c459dab",
          "sha256": "3718a0e6189da1bb2d8a7cd8e41e765bb42df8be7c9d097d888e19b204e10510",
          "sha1": "2e30fc8c796e344903b7362be7a901fb601fd637",
          "md5": "8a2b467bc077b0e58722160e1e0ddd8d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha04.aar",
          "url": "lifecycle-livedata-2.5.0-alpha04.aar",
          "size": 11472,
          "sha512": "c4f529635dc7b93b22577edda4a044a27b2571551e10e8dd1b4b713d6b2d0b1b93cd962d157ba89a4772de03cca942739051c12815ad33279b028ec93c459dab",
          "sha256": "3718a0e6189da1bb2d8a7cd8e41e765bb42df8be7c9d097d888e19b204e10510",
          "sha1": "2e30fc8c796e344903b7362be7a901fb601fd637",
          "md5": "8a2b467bc077b0e58722160e1e0ddd8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha04-sources.jar",
          "url": "lifecycle-livedata-2.5.0-alpha04-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
