{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-beta01.aar",
          "url": "lifecycle-runtime-testing-2.5.0-beta01.aar",
          "size": 8528,
          "sha512": "6b306ffc1bb889cba87cb3e244a8703f7479fb2ff0f7c0b0ee75c2a22059b2e7323e8bf5c74c3fd46f5cfca2c8b1493d1d95a43197de8e13fbf9a097c1402f88",
          "sha256": "e3abe537a219886a7f6519e06bf29a679d81434c4ffe291b74b25aa2c427b467",
          "sha1": "537936e715c094d1659fcaf05d9cbd1ac14a99e1",
          "md5": "5fd8b9dbd055ea61a79ad165ca79b4cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-beta01.aar",
          "url": "lifecycle-runtime-testing-2.5.0-beta01.aar",
          "size": 8528,
          "sha512": "6b306ffc1bb889cba87cb3e244a8703f7479fb2ff0f7c0b0ee75c2a22059b2e7323e8bf5c74c3fd46f5cfca2c8b1493d1d95a43197de8e13fbf9a097c1402f88",
          "sha256": "e3abe537a219886a7f6519e06bf29a679d81434c4ffe291b74b25aa2c427b467",
          "sha1": "537936e715c094d1659fcaf05d9cbd1ac14a99e1",
          "md5": "5fd8b9dbd055ea61a79ad165ca79b4cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-beta01-sources.jar",
          "url": "lifecycle-runtime-testing-2.5.0-beta01-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}