{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "2.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.4.0-beta01.aar",
          "url": "lifecycle-viewmodel-compose-2.4.0-beta01.aar",
          "size": 6693,
          "sha512": "f9ee01746232e656f128f3d7bae912d55339489b99af05ed402255e73465e78ed5f59102ad7b9a4167ac74774676e6382991398320e93926ad813f69a9d3a85d",
          "sha256": "cec87930b14d95e697faa2c0ee6175ac5aef1203366052240c3b02be4c32e626",
          "sha1": "cbd6429a1b72d540d7f256653da735e1cfee042b",
          "md5": "08e6c9b7360585c0567731e839c53bc0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.4.0-beta01.aar",
          "url": "lifecycle-viewmodel-compose-2.4.0-beta01.aar",
          "size": 6693,
          "sha512": "f9ee01746232e656f128f3d7bae912d55339489b99af05ed402255e73465e78ed5f59102ad7b9a4167ac74774676e6382991398320e93926ad813f69a9d3a85d",
          "sha256": "cec87930b14d95e697faa2c0ee6175ac5aef1203366052240c3b02be4c32e626",
          "sha1": "cbd6429a1b72d540d7f256653da735e1cfee042b",
          "md5": "08e6c9b7360585c0567731e839c53bc0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.4.0-beta01-sources.jar",
          "url": "lifecycle-viewmodel-compose-2.4.0-beta01-sources.jar",
          "size": 3092,
          "sha512": "f8b3c8d7c01ef63b5c496edc99325227d3925b6a35bef2d68c84b831100eba76eeeb1664f08e6e7c748923a3921503d690d2bab215e203f9d9f65422fead14fc",
          "sha256": "6608531b0526640b945335b3502a40cfd316fae0cc8d40f24bac787bdc943fcd",
          "sha1": "c9b120561f7ae26405f8a8731d5f1c23190b587d",
          "md5": "6aecbfdf78b3f09f2b4a25d5527f6fe8"
        }
      ]
    }
  ]
}
