{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.5.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha06.aar",
          "url": "lifecycle-livedata-2.5.0-alpha06.aar",
          "size": 11471,
          "sha512": "b9263b5c82d2f30298f4bc6cae147960cff72b2d6082ac6422bc0aef5f24e590deae9fe5123e6f4fd5627bd4489516aec5cb3545742b9266f4142e6956fcc471",
          "sha256": "832a487fc6b26b50105d718972d6beb541d349825a16af48207f95b8603de631",
          "sha1": "597837a06cf7abc3b2c743453faa6466655cfa11",
          "md5": "e264f164769eee437e3186e0ea26cb85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha06.aar",
          "url": "lifecycle-livedata-2.5.0-alpha06.aar",
          "size": 11471,
          "sha512": "b9263b5c82d2f30298f4bc6cae147960cff72b2d6082ac6422bc0aef5f24e590deae9fe5123e6f4fd5627bd4489516aec5cb3545742b9266f4142e6956fcc471",
          "sha256": "832a487fc6b26b50105d718972d6beb541d349825a16af48207f95b8603de631",
          "sha1": "597837a06cf7abc3b2c743453faa6466655cfa11",
          "md5": "e264f164769eee437e3186e0ea26cb85"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha06-sources.jar",
          "url": "lifecycle-livedata-2.5.0-alpha06-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}