{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-alpha02.aar",
          "url": "lifecycle-runtime-testing-2.5.0-alpha02.aar",
          "size": 8460,
          "sha512": "1d4378b908f3007a929e712ceec3b6fb8bd46065cf5f9bed66db86aab81158eefdfb57486f964bcd62959da8db9717ad6b1e891494c542ea1812e5c60dd1fe23",
          "sha256": "d78bb5a0c089442be90c9e0235bb77585a225a8a6099cea4fddb2ce8a95f243b",
          "sha1": "6e6e91876db475d8444b9b07e20558fd9a9d298c",
          "md5": "e501df72e42d3e8ff9c6d1e733eb2b61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-alpha02.aar",
          "url": "lifecycle-runtime-testing-2.5.0-alpha02.aar",
          "size": 8460,
          "sha512": "1d4378b908f3007a929e712ceec3b6fb8bd46065cf5f9bed66db86aab81158eefdfb57486f964bcd62959da8db9717ad6b1e891494c542ea1812e5c60dd1fe23",
          "sha256": "d78bb5a0c089442be90c9e0235bb77585a225a8a6099cea4fddb2ce8a95f243b",
          "sha1": "6e6e91876db475d8444b9b07e20558fd9a9d298c",
          "md5": "e501df72e42d3e8ff9c6d1e733eb2b61"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-alpha02-sources.jar",
          "url": "lifecycle-runtime-testing-2.5.0-alpha02-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}
