{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-alpha01.aar",
          "url": "activity-1.7.0-alpha01.aar",
          "size": 123684,
          "sha512": "86f302271afc11da9ba46a6197143042c8dee03beb6b1dbf6cb75e2ebfa7f8d549e9e266db5feab2873b0f5fef306b8984e781e69e7d155e2b58c778ac2ad262",
          "sha256": "5868f7027efd6fda4e2642d255b624031d2e010e5f591131939503eede7a7a5c",
          "sha1": "8b65622feda5612822944def5ee3627eab128400",
          "md5": "2f43e72db6fd5610c7b871e0e0481fe6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-alpha01.aar",
          "url": "activity-1.7.0-alpha01.aar",
          "size": 123684,
          "sha512": "86f302271afc11da9ba46a6197143042c8dee03beb6b1dbf6cb75e2ebfa7f8d549e9e266db5feab2873b0f5fef306b8984e781e69e7d155e2b58c778ac2ad262",
          "sha256": "5868f7027efd6fda4e2642d255b624031d2e010e5f591131939503eede7a7a5c",
          "sha1": "8b65622feda5612822944def5ee3627eab128400",
          "md5": "2f43e72db6fd5610c7b871e0e0481fe6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.7.0-alpha01-sources.jar",
          "url": "activity-1.7.0-alpha01-sources.jar",
          "size": 48541,
          "sha512": "6891e02bf0ed331a6e0d245847968eadd6e9d6ca7df3f75e664d0b6c6fc77d24159e6e2853ee12e0aa65f07a607dfa2eefca6cd4b64bc83a4f211a9451cfdbd1",
          "sha256": "d754ee6b2d22b681030f51e89ffa304256098339fc07eb9f49a3cc07b25b69fb",
          "sha1": "6f394ed2a3b27058b7be2d7aad0688e0c7ed4280",
          "md5": "578e0c496dea6b23e5d56abdcaabc2ea"
        }
      ]
    }
  ]
}