{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6684396"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0-alpha06"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.3.0-alpha06.aar",
          "url": "lifecycle-runtime-2.3.0-alpha06.aar",
          "size": 11003,
          "sha512": "d65469a3fa0875d4912a22dc6ff3acb98d9f3ad60f415ce87b0b03abd7c32015c7beb6a057df894a9fca96775e4ac25b2c6aae57990f9cdd14726de3dee837bf",
          "sha256": "2ce6101b99ed6949f6f498c934bc7f97bc51d5b6178910b6c828f42cfae6626a",
          "sha1": "0dc94ff71d91bc1f56bfdc5d5b92348a8b18d075",
          "md5": "f82fed737238bd0365242c488af218d0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0-alpha06"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.3.0-alpha06.aar",
          "url": "lifecycle-runtime-2.3.0-alpha06.aar",
          "size": 11003,
          "sha512": "d65469a3fa0875d4912a22dc6ff3acb98d9f3ad60f415ce87b0b03abd7c32015c7beb6a057df894a9fca96775e4ac25b2c6aae57990f9cdd14726de3dee837bf",
          "sha256": "2ce6101b99ed6949f6f498c934bc7f97bc51d5b6178910b6c828f42cfae6626a",
          "sha1": "0dc94ff71d91bc1f56bfdc5d5b92348a8b18d075",
          "md5": "f82fed737238bd0365242c488af218d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.3.0-alpha06-sources.jar",
          "url": "lifecycle-runtime-2.3.0-alpha06-sources.jar",
          "size": 8929,
          "sha512": "1b9f2e8ae941d37d1ee953fa7b4d75b89f8d85f5424acb696b9e9063adffc7f4a8d7e1233efeefe65be4f99c62900c50f92ef0ed0186f608b776edeaaaec9099",
          "sha256": "d45c7777c4525cf5556299bfa6972aa680b01528b7d72a8d58685f23638cfd10",
          "sha1": "4a0db8c2f295015c179a207de65b3dd06862a00f",
          "md5": "d74c833594b74e708a96d2ceee16001e"
        }
      ]
    }
  ]
}
