{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose-samples",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-beta01.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-beta01.aar",
          "size": 40335,
          "sha512": "87e352d6d639261e779cf2f1c78a2617da743654cf4e63db954c3a131c1888fff6bb4fd05828938bcd8517d21a353439b8384617fb98b9abc556abb295eb5b3f",
          "sha256": "79ecdc4fe6fa15bad358aad3b4216fda67a514df99edf2483a3467b1e44d2462",
          "sha1": "2a29d2c6173a30c8e5484b32a11781e08e5d7c90",
          "md5": "ca583850af912a9af4d2ae78a065064d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-beta01.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-beta01.aar",
          "size": 40335,
          "sha512": "87e352d6d639261e779cf2f1c78a2617da743654cf4e63db954c3a131c1888fff6bb4fd05828938bcd8517d21a353439b8384617fb98b9abc556abb295eb5b3f",
          "sha256": "79ecdc4fe6fa15bad358aad3b4216fda67a514df99edf2483a3467b1e44d2462",
          "sha1": "2a29d2c6173a30c8e5484b32a11781e08e5d7c90",
          "md5": "ca583850af912a9af4d2ae78a065064d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-beta01-sources.jar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-beta01-sources.jar",
          "size": 3379,
          "sha512": "71bc321f7f42099ae8f1e6d341f23b8dcd483ea400203cf5ef629c37b0a2f2f704a334d01d7504f067b911fda251851491a2dd21360e275589d92475428a8ab3",
          "sha256": "448ea500e9b2e4b813f1930f06e0de094c5b9fd3e97a6aa97a9cea6119258058",
          "sha1": "a2098e51c34b521e091cdccaa6e3ba228ebc783a",
          "md5": "01b23ed76ba1fcd2795bea5847ddd553"
        }
      ]
    }
  ]
}