{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.3.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6602655"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha05.aar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha05.aar",
          "size": 7591,
          "sha512": "a272b969d2f3b36d6330bdb4e1a9745218c1a51230d20a5e29f480f536fb753d8bc51f765b7f155e72c5ff591d40160526f4e6cb9ee2581628bebcc7ba51104a",
          "sha256": "840aee35ae7df09585289f06a92eea141ada01a74ba26b73fda21f21b4c862fc",
          "sha1": "79306e2d5a9455160ac42685e272cf694cede332",
          "md5": "912c9963f581a32ed1a2da01089bb511"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha05.aar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha05.aar",
          "size": 7591,
          "sha512": "a272b969d2f3b36d6330bdb4e1a9745218c1a51230d20a5e29f480f536fb753d8bc51f765b7f155e72c5ff591d40160526f4e6cb9ee2581628bebcc7ba51104a",
          "sha256": "840aee35ae7df09585289f06a92eea141ada01a74ba26b73fda21f21b4c862fc",
          "sha1": "79306e2d5a9455160ac42685e272cf694cede332",
          "md5": "912c9963f581a32ed1a2da01089bb511"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha05-sources.jar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha05-sources.jar",
          "size": 1809,
          "sha512": "85d5e06438ec35aaeee972795ee55b315c3bee5bb5bdbeebdf09785dad5c73c003adad00a94e3cee71b820bd3f1df337f3290e8032e48bfb2a007e89badae94b",
          "sha256": "f97e2b220a76e4c873132978c3cf668e66b9e5299f3ae8fa0f647b85d16150d3",
          "sha1": "7952288ebf7757e9238984e4f927aed0ac5c6b6c",
          "md5": "c66286898d7af679c567208f7f42d3f2"
        }
      ]
    }
  ]
}
