{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7201951"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.3.1.aar",
          "url": "lifecycle-service-2.3.1.aar",
          "size": 3833,
          "sha512": "8f1ac2e47d4457449131b65955ccdc0b1738bf858727afad5e3402dec62291a2507866de690253a6d2043c78c6ad479fa8f016c3e34da63fa380acae206df2de",
          "sha256": "1e053bfc0e616e1712cf395573fdc81f7c0a3dfb982263271f7a2dd6d9b125e0",
          "sha1": "205c930239317b5b1628a9677ee53bd44a3434d7",
          "md5": "5a7b5ffc7a1079df200f848fa8ee5e06"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.3.1.aar",
          "url": "lifecycle-service-2.3.1.aar",
          "size": 3833,
          "sha512": "8f1ac2e47d4457449131b65955ccdc0b1738bf858727afad5e3402dec62291a2507866de690253a6d2043c78c6ad479fa8f016c3e34da63fa380acae206df2de",
          "sha256": "1e053bfc0e616e1712cf395573fdc81f7c0a3dfb982263271f7a2dd6d9b125e0",
          "sha1": "205c930239317b5b1628a9677ee53bd44a3434d7",
          "md5": "5a7b5ffc7a1079df200f848fa8ee5e06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.3.1-sources.jar",
          "url": "lifecycle-service-2.3.1-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
