{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7104547"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.3.0.aar",
          "url": "lifecycle-reactivestreams-2.3.0.aar",
          "size": 8531,
          "sha512": "8eb5f408bdf94e880fc54eaa7a81a67b38a016c96a300f02d42b8f3a83ef6392c2986ee8caf0ce117dbf3064b33322e5e99964b006511e6b37f6e71ef01455d8",
          "sha256": "c91cc7d718e9c65dfb1075d4ab16cfafc4ca1c59823673728faa7a8be474d120",
          "sha1": "4ffa471d2d671410e7d11a0b3e29f179806d125c",
          "md5": "6f4a21b6650629ec3523550f54e1407d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.3.0.aar",
          "url": "lifecycle-reactivestreams-2.3.0.aar",
          "size": 8531,
          "sha512": "8eb5f408bdf94e880fc54eaa7a81a67b38a016c96a300f02d42b8f3a83ef6392c2986ee8caf0ce117dbf3064b33322e5e99964b006511e6b37f6e71ef01455d8",
          "sha256": "c91cc7d718e9c65dfb1075d4ab16cfafc4ca1c59823673728faa7a8be474d120",
          "sha1": "4ffa471d2d671410e7d11a0b3e29f179806d125c",
          "md5": "6f4a21b6650629ec3523550f54e1407d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.3.0-sources.jar",
          "url": "lifecycle-reactivestreams-2.3.0-sources.jar",
          "size": 3248,
          "sha512": "a6b65d83c8f4d40f76f171140950c3e44745058afe510b3f89b883ae47fe9f1a14c6ab03929077e43c584df3430c28437a32e8d0fba537d5ec6381ff4e6ec7eb",
          "sha256": "25c60c1e6301781e80787118a26d2e3c011187df8356ab427078c18c7e349585",
          "sha1": "31df3402f1e5e287cb5b0e7d9568f100871588f3",
          "md5": "aa8ca57584eb4039b356b2ab8d5a2ae1"
        }
      ]
    }
  ]
}
