{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.4.0-beta01.aar",
          "url": "lifecycle-livedata-2.4.0-beta01.aar",
          "size": 11004,
          "sha512": "273040ca23e88af17ca644a0fc0598d8e947ac1d4a13ff7a15cc5d72edca1bc0e6c69179db8f8003b8326e4f33382648defce81d66d82a6a85d3ffc746538657",
          "sha256": "9d8f50fdfa59c05ccf601bb27f1063a21d2787f4c9fe33c2b6c20ca81ea162a0",
          "sha1": "1d553907d61deb82380faee47757563a1e6758d3",
          "md5": "00a18e498f9b2dfe404de05ec67bc2be"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.4.0-beta01.aar",
          "url": "lifecycle-livedata-2.4.0-beta01.aar",
          "size": 11004,
          "sha512": "273040ca23e88af17ca644a0fc0598d8e947ac1d4a13ff7a15cc5d72edca1bc0e6c69179db8f8003b8326e4f33382648defce81d66d82a6a85d3ffc746538657",
          "sha256": "9d8f50fdfa59c05ccf601bb27f1063a21d2787f4c9fe33c2b6c20ca81ea162a0",
          "sha1": "1d553907d61deb82380faee47757563a1e6758d3",
          "md5": "00a18e498f9b2dfe404de05ec67bc2be"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.4.0-beta01-sources.jar",
          "url": "lifecycle-livedata-2.4.0-beta01-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
