{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.4.0-alpha02.aar",
          "url": "activity-ktx-1.4.0-alpha02.aar",
          "size": 30006,
          "sha512": "f1a62ab71a5f90fb8e1cd78838e8624ea17ac05ac40e08bd3c0f6f9c71eee293ca3cb713de4fc5efc7dc490bcd3dfbeae27e951a8185a818422635637da637bc",
          "sha256": "8e62c98e5ceb642acc227b8c4a78682b5cee971ca537677c074300f5a02c2f9c",
          "sha1": "c4b7401a4985a3d38f8ada27f22cd2bd28322c5a",
          "md5": "8053c94aa7cc8003075e47954cae1e5d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.4.0-alpha02.aar",
          "url": "activity-ktx-1.4.0-alpha02.aar",
          "size": 30006,
          "sha512": "f1a62ab71a5f90fb8e1cd78838e8624ea17ac05ac40e08bd3c0f6f9c71eee293ca3cb713de4fc5efc7dc490bcd3dfbeae27e951a8185a818422635637da637bc",
          "sha256": "8e62c98e5ceb642acc227b8c4a78682b5cee971ca537677c074300f5a02c2f9c",
          "sha1": "c4b7401a4985a3d38f8ada27f22cd2bd28322c5a",
          "md5": "8053c94aa7cc8003075e47954cae1e5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.4.0-alpha02-sources.jar",
          "url": "activity-ktx-1.4.0-alpha02-sources.jar",
          "size": 7767,
          "sha512": "5d813443ac6d811e43d27cb20da46ca2b00d8ae2b67d7afe0c1d8cc0426401fa3fa3931d18398dbffd4a802b1e7e00015f105fff8d06c3664081807d86ae3122",
          "sha256": "c82f0974410b4442695d84c4504cd93efb45adfce625ea469c8134e8679f0c7a",
          "sha1": "3906b867d26e0c0c6e60215a0925e3d2f0c016e2",
          "md5": "89fc20347b040f6cc077ac6fc9e9ff34"
        }
      ]
    }
  ]
}
