{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-ktx",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-alpha03.aar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-alpha03.aar",
          "size": 4037,
          "sha512": "c40b39c829ac0cdb167097b9784b06d2c4644f444a737ef38de753ff79703ca4b67fd7d97ea252caf4090086cf7b8ef4ac81f1483914b9bd1a88ef44684d04a5",
          "sha256": "089ef74e0ee70f84ae96cbe402c6f5af0f5cbfbbf436681888b82e4645286943",
          "sha1": "f220348ab2f2a02b77df86c9318104b65d3bcf83",
          "md5": "e9494e82a54b693e7c6af2bf725fcb3f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-alpha03.aar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-alpha03.aar",
          "size": 4037,
          "sha512": "c40b39c829ac0cdb167097b9784b06d2c4644f444a737ef38de753ff79703ca4b67fd7d97ea252caf4090086cf7b8ef4ac81f1483914b9bd1a88ef44684d04a5",
          "sha256": "089ef74e0ee70f84ae96cbe402c6f5af0f5cbfbbf436681888b82e4645286943",
          "sha1": "f220348ab2f2a02b77df86c9318104b65d3bcf83",
          "md5": "e9494e82a54b693e7c6af2bf725fcb3f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-alpha03-sources.jar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-alpha03-sources.jar",
          "size": 1410,
          "sha512": "bfe6372c5910f626e7b41bb6468d62612d1f1bde9b3c767caaa7eb7c07e93cf00d047d8e909b7c47f2985f42ffa554a82888f83e712473cee8756407fcc09548",
          "sha256": "8af8f2ac694742fe8ae133067dfdec6a193a738f46ba80c59b3e8a4ab36703f3",
          "sha1": "a900dc99643d8638beb02bd809a495f772d457e7",
          "md5": "43d89db66da712ab2560a41753632946"
        }
      ]
    }
  ]
}
