{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "2.5.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-rc02.aar",
          "url": "lifecycle-viewmodel-compose-2.5.0-rc02.aar",
          "size": 20844,
          "sha512": "4df6055d41a31f2eca79e81cbde11562c65ab2946bc338ff504dc79adee575d9652d4262391b5f17b6e2320891fc1f00dcdb1e3257595e71afe7c87b81b2dcda",
          "sha256": "c5f8e1f536b06dec5378bf229c8b0d0fd722ee202787fa95a7b28c79c2905ad0",
          "sha1": "d1cd6bd282d6e6c6ba36ef98a16c100fdcc30021",
          "md5": "7b6c4126026c2f657aa9db641a198950"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-rc02.aar",
          "url": "lifecycle-viewmodel-compose-2.5.0-rc02.aar",
          "size": 20844,
          "sha512": "4df6055d41a31f2eca79e81cbde11562c65ab2946bc338ff504dc79adee575d9652d4262391b5f17b6e2320891fc1f00dcdb1e3257595e71afe7c87b81b2dcda",
          "sha256": "c5f8e1f536b06dec5378bf229c8b0d0fd722ee202787fa95a7b28c79c2905ad0",
          "sha1": "d1cd6bd282d6e6c6ba36ef98a16c100fdcc30021",
          "md5": "7b6c4126026c2f657aa9db641a198950"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-rc02-sources.jar",
          "url": "lifecycle-viewmodel-compose-2.5.0-rc02-sources.jar",
          "size": 6399,
          "sha512": "6ba6428c10ae6dd2e1c3c9f50488ba88d24b2ba59efff1d63a0283a2536d33e0a029209190e1c479ddbe4d9da96c3ff786f6f416bffb53b0d784b800d699dc81",
          "sha256": "bf6ed5adb2c598650ef2637b0829bcac911a8ef3f068680b47337bbf20d33865",
          "sha1": "7a6970be52a10accf604976a4ba7acf5b2459525",
          "md5": "bf77e633e58e57d9bd5d5ee8dc3dd3b8"
        }
      ]
    }
  ]
}