{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7184376"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-1.0.0-alpha03.aar",
          "url": "lifecycle-viewmodel-compose-1.0.0-alpha03.aar",
          "size": 7973,
          "sha512": "6e0473d7cafe5dbd9739928fafa8c322f7d1df0601e108a9fd3d237f361126dc12c7f0572dbfd40e641489ae1edf450b69b956a5437f7f51f42e4b82c37089ef",
          "sha256": "a7d85bb39e82d111ae6c5c5382c3d8f2045b42917e83fc324c34ef38a9885500",
          "sha1": "2ef2e7d161b1f3749342fdd934386079187f2035",
          "md5": "89163dd2c17ecd4d9253d1e9358d0a52"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-1.0.0-alpha03.aar",
          "url": "lifecycle-viewmodel-compose-1.0.0-alpha03.aar",
          "size": 7973,
          "sha512": "6e0473d7cafe5dbd9739928fafa8c322f7d1df0601e108a9fd3d237f361126dc12c7f0572dbfd40e641489ae1edf450b69b956a5437f7f51f42e4b82c37089ef",
          "sha256": "a7d85bb39e82d111ae6c5c5382c3d8f2045b42917e83fc324c34ef38a9885500",
          "sha1": "2ef2e7d161b1f3749342fdd934386079187f2035",
          "md5": "89163dd2c17ecd4d9253d1e9358d0a52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-1.0.0-alpha03-sources.jar",
          "url": "lifecycle-viewmodel-compose-1.0.0-alpha03-sources.jar",
          "size": 2916,
          "sha512": "6da7c39492afbbdc4a878e2f812d714582d95036ec80c45640236f87aab3eb5eaa96423107c04bb0ce96d461fd3653f07dafb353ec9c1911b9c8527ee3b9ee77",
          "sha256": "c683ca62862124133f170c4add1488faf07f9958257659e7cbf0cd0040ebba79",
          "sha1": "04b95044c2925265d7acf1fb092919497e530a36",
          "md5": "3637b5d0853181d4a2e8ecf5c069bfb8"
        }
      ]
    }
  ]
}
