{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.4.0-beta01.aar",
          "url": "lifecycle-livedata-core-ktx-2.4.0-beta01.aar",
          "size": 16240,
          "sha512": "ecaed4ca2d41d1390ed7ce6fb52715bf89dddd265edcd23c97869ac6e743b3fdeb6933f8819c87e1d4480111b8bf3b3be35deff7d4cf3919e708d07352e15b29",
          "sha256": "33190a119cc69bc41cbeb35334b6a864c1d9baebe4199a7ff91ffb1f9d327268",
          "sha1": "726bf26068f5a9f2de15949e6dd2aca32a88bde4",
          "md5": "37b680c8708361238b9c423cb20ce6cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.4.0-beta01.aar",
          "url": "lifecycle-livedata-core-ktx-2.4.0-beta01.aar",
          "size": 16240,
          "sha512": "ecaed4ca2d41d1390ed7ce6fb52715bf89dddd265edcd23c97869ac6e743b3fdeb6933f8819c87e1d4480111b8bf3b3be35deff7d4cf3919e708d07352e15b29",
          "sha256": "33190a119cc69bc41cbeb35334b6a864c1d9baebe4199a7ff91ffb1f9d327268",
          "sha1": "726bf26068f5a9f2de15949e6dd2aca32a88bde4",
          "md5": "37b680c8708361238b9c423cb20ce6cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.4.0-beta01-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.4.0-beta01-sources.jar",
          "size": 1631,
          "sha512": "aec27370748b879276405755e63a377e08307bfe2f370687ee18fa5c43cb5e203fe5e3bcc9cda40390c872bf279e96bc2bae2f0a9e2ee631f861b2ad0e54c0ae",
          "sha256": "b7a2a7c66a58440b0ba30c68abe17074836f217123fb6ea728279834641a7c77",
          "sha1": "0ec507705520b7ddccce7da52bbf5abd9ecd1808",
          "md5": "c552138cfc58a3f4d73c8acbb66e4a86"
        }
      ]
    }
  ]
}
