{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-ktx",
    "version": "2.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.4.0-alpha02.aar",
          "url": "lifecycle-runtime-ktx-2.4.0-alpha02.aar",
          "size": 75833,
          "sha512": "2d0dc0cd0421a347fe8362e270219242219441b72cd8c15a5ed3e1cf6f95e8e85b750bd409320d237a1c1a19b53b2ccf268d57f8c3e1c58c80789af6ef4a7806",
          "sha256": "1e1f5db62d2e1913814a7349c659e6abe2abbadd0b1b78b7d6041828da965d09",
          "sha1": "146b0f74333d862c0391d530c0de0d31b44f3b94",
          "md5": "79a0db37247bf97478484519993cf8c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.4.0-alpha02.aar",
          "url": "lifecycle-runtime-ktx-2.4.0-alpha02.aar",
          "size": 75833,
          "sha512": "2d0dc0cd0421a347fe8362e270219242219441b72cd8c15a5ed3e1cf6f95e8e85b750bd409320d237a1c1a19b53b2ccf268d57f8c3e1c58c80789af6ef4a7806",
          "sha256": "1e1f5db62d2e1913814a7349c659e6abe2abbadd0b1b78b7d6041828da965d09",
          "sha1": "146b0f74333d862c0391d530c0de0d31b44f3b94",
          "md5": "79a0db37247bf97478484519993cf8c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.4.0-alpha02-sources.jar",
          "url": "lifecycle-runtime-ktx-2.4.0-alpha02-sources.jar",
          "size": 14624,
          "sha512": "5ef501873b35bd0765300d5bbabf5816767fab2ea7d4e11e337ad8ef3f442fabef16ca5411d7a69a551afbfca8e27aa89ab7ec4a42ee854d0fa60904e9db6291",
          "sha256": "4f6d03f2c0a986604ea32c2b6a228aa683d9805d69bcd09890bc8bcb200798aa",
          "sha1": "be616d176c571ad4b509e533d806e1c3dbe966a7",
          "md5": "4240f143c21e8d24f809e35e192d5606"
        }
      ]
    }
  ]
}
