{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.6.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.6.0-beta01.aar",
          "url": "lifecycle-livedata-2.6.0-beta01.aar",
          "size": 18698,
          "sha512": "7880d50d7cb780af094a0a9327162782b878323e5ac5325361178612613394f48d7def0c1547ce181f85d2210ebf1de5edff22506eba97ab1738031241ca2046",
          "sha256": "ce3599924dc4a983b9a4ca9678450fc9eaa4c2d11cb86fd92e6656b179438ad2",
          "sha1": "ba138ce13f6859eed6223241d6c1315c6fea5b5f",
          "md5": "7753d28d12e9233f44b0c4bd742bb094"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.6.0-beta01.aar",
          "url": "lifecycle-livedata-2.6.0-beta01.aar",
          "size": 18698,
          "sha512": "7880d50d7cb780af094a0a9327162782b878323e5ac5325361178612613394f48d7def0c1547ce181f85d2210ebf1de5edff22506eba97ab1738031241ca2046",
          "sha256": "ce3599924dc4a983b9a4ca9678450fc9eaa4c2d11cb86fd92e6656b179438ad2",
          "sha1": "ba138ce13f6859eed6223241d6c1315c6fea5b5f",
          "md5": "7753d28d12e9233f44b0c4bd742bb094"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.6.0-beta01-sources.jar",
          "url": "lifecycle-livedata-2.6.0-beta01-sources.jar",
          "size": 6521,
          "sha512": "f4bfd2c1e79d9603e23ad7283a9e0500c874632ec5f29d4a85d00392ff993d4a829fd4c0882a2ee6047513bd71ff607c89e6f93f828efeb6720734cc419ce084",
          "sha256": "b4658f696c7393e561d503a73a0588b3d1d90ce9e1df7b1fe34495a67deae462",
          "sha1": "9b65c1e92aa9b2ce710d8530ec5d0905cce50815",
          "md5": "b5bfa8c321edcb48a141993103a33020"
        }
      ]
    }
  ]
}