{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6860046"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-beta01.aar",
          "url": "lifecycle-runtime-testing-2.3.0-beta01.aar",
          "size": 7882,
          "sha512": "21d689f60667f7dfdb7e8a89fc1cd5370504ad17a90a2f22a36834326cf2966144372960547d11a43cb61c6d330da7fe6fed2cedea1a0031456243bd028607e1",
          "sha256": "a37f88e7c9f1068e0f51cecfbe676e3cefb8f3040d399cde16fc2b40288d4172",
          "sha1": "0a5ab35b312d8b5b20962826d5646287448fda50",
          "md5": "1c945d0e620ba9ee5b4754fe797d0c38"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-beta01.aar",
          "url": "lifecycle-runtime-testing-2.3.0-beta01.aar",
          "size": 7882,
          "sha512": "21d689f60667f7dfdb7e8a89fc1cd5370504ad17a90a2f22a36834326cf2966144372960547d11a43cb61c6d330da7fe6fed2cedea1a0031456243bd028607e1",
          "sha256": "a37f88e7c9f1068e0f51cecfbe676e3cefb8f3040d399cde16fc2b40288d4172",
          "sha1": "0a5ab35b312d8b5b20962826d5646287448fda50",
          "md5": "1c945d0e620ba9ee5b4754fe797d0c38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-beta01-sources.jar",
          "url": "lifecycle-runtime-testing-2.3.0-beta01-sources.jar",
          "size": 1871,
          "sha512": "58b7db22f4599d5e63594c84f3516bdfd338f18096a974249051b7a963c02c81cc261a816de3ff518aebf44201d0f53c37f18d9be61f36d2e930e3944073c962",
          "sha256": "303f991d8d2f7738839b86285f00799a92def6b3bcd399d17259367a33688a52",
          "sha1": "78ad0ddca28690a97453a318ccd728b9ff5f9bd9",
          "md5": "d99f230f54afc3e27c04556989d554fc"
        }
      ]
    }
  ]
}
