{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-process",
    "version": "2.6.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha03"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.6.0-alpha03.aar",
          "url": "lifecycle-process-2.6.0-alpha03.aar",
          "size": 11378,
          "sha512": "b45d7db26582fffb7dc5518795cbcc31ad93731eba2137f3d844afeb240cc0cd43d30ee2fd357451f5c85ac50d71aa3d57b033bc2fd4b6dbe7112323d0b715d9",
          "sha256": "18f1e06eabc0ea35704b7bd21d117d6d99a72ca146e52b45f2e61ac20a423c43",
          "sha1": "4ea41354ab864233c2ce7754fadda28aa53a70bd",
          "md5": "ecf1c1464b938a3fba18cfad741e9567"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha03"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.6.0-alpha03.aar",
          "url": "lifecycle-process-2.6.0-alpha03.aar",
          "size": 11378,
          "sha512": "b45d7db26582fffb7dc5518795cbcc31ad93731eba2137f3d844afeb240cc0cd43d30ee2fd357451f5c85ac50d71aa3d57b033bc2fd4b6dbe7112323d0b715d9",
          "sha256": "18f1e06eabc0ea35704b7bd21d117d6d99a72ca146e52b45f2e61ac20a423c43",
          "sha1": "4ea41354ab864233c2ce7754fadda28aa53a70bd",
          "md5": "ecf1c1464b938a3fba18cfad741e9567"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-process-2.6.0-alpha03-sources.jar",
          "url": "lifecycle-process-2.6.0-alpha03-sources.jar",
          "size": 5906,
          "sha512": "ce90d34c102d83719416317ec6329e10256c3a646f88afedab555f0a4957704876f8f13e086e78e5a4d734e5d1606b1e328c961e7418cfb3d0457d9c78fe7736",
          "sha256": "b40b16492aa34faed4e34fb19f8d12afb79715eeb8ef098df4c5713647cd1a42",
          "sha1": "8fccf25901f65172f1380c9abc6cbbabe809fe6a",
          "md5": "53d76930af8c714cd452d8736b32f67b"
        }
      ]
    }
  ]
}