{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-ktx",
    "version": "2.6.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.6.0-alpha04.aar",
          "url": "lifecycle-runtime-ktx-2.6.0-alpha04.aar",
          "size": 81000,
          "sha512": "6f844f638572cfe88f04e687b4dad5177d13adf51cbcf269f20e237cc98bce4647d926c0487878ac6d48110c65d701275313233a5a6437f85381b378767196cc",
          "sha256": "29586e3fec27f67f9b42435e9a4c8001c495f8009b39862d08a01359a88b929c",
          "sha1": "4d9de22cd39d47aeea71c2ce5a5d1703bcefcf04",
          "md5": "36cc52f29bd98eea362b68b9da2c9ea5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.6.0-alpha04.aar",
          "url": "lifecycle-runtime-ktx-2.6.0-alpha04.aar",
          "size": 81000,
          "sha512": "6f844f638572cfe88f04e687b4dad5177d13adf51cbcf269f20e237cc98bce4647d926c0487878ac6d48110c65d701275313233a5a6437f85381b378767196cc",
          "sha256": "29586e3fec27f67f9b42435e9a4c8001c495f8009b39862d08a01359a88b929c",
          "sha1": "4d9de22cd39d47aeea71c2ce5a5d1703bcefcf04",
          "md5": "36cc52f29bd98eea362b68b9da2c9ea5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.6.0-alpha04-sources.jar",
          "url": "lifecycle-runtime-ktx-2.6.0-alpha04-sources.jar",
          "size": 15137,
          "sha512": "9abb6768450f9c114b9d30d4b4f49f35c2a9de0ccfb777b2cfb6784f7b0bd0aa03b4df75479cddd16d333af1942b4683bab098cab630f9b308d178b45bfdf97d",
          "sha256": "fcf8b2c8046d5b1a879532c4cf286e4a6047a6eeba505a381053d9e13fa6a30f",
          "sha1": "1692f07132f885b44450431a28d5fbaddd95eb4b",
          "md5": "db49516591017f500764df728fe7433c"
        }
      ]
    }
  ]
}