{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-ktx",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.6.0-alpha01.aar",
          "url": "lifecycle-viewmodel-ktx-2.6.0-alpha01.aar",
          "size": 4726,
          "sha512": "897fa1203db9cd419a60c493429bee8993d54bc981273c16b11040d30970f15960dd7ad78b90e1d3cfd986aec02b6f9485f818c65da8f6379f24b4a17f330cc8",
          "sha256": "2d5001e13da501e7c41175ddce5cfbf139a66c4bc590a1dc0385a894620b90c5",
          "sha1": "a9f150652851a72aa7e279307b30bd8ba8cb8018",
          "md5": "4b991686a69ff76c93c59cfb4e8275a9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.6.0-alpha01.aar",
          "url": "lifecycle-viewmodel-ktx-2.6.0-alpha01.aar",
          "size": 4726,
          "sha512": "897fa1203db9cd419a60c493429bee8993d54bc981273c16b11040d30970f15960dd7ad78b90e1d3cfd986aec02b6f9485f818c65da8f6379f24b4a17f330cc8",
          "sha256": "2d5001e13da501e7c41175ddce5cfbf139a66c4bc590a1dc0385a894620b90c5",
          "sha1": "a9f150652851a72aa7e279307b30bd8ba8cb8018",
          "md5": "4b991686a69ff76c93c59cfb4e8275a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.6.0-alpha01-sources.jar",
          "url": "lifecycle-viewmodel-ktx-2.6.0-alpha01-sources.jar",
          "size": 1410,
          "sha512": "bfe6372c5910f626e7b41bb6468d62612d1f1bde9b3c767caaa7eb7c07e93cf00d047d8e909b7c47f2985f42ffa554a82888f83e712473cee8756407fcc09548",
          "sha256": "8af8f2ac694742fe8ae133067dfdec6a193a738f46ba80c59b3e8a4ab36703f3",
          "sha1": "a900dc99643d8638beb02bd809a495f772d457e7",
          "md5": "43d89db66da712ab2560a41753632946"
        }
      ]
    }
  ]
}