{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose-samples",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.4.0.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.4.0.aar",
          "size": 1761,
          "sha512": "187585352093aa6093be3a9ee91eeab2f2f1d6c4fcfb6e835801518ab1713ebc77ad400f80f870ac26cc8ef3dced94b7818708a975ba98e1b8a32e85f83613ec",
          "sha256": "dab5cc80403c200d7c6e77300a500118f96d87e317e1cf97ff229fe3cfcd696a",
          "sha1": "95f3e0e8f433fd30a5a54f4405f3e78a6200cd0b",
          "md5": "75f70677f581d5dab034c3eb02d23c28"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.4.0.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.4.0.aar",
          "size": 1761,
          "sha512": "187585352093aa6093be3a9ee91eeab2f2f1d6c4fcfb6e835801518ab1713ebc77ad400f80f870ac26cc8ef3dced94b7818708a975ba98e1b8a32e85f83613ec",
          "sha256": "dab5cc80403c200d7c6e77300a500118f96d87e317e1cf97ff229fe3cfcd696a",
          "sha1": "95f3e0e8f433fd30a5a54f4405f3e78a6200cd0b",
          "md5": "75f70677f581d5dab034c3eb02d23c28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.4.0-sources.jar",
          "url": "lifecycle-viewmodel-compose-samples-2.4.0-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
