{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-alpha05.aar",
          "url": "lifecycle-runtime-testing-2.5.0-alpha05.aar",
          "size": 8531,
          "sha512": "6e46a35ecac6f9c2c57d4cfcdb49d921ea7110575fcb3ad44169524399b7a2cee2a0a7de5869e8864ff2cfcd30c8b1a77b08967d2eb70f395c0f376e7b1b62f9",
          "sha256": "376594316fa09e20807b05ce3731cd0e0f5ab9c94957f9be428d80e2ea435036",
          "sha1": "d63a5c2e81da44babf2d4ac6cd09f606bd1efd51",
          "md5": "93efcdd3da34913800b17b71137e062e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-alpha05.aar",
          "url": "lifecycle-runtime-testing-2.5.0-alpha05.aar",
          "size": 8531,
          "sha512": "6e46a35ecac6f9c2c57d4cfcdb49d921ea7110575fcb3ad44169524399b7a2cee2a0a7de5869e8864ff2cfcd30c8b1a77b08967d2eb70f395c0f376e7b1b62f9",
          "sha256": "376594316fa09e20807b05ce3731cd0e0f5ab9c94957f9be428d80e2ea435036",
          "sha1": "d63a5c2e81da44babf2d4ac6cd09f606bd1efd51",
          "md5": "93efcdd3da34913800b17b71137e062e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-alpha05-sources.jar",
          "url": "lifecycle-runtime-testing-2.5.0-alpha05-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}