{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-beta01.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-beta01.aar",
          "size": 2938,
          "sha512": "cb26a4e2544d744e60c262d63573bbe72e211e1dc5dadb5807395fe3623fb74a90d4a0b216daddc0b6d2c285ab4ce0bc912782aa2cd91cbd7d3fb5259599f7ae",
          "sha256": "c31d0555302a91b0cb1baac885bc636c8ecd1c8aaf647d4f808983e77436fe31",
          "sha1": "2fb38be7644300e572bbf16033c439bdc5fe7422",
          "md5": "831b4947f444b0c10ec1ef58ccd7721a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-beta01.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-beta01.aar",
          "size": 2938,
          "sha512": "cb26a4e2544d744e60c262d63573bbe72e211e1dc5dadb5807395fe3623fb74a90d4a0b216daddc0b6d2c285ab4ce0bc912782aa2cd91cbd7d3fb5259599f7ae",
          "sha256": "c31d0555302a91b0cb1baac885bc636c8ecd1c8aaf647d4f808983e77436fe31",
          "sha1": "2fb38be7644300e572bbf16033c439bdc5fe7422",
          "md5": "831b4947f444b0c10ec1ef58ccd7721a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-beta01-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-beta01-sources.jar",
          "size": 1261,
          "sha512": "bb0f402ed24247b2fd8e5ecbfec147427d84a8f18bf21cb5857c1fee5746e2a97febac326c894484fe6e86a515fe1bfd05c3b1538eb3f0f1cce712f280a76861",
          "sha256": "c50b9f047a5b5d5ee5d330b3e2dc45f4ae8deca41f607d1d495792c89e731048",
          "sha1": "23c53fd2626cac61baac62c95dec1c49046e0261",
          "md5": "5d68075becef226fa5ce3a00a8721ea7"
        }
      ]
    }
  ]
}