{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.7.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-alpha02.aar",
          "url": "activity-1.7.0-alpha02.aar",
          "size": 123422,
          "sha512": "e241e15e0e45aab547955d20701b64b8741d5ed8b90bd20f02c33a72b6dc04165c4d38b94acbd155cbe3f90e7b931c996aa1f998c7bb68e93ad4b9ec73498f21",
          "sha256": "18b7f32e7235eac8f6bf54e5a2e35eff16cbe4a47a1422bf596f1a48052e5a10",
          "sha1": "c7bf478c6c4d1a07e40d5bc01a321690adc6f42a",
          "md5": "963ae71553c386e756e0d703d6070fa8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-alpha02.aar",
          "url": "activity-1.7.0-alpha02.aar",
          "size": 123422,
          "sha512": "e241e15e0e45aab547955d20701b64b8741d5ed8b90bd20f02c33a72b6dc04165c4d38b94acbd155cbe3f90e7b931c996aa1f998c7bb68e93ad4b9ec73498f21",
          "sha256": "18b7f32e7235eac8f6bf54e5a2e35eff16cbe4a47a1422bf596f1a48052e5a10",
          "sha1": "c7bf478c6c4d1a07e40d5bc01a321690adc6f42a",
          "md5": "963ae71553c386e756e0d703d6070fa8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.7.0-alpha02-sources.jar",
          "url": "activity-1.7.0-alpha02-sources.jar",
          "size": 48466,
          "sha512": "a7bf5b400a05eee8fa1f78526045bc91e02141ca11ca53953ad29fb60b25fc440c448ed7fd95c2c67f1f0bea4687a586972680e6670d8349c8bc60f814d2d235",
          "sha256": "d827debb0a33b70a5eb554559543b100a01388e570418ec04daa981be3eb18c0",
          "sha1": "fd62ee25fc7e1ae374d39c5209d25260b0ef397b",
          "md5": "ac5120b247bb618c6f974bc153d39df9"
        }
      ]
    }
  ]
}