{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.3.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7184376"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-alpha04.aar",
          "url": "activity-1.3.0-alpha04.aar",
          "size": 67980,
          "sha512": "495be72f6a730b8089d1a261f48a40a1ebbf9e619cc9cb156af3e5ef61f952b240a48671ae496920f949a60485520c00931e8395d19fcb492b0ab77b15a864ad",
          "sha256": "56ab6c4ba090c35cd02724cf37604e5dda63c5ad6cc110d2b91e9c6a99701c83",
          "sha1": "4eb851aac0fdce53656e2d4b3db8fde05b7380c8",
          "md5": "37d90d428e2a7aab1d0dbcd93679adb1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-alpha04.aar",
          "url": "activity-1.3.0-alpha04.aar",
          "size": 67980,
          "sha512": "495be72f6a730b8089d1a261f48a40a1ebbf9e619cc9cb156af3e5ef61f952b240a48671ae496920f949a60485520c00931e8395d19fcb492b0ab77b15a864ad",
          "sha256": "56ab6c4ba090c35cd02724cf37604e5dda63c5ad6cc110d2b91e9c6a99701c83",
          "sha1": "4eb851aac0fdce53656e2d4b3db8fde05b7380c8",
          "md5": "37d90d428e2a7aab1d0dbcd93679adb1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.3.0-alpha04-sources.jar",
          "url": "activity-1.3.0-alpha04-sources.jar",
          "size": 35533,
          "sha512": "8f9d38ce9878f534c1a406d9db6f06629fb6391059a63b9b374c3fdeed7308521db29a3824c6bbacbc6327ea8ec6e71955c4a695ba952ca5025c6b2821cd05e7",
          "sha256": "557a71997dbff275a0d1795692a80c6c7f5b286db072900348e8b808330fc36f",
          "sha1": "18a932e80d91414f9b53740bb3ddbb5cb24e1f66",
          "md5": "65ca042e39f813c19bcc4817f99e343c"
        }
      ]
    }
  ]
}
