{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "2.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-alpha01.aar",
          "url": "lifecycle-viewmodel-compose-2.5.0-alpha01.aar",
          "size": 6607,
          "sha512": "36093e6e3504782104e86dd3a5505e66e5e88c7531e77e5c29ee4ed731ef402176ae84fd8bedea28f3ca36dc99ca442ee7ac9352e73b9e619c4ec5c5e800ecfc",
          "sha256": "312c8d3c45961a1d42b28c423b79eecc624192c54bf151d0272a10540e08c585",
          "sha1": "64bba7bea25f76909aee657d4de7c18cda8c785d",
          "md5": "69d1287ec43b6a142d1bcbace90a27a1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-alpha01.aar",
          "url": "lifecycle-viewmodel-compose-2.5.0-alpha01.aar",
          "size": 6607,
          "sha512": "36093e6e3504782104e86dd3a5505e66e5e88c7531e77e5c29ee4ed731ef402176ae84fd8bedea28f3ca36dc99ca442ee7ac9352e73b9e619c4ec5c5e800ecfc",
          "sha256": "312c8d3c45961a1d42b28c423b79eecc624192c54bf151d0272a10540e08c585",
          "sha1": "64bba7bea25f76909aee657d4de7c18cda8c785d",
          "md5": "69d1287ec43b6a142d1bcbace90a27a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-alpha01-sources.jar",
          "url": "lifecycle-viewmodel-compose-2.5.0-alpha01-sources.jar",
          "size": 3092,
          "sha512": "f8b3c8d7c01ef63b5c496edc99325227d3925b6a35bef2d68c84b831100eba76eeeb1664f08e6e7c748923a3921503d690d2bab215e203f9d9f65422fead14fc",
          "sha256": "6608531b0526640b945335b3502a40cfd316fae0cc8d40f24bac787bdc943fcd",
          "sha1": "c9b120561f7ae26405f8a8731d5f1c23190b587d",
          "md5": "6aecbfdf78b3f09f2b4a25d5527f6fe8"
        }
      ]
    }
  ]
}
