{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7104547"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.3.0.aar",
          "url": "lifecycle-livedata-2.3.0.aar",
          "size": 10653,
          "sha512": "4ff181dace40602c5df0b99e8680e8c9e1ea41e2c55b44ed2374aaf91b06a2dbe1dc3015d6b52c97100892cd74ef1166d25514abf537158f6af92bba8d8088e9",
          "sha256": "abbdc2e7efd5d21823b20146b87b2c55b0a6ae71b510a02b2773f0376cb0113f",
          "sha1": "cbfe8923e86ca794ef0ba7670237b344a2b799bb",
          "md5": "d719ff158be63060d0b60a408187812d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.3.0.aar",
          "url": "lifecycle-livedata-2.3.0.aar",
          "size": 10653,
          "sha512": "4ff181dace40602c5df0b99e8680e8c9e1ea41e2c55b44ed2374aaf91b06a2dbe1dc3015d6b52c97100892cd74ef1166d25514abf537158f6af92bba8d8088e9",
          "sha256": "abbdc2e7efd5d21823b20146b87b2c55b0a6ae71b510a02b2773f0376cb0113f",
          "sha1": "cbfe8923e86ca794ef0ba7670237b344a2b799bb",
          "md5": "d719ff158be63060d0b60a408187812d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.3.0-sources.jar",
          "url": "lifecycle-livedata-2.3.0-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
