{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "1.0.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta09"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-beta09"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-1.0.0-alpha07.aar",
          "url": "lifecycle-viewmodel-compose-1.0.0-alpha07.aar",
          "size": 6714,
          "sha512": "8051f1ff5ac6a1ccca8950143284bb97f83bcdd74623e5d0fc70f4afaf746ec3c70cb506ba092460318d6b9af473c1363ed96a44a76ef4fa350b237381583a3b",
          "sha256": "326decb33d56c8f08d7a31609256ba0e26024400c995f8e49e9476fde600e48d",
          "sha1": "e75b02c7cac99f9ab152837ebd8a1b6ffa55e784",
          "md5": "b3bf5466b5744cf85e80d8293befcad0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta09"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-beta09"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-1.0.0-alpha07.aar",
          "url": "lifecycle-viewmodel-compose-1.0.0-alpha07.aar",
          "size": 6714,
          "sha512": "8051f1ff5ac6a1ccca8950143284bb97f83bcdd74623e5d0fc70f4afaf746ec3c70cb506ba092460318d6b9af473c1363ed96a44a76ef4fa350b237381583a3b",
          "sha256": "326decb33d56c8f08d7a31609256ba0e26024400c995f8e49e9476fde600e48d",
          "sha1": "e75b02c7cac99f9ab152837ebd8a1b6ffa55e784",
          "md5": "b3bf5466b5744cf85e80d8293befcad0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-1.0.0-alpha07-sources.jar",
          "url": "lifecycle-viewmodel-compose-1.0.0-alpha07-sources.jar",
          "size": 3092,
          "sha512": "f8b3c8d7c01ef63b5c496edc99325227d3925b6a35bef2d68c84b831100eba76eeeb1664f08e6e7c748923a3921503d690d2bab215e203f9d9f65422fead14fc",
          "sha256": "6608531b0526640b945335b3502a40cfd316fae0cc8d40f24bac787bdc943fcd",
          "sha1": "c9b120561f7ae26405f8a8731d5f1c23190b587d",
          "md5": "6aecbfdf78b3f09f2b4a25d5527f6fe8"
        }
      ]
    }
  ]
}
