{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0.aar",
          "size": 2932,
          "sha512": "70fb839446db302c9398ad39095077f8a99196b161c72b16b97e44670b1d3960a23ad76f2c7ef18a146fd3e978e04ac9a5026edf4387800a655d0d98318e6986",
          "sha256": "229c23fca624d8d63adb69bbac264a291107d2d1ae0d3a42c2cfa465518ee8bc",
          "sha1": "c5f6260df2c215171d8281eede83c05318d52c9d",
          "md5": "13da7d2613c906ece4ff42e38aa59db0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0.aar",
          "size": 2932,
          "sha512": "70fb839446db302c9398ad39095077f8a99196b161c72b16b97e44670b1d3960a23ad76f2c7ef18a146fd3e978e04ac9a5026edf4387800a655d0d98318e6986",
          "sha256": "229c23fca624d8d63adb69bbac264a291107d2d1ae0d3a42c2cfa465518ee8bc",
          "sha1": "c5f6260df2c215171d8281eede83c05318d52c9d",
          "md5": "13da7d2613c906ece4ff42e38aa59db0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-sources.jar",
          "size": 1261,
          "sha512": "bb0f402ed24247b2fd8e5ecbfec147427d84a8f18bf21cb5857c1fee5746e2a97febac326c894484fe6e86a515fe1bfd05c3b1538eb3f0f1cce712f280a76861",
          "sha256": "c50b9f047a5b5d5ee5d330b3e2dc45f4ae8deca41f607d1d495792c89e731048",
          "sha1": "23c53fd2626cac61baac62c95dec1c49046e0261",
          "md5": "5d68075becef226fa5ce3a00a8721ea7"
        }
      ]
    }
  ]
}