{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.1.aar",
          "url": "lifecycle-runtime-testing-2.5.1.aar",
          "size": 8522,
          "sha512": "de85c41c3af8142f038ee769dc29971bd653ccf7706bafc9d48f0c190e209ac706db674f4a554584914b1efefea415879adc66e29f65b46ab23a7607de3b66db",
          "sha256": "d2edae8fd0e47eeb092e295c26d704e8038d47c1f36ab84695e9609d003ea52b",
          "sha1": "9f54db253994dda3ad0fb236b890e2ca53a663e3",
          "md5": "e1a5f975bde3f776c5d546160872c104"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.1.aar",
          "url": "lifecycle-runtime-testing-2.5.1.aar",
          "size": 8522,
          "sha512": "de85c41c3af8142f038ee769dc29971bd653ccf7706bafc9d48f0c190e209ac706db674f4a554584914b1efefea415879adc66e29f65b46ab23a7607de3b66db",
          "sha256": "d2edae8fd0e47eeb092e295c26d704e8038d47c1f36ab84695e9609d003ea52b",
          "sha1": "9f54db253994dda3ad0fb236b890e2ca53a663e3",
          "md5": "e1a5f975bde3f776c5d546160872c104"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.1-sources.jar",
          "url": "lifecycle-runtime-testing-2.5.1-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}