{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6684396"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha06.aar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha06.aar",
          "size": 7685,
          "sha512": "aaa9cf275597da2c109604b0b97a6b9f9dc62948183b7b2e168ba8afb742acd03e77c9da713c8d3f57b05e606739b0eec03589a4564ad91945760eb770d7f4a3",
          "sha256": "e99ebd982ccee974c55df2b4f6fff7f4a2f02b078287add592982f002c5e393b",
          "sha1": "3acea85c3f547ff963073641460fadc56ae7d34c",
          "md5": "8e0f38d9a1537f38b1912e54bd04305e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha06.aar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha06.aar",
          "size": 7685,
          "sha512": "aaa9cf275597da2c109604b0b97a6b9f9dc62948183b7b2e168ba8afb742acd03e77c9da713c8d3f57b05e606739b0eec03589a4564ad91945760eb770d7f4a3",
          "sha256": "e99ebd982ccee974c55df2b4f6fff7f4a2f02b078287add592982f002c5e393b",
          "sha1": "3acea85c3f547ff963073641460fadc56ae7d34c",
          "md5": "8e0f38d9a1537f38b1912e54bd04305e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha06-sources.jar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha06-sources.jar",
          "size": 1871,
          "sha512": "58b7db22f4599d5e63594c84f3516bdfd338f18096a974249051b7a963c02c81cc261a816de3ff518aebf44201d0f53c37f18d9be61f36d2e930e3944073c962",
          "sha256": "303f991d8d2f7738839b86285f00799a92def6b3bcd399d17259367a33688a52",
          "sha1": "78ad0ddca28690a97453a318ccd728b9ff5f9bd9",
          "md5": "d99f230f54afc3e27c04556989d554fc"
        }
      ]
    }
  ]
}
