{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.6.0-alpha01.aar",
          "url": "lifecycle-runtime-testing-2.6.0-alpha01.aar",
          "size": 9188,
          "sha512": "495d3703cdb62f935cdd63b4ba01c5b5ac2550c8f429c66487b85c2aee387f3663002aab72b69316b0c9ff8d65d329a192873347f020cca8a390d19c17d5a097",
          "sha256": "4768c5c9f93e069da1210623e86db7779917cfd78509d299af998100d233d64b",
          "sha1": "1db50932f0af45c2199776a7015950c766c62aae",
          "md5": "8ae9c69638fd29da5dd9fde1affb4050"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.6.0-alpha01.aar",
          "url": "lifecycle-runtime-testing-2.6.0-alpha01.aar",
          "size": 9188,
          "sha512": "495d3703cdb62f935cdd63b4ba01c5b5ac2550c8f429c66487b85c2aee387f3663002aab72b69316b0c9ff8d65d329a192873347f020cca8a390d19c17d5a097",
          "sha256": "4768c5c9f93e069da1210623e86db7779917cfd78509d299af998100d233d64b",
          "sha1": "1db50932f0af45c2199776a7015950c766c62aae",
          "md5": "8ae9c69638fd29da5dd9fde1affb4050"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.6.0-alpha01-sources.jar",
          "url": "lifecycle-runtime-testing-2.6.0-alpha01-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}