{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams",
    "version": "2.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6860046"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.3.0-beta01.aar",
          "url": "lifecycle-reactivestreams-2.3.0-beta01.aar",
          "size": 8319,
          "sha512": "cffbb0d00f2577e06e715a0b33d2998f313d6df510735b3539c767580cf21cf9e5f4df49b0363fdd493b5416a7be054aad3d36016b3d6e3a24360bb2425484a1",
          "sha256": "ee32b6568ca306277e13481e30e2412c33a58750e19dc6a0120091a5286b3bc4",
          "sha1": "a21c4fcdc41e2ece3968ab50f87251fa75db735b",
          "md5": "93ad907fa98f3b534c2d45a2eff0e5e8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.3.0-beta01.aar",
          "url": "lifecycle-reactivestreams-2.3.0-beta01.aar",
          "size": 8319,
          "sha512": "cffbb0d00f2577e06e715a0b33d2998f313d6df510735b3539c767580cf21cf9e5f4df49b0363fdd493b5416a7be054aad3d36016b3d6e3a24360bb2425484a1",
          "sha256": "ee32b6568ca306277e13481e30e2412c33a58750e19dc6a0120091a5286b3bc4",
          "sha1": "a21c4fcdc41e2ece3968ab50f87251fa75db735b",
          "md5": "93ad907fa98f3b534c2d45a2eff0e5e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.3.0-beta01-sources.jar",
          "url": "lifecycle-reactivestreams-2.3.0-beta01-sources.jar",
          "size": 3248,
          "sha512": "a6b65d83c8f4d40f76f171140950c3e44745058afe510b3f89b883ae47fe9f1a14c6ab03929077e43c584df3430c28437a32e8d0fba537d5ec6381ff4e6ec7eb",
          "sha256": "25c60c1e6301781e80787118a26d2e3c011187df8356ab427078c18c7e349585",
          "sha1": "31df3402f1e5e287cb5b0e7d9568f100871588f3",
          "md5": "aa8ca57584eb4039b356b2ab8d5a2ae1"
        }
      ]
    }
  ]
}
