{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.6.0-alpha01.aar",
          "url": "lifecycle-livedata-core-2.6.0-alpha01.aar",
          "size": 10804,
          "sha512": "5b678c60e22dd60a89f4ed7c628fcd819e296eb662c128008bd45dfef9b665a4b9f82ec85c5ef464a6b3e302334323d1106b659b73d6f0a06aaae18c1e73cee8",
          "sha256": "6a6e62b27fa8c372085a5020e2f2cfcc147a3b04fe7afa76f05af6e32060b090",
          "sha1": "881c0e6b570631b56203743d6f4505bec0a00ab0",
          "md5": "363c3073a0b646e2ec427bdfc1d293f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.6.0-alpha01.aar",
          "url": "lifecycle-livedata-core-2.6.0-alpha01.aar",
          "size": 10804,
          "sha512": "5b678c60e22dd60a89f4ed7c628fcd819e296eb662c128008bd45dfef9b665a4b9f82ec85c5ef464a6b3e302334323d1106b659b73d6f0a06aaae18c1e73cee8",
          "sha256": "6a6e62b27fa8c372085a5020e2f2cfcc147a3b04fe7afa76f05af6e32060b090",
          "sha1": "881c0e6b570631b56203743d6f4505bec0a00ab0",
          "md5": "363c3073a0b646e2ec427bdfc1d293f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.6.0-alpha01-sources.jar",
          "url": "lifecycle-livedata-core-2.6.0-alpha01-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}