{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha05.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha05.aar",
          "size": 10086,
          "sha512": "95f1ed10ec9514b15d03d8939a326c7fb249a02543fab7067c8eb287cd0c53fa99cfce7dedf800af03493ac7297bdfc52d15c63ec126f67bd33821fb18179b40",
          "sha256": "9191b0ad6bd84cd8e80fe49114bbce6d914c667a5ece7e75961ae306537f6323",
          "sha1": "3fae9745c41ecf575c1b525c4e42ef536eef96c7",
          "md5": "5370d98ee230d7915c816984177ab922"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha05.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha05.aar",
          "size": 10086,
          "sha512": "95f1ed10ec9514b15d03d8939a326c7fb249a02543fab7067c8eb287cd0c53fa99cfce7dedf800af03493ac7297bdfc52d15c63ec126f67bd33821fb18179b40",
          "sha256": "9191b0ad6bd84cd8e80fe49114bbce6d914c667a5ece7e75961ae306537f6323",
          "sha1": "3fae9745c41ecf575c1b525c4e42ef536eef96c7",
          "md5": "5370d98ee230d7915c816984177ab922"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha05-sources.jar",
          "url": "lifecycle-livedata-core-2.5.0-alpha05-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}