{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.3.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.0-rc01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.0-rc01.aar",
          "url": "activity-ktx-1.3.0-rc01.aar",
          "size": 30066,
          "sha512": "dc19320da47b915b78c28b4457d85de96c4a506c0daeda2021f9d4295c2eda25c63c1e88916dc72c6cac89b8bf17f00f5388df82794fd5c359a475e7091f668e",
          "sha256": "a15f6b028961f3ac56ce6a00d4a3c07ee9390a33c13bf187b2ef77b9bcc1a182",
          "sha1": "2766a772fcb2a0b14ecb90899f770a7b3374f0f5",
          "md5": "e9a28c06ecb626546543d8d319517a9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.0-rc01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.0-rc01.aar",
          "url": "activity-ktx-1.3.0-rc01.aar",
          "size": 30066,
          "sha512": "dc19320da47b915b78c28b4457d85de96c4a506c0daeda2021f9d4295c2eda25c63c1e88916dc72c6cac89b8bf17f00f5388df82794fd5c359a475e7091f668e",
          "sha256": "a15f6b028961f3ac56ce6a00d4a3c07ee9390a33c13bf187b2ef77b9bcc1a182",
          "sha1": "2766a772fcb2a0b14ecb90899f770a7b3374f0f5",
          "md5": "e9a28c06ecb626546543d8d319517a9e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.3.0-rc01-sources.jar",
          "url": "activity-ktx-1.3.0-rc01-sources.jar",
          "size": 7769,
          "sha512": "804afefb365825fba128fb90e94e2a52c592f086d4829c379113a6dff9541f59fba14d174ed54808d3d218fa67d8c7b0d13b46fbf21d5fa37289f20712888cf2",
          "sha256": "e9203b000c2790d6f867dd642380f820cf97ba9a821e96daadac8b7dba19e0b3",
          "sha1": "370e20946dad67d9ce26dbe3f33034ddf84600c4",
          "md5": "eafcc6f70cc644f6a4d16ba2482a3c1b"
        }
      ]
    }
  ]
}
