{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.6.0-alpha01.aar",
          "url": "lifecycle-service-2.6.0-alpha01.aar",
          "size": 5068,
          "sha512": "7c5d23f1997717794169c94fed0d1852dfd44242ac96aa4270ce2aa5d65225d749bca6c8467d870e852b035ac069ae1f83b33603ee6aebf3fdb6c3b6811b36bf",
          "sha256": "2a15699cc028d5d1a1c50c26f859673f60e7d2bdeaaa5fa4823a2a8c3b7fb1af",
          "sha1": "d225e13e0dca12e4d6de43299629cd61b15256bd",
          "md5": "51f5bf07f87051b2d0dedefbc1ea864c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.6.0-alpha01.aar",
          "url": "lifecycle-service-2.6.0-alpha01.aar",
          "size": 5068,
          "sha512": "7c5d23f1997717794169c94fed0d1852dfd44242ac96aa4270ce2aa5d65225d749bca6c8467d870e852b035ac069ae1f83b33603ee6aebf3fdb6c3b6811b36bf",
          "sha256": "2a15699cc028d5d1a1c50c26f859673f60e7d2bdeaaa5fa4823a2a8c3b7fb1af",
          "sha1": "d225e13e0dca12e4d6de43299629cd61b15256bd",
          "md5": "51f5bf07f87051b2d0dedefbc1ea864c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.6.0-alpha01-sources.jar",
          "url": "lifecycle-service-2.6.0-alpha01-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}