{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-process",
    "version": "2.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.6.0-alpha05.aar",
          "url": "lifecycle-process-2.6.0-alpha05.aar",
          "size": 16083,
          "sha512": "903e23bdfafc86f56467e4c52e68bc6bb08d75bc60a608a506ba51e13a640177ac557b4e9aeba43364df9d17160258a6ba28592257d8fe0e25baa73af1f085a8",
          "sha256": "3f87dc2cd7202fe5a9ffc88b88856c4d3e4a50523922d67e4e5d7caa7f390e87",
          "sha1": "aaf8c9bbd9c1506f7f61f0a19cd47ccc1321eca6",
          "md5": "748daee29583fc11d4711a6ad30b5012"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.6.0-alpha05.aar",
          "url": "lifecycle-process-2.6.0-alpha05.aar",
          "size": 16083,
          "sha512": "903e23bdfafc86f56467e4c52e68bc6bb08d75bc60a608a506ba51e13a640177ac557b4e9aeba43364df9d17160258a6ba28592257d8fe0e25baa73af1f085a8",
          "sha256": "3f87dc2cd7202fe5a9ffc88b88856c4d3e4a50523922d67e4e5d7caa7f390e87",
          "sha1": "aaf8c9bbd9c1506f7f61f0a19cd47ccc1321eca6",
          "md5": "748daee29583fc11d4711a6ad30b5012"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-process-2.6.0-alpha05-sources.jar",
          "url": "lifecycle-process-2.6.0-alpha05-sources.jar",
          "size": 5597,
          "sha512": "327ee1d1e7162364b4d8f138f2b6ff0a15e180d0f4dca87c5c6111c93fe5318376feb191990f4fac53b1a32e0ae00bc49bae9eebdc0e19dea1f2e91ce6eb47c9",
          "sha256": "558e140b22cac6460d398ea700628c5ca0b008bfc2a81dbd428c03ef5ca52884",
          "sha1": "ffa3d8ec6544d8b65169c1d67170942bd4345476",
          "md5": "47135d0f0ed3ad38262c00dd075c4580"
        }
      ]
    }
  ]
}