{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.5.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-rc02.aar",
          "url": "lifecycle-service-2.5.0-rc02.aar",
          "size": 4362,
          "sha512": "ad4d5bc064f2a1c66d93a6c206c6627f8fce2b4807bdfb7203cd43d7c4e096c8ce5b08459e474aec423ce6efb901a3aa859ea441e92e65c930dba8549d9914c6",
          "sha256": "8b7ac413b947dc5573220094d690d67710cca385050ba3f8601a514b37cd8f67",
          "sha1": "218d57ce0af078d6e1dc93df4acb0b3135172664",
          "md5": "53eccbae0864354fa02be2de11a8a75c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-rc02.aar",
          "url": "lifecycle-service-2.5.0-rc02.aar",
          "size": 4362,
          "sha512": "ad4d5bc064f2a1c66d93a6c206c6627f8fce2b4807bdfb7203cd43d7c4e096c8ce5b08459e474aec423ce6efb901a3aa859ea441e92e65c930dba8549d9914c6",
          "sha256": "8b7ac413b947dc5573220094d690d67710cca385050ba3f8601a514b37cd8f67",
          "sha1": "218d57ce0af078d6e1dc93df4acb0b3135172664",
          "md5": "53eccbae0864354fa02be2de11a8a75c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.5.0-rc02-sources.jar",
          "url": "lifecycle-service-2.5.0-rc02-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}