{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.7.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-alpha04.aar",
          "url": "activity-1.7.0-alpha04.aar",
          "size": 128372,
          "sha512": "56b9d946df6e245d3eb7ed497cf3e2fd719f23f146209aa59babe64a8637b225bbc966b6fdb314dd9acb04aa0ecdcb75392bfc85756101c23b3f00d1cc292522",
          "sha256": "de15f50ebcaff26f43daedbf540f71fde4a9301574462f445305ea05a9dd870b",
          "sha1": "90a8e7a4d48f443c4c17898c1a52fa45f332055d",
          "md5": "0c5cdc9450a93c9209282277a912c5ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-alpha04.aar",
          "url": "activity-1.7.0-alpha04.aar",
          "size": 128372,
          "sha512": "56b9d946df6e245d3eb7ed497cf3e2fd719f23f146209aa59babe64a8637b225bbc966b6fdb314dd9acb04aa0ecdcb75392bfc85756101c23b3f00d1cc292522",
          "sha256": "de15f50ebcaff26f43daedbf540f71fde4a9301574462f445305ea05a9dd870b",
          "sha1": "90a8e7a4d48f443c4c17898c1a52fa45f332055d",
          "md5": "0c5cdc9450a93c9209282277a912c5ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.7.0-alpha04-sources.jar",
          "url": "activity-1.7.0-alpha04-sources.jar",
          "size": 48862,
          "sha512": "c5a5418d7dfdb55c8dbaf17e0be8f539f0000b4fa82529bf49542d5cc6eabef0030538961cf2ba89ddfed5fddac6a233827ff0364ad7b723c2ee539354095e7b",
          "sha256": "14e652365ffff43d7a9b4aa23f59cd028380991b932c8e1b2db5b21988baf2ca",
          "sha1": "0a71f41b5e02dcfdd2a476ffaa7bd26d382ea05e",
          "md5": "fd25cb3c28aa8716ba7960197b55573c"
        }
      ]
    }
  ]
}