{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-common",
    "version": "2.6.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lifecycle-common-2.6.0-beta01.jar",
          "url": "lifecycle-common-2.6.0-beta01.jar",
          "size": 52313,
          "sha512": "3b8211e4289a0009534ff9191da5f705bc6c7c5e3df8e535d380233e87742772113c1b3511d3fb57bdd63c0e99fea4ea10276fe0f946835363ae7d77f5955536",
          "sha256": "7fccacdd6cd3dcd0ff409a1a253d8442e7880d411c6a29644a0fad1b6dd049b9",
          "sha1": "5ce6f03b6b940a5ddb9cd4c4bee782b2a41183b4",
          "md5": "76f99cef081d8511d62519a1a572f434"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-common-2.6.0-beta01.jar",
          "url": "lifecycle-common-2.6.0-beta01.jar",
          "size": 52313,
          "sha512": "3b8211e4289a0009534ff9191da5f705bc6c7c5e3df8e535d380233e87742772113c1b3511d3fb57bdd63c0e99fea4ea10276fe0f946835363ae7d77f5955536",
          "sha256": "7fccacdd6cd3dcd0ff409a1a253d8442e7880d411c6a29644a0fad1b6dd049b9",
          "sha1": "5ce6f03b6b940a5ddb9cd4c4bee782b2a41183b4",
          "md5": "76f99cef081d8511d62519a1a572f434"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-common-2.6.0-beta01-sources.jar",
          "url": "lifecycle-common-2.6.0-beta01-sources.jar",
          "size": 24682,
          "sha512": "7727681b4a417bb8d23a4e1640de957986454a72756dd879c891dbc4a192d8018e4bfbd75f2de6faae4640dc77b5aa67577309088b9616793cff57f81890551c",
          "sha256": "9b194a75aa6724bdac277be839eddd5d49192d64389d5ac02d1f6bb6c334124e",
          "sha1": "a2a417e26f5d4c961d9621d0540014e1706d0c52",
          "md5": "555b73990dfd5183e738ec2fee6f4a17"
        }
      ]
    }
  ]
}