{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "2.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-alpha02.aar",
          "url": "lifecycle-viewmodel-compose-2.5.0-alpha02.aar",
          "size": 6607,
          "sha512": "79bf318600a86efb95a3d21cd2c4a5069eac517baca40c4e80e5406b06129290ba70394032c22b41aaf57cae7078c7864b64d7a67a987964ddc090bae457db50",
          "sha256": "ecd3c8f2b26e4d84771dd68f15ced2178e3831a9b2186873ba215ebaf59bf249",
          "sha1": "6ed5f25a7a0ee41ce7923b8d7535fb184285a838",
          "md5": "d4c735f7632253cce0b44c4366b73dd8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-alpha02.aar",
          "url": "lifecycle-viewmodel-compose-2.5.0-alpha02.aar",
          "size": 6607,
          "sha512": "79bf318600a86efb95a3d21cd2c4a5069eac517baca40c4e80e5406b06129290ba70394032c22b41aaf57cae7078c7864b64d7a67a987964ddc090bae457db50",
          "sha256": "ecd3c8f2b26e4d84771dd68f15ced2178e3831a9b2186873ba215ebaf59bf249",
          "sha1": "6ed5f25a7a0ee41ce7923b8d7535fb184285a838",
          "md5": "d4c735f7632253cce0b44c4366b73dd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-alpha02-sources.jar",
          "url": "lifecycle-viewmodel-compose-2.5.0-alpha02-sources.jar",
          "size": 3092,
          "sha512": "f8b3c8d7c01ef63b5c496edc99325227d3925b6a35bef2d68c84b831100eba76eeeb1664f08e6e7c748923a3921503d690d2bab215e203f9d9f65422fead14fc",
          "sha256": "6608531b0526640b945335b3502a40cfd316fae0cc8d40f24bac787bdc943fcd",
          "sha1": "c9b120561f7ae26405f8a8731d5f1c23190b587d",
          "md5": "6aecbfdf78b3f09f2b4a25d5527f6fe8"
        }
      ]
    }
  ]
}
