{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.3.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7285231"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-alpha07.aar",
          "url": "activity-1.3.0-alpha07.aar",
          "size": 67973,
          "sha512": "c085cdc804aa4b491122a4fe5afb248ea7bf53d49e46e47362abca7a36687d6d4ec109fbaecc1143fc31d6f7820233e44c02afeaaeb93ed3b563358598d04684",
          "sha256": "4c8471966efb604ba1e8016bcfdfda77d0dfc379de50c0d0e43b5c7d2da0147c",
          "sha1": "934a1de248fbf7421d3cef079ecdb672e7831367",
          "md5": "a2687991c6b75f2956a02a78a64162de"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-alpha07.aar",
          "url": "activity-1.3.0-alpha07.aar",
          "size": 67973,
          "sha512": "c085cdc804aa4b491122a4fe5afb248ea7bf53d49e46e47362abca7a36687d6d4ec109fbaecc1143fc31d6f7820233e44c02afeaaeb93ed3b563358598d04684",
          "sha256": "4c8471966efb604ba1e8016bcfdfda77d0dfc379de50c0d0e43b5c7d2da0147c",
          "sha1": "934a1de248fbf7421d3cef079ecdb672e7831367",
          "md5": "a2687991c6b75f2956a02a78a64162de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.3.0-alpha07-sources.jar",
          "url": "activity-1.3.0-alpha07-sources.jar",
          "size": 35608,
          "sha512": "53d529ca53db82f838aae1c6bb84069e973424350a94cb7602b70e7155281088d39a57564eee4842f97416286f9fc5a76ce058b034bc502eadc7f1ab6d983249",
          "sha256": "0cffd6a421f6c3a172b256dac2a597093b96ac7224157d0c62057610bcd5ba2b",
          "sha1": "8b49edd0e1494eafb504f24514f943fa3937d3bf",
          "md5": "79e13286c89746869b88fa2194bb75b0"
        }
      ]
    }
  ]
}
