{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.3.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6558100"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.3.0-alpha04.aar",
          "url": "lifecycle-livedata-2.3.0-alpha04.aar",
          "size": 10205,
          "sha512": "00bd5c74112c5c54cb4fd9496aa405addf94dcbc00c39a56f8a73b748856ddcd80f6e04958ebf1fc6473caad846632a7499c2ae81e58263a28c8fc79683483f0",
          "sha256": "32c5302bfb2d0a7c917d4bc8b8febd92ae249d14e5defda56f2f0ff253a2dfc3",
          "sha1": "9dd6987d37bb947ac14718fb7ccb54c30607298b",
          "md5": "50cb83b0c4819101461bf4faf1905618"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.3.0-alpha04.aar",
          "url": "lifecycle-livedata-2.3.0-alpha04.aar",
          "size": 10205,
          "sha512": "00bd5c74112c5c54cb4fd9496aa405addf94dcbc00c39a56f8a73b748856ddcd80f6e04958ebf1fc6473caad846632a7499c2ae81e58263a28c8fc79683483f0",
          "sha256": "32c5302bfb2d0a7c917d4bc8b8febd92ae249d14e5defda56f2f0ff253a2dfc3",
          "sha1": "9dd6987d37bb947ac14718fb7ccb54c30607298b",
          "md5": "50cb83b0c4819101461bf4faf1905618"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.3.0-alpha04-sources.jar",
          "url": "lifecycle-livedata-2.3.0-alpha04-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
