{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.6.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.0-alpha03"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0-beta01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.6.0-alpha03.aar",
          "url": "activity-ktx-1.6.0-alpha03.aar",
          "size": 31259,
          "sha512": "e5a7debfaf0e29b36257543fca8a2df3204fde4328bb9fca1c1b489bcc32f49ca9c26ddd304381c042dc5581f6262fb9fdd6f8a3cf98f73c9d462d58968e4c02",
          "sha256": "6b0e7f08db2a97e7735bc9a58619dddabad3a5536ea2e2e78508be0838e05882",
          "sha1": "4ff81b49b5bd0fb0a08ae92a6ce1f795a7f69e14",
          "md5": "6cf99acccaf2e8016fd53eab66bdc0c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.0-alpha03"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0-beta01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.6.0-alpha03.aar",
          "url": "activity-ktx-1.6.0-alpha03.aar",
          "size": 31259,
          "sha512": "e5a7debfaf0e29b36257543fca8a2df3204fde4328bb9fca1c1b489bcc32f49ca9c26ddd304381c042dc5581f6262fb9fdd6f8a3cf98f73c9d462d58968e4c02",
          "sha256": "6b0e7f08db2a97e7735bc9a58619dddabad3a5536ea2e2e78508be0838e05882",
          "sha1": "4ff81b49b5bd0fb0a08ae92a6ce1f795a7f69e14",
          "md5": "6cf99acccaf2e8016fd53eab66bdc0c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.6.0-alpha03-sources.jar",
          "url": "activity-ktx-1.6.0-alpha03-sources.jar",
          "size": 7896,
          "sha512": "410bbd1a10f608fdc92ce2597cac6d8e8bc24c7c2a3de296016e04106298d0df3108cc767b661b869d7160403664b806051b2023a4359afa72f5de366d6660ae",
          "sha256": "89dd07b2ecd1e7678fcee8a3cde667ae51f251c88b3bce5ea8298662c118c909",
          "sha1": "919ce22f7ced37bb707da496c1852fa8a30b6571",
          "md5": "2086f53f293836c195e19cf368e671f1"
        }
      ]
    }
  ]
}