{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.4.0-beta01.aar",
          "url": "lifecycle-runtime-testing-2.4.0-beta01.aar",
          "size": 8453,
          "sha512": "276942c34d950ec9f617d1dc96dc3eb4b0e79d79e80d713fc1e34510eaae744af345a487732c8b6e8d68d05e1e4fe0640919a9d12c6c9df1f7c6185e47e06df1",
          "sha256": "5ac856839a4d154965f02cf831d46d042bc09b6f927583aac9c83b28a26a717e",
          "sha1": "989135a0c92300ec0160c9f5fac919e440a8193e",
          "md5": "d9457bf63178f801a15243a4ee9edef1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.4.0-beta01.aar",
          "url": "lifecycle-runtime-testing-2.4.0-beta01.aar",
          "size": 8453,
          "sha512": "276942c34d950ec9f617d1dc96dc3eb4b0e79d79e80d713fc1e34510eaae744af345a487732c8b6e8d68d05e1e4fe0640919a9d12c6c9df1f7c6185e47e06df1",
          "sha256": "5ac856839a4d154965f02cf831d46d042bc09b6f927583aac9c83b28a26a717e",
          "sha1": "989135a0c92300ec0160c9f5fac919e440a8193e",
          "md5": "d9457bf63178f801a15243a4ee9edef1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.4.0-beta01-sources.jar",
          "url": "lifecycle-runtime-testing-2.4.0-beta01-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}
