{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.3.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6759487"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.3.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-alpha07.aar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-alpha07.aar",
          "size": 2354,
          "sha512": "acf1ff89cef202d582a833b310c55a4e578198a77b5477f9d9bdf74d57e267d5bd2ac1678c824da017b27b7d92976c95de76f00ea33b87353c11c7edcb549504",
          "sha256": "d462824f4eee7b3750f7f6ec0733304e8339a317aa068598565c2d55c6fb6b88",
          "sha1": "7f26bfdc194da8fef04ea5362d4361381a580cb6",
          "md5": "5d550a5ac2fbb8172bc500e7febc2dd6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.3.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-alpha07.aar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-alpha07.aar",
          "size": 2354,
          "sha512": "acf1ff89cef202d582a833b310c55a4e578198a77b5477f9d9bdf74d57e267d5bd2ac1678c824da017b27b7d92976c95de76f00ea33b87353c11c7edcb549504",
          "sha256": "d462824f4eee7b3750f7f6ec0733304e8339a317aa068598565c2d55c6fb6b88",
          "sha1": "7f26bfdc194da8fef04ea5362d4361381a580cb6",
          "md5": "5d550a5ac2fbb8172bc500e7febc2dd6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-alpha07-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-alpha07-sources.jar",
          "size": 1260,
          "sha512": "9855fea967e2e3e524d04ecf0d9838f1c96fd94b80c348dc612c69bd42ca82ce4779cf587cc833a4dde819b94f2e92589cc478ab28b31638de1e1b32d7a61c36",
          "sha256": "36ab72c2b848531aed3a416c5d0636c24cc64463b3685b0825eab17924b0aa4e",
          "sha1": "f1045318682f7dbef230a3cf1ce0ed2377d14903",
          "md5": "173bdd2cae36a9dc56a58e4f5482488d"
        }
      ]
    }
  ]
}
