{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.5.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-alpha04.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-alpha04.aar",
          "size": 16363,
          "sha512": "37020ef90d85568d2ac0176112673bbe68275c660d758b0fe050252f4015b8c8d56b9884e9428fed59b43adc0f5b373dc41888023fb26a7ba1a0282002cdf5bd",
          "sha256": "be881b4e6749fce50ae8c6b12f421d4bf7c436e6d5a7a17f99b8a1383f9f1289",
          "sha1": "8e3e344510a5b16d6d7a34c7545d71c226a36d35",
          "md5": "cafc4fcd04c65ebaf6dd3e89d0e3981b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-alpha04.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-alpha04.aar",
          "size": 16363,
          "sha512": "37020ef90d85568d2ac0176112673bbe68275c660d758b0fe050252f4015b8c8d56b9884e9428fed59b43adc0f5b373dc41888023fb26a7ba1a0282002cdf5bd",
          "sha256": "be881b4e6749fce50ae8c6b12f421d4bf7c436e6d5a7a17f99b8a1383f9f1289",
          "sha1": "8e3e344510a5b16d6d7a34c7545d71c226a36d35",
          "md5": "cafc4fcd04c65ebaf6dd3e89d0e3981b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-alpha04-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-alpha04-sources.jar",
          "size": 1631,
          "sha512": "aec27370748b879276405755e63a377e08307bfe2f370687ee18fa5c43cb5e203fe5e3bcc9cda40390c872bf279e96bc2bae2f0a9e2ee631f861b2ad0e54c0ae",
          "sha256": "b7a2a7c66a58440b0ba30c68abe17074836f217123fb6ea728279834641a7c77",
          "sha1": "0ec507705520b7ddccce7da52bbf5abd9ecd1808",
          "md5": "c552138cfc58a3f4d73c8acbb66e4a86"
        }
      ]
    }
  ]
}
