{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose-samples",
    "version": "2.5.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-rc02.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-rc02.aar",
          "size": 40333,
          "sha512": "421010e7fa2956389b0f2c605e6b54218285bf5f8ae4347126552df2e7633d97333bb539c43f410f00b8b417a0081efb54b262e761595b04cf8844a93d93bccf",
          "sha256": "380bd70a688b4cfbab0df5bd3c5cd5ebdeb3faea336c0e3ecb658671e1356bf8",
          "sha1": "1f2ff14ab8063ab8c0fbee9b8cc1ff515e1d9b7b",
          "md5": "bae8b3f3ef38c47a240f3db01113c941"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-rc02.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-rc02.aar",
          "size": 40333,
          "sha512": "421010e7fa2956389b0f2c605e6b54218285bf5f8ae4347126552df2e7633d97333bb539c43f410f00b8b417a0081efb54b262e761595b04cf8844a93d93bccf",
          "sha256": "380bd70a688b4cfbab0df5bd3c5cd5ebdeb3faea336c0e3ecb658671e1356bf8",
          "sha1": "1f2ff14ab8063ab8c0fbee9b8cc1ff515e1d9b7b",
          "md5": "bae8b3f3ef38c47a240f3db01113c941"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-rc02-sources.jar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-rc02-sources.jar",
          "size": 3379,
          "sha512": "71bc321f7f42099ae8f1e6d341f23b8dcd483ea400203cf5ef629c37b0a2f2f704a334d01d7504f067b911fda251851491a2dd21360e275589d92475428a8ab3",
          "sha256": "448ea500e9b2e4b813f1930f06e0de094c5b9fd3e97a6aa97a9cea6119258058",
          "sha1": "a2098e51c34b521e091cdccaa6e3ba228ebc783a",
          "md5": "01b23ed76ba1fcd2795bea5847ddd553"
        }
      ]
    }
  ]
}