{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.3.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7285231"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.0-alpha07"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.0-alpha07.aar",
          "url": "activity-ktx-1.3.0-alpha07.aar",
          "size": 20431,
          "sha512": "19d028af03dc15cac3c5e9fd65d46aad253cb4e3d481d0aed9b9f3a326114749ae7c3df7537b0d4f201ad35234d626b667e78475b00f044ec1b89d0bb8216049",
          "sha256": "1e0b70d7f4fe9eaee69f925ec785ce7918114dd5e31514935892c76d271b28b7",
          "sha1": "ab663083c9aeac5f00e392f9f7ae13e80e0b4b97",
          "md5": "57fabf7cc9b2de32772260244cabddac"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.0-alpha07"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.0-alpha07.aar",
          "url": "activity-ktx-1.3.0-alpha07.aar",
          "size": 20431,
          "sha512": "19d028af03dc15cac3c5e9fd65d46aad253cb4e3d481d0aed9b9f3a326114749ae7c3df7537b0d4f201ad35234d626b667e78475b00f044ec1b89d0bb8216049",
          "sha256": "1e0b70d7f4fe9eaee69f925ec785ce7918114dd5e31514935892c76d271b28b7",
          "sha1": "ab663083c9aeac5f00e392f9f7ae13e80e0b4b97",
          "md5": "57fabf7cc9b2de32772260244cabddac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.3.0-alpha07-sources.jar",
          "url": "activity-ktx-1.3.0-alpha07-sources.jar",
          "size": 6133,
          "sha512": "a5266f324c627f8819af1667fb4f31e61196fc118c691c07570487ee2eb7584d5415faa8a85eecd06e810f4448d893a8ddddd32e9e229b514466ad0f7f81c5d9",
          "sha256": "4d8c5ae5ebb411cf3770fc3546a93c527a20819762b4807fec8ea1c7521ce06e",
          "sha1": "8de8463662d207920c11530ec0e76af3005f0061",
          "md5": "7f56f8cdd73c71afc49702017eb9408b"
        }
      ]
    }
  ]
}
