{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.3.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6558100"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.3.0-alpha04.aar",
          "url": "lifecycle-livedata-core-ktx-2.3.0-alpha04.aar",
          "size": 13549,
          "sha512": "1ad0aacc4ad0b837db2ea445772ddc55fc0f901128e0150286859881cbde21a4c4178a8af5ce84f0f0e9b6aa0b61b467f98cde5708d574e5254fb4234c1c4cd8",
          "sha256": "86d32758494fa00f9da62b2997fc1dc5ac5a7e806e757852a89d3b7bfce74866",
          "sha1": "85b220e5d98abf944b618d6d7022c45494105100",
          "md5": "1d24f8cb657d468141f0ded459a30416"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.3.0-alpha04.aar",
          "url": "lifecycle-livedata-core-ktx-2.3.0-alpha04.aar",
          "size": 13549,
          "sha512": "1ad0aacc4ad0b837db2ea445772ddc55fc0f901128e0150286859881cbde21a4c4178a8af5ce84f0f0e9b6aa0b61b467f98cde5708d574e5254fb4234c1c4cd8",
          "sha256": "86d32758494fa00f9da62b2997fc1dc5ac5a7e806e757852a89d3b7bfce74866",
          "sha1": "85b220e5d98abf944b618d6d7022c45494105100",
          "md5": "1d24f8cb657d468141f0ded459a30416"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.3.0-alpha04-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.3.0-alpha04-sources.jar",
          "size": 1548,
          "sha512": "a662df037b63f97dcdea59f18a27f66767a45def78c6a355c58d8d758c7ca197128c71cebd9d0f4a617e71430d837f11ec5aa73e614176a92148d1139f22d2cc",
          "sha256": "d962111f3f83b59b90c7fee2f1c47a6532629cebc01c407be39adf34e4d0d09c",
          "sha1": "7aa8d50b21a293f7a525ec84869c421a963b0188",
          "md5": "ffc8824f250177b16aac3a764f60408a"
        }
      ]
    }
  ]
}
