{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha02.aar",
          "url": "lifecycle-livedata-2.5.0-alpha02.aar",
          "size": 11431,
          "sha512": "dc59903e472d70fdcb2ad5f036c783834cdebeae62b3d879cfc451833d4ec2bdd7e41ce9fd808e20fbea84a694cea204c9971e8e53cb9a4dfc3aca1758189fd8",
          "sha256": "b5b93df5b0356e6e1043357269f3f878e578aa61493ddeb8a4d9c565642e5ba7",
          "sha1": "88db64535ac7b1f2a43fbc486537e0eda823e81e",
          "md5": "34ca769b0b6f6278cc6473d5342e4f9a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha02.aar",
          "url": "lifecycle-livedata-2.5.0-alpha02.aar",
          "size": 11431,
          "sha512": "dc59903e472d70fdcb2ad5f036c783834cdebeae62b3d879cfc451833d4ec2bdd7e41ce9fd808e20fbea84a694cea204c9971e8e53cb9a4dfc3aca1758189fd8",
          "sha256": "b5b93df5b0356e6e1043357269f3f878e578aa61493ddeb8a4d9c565642e5ba7",
          "sha1": "88db64535ac7b1f2a43fbc486537e0eda823e81e",
          "md5": "34ca769b0b6f6278cc6473d5342e4f9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha02-sources.jar",
          "url": "lifecycle-livedata-2.5.0-alpha02-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
