{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose-samples",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.6.0-alpha01.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.6.0-alpha01.aar",
          "size": 41032,
          "sha512": "8d1630f52306de152d395cdd3413aea5ae219e97e52a7ce2ee75cacb03b8f6bc6f124a9153d1b7ef58d3a939e39d4f1f9fa5b4568e2d29e11b111d8724286643",
          "sha256": "dc7d1d8787adde21d6d6cfaab40ac662a902a781e8e52e52f99bd7d110aec300",
          "sha1": "f17003973a2bf31104e8227363811916fa457501",
          "md5": "0abf4627147ecd5edaee5b7504b914db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.6.0-alpha01.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.6.0-alpha01.aar",
          "size": 41032,
          "sha512": "8d1630f52306de152d395cdd3413aea5ae219e97e52a7ce2ee75cacb03b8f6bc6f124a9153d1b7ef58d3a939e39d4f1f9fa5b4568e2d29e11b111d8724286643",
          "sha256": "dc7d1d8787adde21d6d6cfaab40ac662a902a781e8e52e52f99bd7d110aec300",
          "sha1": "f17003973a2bf31104e8227363811916fa457501",
          "md5": "0abf4627147ecd5edaee5b7504b914db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.6.0-alpha01-sources.jar",
          "url": "lifecycle-viewmodel-compose-samples-2.6.0-alpha01-sources.jar",
          "size": 3379,
          "sha512": "71bc321f7f42099ae8f1e6d341f23b8dcd483ea400203cf5ef629c37b0a2f2f704a334d01d7504f067b911fda251851491a2dd21360e275589d92475428a8ab3",
          "sha256": "448ea500e9b2e4b813f1930f06e0de094c5b9fd3e97a6aa97a9cea6119258058",
          "sha1": "a2098e51c34b521e091cdccaa6e3ba228ebc783a",
          "md5": "01b23ed76ba1fcd2795bea5847ddd553"
        }
      ]
    }
  ]
}