{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "2.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-alpha05.aar",
          "url": "lifecycle-viewmodel-compose-2.5.0-alpha05.aar",
          "size": 11813,
          "sha512": "a17ef6cad056cda0e7947d2d44b3a1f289490380a7ca0d8d7609a4269e648414b200b0b4a613d5850c5a90651890ba46dc466d35ab22754aec2960227bd41ec7",
          "sha256": "8a8b3a4227f3ef2d11bc1dd095beb5bcc1ca82d4a76d48c3bc8bfb634a4ead34",
          "sha1": "7fc82e7ad5ca698a508e4f63b45877f457904bf4",
          "md5": "5658751481a6cd2108649eaca7015e23"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-alpha05.aar",
          "url": "lifecycle-viewmodel-compose-2.5.0-alpha05.aar",
          "size": 11813,
          "sha512": "a17ef6cad056cda0e7947d2d44b3a1f289490380a7ca0d8d7609a4269e648414b200b0b4a613d5850c5a90651890ba46dc466d35ab22754aec2960227bd41ec7",
          "sha256": "8a8b3a4227f3ef2d11bc1dd095beb5bcc1ca82d4a76d48c3bc8bfb634a4ead34",
          "sha1": "7fc82e7ad5ca698a508e4f63b45877f457904bf4",
          "md5": "5658751481a6cd2108649eaca7015e23"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-alpha05-sources.jar",
          "url": "lifecycle-viewmodel-compose-2.5.0-alpha05-sources.jar",
          "size": 5353,
          "sha512": "87a95cd51f98eb4b5edf40289ec75352e14f8a3383e28ddef71cb01c7f0ba1905b59a5f2f50c6d9b28875a5bd51ff4897fe129032030aeff811a7e0785e72647",
          "sha256": "d39d3f8deea45086c6e0e7d64faa51d245634d49568abacea73f23fdd1f961ab",
          "sha1": "06a42df09926abe4eb34e752b2c7ccd0cba05d63",
          "md5": "7e25dde5d774fac3b29485b446f2946e"
        }
      ]
    }
  ]
}