{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha01.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha01.aar",
          "size": 10047,
          "sha512": "33912507df8e06b9759b3fb9fe7e7451e7c70b5f457de95aa1ed2c8873a3d888a899da78e8f3599ef97f927ca450905121987b974448d638df231b10cb6ffd4a",
          "sha256": "379742328f1e93c0330a833f55afb5eb9ca192f52aa574f2df4cdf004112f1cb",
          "sha1": "463b2a2f4d617df4a5ac11bbe6933fb60778d484",
          "md5": "df52824b17541fd08e6489e1cebf1a44"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha01.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha01.aar",
          "size": 10047,
          "sha512": "33912507df8e06b9759b3fb9fe7e7451e7c70b5f457de95aa1ed2c8873a3d888a899da78e8f3599ef97f927ca450905121987b974448d638df231b10cb6ffd4a",
          "sha256": "379742328f1e93c0330a833f55afb5eb9ca192f52aa574f2df4cdf004112f1cb",
          "sha1": "463b2a2f4d617df4a5ac11bbe6933fb60778d484",
          "md5": "df52824b17541fd08e6489e1cebf1a44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha01-sources.jar",
          "url": "lifecycle-livedata-core-2.5.0-alpha01-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}
