{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6501513"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha03.aar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha03.aar",
          "size": 7591,
          "sha512": "39c06f2e215b708abb16b17883a8f4a2c41b924f3b5b4bb02808b5750ca4ba56144e85b0ca4a25d440105119525b5ebbc3a14a907b265e661048f7cb551185e9",
          "sha256": "5ee32ec02022ff82dd260bd9d0808f887b590705b2e6357080ead41c54d86938",
          "sha1": "4cc91373f651f5fb2f056c317d5df6578f518dc3",
          "md5": "b01f724826e01249ae60bf20e8bc0b56"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha03.aar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha03.aar",
          "size": 7591,
          "sha512": "39c06f2e215b708abb16b17883a8f4a2c41b924f3b5b4bb02808b5750ca4ba56144e85b0ca4a25d440105119525b5ebbc3a14a907b265e661048f7cb551185e9",
          "sha256": "5ee32ec02022ff82dd260bd9d0808f887b590705b2e6357080ead41c54d86938",
          "sha1": "4cc91373f651f5fb2f056c317d5df6578f518dc3",
          "md5": "b01f724826e01249ae60bf20e8bc0b56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha03-sources.jar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha03-sources.jar",
          "size": 1809,
          "sha512": "85d5e06438ec35aaeee972795ee55b315c3bee5bb5bdbeebdf09785dad5c73c003adad00a94e3cee71b820bd3f1df337f3290e8032e48bfb2a007e89badae94b",
          "sha256": "f97e2b220a76e4c873132978c3cf668e66b9e5299f3ae8fa0f647b85d16150d3",
          "sha1": "7952288ebf7757e9238984e4f927aed0ac5c6b6c",
          "md5": "c66286898d7af679c567208f7f42d3f2"
        }
      ]
    }
  ]
}
