{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "2.6.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.6.0-beta01.aar",
          "url": "lifecycle-viewmodel-compose-2.6.0-beta01.aar",
          "size": 22184,
          "sha512": "29d9b3a85e5b24af8589c495e3c238d0d7231e86f18db7b88d7fc307d9b430a0d061c08a0f56ca5beb859196a05c44decd9af5132405d5931ac9eae7a903b79d",
          "sha256": "402765fb45adfec3483e2f1e54dad36a822586cc9fb3b80a8a7cad4d6f390204",
          "sha1": "683c72a57bf6fb1f85fb211e458af2080845f032",
          "md5": "68cb45bc6c1753b53a3ebd99ae51f3ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.6.0-beta01.aar",
          "url": "lifecycle-viewmodel-compose-2.6.0-beta01.aar",
          "size": 22184,
          "sha512": "29d9b3a85e5b24af8589c495e3c238d0d7231e86f18db7b88d7fc307d9b430a0d061c08a0f56ca5beb859196a05c44decd9af5132405d5931ac9eae7a903b79d",
          "sha256": "402765fb45adfec3483e2f1e54dad36a822586cc9fb3b80a8a7cad4d6f390204",
          "sha1": "683c72a57bf6fb1f85fb211e458af2080845f032",
          "md5": "68cb45bc6c1753b53a3ebd99ae51f3ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.6.0-beta01-sources.jar",
          "url": "lifecycle-viewmodel-compose-2.6.0-beta01-sources.jar",
          "size": 6396,
          "sha512": "3b5447825c7f6a7a07fcf51378434317fe244b776ce76ec466a8516fa72b2aaaa5b8fd3878dd53f794a84a343b4eefd436ba80e6b5939afe9233d5a724ac1c3c",
          "sha256": "a1b03aa42a3bfec09a42a4dc7dfdef64e89d84c70c9208b347f52b7e2950cc3d",
          "sha1": "391e6f5d454ca22eafbe525e3c1f2684a089ebab",
          "md5": "599af6caf5b10313327915b8e109daef"
        }
      ]
    }
  ]
}