{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-process",
    "version": "2.6.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.6.0-alpha04.aar",
          "url": "lifecycle-process-2.6.0-alpha04.aar",
          "size": 12965,
          "sha512": "53931599e8e45906521de07f07ca05c20bbf8450366ecb5fc7b18652382f2e21311b20d05b0ecd5d3da5d88ef4790c394d7e7589488b3f4e73b1e3b1d1c028a2",
          "sha256": "eee80b402d2d73d28cf96fe7a5348661858d63ae926489ae4abac747d15eda07",
          "sha1": "f13593f71ee6e45ebb93e7cd737ebe60c7ba6b2f",
          "md5": "c2bfeea761453c66154af7df34dc1a55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.6.0-alpha04.aar",
          "url": "lifecycle-process-2.6.0-alpha04.aar",
          "size": 12965,
          "sha512": "53931599e8e45906521de07f07ca05c20bbf8450366ecb5fc7b18652382f2e21311b20d05b0ecd5d3da5d88ef4790c394d7e7589488b3f4e73b1e3b1d1c028a2",
          "sha256": "eee80b402d2d73d28cf96fe7a5348661858d63ae926489ae4abac747d15eda07",
          "sha1": "f13593f71ee6e45ebb93e7cd737ebe60c7ba6b2f",
          "md5": "c2bfeea761453c66154af7df34dc1a55"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-process-2.6.0-alpha04-sources.jar",
          "url": "lifecycle-process-2.6.0-alpha04-sources.jar",
          "size": 5706,
          "sha512": "089ecc45df716c225d86efb9b5ccce793373158b3bd65bda0552eac474466a512347ef756c14d4a9a565434240d5e5d2ee47c31dcec8b60ffef6496284f5285c",
          "sha256": "b3486fc64edb0b62ed924ccec7e87d979b940c654743a0154d429a3559a045bf",
          "sha1": "6fda29a2b792bbfc329763a3eb41f60834f2c439",
          "md5": "fc9778393b4b2102215176ec213a09cb"
        }
      ]
    }
  ]
}