{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-common",
    "version": "2.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-common-2.6.0-alpha05.jar",
          "url": "lifecycle-common-2.6.0-alpha05.jar",
          "size": 29871,
          "sha512": "741f5cd6c8724c1c79eb07b4aab5489642ddab339b5d2bd68e8044efa213fde0e2f63ff575139dc1cc3a8ff152debef5f171e4951dd8386b9c1379cb2145072b",
          "sha256": "6ef104f3d2a0126743711976d5de0d9834044acc745c7e501e2e55df4451b7ef",
          "sha1": "173637255bca2d94abea11c3519d5dfd5deab2bd",
          "md5": "2c6489aeca5c7451c3dcfadd6a8f103c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-common-2.6.0-alpha05.jar",
          "url": "lifecycle-common-2.6.0-alpha05.jar",
          "size": 29871,
          "sha512": "741f5cd6c8724c1c79eb07b4aab5489642ddab339b5d2bd68e8044efa213fde0e2f63ff575139dc1cc3a8ff152debef5f171e4951dd8386b9c1379cb2145072b",
          "sha256": "6ef104f3d2a0126743711976d5de0d9834044acc745c7e501e2e55df4451b7ef",
          "sha1": "173637255bca2d94abea11c3519d5dfd5deab2bd",
          "md5": "2c6489aeca5c7451c3dcfadd6a8f103c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-common-2.6.0-alpha05-sources.jar",
          "url": "lifecycle-common-2.6.0-alpha05-sources.jar",
          "size": 18065,
          "sha512": "3e82b374fc92e31d97a4f2c9951e33f29f2e8c9aebba47c880cf3d223867717551212a1c5cc47cfa9f2b3fa8dcd2d28ee130f08e6209cabf73f8a04f1ba84e96",
          "sha256": "b40690ba5b1283686d3b3c24fcd697f6926f7464d27efdfb39fdb90213ac5056",
          "sha1": "f0c15beda4bf95b55449cfe0a773b1d58a9168ef",
          "md5": "248fa61ab0d1ca43d34b9252b73d395b"
        }
      ]
    }
  ]
}