{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-alpha02.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-alpha02.aar",
          "size": 16328,
          "sha512": "3dacfc1f22b504f23d3cbc7ba52018dc496c4fec61923548d23bcd2d752f5853257ab56443246393e86efb1c373fd0f69fcf117cf54d57d10bc9187bc5a1b5e4",
          "sha256": "fee472af027c4dd8eced201a7e268b08242ae3cc80e01881b7af1abb855b93bb",
          "sha1": "a148d148316ae65fffc8973fe1fee7185290541e",
          "md5": "a05095f42ed44800f2e5ab5bb53de96e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-alpha02.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-alpha02.aar",
          "size": 16328,
          "sha512": "3dacfc1f22b504f23d3cbc7ba52018dc496c4fec61923548d23bcd2d752f5853257ab56443246393e86efb1c373fd0f69fcf117cf54d57d10bc9187bc5a1b5e4",
          "sha256": "fee472af027c4dd8eced201a7e268b08242ae3cc80e01881b7af1abb855b93bb",
          "sha1": "a148d148316ae65fffc8973fe1fee7185290541e",
          "md5": "a05095f42ed44800f2e5ab5bb53de96e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-alpha02-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-alpha02-sources.jar",
          "size": 1631,
          "sha512": "aec27370748b879276405755e63a377e08307bfe2f370687ee18fa5c43cb5e203fe5e3bcc9cda40390c872bf279e96bc2bae2f0a9e2ee631f861b2ad0e54c0ae",
          "sha256": "b7a2a7c66a58440b0ba30c68abe17074836f217123fb6ea728279834641a7c77",
          "sha1": "0ec507705520b7ddccce7da52bbf5abd9ecd1808",
          "md5": "c552138cfc58a3f4d73c8acbb66e4a86"
        }
      ]
    }
  ]
}
