{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.4.0-beta01.aar",
          "url": "activity-ktx-1.4.0-beta01.aar",
          "size": 30005,
          "sha512": "5806ba556d89b58aee24280a0bd88d5560ca0fe9023c64a2549997bd85989594ed009ceb992c5cd5632bc1379ed3f6767bb578af9862e6b1338995680feda421",
          "sha256": "7e2926a21f78e6ed25567e3ee1ffe55ebbd018d37a6518a4af7dcc03767a222b",
          "sha1": "85a72a257699b3dee584154a8b7ce2fd455fa4cc",
          "md5": "97e65cdd1337172fdf5acd7498e19796"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.4.0-beta01.aar",
          "url": "activity-ktx-1.4.0-beta01.aar",
          "size": 30005,
          "sha512": "5806ba556d89b58aee24280a0bd88d5560ca0fe9023c64a2549997bd85989594ed009ceb992c5cd5632bc1379ed3f6767bb578af9862e6b1338995680feda421",
          "sha256": "7e2926a21f78e6ed25567e3ee1ffe55ebbd018d37a6518a4af7dcc03767a222b",
          "sha1": "85a72a257699b3dee584154a8b7ce2fd455fa4cc",
          "md5": "97e65cdd1337172fdf5acd7498e19796"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.4.0-beta01-sources.jar",
          "url": "activity-ktx-1.4.0-beta01-sources.jar",
          "size": 7767,
          "sha512": "5d813443ac6d811e43d27cb20da46ca2b00d8ae2b67d7afe0c1d8cc0426401fa3fa3931d18398dbffd4a802b1e7e00015f105fff8d06c3664081807d86ae3122",
          "sha256": "c82f0974410b4442695d84c4504cd93efb45adfce625ea469c8134e8679f0c7a",
          "sha1": "3906b867d26e0c0c6e60215a0925e3d2f0c016e2",
          "md5": "89fc20347b040f6cc077ac6fc9e9ff34"
        }
      ]
    }
  ]
}
