{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-beta01.aar",
          "url": "lifecycle-viewmodel-compose-2.5.0-beta01.aar",
          "size": 20847,
          "sha512": "0dad7e4a7ae4e632b0266762a1cfcba7adae94e8b6f844e82c98c332abfbb42e5f15df39353b5cdd5dad265a26448252381438093085ec4dd40377710959ba06",
          "sha256": "d9d5d476856e7dbae875ca0a92f32184aa3a807b09e67422ab7f443e4055b25c",
          "sha1": "91734a93582de0938c30dc444209b000efc06e28",
          "md5": "3237e0411eb2da6e4657c37535100359"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-beta01.aar",
          "url": "lifecycle-viewmodel-compose-2.5.0-beta01.aar",
          "size": 20847,
          "sha512": "0dad7e4a7ae4e632b0266762a1cfcba7adae94e8b6f844e82c98c332abfbb42e5f15df39353b5cdd5dad265a26448252381438093085ec4dd40377710959ba06",
          "sha256": "d9d5d476856e7dbae875ca0a92f32184aa3a807b09e67422ab7f443e4055b25c",
          "sha1": "91734a93582de0938c30dc444209b000efc06e28",
          "md5": "3237e0411eb2da6e4657c37535100359"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.5.0-beta01-sources.jar",
          "url": "lifecycle-viewmodel-compose-2.5.0-beta01-sources.jar",
          "size": 6399,
          "sha512": "6ba6428c10ae6dd2e1c3c9f50488ba88d24b2ba59efff1d63a0283a2536d33e0a029209190e1c479ddbe4d9da96c3ff786f6f416bffb53b0d784b800d699dc81",
          "sha256": "bf6ed5adb2c598650ef2637b0829bcac911a8ef3f068680b47337bbf20d33865",
          "sha1": "7a6970be52a10accf604976a4ba7acf5b2459525",
          "md5": "bf77e633e58e57d9bd5d5ee8dc3dd3b8"
        }
      ]
    }
  ]
}