{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose-samples",
    "version": "2.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-alpha02.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-alpha02.aar",
          "size": 1793,
          "sha512": "ce2d1092c1a101a1694e128f86d136d7c3688ff0109d49e260d16d737c1e9899fc9010f936a1dfd5db1927017292d492b60cd6eb228cbfbf1b615de168a38f55",
          "sha256": "745fabe153b39440b09b363e241a49b71165448c8b969700d29aa1fb1e65b41e",
          "sha1": "d2380bf2948642167c77eb42c47b6a28a1cd58b9",
          "md5": "f68a66c3203eabb4f2485f20695fa084"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-alpha02.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-alpha02.aar",
          "size": 1793,
          "sha512": "ce2d1092c1a101a1694e128f86d136d7c3688ff0109d49e260d16d737c1e9899fc9010f936a1dfd5db1927017292d492b60cd6eb228cbfbf1b615de168a38f55",
          "sha256": "745fabe153b39440b09b363e241a49b71165448c8b969700d29aa1fb1e65b41e",
          "sha1": "d2380bf2948642167c77eb42c47b6a28a1cd58b9",
          "md5": "f68a66c3203eabb4f2485f20695fa084"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-alpha02-sources.jar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-alpha02-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
