{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.6.0-alpha01.aar",
          "url": "lifecycle-reactivestreams-ktx-2.6.0-alpha01.aar",
          "size": 3638,
          "sha512": "f72eca85c878fa65fc1de2bbf889ac22c502acc725c9f4b5735b04aa21f73a25cae869ff3eef207d4707301a95b494e65a41b41c5cbcc453c7d352d14ce906f1",
          "sha256": "429ac6971eeaeff57c158866bc2347dd7d414076d3a96e74f105bbc74e8dd5fd",
          "sha1": "51b299247500097b76c0320525b1c60cfd503e2e",
          "md5": "a6fae6871890669bea676e94f553abd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.6.0-alpha01.aar",
          "url": "lifecycle-reactivestreams-ktx-2.6.0-alpha01.aar",
          "size": 3638,
          "sha512": "f72eca85c878fa65fc1de2bbf889ac22c502acc725c9f4b5735b04aa21f73a25cae869ff3eef207d4707301a95b494e65a41b41c5cbcc453c7d352d14ce906f1",
          "sha256": "429ac6971eeaeff57c158866bc2347dd7d414076d3a96e74f105bbc74e8dd5fd",
          "sha1": "51b299247500097b76c0320525b1c60cfd503e2e",
          "md5": "a6fae6871890669bea676e94f553abd7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.6.0-alpha01-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.6.0-alpha01-sources.jar",
          "size": 1261,
          "sha512": "bb0f402ed24247b2fd8e5ecbfec147427d84a8f18bf21cb5857c1fee5746e2a97febac326c894484fe6e86a515fe1bfd05c3b1538eb3f0f1cce712f280a76861",
          "sha256": "c50b9f047a5b5d5ee5d330b3e2dc45f4ae8deca41f607d1d495792c89e731048",
          "sha1": "23c53fd2626cac61baac62c95dec1c49046e0261",
          "md5": "5d68075becef226fa5ce3a00a8721ea7"
        }
      ]
    }
  ]
}