{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pinterest.ktlint",
    "module": "ktlint-reporter-checkstyle",
    "version": "0.46.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-reporter-checkstyle-0.46.0-SNAPSHOT.jar",
          "url": "ktlint-reporter-checkstyle-0.46.0-SNAPSHOT.jar",
          "size": 6917,
          "sha512": "6cf67cd34b127c0c30af046ec01f1e0dc769ccd10eba010c05ac82155d3e4af6eca916a93d3852a22d9c519c78490b9a23c53774088a626c0599144e48b63eeb",
          "sha256": "c3162217d9417da0392f18005e37464d7126ced6eba4a0e3782d7bec3f21c36f",
          "sha1": "4d2c2d5668f5de3aaa7db675ac42ec2ea883907a",
          "md5": "a4496559765601c9b86bc2984f3d41b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pinterest.ktlint",
          "module": "ktlint-core",
          "version": {
            "requires": "0.46.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "ktlint-reporter-checkstyle-0.46.0-SNAPSHOT.jar",
          "url": "ktlint-reporter-checkstyle-0.46.0-SNAPSHOT.jar",
          "size": 6917,
          "sha512": "6cf67cd34b127c0c30af046ec01f1e0dc769ccd10eba010c05ac82155d3e4af6eca916a93d3852a22d9c519c78490b9a23c53774088a626c0599144e48b63eeb",
          "sha256": "c3162217d9417da0392f18005e37464d7126ced6eba4a0e3782d7bec3f21c36f",
          "sha1": "4d2c2d5668f5de3aaa7db675ac42ec2ea883907a",
          "md5": "a4496559765601c9b86bc2984f3d41b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-reporter-checkstyle-0.46.0-SNAPSHOT-sources.jar",
          "url": "ktlint-reporter-checkstyle-0.46.0-SNAPSHOT-sources.jar",
          "size": 2435,
          "sha512": "87d42aff091c1bb488ef95c2a772ac2bed6e6eabc7ea25550c8a53b2fa900e2029d719945abe6bf85c931e1af7a85b05b947fc00957d6e89d1afd039fef2ec37",
          "sha256": "e86d1b6a033696747d551cd4b84fec9944443869d027dbd098126866b847b9e0",
          "sha1": "f775b90e6066bcc053ceb9627b956d374845a778",
          "md5": "7ef1c2e9ce1d2c4d0e56b8447d6ff956"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktlint-reporter-checkstyle-0.46.0-SNAPSHOT-javadoc.jar",
          "url": "ktlint-reporter-checkstyle-0.46.0-SNAPSHOT-javadoc.jar",
          "size": 269722,
          "sha512": "96885a839cfa2c67ba7eb30db42aec90b323df54c476db4be2a169b563f61fee4b9af5d5868f49227b1a7c953f475092e1ea4ade23c97c20100876f5e91b108d",
          "sha256": "f71b8518c2d6978021cc0b2eb7f9a4ef7219ee24da4092d9c1d6f6033ef4b19a",
          "sha1": "c62925cfcaa18ac2b064641585759478f675f87b",
          "md5": "aeff55ef414ca453bc7381990d53c22a"
        }
      ]
    }
  ]
}
