{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-beta01.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-beta01.aar",
          "size": 19632,
          "sha512": "914e0690d055134b90c8401a1ae18f7f9d52fe9d47ca62ce7e1724373e9fd982a69486f73a570f4dd09868ccc80e91349a0b7edf3c2ee95824ed1dd570611245",
          "sha256": "c76f9dcff0f8c47f9e6c6c9c9168b3bc6824031f6aeb1ea9fa7e62db5ad528fe",
          "sha1": "01a0a4357f2d0bc8481efb96a7906829f341c19d",
          "md5": "16a5c980c352503130d7ea30e763b296"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-beta01.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-beta01.aar",
          "size": 19632,
          "sha512": "914e0690d055134b90c8401a1ae18f7f9d52fe9d47ca62ce7e1724373e9fd982a69486f73a570f4dd09868ccc80e91349a0b7edf3c2ee95824ed1dd570611245",
          "sha256": "c76f9dcff0f8c47f9e6c6c9c9168b3bc6824031f6aeb1ea9fa7e62db5ad528fe",
          "sha1": "01a0a4357f2d0bc8481efb96a7906829f341c19d",
          "md5": "16a5c980c352503130d7ea30e763b296"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-beta01-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-beta01-sources.jar",
          "size": 1631,
          "sha512": "aec27370748b879276405755e63a377e08307bfe2f370687ee18fa5c43cb5e203fe5e3bcc9cda40390c872bf279e96bc2bae2f0a9e2ee631f861b2ad0e54c0ae",
          "sha256": "b7a2a7c66a58440b0ba30c68abe17074836f217123fb6ea728279834641a7c77",
          "sha1": "0ec507705520b7ddccce7da52bbf5abd9ecd1808",
          "md5": "c552138cfc58a3f4d73c8acbb66e4a86"
        }
      ]
    }
  ]
}