{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "2.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.6.0-alpha05.aar",
          "url": "lifecycle-viewmodel-compose-2.6.0-alpha05.aar",
          "size": 22220,
          "sha512": "99ac1a50ff4fccb5fed3fa7a3e249ef698a39005fe8ee28635634b0349b8ef376b702a2d67ebc05f6b1a992c5805ef0817b965323df6901610ec74ec66f1fe25",
          "sha256": "a294d2c86cc4a7baf83c0b22b67393292c6e7873de71f3f5beabf1965726a025",
          "sha1": "40cc7cfac4aca21e8c076e3529bfe1045f92eb81",
          "md5": "5b4d75232df2993b8068448901433937"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.6.0-alpha05.aar",
          "url": "lifecycle-viewmodel-compose-2.6.0-alpha05.aar",
          "size": 22220,
          "sha512": "99ac1a50ff4fccb5fed3fa7a3e249ef698a39005fe8ee28635634b0349b8ef376b702a2d67ebc05f6b1a992c5805ef0817b965323df6901610ec74ec66f1fe25",
          "sha256": "a294d2c86cc4a7baf83c0b22b67393292c6e7873de71f3f5beabf1965726a025",
          "sha1": "40cc7cfac4aca21e8c076e3529bfe1045f92eb81",
          "md5": "5b4d75232df2993b8068448901433937"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.6.0-alpha05-sources.jar",
          "url": "lifecycle-viewmodel-compose-2.6.0-alpha05-sources.jar",
          "size": 6396,
          "sha512": "3b5447825c7f6a7a07fcf51378434317fe244b776ce76ec466a8516fa72b2aaaa5b8fd3878dd53f794a84a343b4eefd436ba80e6b5939afe9233d5a724ac1c3c",
          "sha256": "a1b03aa42a3bfec09a42a4dc7dfdef64e89d84c70c9208b347f52b7e2950cc3d",
          "sha1": "391e6f5d454ca22eafbe525e3c1f2684a089ebab",
          "md5": "599af6caf5b10313327915b8e109daef"
        }
      ]
    }
  ]
}