{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7123292"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-1.0.0-alpha01.aar",
          "url": "lifecycle-viewmodel-compose-1.0.0-alpha01.aar",
          "size": 17907,
          "sha512": "10a736a23066a77840e75a1d4640cff1555f0ffbabfc2f7b81cbee6bb41b953ad5df8659b7c82581025b3a6c51c70a5b9ada68b3b59c75b8ea0689fec96f62f3",
          "sha256": "a56185cfafdc652297dbf2db5314774334eba6e4ccf4516a4d6c2a78ec22e8e3",
          "sha1": "423bacd0ddc4bf455762188279497e685a4146da",
          "md5": "d13d995726d4e66cf380aa50d3ab875c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-1.0.0-alpha01.aar",
          "url": "lifecycle-viewmodel-compose-1.0.0-alpha01.aar",
          "size": 17907,
          "sha512": "10a736a23066a77840e75a1d4640cff1555f0ffbabfc2f7b81cbee6bb41b953ad5df8659b7c82581025b3a6c51c70a5b9ada68b3b59c75b8ea0689fec96f62f3",
          "sha256": "a56185cfafdc652297dbf2db5314774334eba6e4ccf4516a4d6c2a78ec22e8e3",
          "sha1": "423bacd0ddc4bf455762188279497e685a4146da",
          "md5": "d13d995726d4e66cf380aa50d3ab875c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-1.0.0-alpha01-sources.jar",
          "url": "lifecycle-viewmodel-compose-1.0.0-alpha01-sources.jar",
          "size": 2819,
          "sha512": "0fec074061604960a7e488653a989e02ef2b41bdca00eb3ae80556dcca89bc2c5126d8f23aaa37329454a757b670861ec736261641ada0c283fcdc7fb76d8d83",
          "sha256": "33cc381b251ca3a9c4cbf5b21f6e95331b89b3dc87f77fa4df078b8b27e2746c",
          "sha1": "d2a67ea26c97c6261f6a3edb944dae5930dd0fee",
          "md5": "5a6fd82fd77c82fae879e7dcc11bbe10"
        }
      ]
    }
  ]
}
