{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.4.0-rc01.aar",
          "url": "lifecycle-livedata-2.4.0-rc01.aar",
          "size": 11002,
          "sha512": "7d99d26a12ec89fc14fcb428b0e2d3792cdf66a7291874385d34c05fd4d64105285b79d5dbb40f52f3743d56b0c73cadfe4cbd8f9e10780aa194bad00728452e",
          "sha256": "d4a854f5cd102b1fd91e7a3a7f9d7b2f13e59cf4b5a822e67197aafc74d34f6e",
          "sha1": "cfa55b21b144c898818cbfc5e4d326395cbba53c",
          "md5": "45410fb0b82174e93836819a54514d68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.4.0-rc01.aar",
          "url": "lifecycle-livedata-2.4.0-rc01.aar",
          "size": 11002,
          "sha512": "7d99d26a12ec89fc14fcb428b0e2d3792cdf66a7291874385d34c05fd4d64105285b79d5dbb40f52f3743d56b0c73cadfe4cbd8f9e10780aa194bad00728452e",
          "sha256": "d4a854f5cd102b1fd91e7a3a7f9d7b2f13e59cf4b5a822e67197aafc74d34f6e",
          "sha1": "cfa55b21b144c898818cbfc5e4d326395cbba53c",
          "md5": "45410fb0b82174e93836819a54514d68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.4.0-rc01-sources.jar",
          "url": "lifecycle-livedata-2.4.0-rc01-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
