{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha03.aar",
          "url": "lifecycle-service-2.5.0-alpha03.aar",
          "size": 4365,
          "sha512": "5c7215f99c25d14e0c5956915df3e022c9a2bbd5b1144d5d2effc6c4ace0d852b6fce7721723f07a3aaf497497be148eaf60258e44a6c94a7a46dd045920f2dd",
          "sha256": "7c638a21fae55192dae7d0255505ad45f41a5fd59410a0faffa16413299d2cf2",
          "sha1": "a5ac330d8cd89074b01a28223143e565a2880c4f",
          "md5": "104801aba7ec61e86b02a8961bf926e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha03.aar",
          "url": "lifecycle-service-2.5.0-alpha03.aar",
          "size": 4365,
          "sha512": "5c7215f99c25d14e0c5956915df3e022c9a2bbd5b1144d5d2effc6c4ace0d852b6fce7721723f07a3aaf497497be148eaf60258e44a6c94a7a46dd045920f2dd",
          "sha256": "7c638a21fae55192dae7d0255505ad45f41a5fd59410a0faffa16413299d2cf2",
          "sha1": "a5ac330d8cd89074b01a28223143e565a2880c4f",
          "md5": "104801aba7ec61e86b02a8961bf926e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha03-sources.jar",
          "url": "lifecycle-service-2.5.0-alpha03-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
