{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-process",
    "version": "2.5.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.5.0-rc02.aar",
          "url": "lifecycle-process-2.5.0-rc02.aar",
          "size": 10560,
          "sha512": "c1866009f5ea5639c9332877fd8f1604572b939b4094779ede5988b6b431ca1e5fcc0aa4cc8d978c56d5957dcbe492b2a7f8b367b5f2e1937936eecff30bf3cc",
          "sha256": "7331257a1ac3c339e54439cf1a9d04f1cd841da4783d1aaa4a2ea9cfbe0cdaf2",
          "sha1": "0be32d3d27773dff368c392d3cf0573baf07f957",
          "md5": "dbf0a57864adf41579177a0af83bb578"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.5.0-rc02.aar",
          "url": "lifecycle-process-2.5.0-rc02.aar",
          "size": 10560,
          "sha512": "c1866009f5ea5639c9332877fd8f1604572b939b4094779ede5988b6b431ca1e5fcc0aa4cc8d978c56d5957dcbe492b2a7f8b367b5f2e1937936eecff30bf3cc",
          "sha256": "7331257a1ac3c339e54439cf1a9d04f1cd841da4783d1aaa4a2ea9cfbe0cdaf2",
          "sha1": "0be32d3d27773dff368c392d3cf0573baf07f957",
          "md5": "dbf0a57864adf41579177a0af83bb578"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-process-2.5.0-rc02-sources.jar",
          "url": "lifecycle-process-2.5.0-rc02-sources.jar",
          "size": 5906,
          "sha512": "ce90d34c102d83719416317ec6329e10256c3a646f88afedab555f0a4957704876f8f13e086e78e5a4d734e5d1606b1e328c961e7418cfb3d0457d9c78fe7736",
          "sha256": "b40b16492aa34faed4e34fb19f8d12afb79715eeb8ef098df4c5713647cd1a42",
          "sha1": "8fccf25901f65172f1380c9abc6cbbabe809fe6a",
          "md5": "53d76930af8c714cd452d8736b32f67b"
        }
      ]
    }
  ]
}