{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.6.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.6.0-alpha03.aar",
          "url": "lifecycle-service-2.6.0-alpha03.aar",
          "size": 5098,
          "sha512": "07295d925804bcea3aac004a3ce7ad10d6aae6334ddf3e593efa06ea12b549146b8abfe7e25c106e1ebf9555f4b5f026eb0f96fd9dd066bc32b88d2cda255bd1",
          "sha256": "fbf8c16745fdd734169351a2d494fe522f6a51c44faa4f9e345f4bbadb5a52ba",
          "sha1": "9d712b258c5d1eda14655bad1f7b4d88e42682e0",
          "md5": "443d6810f0a3360b19c57027deb93161"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.6.0-alpha03.aar",
          "url": "lifecycle-service-2.6.0-alpha03.aar",
          "size": 5098,
          "sha512": "07295d925804bcea3aac004a3ce7ad10d6aae6334ddf3e593efa06ea12b549146b8abfe7e25c106e1ebf9555f4b5f026eb0f96fd9dd066bc32b88d2cda255bd1",
          "sha256": "fbf8c16745fdd734169351a2d494fe522f6a51c44faa4f9e345f4bbadb5a52ba",
          "sha1": "9d712b258c5d1eda14655bad1f7b4d88e42682e0",
          "md5": "443d6810f0a3360b19c57027deb93161"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.6.0-alpha03-sources.jar",
          "url": "lifecycle-service-2.6.0-alpha03-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}