{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.5.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha06.aar",
          "url": "lifecycle-service-2.5.0-alpha06.aar",
          "size": 4366,
          "sha512": "ed0595e644e9b0569dc601c5ee7fbf04f50f0782b4be523966b5af4332b38c1d648a5520824c6395c51bfb2cba6ea883d60b34f96b524be18580a78354881cd8",
          "sha256": "9691193a55b70186e07d2b489af23a7112434456458ed446d5d5bdaeb28865bf",
          "sha1": "b1178e511e64845c6d4d54ed93ebcf9b6eeb7d0a",
          "md5": "47d128f905720c73c565a670ff20880c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha06.aar",
          "url": "lifecycle-service-2.5.0-alpha06.aar",
          "size": 4366,
          "sha512": "ed0595e644e9b0569dc601c5ee7fbf04f50f0782b4be523966b5af4332b38c1d648a5520824c6395c51bfb2cba6ea883d60b34f96b524be18580a78354881cd8",
          "sha256": "9691193a55b70186e07d2b489af23a7112434456458ed446d5d5bdaeb28865bf",
          "sha1": "b1178e511e64845c6d4d54ed93ebcf9b6eeb7d0a",
          "md5": "47d128f905720c73c565a670ff20880c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha06-sources.jar",
          "url": "lifecycle-service-2.5.0-alpha06-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}