{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-process",
    "version": "2.6.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.6.0-beta01.aar",
          "url": "lifecycle-process-2.6.0-beta01.aar",
          "size": 16105,
          "sha512": "bdc4149e38cd39d5d614dab8223be478838a24f531678453b7b5afe99d780f76f0a76777043b5066b8d31d4a6f699e462742afa5411b228e3a707d7f6af3b190",
          "sha256": "04b716f79822e6c19c27194cbebba8746cf114f3b61bae2819b2044268834062",
          "sha1": "a80912e93353be2d1f84aea38f143128530935f7",
          "md5": "71d5174f69c1831c71b44493429b83fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.6.0-beta01.aar",
          "url": "lifecycle-process-2.6.0-beta01.aar",
          "size": 16105,
          "sha512": "bdc4149e38cd39d5d614dab8223be478838a24f531678453b7b5afe99d780f76f0a76777043b5066b8d31d4a6f699e462742afa5411b228e3a707d7f6af3b190",
          "sha256": "04b716f79822e6c19c27194cbebba8746cf114f3b61bae2819b2044268834062",
          "sha1": "a80912e93353be2d1f84aea38f143128530935f7",
          "md5": "71d5174f69c1831c71b44493429b83fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-process-2.6.0-beta01-sources.jar",
          "url": "lifecycle-process-2.6.0-beta01-sources.jar",
          "size": 5598,
          "sha512": "ed8f8f56e3e1de91e8307d32b5f65fd9bfb66aca2f1729c728179c73002ef37546ee42cdf9f0cf30ca77571a94bec993e6a54a1eb334494a49db0c967ccd3c21",
          "sha256": "f6f6c2465bf5219798d64ed255a1768cf26547d56755c0cceb32e752a231f689",
          "sha1": "0dd039c5f2bbb7b39abdef48c2144039069b7bd7",
          "md5": "de3f744186869ca53646608d5b33903c"
        }
      ]
    }
  ]
}