{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-alpha02.aar",
          "url": "lifecycle-livedata-core-2.4.0-alpha02.aar",
          "size": 9667,
          "sha512": "ce1fbdb3242d56dde8d6ff816a7e14fcb197358f9e4271ef7e05e30daeadb76ae2ddc71ca07a19bacde60ae070fe71698e6ad7ba913ab0b46b599fc17462691f",
          "sha256": "fc6f4099bb35a9a700d4ada4cab1fcd0025d9606db6e0c369ad29cf3be2abf0a",
          "sha1": "5555afe1c4dd24df26e9a76f78681ab299fb1a2c",
          "md5": "02bc610363a0aeb039b3ccce18d1268d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-alpha02.aar",
          "url": "lifecycle-livedata-core-2.4.0-alpha02.aar",
          "size": 9667,
          "sha512": "ce1fbdb3242d56dde8d6ff816a7e14fcb197358f9e4271ef7e05e30daeadb76ae2ddc71ca07a19bacde60ae070fe71698e6ad7ba913ab0b46b599fc17462691f",
          "sha256": "fc6f4099bb35a9a700d4ada4cab1fcd0025d9606db6e0c369ad29cf3be2abf0a",
          "sha1": "5555afe1c4dd24df26e9a76f78681ab299fb1a2c",
          "md5": "02bc610363a0aeb039b3ccce18d1268d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-alpha02-sources.jar",
          "url": "lifecycle-livedata-core-2.4.0-alpha02-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}
