{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.4.0-alpha02.aar",
          "url": "lifecycle-runtime-testing-2.4.0-alpha02.aar",
          "size": 8484,
          "sha512": "c0c2ba56d1e78c7bb1998279bc982a77c912c33d1cfcde8453d2aa7bb11ccb112d2c5f9ea1f8e29b2fccc237e50a522d979a66d9f5bbc6b47510376af8da962a",
          "sha256": "adb8c8d8344e9a9433ab12c61ef2048863c07051c7595a96f29daeec9298b5eb",
          "sha1": "ce5442aee958b2b54cc8dd4914cc535be32122b0",
          "md5": "da2c6cf4a1ea19ac1789f8eceb247ad5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.4.0-alpha02.aar",
          "url": "lifecycle-runtime-testing-2.4.0-alpha02.aar",
          "size": 8484,
          "sha512": "c0c2ba56d1e78c7bb1998279bc982a77c912c33d1cfcde8453d2aa7bb11ccb112d2c5f9ea1f8e29b2fccc237e50a522d979a66d9f5bbc6b47510376af8da962a",
          "sha256": "adb8c8d8344e9a9433ab12c61ef2048863c07051c7595a96f29daeec9298b5eb",
          "sha1": "ce5442aee958b2b54cc8dd4914cc535be32122b0",
          "md5": "da2c6cf4a1ea19ac1789f8eceb247ad5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.4.0-alpha02-sources.jar",
          "url": "lifecycle-runtime-testing-2.4.0-alpha02-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}
