{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.5.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.5.0-alpha06.aar",
          "url": "lifecycle-viewmodel-2.5.0-alpha06.aar",
          "size": 34571,
          "sha512": "4d1b87875004bb37fde6dbaeb27d7ff844d02d89d1ea97290c3e8b799c676d66aa9d8bae694516bc60996f42de629f1c554b46aa5c646f6b94c2a82e5f571545",
          "sha256": "7503605437c53e9daed9cb8821da03db4188ad992ee43e535dc747b6de6dadf4",
          "sha1": "4d4726fad2d1c95e5fe63b04dbb09cf267971bb3",
          "md5": "eff649529fc4c05bb1550a8aba39db32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.5.0-alpha06.aar",
          "url": "lifecycle-viewmodel-2.5.0-alpha06.aar",
          "size": 34571,
          "sha512": "4d1b87875004bb37fde6dbaeb27d7ff844d02d89d1ea97290c3e8b799c676d66aa9d8bae694516bc60996f42de629f1c554b46aa5c646f6b94c2a82e5f571545",
          "sha256": "7503605437c53e9daed9cb8821da03db4188ad992ee43e535dc747b6de6dadf4",
          "sha1": "4d4726fad2d1c95e5fe63b04dbb09cf267971bb3",
          "md5": "eff649529fc4c05bb1550a8aba39db32"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-2.5.0-alpha06-sources.jar",
          "url": "lifecycle-viewmodel-2.5.0-alpha06-sources.jar",
          "size": 17218,
          "sha512": "d5732c2880bdeb97a35f567a476e94faca936d492f912827ba8d427d5e4874b7b314f8374f6f9ef74d2fd58ef3f1379aa0b2c1242b80741e9d9ffa02e6b13ad7",
          "sha256": "36f2f1851c2b8368bd5716003e893684bcc368b26df529cd310e0d3b0fa3e2d5",
          "sha1": "5b3fa761abf3169bc953609ea7e5f0c2abb0f6a5",
          "md5": "053cecbaa6b38dc80f3ea8bed0f1ca72"
        }
      ]
    }
  ]
}