{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-alpha05.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-alpha05.aar",
          "size": 16362,
          "sha512": "de90fc6264142abf4ad40ca1262f521327a9d66de7efb5797a2bad4f290aae659b94793e5386b50773952b729b55fa61c68f703fbc1e516b0e05d05577b62984",
          "sha256": "6a541b2af9af4917adc1806b54d9b39455f5d589c5a7c665a7503fd82f940eff",
          "sha1": "9b605320b34274767bba117497db743e16bd8873",
          "md5": "3f93984126cfbe3b756913f40ac29a50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-alpha05.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-alpha05.aar",
          "size": 16362,
          "sha512": "de90fc6264142abf4ad40ca1262f521327a9d66de7efb5797a2bad4f290aae659b94793e5386b50773952b729b55fa61c68f703fbc1e516b0e05d05577b62984",
          "sha256": "6a541b2af9af4917adc1806b54d9b39455f5d589c5a7c665a7503fd82f940eff",
          "sha1": "9b605320b34274767bba117497db743e16bd8873",
          "md5": "3f93984126cfbe3b756913f40ac29a50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-alpha05-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-alpha05-sources.jar",
          "size": 1631,
          "sha512": "aec27370748b879276405755e63a377e08307bfe2f370687ee18fa5c43cb5e203fe5e3bcc9cda40390c872bf279e96bc2bae2f0a9e2ee631f861b2ad0e54c0ae",
          "sha256": "b7a2a7c66a58440b0ba30c68abe17074836f217123fb6ea728279834641a7c77",
          "sha1": "0ec507705520b7ddccce7da52bbf5abd9ecd1808",
          "md5": "c552138cfc58a3f4d73c8acbb66e4a86"
        }
      ]
    }
  ]
}