{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha03.aar",
          "url": "lifecycle-livedata-2.5.0-alpha03.aar",
          "size": 11472,
          "sha512": "dbdcc41e7afc62f7e57a284aa2fa8dd4f43aa694cc1dfa7f821a8fb7250b93d902ca908804a03b6fc308dc3ca9196296ad9798390793a5090e11a534b39eebc2",
          "sha256": "6fc449546e0c9416910625526c6f925047d6f6a573f9c58f18cb9f60cb5b750b",
          "sha1": "049a52634e0bb9cabb2973c207f24d75dcf337f5",
          "md5": "b8cb4998e6209ed819e91922d364e7b7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha03.aar",
          "url": "lifecycle-livedata-2.5.0-alpha03.aar",
          "size": 11472,
          "sha512": "dbdcc41e7afc62f7e57a284aa2fa8dd4f43aa694cc1dfa7f821a8fb7250b93d902ca908804a03b6fc308dc3ca9196296ad9798390793a5090e11a534b39eebc2",
          "sha256": "6fc449546e0c9416910625526c6f925047d6f6a573f9c58f18cb9f60cb5b750b",
          "sha1": "049a52634e0bb9cabb2973c207f24d75dcf337f5",
          "md5": "b8cb4998e6209ed819e91922d364e7b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha03-sources.jar",
          "url": "lifecycle-livedata-2.5.0-alpha03-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
