{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-process",
    "version": "2.5.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.5.0-alpha06.aar",
          "url": "lifecycle-process-2.5.0-alpha06.aar",
          "size": 10564,
          "sha512": "3eade27e03ece8d244c3d6bf03bde23cff7c8f9391148a14e18c4bc75db8427d727b2ed11c36448fa8305ab38e1385018d55ad22fc248e4f3fbdc40b6088f4d4",
          "sha256": "46aa5fed591e7f8552e4bb353005069fc5f70bf34ea8a8df7f94aebe73176813",
          "sha1": "6b71f97a4f3800a21ba5961938327447023d35cf",
          "md5": "07f16b0b2be55ed6270e68ddff2b0453"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.5.0-alpha06.aar",
          "url": "lifecycle-process-2.5.0-alpha06.aar",
          "size": 10564,
          "sha512": "3eade27e03ece8d244c3d6bf03bde23cff7c8f9391148a14e18c4bc75db8427d727b2ed11c36448fa8305ab38e1385018d55ad22fc248e4f3fbdc40b6088f4d4",
          "sha256": "46aa5fed591e7f8552e4bb353005069fc5f70bf34ea8a8df7f94aebe73176813",
          "sha1": "6b71f97a4f3800a21ba5961938327447023d35cf",
          "md5": "07f16b0b2be55ed6270e68ddff2b0453"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-process-2.5.0-alpha06-sources.jar",
          "url": "lifecycle-process-2.5.0-alpha06-sources.jar",
          "size": 5906,
          "sha512": "ce90d34c102d83719416317ec6329e10256c3a646f88afedab555f0a4957704876f8f13e086e78e5a4d734e5d1606b1e328c961e7418cfb3d0457d9c78fe7736",
          "sha256": "b40b16492aa34faed4e34fb19f8d12afb79715eeb8ef098df4c5713647cd1a42",
          "sha1": "8fccf25901f65172f1380c9abc6cbbabe809fe6a",
          "md5": "53d76930af8c714cd452d8736b32f67b"
        }
      ]
    }
  ]
}