{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.4.0-rc01.aar",
          "url": "lifecycle-runtime-2.4.0-rc01.aar",
          "size": 11490,
          "sha512": "650c371e9c84c2aaadbf65c5f5073bb54d8454e41d7f756e9c2b99eda3d6f6bc48ab5e2c5ba8c84b911faf8eb230f816ae6e23a869e6267c55f8e465ee928a1e",
          "sha256": "7f118f493a712c115f086197e848cfb99cbea36fe2d04f2ea9de9f8336a4ae73",
          "sha1": "ea93f15fcbdaac31af4f6d4858b1a3394fe1d8c4",
          "md5": "00a29febb644b02e2efbdca8bdca089e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.4.0-rc01.aar",
          "url": "lifecycle-runtime-2.4.0-rc01.aar",
          "size": 11490,
          "sha512": "650c371e9c84c2aaadbf65c5f5073bb54d8454e41d7f756e9c2b99eda3d6f6bc48ab5e2c5ba8c84b911faf8eb230f816ae6e23a869e6267c55f8e465ee928a1e",
          "sha256": "7f118f493a712c115f086197e848cfb99cbea36fe2d04f2ea9de9f8336a4ae73",
          "sha1": "ea93f15fcbdaac31af4f6d4858b1a3394fe1d8c4",
          "md5": "00a29febb644b02e2efbdca8bdca089e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.4.0-rc01-sources.jar",
          "url": "lifecycle-runtime-2.4.0-rc01-sources.jar",
          "size": 8927,
          "sha512": "3a9f03beaffff0b273188c91a18f234962052eed4257f5b18b5098d09e2ed9799e3870b5b8cc63eeb429f03ef294f3109365c794bb84b11742048d1a1a0a4288",
          "sha256": "a1757f478939a9ae47e3a005f5c3ce051e50859d54478e3b931fdb06738269a9",
          "sha1": "ae7040cf314de81d20ac69f28f5ab6c9a2c0d1ab",
          "md5": "a34ad95ef12973e07a73efde45a2504e"
        }
      ]
    }
  ]
}
