{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-alpha03.aar",
          "url": "lifecycle-livedata-core-2.4.0-alpha03.aar",
          "size": 9451,
          "sha512": "66997ce5177df53971d1da47f2aadd263d12a242bbf89bb2d74515d7dde58f993274b3e17e14e82c6063675d70baabe52e32de5edae615ea8b17c4452fd64b65",
          "sha256": "7aae5fbf499da6c891ddc88019bd1d478765bc24b014c97ee3258db2a86b7880",
          "sha1": "c09e5a1bfdfb4e5b925f3b95e95ca8f2fe67a54e",
          "md5": "2b434d95c222c87eabf8fe889f200644"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-alpha03.aar",
          "url": "lifecycle-livedata-core-2.4.0-alpha03.aar",
          "size": 9451,
          "sha512": "66997ce5177df53971d1da47f2aadd263d12a242bbf89bb2d74515d7dde58f993274b3e17e14e82c6063675d70baabe52e32de5edae615ea8b17c4452fd64b65",
          "sha256": "7aae5fbf499da6c891ddc88019bd1d478765bc24b014c97ee3258db2a86b7880",
          "sha1": "c09e5a1bfdfb4e5b925f3b95e95ca8f2fe67a54e",
          "md5": "2b434d95c222c87eabf8fe889f200644"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-alpha03-sources.jar",
          "url": "lifecycle-livedata-core-2.4.0-alpha03-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}
