{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.6.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.6.0-beta01.aar",
          "url": "lifecycle-runtime-2.6.0-beta01.aar",
          "size": 21745,
          "sha512": "aa1c35aa82164022b70e1444f63f3f000ccb5e14a55b54ac04b91b75d95bf93b323dabdb9311105e93c27ecac6d87ca8ae6b2f993a6dff155cbfc35b95bdb6c6",
          "sha256": "53cb3e253239094fbbd657347bbeffa90fe0d24c5ce071b8fa98d034916aca3b",
          "sha1": "24c550e2306845331376de1649a994d13bb7a55a",
          "md5": "1ad964fa277a48716c79c1258abdc70c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0-rc01"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.2.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.6.0-beta01.aar",
          "url": "lifecycle-runtime-2.6.0-beta01.aar",
          "size": 21745,
          "sha512": "aa1c35aa82164022b70e1444f63f3f000ccb5e14a55b54ac04b91b75d95bf93b323dabdb9311105e93c27ecac6d87ca8ae6b2f993a6dff155cbfc35b95bdb6c6",
          "sha256": "53cb3e253239094fbbd657347bbeffa90fe0d24c5ce071b8fa98d034916aca3b",
          "sha1": "24c550e2306845331376de1649a994d13bb7a55a",
          "md5": "1ad964fa277a48716c79c1258abdc70c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.6.0-beta01-sources.jar",
          "url": "lifecycle-runtime-2.6.0-beta01-sources.jar",
          "size": 8601,
          "sha512": "6063b882107bcf76e6280797ce65e860274a97fb32de8cd8c2a4e356f2a35313436dbe1b1cb254070a1c0820089c31e7ad93bd42f80b49d6a160d1d7600cb17f",
          "sha256": "07129c61c68a7c4333aeabe1712827c33677f973db29bc11b99044463899b13d",
          "sha1": "f653a171fc041d7062a83c81458c12f0201bcd6f",
          "md5": "40db71daf9d0b4f55bfa265236a651fa"
        }
      ]
    }
  ]
}