{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.4.0-beta01.aar",
          "url": "lifecycle-reactivestreams-ktx-2.4.0-beta01.aar",
          "size": 2875,
          "sha512": "46706dee04bb75035271c2f8e9f162d08c0fdc60acaa8c7e39e8bef3c97452e854f7172b6c475c4fbf0c6e1379c9463644d67f0af20e0cbdb4bf3567ce7121c5",
          "sha256": "47cef5d97a29fd4440386e31a04faa8334e4d2f1fa74e21552b43a6343df0fcf",
          "sha1": "9ad54f20fec2ff15a2638cdedd06feb58041227b",
          "md5": "f990f84e40e48d527dc416c15e1387e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.4.0-beta01.aar",
          "url": "lifecycle-reactivestreams-ktx-2.4.0-beta01.aar",
          "size": 2875,
          "sha512": "46706dee04bb75035271c2f8e9f162d08c0fdc60acaa8c7e39e8bef3c97452e854f7172b6c475c4fbf0c6e1379c9463644d67f0af20e0cbdb4bf3567ce7121c5",
          "sha256": "47cef5d97a29fd4440386e31a04faa8334e4d2f1fa74e21552b43a6343df0fcf",
          "sha1": "9ad54f20fec2ff15a2638cdedd06feb58041227b",
          "md5": "f990f84e40e48d527dc416c15e1387e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.4.0-beta01-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.4.0-beta01-sources.jar",
          "size": 1261,
          "sha512": "bb0f402ed24247b2fd8e5ecbfec147427d84a8f18bf21cb5857c1fee5746e2a97febac326c894484fe6e86a515fe1bfd05c3b1538eb3f0f1cce712f280a76861",
          "sha256": "c50b9f047a5b5d5ee5d330b3e2dc45f4ae8deca41f607d1d495792c89e731048",
          "sha1": "23c53fd2626cac61baac62c95dec1c49046e0261",
          "md5": "5d68075becef226fa5ce3a00a8721ea7"
        }
      ]
    }
  ]
}
