{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-ktx",
    "version": "2.5.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-alpha06.aar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-alpha06.aar",
          "size": 4037,
          "sha512": "b6a553b90c1d3ffcf2a4535c9c64bdc8f3b6ba9473478ea415e71c4bc80cbf6faa918f99cbf41240a5fa0679f170d962e0d74f53392e27349892855a67a9d4c0",
          "sha256": "e0a636fde598e182b5b8524080603f7593a14faf306977126427c7b018c10f81",
          "sha1": "6a7ca2ba16dae8ddea1b7c186233762a31c17d61",
          "md5": "8d1e20abaa4efab8314b35bc1eff8fcf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-alpha06.aar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-alpha06.aar",
          "size": 4037,
          "sha512": "b6a553b90c1d3ffcf2a4535c9c64bdc8f3b6ba9473478ea415e71c4bc80cbf6faa918f99cbf41240a5fa0679f170d962e0d74f53392e27349892855a67a9d4c0",
          "sha256": "e0a636fde598e182b5b8524080603f7593a14faf306977126427c7b018c10f81",
          "sha1": "6a7ca2ba16dae8ddea1b7c186233762a31c17d61",
          "md5": "8d1e20abaa4efab8314b35bc1eff8fcf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-alpha06-sources.jar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-alpha06-sources.jar",
          "size": 1410,
          "sha512": "bfe6372c5910f626e7b41bb6468d62612d1f1bde9b3c767caaa7eb7c07e93cf00d047d8e909b7c47f2985f42ffa554a82888f83e712473cee8756407fcc09548",
          "sha256": "8af8f2ac694742fe8ae133067dfdec6a193a738f46ba80c59b3e8a4ab36703f3",
          "sha1": "a900dc99643d8638beb02bd809a495f772d457e7",
          "md5": "43d89db66da712ab2560a41753632946"
        }
      ]
    }
  ]
}