{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.4.0-alpha02.aar",
          "url": "lifecycle-runtime-2.4.0-alpha02.aar",
          "size": 11636,
          "sha512": "02fe62dcdbf22ebb44369b67d9295ab0bec0318e9b0d1fca0002530f583be1758067389ddc6e36e7d26e98bf24e82ccd5ea98e0bf39e35b311ae1ca71a7684f0",
          "sha256": "472aad75f69f1f43970eb809eacbe9ce2680559ee39bffc19f89bf58b956c595",
          "sha1": "1ed2d311a391d1e7883d2a71aa9afe37b4d642d7",
          "md5": "f4c4284904134b42bb3e6a6b6430f2e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.4.0-alpha02.aar",
          "url": "lifecycle-runtime-2.4.0-alpha02.aar",
          "size": 11636,
          "sha512": "02fe62dcdbf22ebb44369b67d9295ab0bec0318e9b0d1fca0002530f583be1758067389ddc6e36e7d26e98bf24e82ccd5ea98e0bf39e35b311ae1ca71a7684f0",
          "sha256": "472aad75f69f1f43970eb809eacbe9ce2680559ee39bffc19f89bf58b956c595",
          "sha1": "1ed2d311a391d1e7883d2a71aa9afe37b4d642d7",
          "md5": "f4c4284904134b42bb3e6a6b6430f2e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.4.0-alpha02-sources.jar",
          "url": "lifecycle-runtime-2.4.0-alpha02-sources.jar",
          "size": 8927,
          "sha512": "3a9f03beaffff0b273188c91a18f234962052eed4257f5b18b5098d09e2ed9799e3870b5b8cc63eeb429f03ef294f3109365c794bb84b11742048d1a1a0a4288",
          "sha256": "a1757f478939a9ae47e3a005f5c3ce051e50859d54478e3b931fdb06738269a9",
          "sha1": "ae7040cf314de81d20ac69f28f5ab6c9a2c0d1ab",
          "md5": "a34ad95ef12973e07a73efde45a2504e"
        }
      ]
    }
  ]
}
