{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-ktx",
    "version": "2.5.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.5.0-rc02.aar",
          "url": "lifecycle-runtime-ktx-2.5.0-rc02.aar",
          "size": 79846,
          "sha512": "6032cbb88edb24f9a0f8af6e3aa354b69b31811d84b7e6bd524a53d60068b11b3c2f2eb67203e4e43199b5d29371236931979b80c745f8b8af7ef565d90b6eea",
          "sha256": "661ab576d348053abbde2bf334a53e721ed9300ea5c9cc0eaa31259efc15467d",
          "sha1": "ccf4f240c0e9f324bac060d5b5e1ed2fee884307",
          "md5": "a54461fb6c9e563dacf5a41cf2bd8f6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.5.0-rc02.aar",
          "url": "lifecycle-runtime-ktx-2.5.0-rc02.aar",
          "size": 79846,
          "sha512": "6032cbb88edb24f9a0f8af6e3aa354b69b31811d84b7e6bd524a53d60068b11b3c2f2eb67203e4e43199b5d29371236931979b80c745f8b8af7ef565d90b6eea",
          "sha256": "661ab576d348053abbde2bf334a53e721ed9300ea5c9cc0eaa31259efc15467d",
          "sha1": "ccf4f240c0e9f324bac060d5b5e1ed2fee884307",
          "md5": "a54461fb6c9e563dacf5a41cf2bd8f6e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.5.0-rc02-sources.jar",
          "url": "lifecycle-runtime-ktx-2.5.0-rc02-sources.jar",
          "size": 14828,
          "sha512": "e970319d029eab328f11c9cf9f263f8aae0b958f2be8a6c6ee5fdc8e785a1ef8caf4de5e5a42e32394437d77605ebfa74d9018acba18287ecf12cdf5da809802",
          "sha256": "9c1d28b751c500263b5d4d81caf6bd541944d91e295df85273b09e7b7d0baed3",
          "sha1": "6d338022f8fa82c24121d5d249fe5daeeb297742",
          "md5": "6bd895cc45fa4ff72bfb62dfa2cc7602"
        }
      ]
    }
  ]
}