{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-beta01.aar",
          "url": "lifecycle-service-2.5.0-beta01.aar",
          "size": 4365,
          "sha512": "4f83c99c89e41b806bb2d3f78cb4ee0cd8ed159b7351c10d3218ae348661aad4a9bf4899c33a93f1d2ff6b8ae1feeef986b63a3d4a4c7359bc0a0777dfac7bb6",
          "sha256": "348f1e35cc34583c89d07817413cd311643df4f0d0d5654a00614295e4f04da3",
          "sha1": "e7e487914fef1b58f00c7c13eded205ca0b3b2a1",
          "md5": "f8e50ed0862c13cbeb1c44ff188d0996"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-beta01.aar",
          "url": "lifecycle-service-2.5.0-beta01.aar",
          "size": 4365,
          "sha512": "4f83c99c89e41b806bb2d3f78cb4ee0cd8ed159b7351c10d3218ae348661aad4a9bf4899c33a93f1d2ff6b8ae1feeef986b63a3d4a4c7359bc0a0777dfac7bb6",
          "sha256": "348f1e35cc34583c89d07817413cd311643df4f0d0d5654a00614295e4f04da3",
          "sha1": "e7e487914fef1b58f00c7c13eded205ca0b3b2a1",
          "md5": "f8e50ed0862c13cbeb1c44ff188d0996"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.5.0-beta01-sources.jar",
          "url": "lifecycle-service-2.5.0-beta01-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}