{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.6.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.6.0-beta01.aar",
          "url": "lifecycle-runtime-testing-2.6.0-beta01.aar",
          "size": 9360,
          "sha512": "46e4be3fbbe6614afd04bf577558662e2b5bb0ace303db50b12dee75d282d88122d394afa0b8e774b1548a83e698f0bc8ca9604da3020b2eb542292aaa838c90",
          "sha256": "64acf76de4c962312a448900636573be694c621c48ce7e40544b37b5fb1ade10",
          "sha1": "efbaa30bce05ecca5209220e99e597437b53c4f9",
          "md5": "423d5df01ad086b6e161d64d6887f1ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.6.0-beta01.aar",
          "url": "lifecycle-runtime-testing-2.6.0-beta01.aar",
          "size": 9360,
          "sha512": "46e4be3fbbe6614afd04bf577558662e2b5bb0ace303db50b12dee75d282d88122d394afa0b8e774b1548a83e698f0bc8ca9604da3020b2eb542292aaa838c90",
          "sha256": "64acf76de4c962312a448900636573be694c621c48ce7e40544b37b5fb1ade10",
          "sha1": "efbaa30bce05ecca5209220e99e597437b53c4f9",
          "md5": "423d5df01ad086b6e161d64d6887f1ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.6.0-beta01-sources.jar",
          "url": "lifecycle-runtime-testing-2.6.0-beta01-sources.jar",
          "size": 1884,
          "sha512": "36b6674d2f8884e90fddbd881514e8c2c1dea3a3b5fc3a6852216ec6ab43eff6ce9dcd22b5334f83873a7829f88385cb6aceea68ad755d2d5b3207a698452a9c",
          "sha256": "3cbceac63b8787ab77aba52121f1e2bab197cf35ffe4a0498693f3a65aa09572",
          "sha1": "7a6d9b897803f01e2b4914729ce69a7de24e0b58",
          "md5": "1d6900b324dba96555700b4f89cb52ee"
        }
      ]
    }
  ]
}