{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha03.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha03.aar",
          "size": 10086,
          "sha512": "be894b7efea9f3c676b105da60d08acf0d7003f38e39add8ee16c09d58c08a636b7f9dbc26228df2580291ff947c5f712c079fbf06efa24bd832d32d141a2637",
          "sha256": "5fc71f647cf2db86676bf706d8e58e76d376327a344bc8fe9366b884f59f5107",
          "sha1": "23bc57814dfa69b4f44bdee8c6a424809652e89b",
          "md5": "1b3cf086653bf56825b8194702ce2aa2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha03.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha03.aar",
          "size": 10086,
          "sha512": "be894b7efea9f3c676b105da60d08acf0d7003f38e39add8ee16c09d58c08a636b7f9dbc26228df2580291ff947c5f712c079fbf06efa24bd832d32d141a2637",
          "sha256": "5fc71f647cf2db86676bf706d8e58e76d376327a344bc8fe9366b884f59f5107",
          "sha1": "23bc57814dfa69b4f44bdee8c6a424809652e89b",
          "md5": "1b3cf086653bf56825b8194702ce2aa2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha03-sources.jar",
          "url": "lifecycle-livedata-core-2.5.0-alpha03-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}
