{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-rc01.aar",
          "url": "lifecycle-service-2.5.0-rc01.aar",
          "size": 4359,
          "sha512": "27956a2b7212e358d468baa8529ea371903312330a3236fb37b00e96440f98daac1c3c0084a74e9a6fae375632b1bc6fa7d89f403e36727d7754c76d98939c09",
          "sha256": "79957e8cc4296354ac376e2719f68b042262c07e65abb7a6f41b3ea337cd4b11",
          "sha1": "338c096e6b78e3dc86950cc0d336bab3c12dd591",
          "md5": "8299290a4482c05d1a5888867d5ac8ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-rc01.aar",
          "url": "lifecycle-service-2.5.0-rc01.aar",
          "size": 4359,
          "sha512": "27956a2b7212e358d468baa8529ea371903312330a3236fb37b00e96440f98daac1c3c0084a74e9a6fae375632b1bc6fa7d89f403e36727d7754c76d98939c09",
          "sha256": "79957e8cc4296354ac376e2719f68b042262c07e65abb7a6f41b3ea337cd4b11",
          "sha1": "338c096e6b78e3dc86950cc0d336bab3c12dd591",
          "md5": "8299290a4482c05d1a5888867d5ac8ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.5.0-rc01-sources.jar",
          "url": "lifecycle-service-2.5.0-rc01-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}