{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-alpha03.aar",
          "url": "lifecycle-runtime-2.5.0-alpha03.aar",
          "size": 12296,
          "sha512": "f2c65799dc3612b37bb4ceab75843b6a08bafe4dab10e277ca979dfb351b056673a59e2ef05aa015d1b0ebfd4ce87e86940f66b70f897b7d91d4c88c8c465fab",
          "sha256": "5d200b3727a69947618117bea76f9a726d969b476898920a8029bded1aeed558",
          "sha1": "325e00bfca2445bb52e53561d0a1e4af6e3edb9a",
          "md5": "d90360942db086fc276bb4418d01dd1d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-alpha03.aar",
          "url": "lifecycle-runtime-2.5.0-alpha03.aar",
          "size": 12296,
          "sha512": "f2c65799dc3612b37bb4ceab75843b6a08bafe4dab10e277ca979dfb351b056673a59e2ef05aa015d1b0ebfd4ce87e86940f66b70f897b7d91d4c88c8c465fab",
          "sha256": "5d200b3727a69947618117bea76f9a726d969b476898920a8029bded1aeed558",
          "sha1": "325e00bfca2445bb52e53561d0a1e4af6e3edb9a",
          "md5": "d90360942db086fc276bb4418d01dd1d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-alpha03-sources.jar",
          "url": "lifecycle-runtime-2.5.0-alpha03-sources.jar",
          "size": 8970,
          "sha512": "2009c123e8c19a76eb578ab4a999257a8a815e0f576678921cb327ace677502a07c117cd74a3d88e9cc901591f3e993420a60fc7177abe2e3b08532eddb5a4cf",
          "sha256": "7dd944be47d1245d17aae7cc656880f1d91695501955da5256c8659c6964e656",
          "sha1": "0d255b447102736e536a28b97671c6a736c801b7",
          "md5": "bc3ece2ea0121fea9bc2ba8334f1e80e"
        }
      ]
    }
  ]
}
