{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-compiler",
    "version": "2.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7217131"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.4.0-alpha01.jar",
          "url": "lifecycle-compiler-2.4.0-alpha01.jar",
          "size": 51213,
          "sha512": "4d0a2a14dac7c59dd587dec79550cdca2d691282043160c2434e2e510053c659a606560c670ef98a893cc411361bc78ad0b6da6b2a396254398c7d100b88c8d3",
          "sha256": "e5909878d13258e58a305d604f9e8ada2418669308d233da1a47ea7b236b39fa",
          "sha1": "936d05f2f22ebdfc6ebfbc19b9aaf344b087ad2f",
          "md5": "34e47d7ee858242a2b124dcfa9b8ebc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-compiler-2.4.0-alpha01.jar",
          "url": "lifecycle-compiler-2.4.0-alpha01.jar",
          "size": 51213,
          "sha512": "4d0a2a14dac7c59dd587dec79550cdca2d691282043160c2434e2e510053c659a606560c670ef98a893cc411361bc78ad0b6da6b2a396254398c7d100b88c8d3",
          "sha256": "e5909878d13258e58a305d604f9e8ada2418669308d233da1a47ea7b236b39fa",
          "sha1": "936d05f2f22ebdfc6ebfbc19b9aaf344b087ad2f",
          "md5": "34e47d7ee858242a2b124dcfa9b8ebc2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.4.0-alpha01-sources.jar",
          "url": "lifecycle-compiler-2.4.0-alpha01-sources.jar",
          "size": 18945,
          "sha512": "b98b5c854261d05e0a835e6b22e64d4335c47955d6813c565b2c241227e35594f9ffb95d8f108c33863f02fda6004cfa46ffb9d1df2d749a4edac60a50f82bd5",
          "sha256": "6f5dbfbca2596359127a69e76041db82244e364771e7e41bd28d1ef9d6fdcbdd",
          "sha1": "d677635574a41614848015dd8be201db36321879",
          "md5": "838e6095ded0e64250795dfcd49368df"
        }
      ]
    }
  ]
}
