{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.5.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-alpha04.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-alpha04.aar",
          "size": 2942,
          "sha512": "ea8fc50e52f65fa94dd8e5eb872be02ebcfe6bb7c01424c79453ae0d99bb87d3535987893e7d1cb1836d277376cbc33bd3f72e24eed633cbe071dd47a2e0b318",
          "sha256": "ee5bfd772cb83c66fad46b25c9230be5625e60014e13cdd963ec7a23591d035a",
          "sha1": "20684c01ed1dd0315c1180809b7c1eca618c9bb6",
          "md5": "69a3fdea435afd46b5c2bc5526943010"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-alpha04.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-alpha04.aar",
          "size": 2942,
          "sha512": "ea8fc50e52f65fa94dd8e5eb872be02ebcfe6bb7c01424c79453ae0d99bb87d3535987893e7d1cb1836d277376cbc33bd3f72e24eed633cbe071dd47a2e0b318",
          "sha256": "ee5bfd772cb83c66fad46b25c9230be5625e60014e13cdd963ec7a23591d035a",
          "sha1": "20684c01ed1dd0315c1180809b7c1eca618c9bb6",
          "md5": "69a3fdea435afd46b5c2bc5526943010"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-alpha04-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-alpha04-sources.jar",
          "size": 1261,
          "sha512": "bb0f402ed24247b2fd8e5ecbfec147427d84a8f18bf21cb5857c1fee5746e2a97febac326c894484fe6e86a515fe1bfd05c3b1538eb3f0f1cce712f280a76861",
          "sha256": "c50b9f047a5b5d5ee5d330b3e2dc45f4ae8deca41f607d1d495792c89e731048",
          "sha1": "23c53fd2626cac61baac62c95dec1c49046e0261",
          "md5": "5d68075becef226fa5ce3a00a8721ea7"
        }
      ]
    }
  ]
}
