{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose-samples",
    "version": "2.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.4.0-rc01.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.4.0-rc01.aar",
          "size": 1766,
          "sha512": "81d4bea5eec44ca90498e39042b1366ad0fdc097fa4d3064c03d352d985dfc87cb02ce6afe1c460293f0eacc9fe43097c4cb355ff56c76c341b14abca5140126",
          "sha256": "e1f0c790a6666a8013624e4b8504c39d64718a53ab9b4a871985e4aa414549d8",
          "sha1": "6f9d0b0ee87d6e964eb3a6dd6e4724de3eff8458",
          "md5": "4702ff3205c4e2755e433d936c90a54f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.4.0-rc01.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.4.0-rc01.aar",
          "size": 1766,
          "sha512": "81d4bea5eec44ca90498e39042b1366ad0fdc097fa4d3064c03d352d985dfc87cb02ce6afe1c460293f0eacc9fe43097c4cb355ff56c76c341b14abca5140126",
          "sha256": "e1f0c790a6666a8013624e4b8504c39d64718a53ab9b4a871985e4aa414549d8",
          "sha1": "6f9d0b0ee87d6e964eb3a6dd6e4724de3eff8458",
          "md5": "4702ff3205c4e2755e433d936c90a54f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.4.0-rc01-sources.jar",
          "url": "lifecycle-viewmodel-compose-samples-2.4.0-rc01-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
