{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-compose",
    "version": "2.6.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.6.0-beta01.aar",
          "url": "lifecycle-runtime-compose-2.6.0-beta01.aar",
          "size": 11808,
          "sha512": "6ade2faa3097c7e6441d6dfee1585ef7b2bf211bba865b79eb20baad64cfaaa7c07625484dac983189681d0e42e9d05b200f279ba862c0c1f6aabb88c4f0ba3f",
          "sha256": "72fbb3db9d77923e3a61efe94501d859479f6475753d40ecaf9bfd82e3d96940",
          "sha1": "eec56c2c01572cec6e0b3fa6bbf4e354256f4c4b",
          "md5": "3abac4e7e66766f2732d4423bedb082b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.6.0-beta01.aar",
          "url": "lifecycle-runtime-compose-2.6.0-beta01.aar",
          "size": 11808,
          "sha512": "6ade2faa3097c7e6441d6dfee1585ef7b2bf211bba865b79eb20baad64cfaaa7c07625484dac983189681d0e42e9d05b200f279ba862c0c1f6aabb88c4f0ba3f",
          "sha256": "72fbb3db9d77923e3a61efe94501d859479f6475753d40ecaf9bfd82e3d96940",
          "sha1": "eec56c2c01572cec6e0b3fa6bbf4e354256f4c4b",
          "md5": "3abac4e7e66766f2732d4423bedb082b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.6.0-beta01-sources.jar",
          "url": "lifecycle-runtime-compose-2.6.0-beta01-sources.jar",
          "size": 2157,
          "sha512": "10ac2fd95ba549e3a1684facaf6caae2248ff24541681aa23db2aa13d1b6d76e62f14c180865a84836007cda8f865146b1118d90c99b29b35c7cb2ec77cde361",
          "sha256": "dc61e56cf83fda48b6116e89f21846ec63d768d2e800ac0fe6993289c6dbe926",
          "sha1": "7f01a3a02a438ea53e95a9922ee61da155d4355a",
          "md5": "107d8a6aa18818fc9a42e3217acef789"
        }
      ]
    }
  ]
}