{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.6.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.6.0-alpha04.aar",
          "url": "lifecycle-livedata-core-ktx-2.6.0-alpha04.aar",
          "size": 20260,
          "sha512": "4e876d2fd156679b57c2053f308cae7353e655aca337e571664baa955eec7be4a4ba81e0403168c91e912c58d02590e66d3799decbb49ba2524af494337a1cf8",
          "sha256": "7ca7f679b0e3aa45d49f494733dbb6ea56da0268f72c4608baa6cb7b4fe39b01",
          "sha1": "dda43537fd14e097a0da572655844fdf8cffafe6",
          "md5": "6ffd6375ae3f4df83ef31600d6e6f5d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.6.0-alpha04.aar",
          "url": "lifecycle-livedata-core-ktx-2.6.0-alpha04.aar",
          "size": 20260,
          "sha512": "4e876d2fd156679b57c2053f308cae7353e655aca337e571664baa955eec7be4a4ba81e0403168c91e912c58d02590e66d3799decbb49ba2524af494337a1cf8",
          "sha256": "7ca7f679b0e3aa45d49f494733dbb6ea56da0268f72c4608baa6cb7b4fe39b01",
          "sha1": "dda43537fd14e097a0da572655844fdf8cffafe6",
          "md5": "6ffd6375ae3f4df83ef31600d6e6f5d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.6.0-alpha04-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.6.0-alpha04-sources.jar",
          "size": 1631,
          "sha512": "179c4e8be100039ce10c53fb85e4c468895d76dd558d3f8d5eb049e1474b00152667389033438de76e6c65acb59ed4401bcfbb4c3a5a997133fcaf8d079d2797",
          "sha256": "52aebe57b7619530d5d762671262a6be54972c7ab64e41a330d81ab21adfcba9",
          "sha1": "0679a0782faddfa90863d19babbe2b44ded7d13b",
          "md5": "663ab746fbe90329cd36af2559f9f79f"
        }
      ]
    }
  ]
}