{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-alpha02.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-alpha02.aar",
          "size": 2904,
          "sha512": "21c72c9ed57de89c3bc034007094b3743a888e6e6fcbc6e06c671709453b7c571691dcfda78011af3a0f0ee55cce8183b068d24a29876bf47a2fef1a374e2b4f",
          "sha256": "aff2321c7a432e77799c4c51ff1168869cd201816d3ff0c23ce1eda2fc961753",
          "sha1": "1a1b6d55306982979b5892247bec2b5c6f78d34a",
          "md5": "2b163a5d4b32e844cbeb20d252576cbb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-alpha02.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-alpha02.aar",
          "size": 2904,
          "sha512": "21c72c9ed57de89c3bc034007094b3743a888e6e6fcbc6e06c671709453b7c571691dcfda78011af3a0f0ee55cce8183b068d24a29876bf47a2fef1a374e2b4f",
          "sha256": "aff2321c7a432e77799c4c51ff1168869cd201816d3ff0c23ce1eda2fc961753",
          "sha1": "1a1b6d55306982979b5892247bec2b5c6f78d34a",
          "md5": "2b163a5d4b32e844cbeb20d252576cbb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-alpha02-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-alpha02-sources.jar",
          "size": 1261,
          "sha512": "bb0f402ed24247b2fd8e5ecbfec147427d84a8f18bf21cb5857c1fee5746e2a97febac326c894484fe6e86a515fe1bfd05c3b1538eb3f0f1cce712f280a76861",
          "sha256": "c50b9f047a5b5d5ee5d330b3e2dc45f4ae8deca41f607d1d495792c89e731048",
          "sha1": "23c53fd2626cac61baac62c95dec1c49046e0261",
          "md5": "5d68075becef226fa5ce3a00a8721ea7"
        }
      ]
    }
  ]
}
