{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-rc01.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-rc01.aar",
          "size": 2937,
          "sha512": "3f7280d62ea6efa9fa88ffc49dd9e57a41e1046db10bff79f3d1e9e165e6269517997f8add4137ce2ab4152407811a1399869167ebf2b2763adc0e357b925615",
          "sha256": "68a1ea4531e2f80613b35de9e0005c99e7bd659dde99d837bc5c6bc7101fdf96",
          "sha1": "e147b939c8c311ed47d569f01d24eba307bb013d",
          "md5": "81cd45af6eef24648a14465e94c6dd54"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-rc01.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-rc01.aar",
          "size": 2937,
          "sha512": "3f7280d62ea6efa9fa88ffc49dd9e57a41e1046db10bff79f3d1e9e165e6269517997f8add4137ce2ab4152407811a1399869167ebf2b2763adc0e357b925615",
          "sha256": "68a1ea4531e2f80613b35de9e0005c99e7bd659dde99d837bc5c6bc7101fdf96",
          "sha1": "e147b939c8c311ed47d569f01d24eba307bb013d",
          "md5": "81cd45af6eef24648a14465e94c6dd54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-rc01-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-rc01-sources.jar",
          "size": 1261,
          "sha512": "bb0f402ed24247b2fd8e5ecbfec147427d84a8f18bf21cb5857c1fee5746e2a97febac326c894484fe6e86a515fe1bfd05c3b1538eb3f0f1cce712f280a76861",
          "sha256": "c50b9f047a5b5d5ee5d330b3e2dc45f4ae8deca41f607d1d495792c89e731048",
          "sha1": "23c53fd2626cac61baac62c95dec1c49046e0261",
          "md5": "5d68075becef226fa5ce3a00a8721ea7"
        }
      ]
    }
  ]
}