{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.6.0-alpha01.aar",
          "url": "lifecycle-livedata-core-ktx-2.6.0-alpha01.aar",
          "size": 20287,
          "sha512": "4cb6726221eda5804d6feea2a950e40e43359c3d2e4c5f86236c187f418831d776ee88de4906922d9c26df3b10a7a0d8382f3583bd5b202ab0a18a350f5171ef",
          "sha256": "d91f7c51b9380e5cb0070869eb4c4b2eaf3a2bd351a38bb271925ec24951110f",
          "sha1": "ab7a00d12fee5bdabc887ce3e31961e94392c174",
          "md5": "9177f22a28f6c395711d16d7554b39e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.6.0-alpha01.aar",
          "url": "lifecycle-livedata-core-ktx-2.6.0-alpha01.aar",
          "size": 20287,
          "sha512": "4cb6726221eda5804d6feea2a950e40e43359c3d2e4c5f86236c187f418831d776ee88de4906922d9c26df3b10a7a0d8382f3583bd5b202ab0a18a350f5171ef",
          "sha256": "d91f7c51b9380e5cb0070869eb4c4b2eaf3a2bd351a38bb271925ec24951110f",
          "sha1": "ab7a00d12fee5bdabc887ce3e31961e94392c174",
          "md5": "9177f22a28f6c395711d16d7554b39e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.6.0-alpha01-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.6.0-alpha01-sources.jar",
          "size": 1631,
          "sha512": "aec27370748b879276405755e63a377e08307bfe2f370687ee18fa5c43cb5e203fe5e3bcc9cda40390c872bf279e96bc2bae2f0a9e2ee631f861b2ad0e54c0ae",
          "sha256": "b7a2a7c66a58440b0ba30c68abe17074836f217123fb6ea728279834641a7c77",
          "sha1": "0ec507705520b7ddccce7da52bbf5abd9ecd1808",
          "md5": "c552138cfc58a3f4d73c8acbb66e4a86"
        }
      ]
    }
  ]
}