{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.5.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha06.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha06.aar",
          "size": 10086,
          "sha512": "4a9fa42ce73113719194df56ef5bc7b3bda2fcfcd56d5a2766002a2559c3185f55744d82fde33ea56c2ad972f2bbe8d8734b7bdfeb667cd48e5a3ea581140937",
          "sha256": "168c191c492f8c30b27ad8b3e5f940c84482ebaf685059cb0716aaaad03684f3",
          "sha1": "c25b4c4274f973c6ff2cc4a113d2db6b89c7918a",
          "md5": "16198e7e838a9ea651769edcb64fac37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha06.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha06.aar",
          "size": 10086,
          "sha512": "4a9fa42ce73113719194df56ef5bc7b3bda2fcfcd56d5a2766002a2559c3185f55744d82fde33ea56c2ad972f2bbe8d8734b7bdfeb667cd48e5a3ea581140937",
          "sha256": "168c191c492f8c30b27ad8b3e5f940c84482ebaf685059cb0716aaaad03684f3",
          "sha1": "c25b4c4274f973c6ff2cc4a113d2db6b89c7918a",
          "md5": "16198e7e838a9ea651769edcb64fac37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha06-sources.jar",
          "url": "lifecycle-livedata-core-2.5.0-alpha06-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}