{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.4.0-beta01.aar",
          "url": "lifecycle-viewmodel-2.4.0-beta01.aar",
          "size": 19069,
          "sha512": "34112575d83cea38fdc5c12a682e6a390e34a9f45c3a92750801c4102c1a0671bc982fe7891531b7f18e76a0d43b4da404579901ad09f5d0cde92cb57e691a9c",
          "sha256": "3d2a6f45d76745beaa660721fb79bca91c6cc1dd70a7ce209c2f0073fc820cfc",
          "sha1": "96b6259b54b0567ac585edfb8ba4667c74c369f1",
          "md5": "a7f17057136e8b76ac9b0abf5a9a0d0b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.4.0-beta01.aar",
          "url": "lifecycle-viewmodel-2.4.0-beta01.aar",
          "size": 19069,
          "sha512": "34112575d83cea38fdc5c12a682e6a390e34a9f45c3a92750801c4102c1a0671bc982fe7891531b7f18e76a0d43b4da404579901ad09f5d0cde92cb57e691a9c",
          "sha256": "3d2a6f45d76745beaa660721fb79bca91c6cc1dd70a7ce209c2f0073fc820cfc",
          "sha1": "96b6259b54b0567ac585edfb8ba4667c74c369f1",
          "md5": "a7f17057136e8b76ac9b0abf5a9a0d0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-2.4.0-beta01-sources.jar",
          "url": "lifecycle-viewmodel-2.4.0-beta01-sources.jar",
          "size": 12799,
          "sha512": "b728bb2a1b2c4225315402dbc55b952f4ba31bad3f2d6285663b471ecf50813a8447a6b3bdf156d48adccf6f481c5a6ee61737f724204e363b8ca61b8b8e847b",
          "sha256": "21535e6920d73491c75aefc6ca6fd2217ecaf3eedfb474736c35d2870be6dd2d",
          "sha1": "c5e216fe2f1b1de75552f99f5a562ae89f7d7b84",
          "md5": "9046ce6463b0567e3a8fd6e3b920ad1b"
        }
      ]
    }
  ]
}
