{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7514997"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.2.4.aar",
          "url": "activity-ktx-1.2.4.aar",
          "size": 19826,
          "sha512": "eabe2aabd83a6f7f1bd414e5300cda0cbab9df84bd6151d9485047a660e90a7748641f4c504d2d8eb93ae07e7b47d0b72749804e87013d1f0d11c458c49e1104",
          "sha256": "35cb730ecace7757c2a624044b539d59df58fcea36ef3fd543ce660077169219",
          "sha1": "512b5a11d3c72e4aa9d5f286449bdc18f648f675",
          "md5": "c6bdacbd4472f26edc3680b6a291381b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.2.4.aar",
          "url": "activity-ktx-1.2.4.aar",
          "size": 19826,
          "sha512": "eabe2aabd83a6f7f1bd414e5300cda0cbab9df84bd6151d9485047a660e90a7748641f4c504d2d8eb93ae07e7b47d0b72749804e87013d1f0d11c458c49e1104",
          "sha256": "35cb730ecace7757c2a624044b539d59df58fcea36ef3fd543ce660077169219",
          "sha1": "512b5a11d3c72e4aa9d5f286449bdc18f648f675",
          "md5": "c6bdacbd4472f26edc3680b6a291381b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.2.4-sources.jar",
          "url": "activity-ktx-1.2.4-sources.jar",
          "size": 6133,
          "sha512": "a5266f324c627f8819af1667fb4f31e61196fc118c691c07570487ee2eb7584d5415faa8a85eecd06e810f4448d893a8ddddd32e9e229b514466ad0f7f81c5d9",
          "sha256": "4d8c5ae5ebb411cf3770fc3546a93c527a20819762b4807fec8ea1c7521ce06e",
          "sha1": "8de8463662d207920c11530ec0e76af3005f0061",
          "md5": "7f56f8cdd73c71afc49702017eb9408b"
        }
      ]
    }
  ]
}
