{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.3.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7217131"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-alpha05.aar",
          "url": "activity-1.3.0-alpha05.aar",
          "size": 68060,
          "sha512": "c29188e28774c6d2ef5d73fec0fca407f09846150dde46f50d06e6219c7d01e36afa3e1503dd0275fc086ccb65a1a4d779bb2e53294353dd009e6a9dad4fc9cc",
          "sha256": "4e81c503b1c717804dcb5cfae24484bca5a9e3aa062e34489c0be8786a218452",
          "sha1": "226778dde935a496bb93a1e2d801139cd510e0a0",
          "md5": "a1160019065df838ff14a8fe94cc4aad"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-alpha05.aar",
          "url": "activity-1.3.0-alpha05.aar",
          "size": 68060,
          "sha512": "c29188e28774c6d2ef5d73fec0fca407f09846150dde46f50d06e6219c7d01e36afa3e1503dd0275fc086ccb65a1a4d779bb2e53294353dd009e6a9dad4fc9cc",
          "sha256": "4e81c503b1c717804dcb5cfae24484bca5a9e3aa062e34489c0be8786a218452",
          "sha1": "226778dde935a496bb93a1e2d801139cd510e0a0",
          "md5": "a1160019065df838ff14a8fe94cc4aad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.3.0-alpha05-sources.jar",
          "url": "activity-1.3.0-alpha05-sources.jar",
          "size": 35608,
          "sha512": "53d529ca53db82f838aae1c6bb84069e973424350a94cb7602b70e7155281088d39a57564eee4842f97416286f9fc5a76ce058b034bc502eadc7f1ab6d983249",
          "sha256": "0cffd6a421f6c3a172b256dac2a597093b96ac7224157d0c62057610bcd5ba2b",
          "sha1": "8b49edd0e1494eafb504f24514f943fa3937d3bf",
          "md5": "79e13286c89746869b88fa2194bb75b0"
        }
      ]
    }
  ]
}
