{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-rc01.aar",
          "url": "lifecycle-runtime-testing-2.5.0-rc01.aar",
          "size": 8527,
          "sha512": "19714f718bd5e1e97f7fa0fcda1cb7bac13a61eab17378741d3226f0346b8fdf5afd07b5a9c24c7bc1f4bca955cfb75553794bc3284618735d99f9eff9a98fc5",
          "sha256": "2754550f0ee4be2dc7b17c8bfc7c6ed64d8a4eb6de4343d445e47ab97e4c1413",
          "sha1": "3ed0072711154851fd00398ff51c5d8b7ddb4d92",
          "md5": "7efe4176f7f40201b905e7ef5a1e5f7a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-rc01.aar",
          "url": "lifecycle-runtime-testing-2.5.0-rc01.aar",
          "size": 8527,
          "sha512": "19714f718bd5e1e97f7fa0fcda1cb7bac13a61eab17378741d3226f0346b8fdf5afd07b5a9c24c7bc1f4bca955cfb75553794bc3284618735d99f9eff9a98fc5",
          "sha256": "2754550f0ee4be2dc7b17c8bfc7c6ed64d8a4eb6de4343d445e47ab97e4c1413",
          "sha1": "3ed0072711154851fd00398ff51c5d8b7ddb4d92",
          "md5": "7efe4176f7f40201b905e7ef5a1e5f7a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-rc01-sources.jar",
          "url": "lifecycle-runtime-testing-2.5.0-rc01-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}