{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.6.0-alpha01.aar",
          "url": "lifecycle-runtime-2.6.0-alpha01.aar",
          "size": 13033,
          "sha512": "061d39f4d47d01785819595dc261f9d102a6ed150f5bb6074fea95a2ace4b60fb17caeeed0252cf07e5418cf34e5f0cc4c551f8d71fd76cb7e824d2ecc6edb8e",
          "sha256": "026e588b8cf59d4c28aeb7c55a6e0203632c3e0186e62c9b0f460d0dc5bd18ac",
          "sha1": "2e30f33de8e1bc3dc7ed1ac4feb8e22014ff7d9c",
          "md5": "dd38ef09945a7f2c666a065f5a4d4fa1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.6.0-alpha01.aar",
          "url": "lifecycle-runtime-2.6.0-alpha01.aar",
          "size": 13033,
          "sha512": "061d39f4d47d01785819595dc261f9d102a6ed150f5bb6074fea95a2ace4b60fb17caeeed0252cf07e5418cf34e5f0cc4c551f8d71fd76cb7e824d2ecc6edb8e",
          "sha256": "026e588b8cf59d4c28aeb7c55a6e0203632c3e0186e62c9b0f460d0dc5bd18ac",
          "sha1": "2e30f33de8e1bc3dc7ed1ac4feb8e22014ff7d9c",
          "md5": "dd38ef09945a7f2c666a065f5a4d4fa1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.6.0-alpha01-sources.jar",
          "url": "lifecycle-runtime-2.6.0-alpha01-sources.jar",
          "size": 8970,
          "sha512": "2009c123e8c19a76eb578ab4a999257a8a815e0f576678921cb327ace677502a07c117cd74a3d88e9cc901591f3e993420a60fc7177abe2e3b08532eddb5a4cf",
          "sha256": "7dd944be47d1245d17aae7cc656880f1d91695501955da5256c8659c6964e656",
          "sha1": "0d255b447102736e536a28b97671c6a736c801b7",
          "md5": "bc3ece2ea0121fea9bc2ba8334f1e80e"
        }
      ]
    }
  ]
}