{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.4.0-beta01.aar",
          "url": "lifecycle-runtime-2.4.0-beta01.aar",
          "size": 11491,
          "sha512": "14f715c322d442d62edcb23655ddf77369009df7184b334900cc3bb1c0955c2f4167e1cf4e42088018e22c75d8e4db8b944a64a18a15d4c6a7a008bd12a8dd81",
          "sha256": "ac38d02b087238445d222f072c334555bf12591397464db066ce7850db33cf65",
          "sha1": "36a1d0f915c9b3262c4de30888a3e226ca8586da",
          "md5": "a7e9f9a1adcb34e277ded9b1636b4bd1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.4.0-beta01.aar",
          "url": "lifecycle-runtime-2.4.0-beta01.aar",
          "size": 11491,
          "sha512": "14f715c322d442d62edcb23655ddf77369009df7184b334900cc3bb1c0955c2f4167e1cf4e42088018e22c75d8e4db8b944a64a18a15d4c6a7a008bd12a8dd81",
          "sha256": "ac38d02b087238445d222f072c334555bf12591397464db066ce7850db33cf65",
          "sha1": "36a1d0f915c9b3262c4de30888a3e226ca8586da",
          "md5": "a7e9f9a1adcb34e277ded9b1636b4bd1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.4.0-beta01-sources.jar",
          "url": "lifecycle-runtime-2.4.0-beta01-sources.jar",
          "size": 8927,
          "sha512": "3a9f03beaffff0b273188c91a18f234962052eed4257f5b18b5098d09e2ed9799e3870b5b8cc63eeb429f03ef294f3109365c794bb84b11742048d1a1a0a4288",
          "sha256": "a1757f478939a9ae47e3a005f5c3ce051e50859d54478e3b931fdb06738269a9",
          "sha1": "ae7040cf314de81d20ac69f28f5ab6c9a2c0d1ab",
          "md5": "a34ad95ef12973e07a73efde45a2504e"
        }
      ]
    }
  ]
}
