{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams",
    "version": "2.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.4.0-alpha02.aar",
          "url": "lifecycle-reactivestreams-2.4.0-alpha02.aar",
          "size": 9067,
          "sha512": "9ae99b0a1acd73147d091d8da237516c9b928da891f13bc995f6795733a0f7e294842995ff43a8bb49783353118b55b5880cb0d2caf899ad0fa12ecd87f849ef",
          "sha256": "48a57bc39c86a666cbdd88c4e355902be6aa28b9456bf76ca44fb42188ed34c4",
          "sha1": "25205867ee733074d615efc325527f6c73a0064c",
          "md5": "688860d2fbb583ec310da4f8d72a0636"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.4.0-alpha02.aar",
          "url": "lifecycle-reactivestreams-2.4.0-alpha02.aar",
          "size": 9067,
          "sha512": "9ae99b0a1acd73147d091d8da237516c9b928da891f13bc995f6795733a0f7e294842995ff43a8bb49783353118b55b5880cb0d2caf899ad0fa12ecd87f849ef",
          "sha256": "48a57bc39c86a666cbdd88c4e355902be6aa28b9456bf76ca44fb42188ed34c4",
          "sha1": "25205867ee733074d615efc325527f6c73a0064c",
          "md5": "688860d2fbb583ec310da4f8d72a0636"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-2.4.0-alpha02-sources.jar",
          "url": "lifecycle-reactivestreams-2.4.0-alpha02-sources.jar",
          "size": 3248,
          "sha512": "a6b65d83c8f4d40f76f171140950c3e44745058afe510b3f89b883ae47fe9f1a14c6ab03929077e43c584df3430c28437a32e8d0fba537d5ec6381ff4e6ec7eb",
          "sha256": "25c60c1e6301781e80787118a26d2e3c011187df8356ab427078c18c7e349585",
          "sha1": "31df3402f1e5e287cb5b0e7d9568f100871588f3",
          "md5": "aa8ca57584eb4039b356b2ab8d5a2ae1"
        }
      ]
    }
  ]
}
