{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.0-rc01.aar",
          "url": "lifecycle-service-2.4.0-rc01.aar",
          "size": 4305,
          "sha512": "5c253d0860e869e8df9d4267b1b05ad48a9432082987fa26691553f33fca1f49199a5ffc3b5c95af5a56a6de7ffcab62e0ab285be92a9ccbd80d221400d010f4",
          "sha256": "b7ac4bcc20cf59f263a658bfa6bbecb3085de5fc3f4ae9d6935345956d3b06bb",
          "sha1": "6bb2aed76e29057d8152167f09831c0838f52c90",
          "md5": "d651ca81c598bc9d4bf4ff9f8896119c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.0-rc01.aar",
          "url": "lifecycle-service-2.4.0-rc01.aar",
          "size": 4305,
          "sha512": "5c253d0860e869e8df9d4267b1b05ad48a9432082987fa26691553f33fca1f49199a5ffc3b5c95af5a56a6de7ffcab62e0ab285be92a9ccbd80d221400d010f4",
          "sha256": "b7ac4bcc20cf59f263a658bfa6bbecb3085de5fc3f4ae9d6935345956d3b06bb",
          "sha1": "6bb2aed76e29057d8152167f09831c0838f52c90",
          "md5": "d651ca81c598bc9d4bf4ff9f8896119c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.4.0-rc01-sources.jar",
          "url": "lifecycle-service-2.4.0-rc01-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
