{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-ktx",
    "version": "2.5.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-rc02.aar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-rc02.aar",
          "size": 4028,
          "sha512": "a9dfcda07a0cdde7ae59d17a3c444a42d591f3a466849538122fb2b90c33d048dc16621f3a4df40d8eb1fe118afc878d1b610e7ec1482c937270f7ef4b3d0e41",
          "sha256": "b0eac7ebaf5fb8a9db5d29fd5e4c0b4956fdbbe82e7219c05cc6c87469f21ecf",
          "sha1": "7743fbd573b330da97a4c8aa27e221e95ada2e9a",
          "md5": "512428c658c7cf474e64621e5a9da58c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-rc02.aar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-rc02.aar",
          "size": 4028,
          "sha512": "a9dfcda07a0cdde7ae59d17a3c444a42d591f3a466849538122fb2b90c33d048dc16621f3a4df40d8eb1fe118afc878d1b610e7ec1482c937270f7ef4b3d0e41",
          "sha256": "b0eac7ebaf5fb8a9db5d29fd5e4c0b4956fdbbe82e7219c05cc6c87469f21ecf",
          "sha1": "7743fbd573b330da97a4c8aa27e221e95ada2e9a",
          "md5": "512428c658c7cf474e64621e5a9da58c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.0-rc02-sources.jar",
          "url": "lifecycle-viewmodel-ktx-2.5.0-rc02-sources.jar",
          "size": 1410,
          "sha512": "bfe6372c5910f626e7b41bb6468d62612d1f1bde9b3c767caaa7eb7c07e93cf00d047d8e909b7c47f2985f42ffa554a82888f83e712473cee8756407fcc09548",
          "sha256": "8af8f2ac694742fe8ae133067dfdec6a193a738f46ba80c59b3e8a4ab36703f3",
          "sha1": "a900dc99643d8638beb02bd809a495f772d457e7",
          "md5": "43d89db66da712ab2560a41753632946"
        }
      ]
    }
  ]
}