{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.6.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.6.0-alpha04.aar",
          "url": "lifecycle-livedata-core-2.6.0-alpha04.aar",
          "size": 10952,
          "sha512": "7b43ad91678b2ae91cdfb8f656a882677f7453c4144e068f68546d44c73ebfda78896599c49355dbe8511933e3aec8fea2fa559805c71158c77923678bbea37a",
          "sha256": "598e9f69b9b982afd3525388033e32458ec3a54390c2354e5baa36a479142a6e",
          "sha1": "dd3ec016f1d23f50fc7c21c27d38e48a97cafc4c",
          "md5": "0209f7e9b423e700fa093372dfda5d3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.6.0-alpha04.aar",
          "url": "lifecycle-livedata-core-2.6.0-alpha04.aar",
          "size": 10952,
          "sha512": "7b43ad91678b2ae91cdfb8f656a882677f7453c4144e068f68546d44c73ebfda78896599c49355dbe8511933e3aec8fea2fa559805c71158c77923678bbea37a",
          "sha256": "598e9f69b9b982afd3525388033e32458ec3a54390c2354e5baa36a479142a6e",
          "sha1": "dd3ec016f1d23f50fc7c21c27d38e48a97cafc4c",
          "md5": "0209f7e9b423e700fa093372dfda5d3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.6.0-alpha04-sources.jar",
          "url": "lifecycle-livedata-core-2.6.0-alpha04-sources.jar",
          "size": 6970,
          "sha512": "342a5cc1b0f529acb6c1cc4885e10825c86a10c5bc000095db042f74c0147c81b53fd845b8716556ee8bfca68f9921ab6bb61f59d9e8bead2d559797fbd0d186",
          "sha256": "766e25d665caeb1bda120aa69f4ff30f28b7b28105c1e87cede7a32a5361bde8",
          "sha1": "fb83db0944e8fa5fd787bdb5dbb817d43a984a19",
          "md5": "c742ff8d8a84d365fbf2415441fef8d9"
        }
      ]
    }
  ]
}