{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-compiler",
    "version": "2.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6684396"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.3.0-alpha06.jar",
          "url": "lifecycle-compiler-2.3.0-alpha06.jar",
          "size": 51153,
          "sha512": "55155d1c8991b5c1c87612d07cee681c9cc5f6cd5df17a5f99362fca331de43aa4b30a93a215bfb4c53a96998e8f6f0228a9de1450bf018456b8926bbd5e5f29",
          "sha256": "ac7ad97a28159dc14edfa17d078731738b846f15f29bc637b8f779a0a1dceffa",
          "sha1": "dc168708358c15b4b6e132618a7d3562c23bf6c1",
          "md5": "5dc6c817fd82ddbb747e3b4c48c0096b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-compiler-2.3.0-alpha06.jar",
          "url": "lifecycle-compiler-2.3.0-alpha06.jar",
          "size": 51153,
          "sha512": "55155d1c8991b5c1c87612d07cee681c9cc5f6cd5df17a5f99362fca331de43aa4b30a93a215bfb4c53a96998e8f6f0228a9de1450bf018456b8926bbd5e5f29",
          "sha256": "ac7ad97a28159dc14edfa17d078731738b846f15f29bc637b8f779a0a1dceffa",
          "sha1": "dc168708358c15b4b6e132618a7d3562c23bf6c1",
          "md5": "5dc6c817fd82ddbb747e3b4c48c0096b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.3.0-alpha06-sources.jar",
          "url": "lifecycle-compiler-2.3.0-alpha06-sources.jar",
          "size": 18912,
          "sha512": "d55e240a42ac42dbbe2112612ec4a62dc9a1a89767d82a8c278fe05a11120a920fe95a7ba978a81db5d2a163a235d8eb3a1e483467cdab77ebc39d4cc0e0d834",
          "sha256": "2ee75cf3ef552e2aa557441a1c8ceaf94ca958fe73e675502c5abd1983713a12",
          "sha1": "95009d9a54d9956e88c00ad40b3b0a9d748bdce9",
          "md5": "782d416c2d6a2e946683e77337bf30d1"
        }
      ]
    }
  ]
}
