{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-compiler",
    "version": "2.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6860046"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.3.0-beta01.jar",
          "url": "lifecycle-compiler-2.3.0-beta01.jar",
          "size": 51196,
          "sha512": "721f1a337af35637383028f202bed8a362df55ef4c64d8a9ac960d44b4abefe88d4d08818ace7d6703eb1cd4597e19c6a1aaf89a7f888b2642d2241f5e72d273",
          "sha256": "3c6d3ff5a2b878867f6da6c57af6618852a20a6e68c6238dbedf32244564fd5d",
          "sha1": "d3495df0c2c4137ffa67b501430acedcb1629ccd",
          "md5": "b853cc7cec29bb3c12b92088d8a5e32e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-compiler-2.3.0-beta01.jar",
          "url": "lifecycle-compiler-2.3.0-beta01.jar",
          "size": 51196,
          "sha512": "721f1a337af35637383028f202bed8a362df55ef4c64d8a9ac960d44b4abefe88d4d08818ace7d6703eb1cd4597e19c6a1aaf89a7f888b2642d2241f5e72d273",
          "sha256": "3c6d3ff5a2b878867f6da6c57af6618852a20a6e68c6238dbedf32244564fd5d",
          "sha1": "d3495df0c2c4137ffa67b501430acedcb1629ccd",
          "md5": "b853cc7cec29bb3c12b92088d8a5e32e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.3.0-beta01-sources.jar",
          "url": "lifecycle-compiler-2.3.0-beta01-sources.jar",
          "size": 18945,
          "sha512": "b98b5c854261d05e0a835e6b22e64d4335c47955d6813c565b2c241227e35594f9ffb95d8f108c33863f02fda6004cfa46ffb9d1df2d749a4edac60a50f82bd5",
          "sha256": "6f5dbfbca2596359127a69e76041db82244e364771e7e41bd28d1ef9d6fdcbdd",
          "sha1": "d677635574a41614848015dd8be201db36321879",
          "md5": "838e6095ded0e64250795dfcd49368df"
        }
      ]
    }
  ]
}
