{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha04"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.7.0-alpha03.aar",
          "url": "activity-ktx-1.7.0-alpha03.aar",
          "size": 32054,
          "sha512": "8a4b4e8a01103aba27bb41ab650fd71fe09402852f4e2ccec4bcc39248263353e710455143ec4b2b8f59c9b862e9c9d03aa6d7375e9ca34f16fef4dded8ab776",
          "sha256": "696981e29384d47b7f3ff9816204a8a8ec401b0543012208035859a280d036d2",
          "sha1": "61f2214b4a551a757fe417e1bd88524097a5c74f",
          "md5": "95572300fecce54f570c88383e2a138c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha04"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.7.0-alpha03.aar",
          "url": "activity-ktx-1.7.0-alpha03.aar",
          "size": 32054,
          "sha512": "8a4b4e8a01103aba27bb41ab650fd71fe09402852f4e2ccec4bcc39248263353e710455143ec4b2b8f59c9b862e9c9d03aa6d7375e9ca34f16fef4dded8ab776",
          "sha256": "696981e29384d47b7f3ff9816204a8a8ec401b0543012208035859a280d036d2",
          "sha1": "61f2214b4a551a757fe417e1bd88524097a5c74f",
          "md5": "95572300fecce54f570c88383e2a138c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.7.0-alpha03-sources.jar",
          "url": "activity-ktx-1.7.0-alpha03-sources.jar",
          "size": 7896,
          "sha512": "8e286e8abe3b1db909c991f06f5a60269d1926c284b6db5a315d5afab6a2561e10c38bd9abb9c68cb3d40e2897322b23e4272dec3d1f907560907c5ac1edd76c",
          "sha256": "89b37a47666039c0a5756455b1b624ed424c2b9cbc9498f5a9aa49aafcfb4214",
          "sha1": "d90f3bb2956ad5db773b8e794231cb2a5efaacee",
          "md5": "6a6354634340cc1a566bbd0d592b304b"
        }
      ]
    }
  ]
}