{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.5.0-alpha03.aar",
          "url": "activity-1.5.0-alpha03.aar",
          "size": 92643,
          "sha512": "6018c15c999e0d4bb51b5372e04191f2cbebb54db22b5053bf652785f74972f826275c09c897f26c750d8bce07f5e7d04358522cf33f90a15ef3646679a990b3",
          "sha256": "be2d888b660dea618fc02b1ec8d8195c1c528b41966c05f90c7a87dfb90a58b6",
          "sha1": "d96f332de180d38fd0db4354837e3ff5a3d83f25",
          "md5": "705790a099c2feeadab4f768972c03fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.5.0-alpha03.aar",
          "url": "activity-1.5.0-alpha03.aar",
          "size": 92643,
          "sha512": "6018c15c999e0d4bb51b5372e04191f2cbebb54db22b5053bf652785f74972f826275c09c897f26c750d8bce07f5e7d04358522cf33f90a15ef3646679a990b3",
          "sha256": "be2d888b660dea618fc02b1ec8d8195c1c528b41966c05f90c7a87dfb90a58b6",
          "sha1": "d96f332de180d38fd0db4354837e3ff5a3d83f25",
          "md5": "705790a099c2feeadab4f768972c03fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.5.0-alpha03-sources.jar",
          "url": "activity-1.5.0-alpha03-sources.jar",
          "size": 39882,
          "sha512": "5bbc4be483800fe8c511d7a825c93680245cced0ae09ac6b28f02a9d1dce0cc5bcd5fc56855e4f8a982d085eb75cf486eb027522ccdff5d45e7f7a9d699b4936",
          "sha256": "aed2b7301cb9a94e9c340be6df927294969282db4f0e094b98d6ca9dfede8778",
          "sha1": "7ff0d8176dc874ddcc1015e27db0fe9697557935",
          "md5": "22ed71abec21c2f8b0ce0e514e63d233"
        }
      ]
    }
  ]
}
