{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.5.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-alpha06.aar",
          "url": "lifecycle-runtime-2.5.0-alpha06.aar",
          "size": 12296,
          "sha512": "2fe5fb65b4d08670eaae7d7f0994258a4026b8fa436f9f0d70b5a20e9f5bc4d783185a0f04f65b61a06b4b82a672c9a989a0d0a28b5645663f0fbc318cf2dd1e",
          "sha256": "f63b793629d44835d223f1d712c5b5830e080ebafada714a4d5e0c9967e72ef7",
          "sha1": "792277a8a6996e0e6c411f941717a00a5cb86560",
          "md5": "4b1430c67c522367f26da9b3d1f4d5bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-alpha06.aar",
          "url": "lifecycle-runtime-2.5.0-alpha06.aar",
          "size": 12296,
          "sha512": "2fe5fb65b4d08670eaae7d7f0994258a4026b8fa436f9f0d70b5a20e9f5bc4d783185a0f04f65b61a06b4b82a672c9a989a0d0a28b5645663f0fbc318cf2dd1e",
          "sha256": "f63b793629d44835d223f1d712c5b5830e080ebafada714a4d5e0c9967e72ef7",
          "sha1": "792277a8a6996e0e6c411f941717a00a5cb86560",
          "md5": "4b1430c67c522367f26da9b3d1f4d5bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-alpha06-sources.jar",
          "url": "lifecycle-runtime-2.5.0-alpha06-sources.jar",
          "size": 8970,
          "sha512": "2009c123e8c19a76eb578ab4a999257a8a815e0f576678921cb327ace677502a07c117cd74a3d88e9cc901591f3e993420a60fc7177abe2e3b08532eddb5a4cf",
          "sha256": "7dd944be47d1245d17aae7cc656880f1d91695501955da5256c8659c6964e656",
          "sha1": "0d255b447102736e536a28b97671c6a736c801b7",
          "md5": "bc3ece2ea0121fea9bc2ba8334f1e80e"
        }
      ]
    }
  ]
}