{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-alpha02.aar",
          "url": "lifecycle-runtime-2.5.0-alpha02.aar",
          "size": 12224,
          "sha512": "37ddfc262b8d3e9755b97ca29000ce8e95f854f38b772c775493621102b72b88686632e3323002e1d4b0ef7cffcb0b8cf7d3fd2ba6edf831da046027a5223ed0",
          "sha256": "0bedca9ffffbf64beff16f5c963cff516298c0d60dca430c16544e550e8e636a",
          "sha1": "903c9bd5fd5b9295d01d2dac983e9ad9795484c8",
          "md5": "e63d837fe11a7cb1cc64143b7ebcc99b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-alpha02.aar",
          "url": "lifecycle-runtime-2.5.0-alpha02.aar",
          "size": 12224,
          "sha512": "37ddfc262b8d3e9755b97ca29000ce8e95f854f38b772c775493621102b72b88686632e3323002e1d4b0ef7cffcb0b8cf7d3fd2ba6edf831da046027a5223ed0",
          "sha256": "0bedca9ffffbf64beff16f5c963cff516298c0d60dca430c16544e550e8e636a",
          "sha1": "903c9bd5fd5b9295d01d2dac983e9ad9795484c8",
          "md5": "e63d837fe11a7cb1cc64143b7ebcc99b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.5.0-alpha02-sources.jar",
          "url": "lifecycle-runtime-2.5.0-alpha02-sources.jar",
          "size": 8927,
          "sha512": "3a9f03beaffff0b273188c91a18f234962052eed4257f5b18b5098d09e2ed9799e3870b5b8cc63eeb429f03ef294f3109365c794bb84b11742048d1a1a0a4288",
          "sha256": "a1757f478939a9ae47e3a005f5c3ce051e50859d54478e3b931fdb06738269a9",
          "sha1": "ae7040cf314de81d20ac69f28f5ab6c9a2c0d1ab",
          "md5": "a34ad95ef12973e07a73efde45a2504e"
        }
      ]
    }
  ]
}
