{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.4.0-alpha03.aar",
          "url": "lifecycle-runtime-2.4.0-alpha03.aar",
          "size": 11454,
          "sha512": "b2ed698d0dc7409e3f36a2923599ca5be4e6f704a61b40149109880eb2a2ad172d8417aac4859909b06bc6382db15972785cc01133096057d8f80df56a4be1a1",
          "sha256": "c9f66a3647317c49e8a9f6e36da580a0f36e72d3e3cce954ecf56346e1d473b8",
          "sha1": "318647b7c9b94c17f8c821f48f49cbb20bb807f8",
          "md5": "352c170cdf370c97375511472d702970"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.4.0-alpha03.aar",
          "url": "lifecycle-runtime-2.4.0-alpha03.aar",
          "size": 11454,
          "sha512": "b2ed698d0dc7409e3f36a2923599ca5be4e6f704a61b40149109880eb2a2ad172d8417aac4859909b06bc6382db15972785cc01133096057d8f80df56a4be1a1",
          "sha256": "c9f66a3647317c49e8a9f6e36da580a0f36e72d3e3cce954ecf56346e1d473b8",
          "sha1": "318647b7c9b94c17f8c821f48f49cbb20bb807f8",
          "md5": "352c170cdf370c97375511472d702970"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.4.0-alpha03-sources.jar",
          "url": "lifecycle-runtime-2.4.0-alpha03-sources.jar",
          "size": 8927,
          "sha512": "3a9f03beaffff0b273188c91a18f234962052eed4257f5b18b5098d09e2ed9799e3870b5b8cc63eeb429f03ef294f3109365c794bb84b11742048d1a1a0a4288",
          "sha256": "a1757f478939a9ae47e3a005f5c3ce051e50859d54478e3b931fdb06738269a9",
          "sha1": "ae7040cf314de81d20ac69f28f5ab6c9a2c0d1ab",
          "md5": "a34ad95ef12973e07a73efde45a2504e"
        }
      ]
    }
  ]
}
