{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-compose-samples",
    "version": "2.6.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-beta01.aar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-beta01.aar",
          "size": 9998,
          "sha512": "c29ea6294a4d09720caf2ad4f5bfc9d9714e7a4233cc656426db5b8630ece60a8ebe5c9283ddcdf76ff5ed889bc4eb2638e75ec54b9c0bc5c4917c5950bcc534",
          "sha256": "73b4aa0cb7a89a67bf3640897026ac30c8bc0242b96e484515d4adbdc16fdd54",
          "sha1": "e2ae49f6856a6d039d132d3885d812f523ee8323",
          "md5": "6d05418620d732564723d9ef8b0af16e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-beta01.aar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-beta01.aar",
          "size": 9998,
          "sha512": "c29ea6294a4d09720caf2ad4f5bfc9d9714e7a4233cc656426db5b8630ece60a8ebe5c9283ddcdf76ff5ed889bc4eb2638e75ec54b9c0bc5c4917c5950bcc534",
          "sha256": "73b4aa0cb7a89a67bf3640897026ac30c8bc0242b96e484515d4adbdc16fdd54",
          "sha1": "e2ae49f6856a6d039d132d3885d812f523ee8323",
          "md5": "6d05418620d732564723d9ef8b0af16e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-beta01-sources.jar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-beta01-sources.jar",
          "size": 1695,
          "sha512": "6b7c33ed90518314fee86c5c196986c42bc1fd965e75abab33607256fd49b942f5cf46a41cd0f731cda7d8352aecb59dff83d9c69fb2e4db11cc7328769d255a",
          "sha256": "9c3611e02a386c84b38c6711d16008c69c54f1f594e24493a561f5de1241f7e0",
          "sha1": "5de57691b2ad2b85a7e59bfe2913b05d9e404281",
          "md5": "5552d4402a66cb165bfbcabb7de21974"
        }
      ]
    }
  ]
}