{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose-samples",
    "version": "2.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-alpha01.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-alpha01.aar",
          "size": 1793,
          "sha512": "3b995acea8c091a9e6535e40847396461413c0beff634a5b6583156823511dd78596da22a307020e01eb6a83cb0ada209b0d3657d27f25b8aebd8f3adb314fd1",
          "sha256": "d2c40cc3852f20f9267155ac9b84d3dbe9ecd6072d99d4121b359ede2db29e10",
          "sha1": "33a30e0f5d128ff00d6ad16efd9b8717a3a3228f",
          "md5": "0a6a5543c93bf40953643fe7bcffeced"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-alpha01.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-alpha01.aar",
          "size": 1793,
          "sha512": "3b995acea8c091a9e6535e40847396461413c0beff634a5b6583156823511dd78596da22a307020e01eb6a83cb0ada209b0d3657d27f25b8aebd8f3adb314fd1",
          "sha256": "d2c40cc3852f20f9267155ac9b84d3dbe9ecd6072d99d4121b359ede2db29e10",
          "sha1": "33a30e0f5d128ff00d6ad16efd9b8717a3a3228f",
          "md5": "0a6a5543c93bf40953643fe7bcffeced"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-alpha01-sources.jar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-alpha01-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
