{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "1.0.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta07"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-beta07"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-1.0.0-alpha05.aar",
          "url": "lifecycle-viewmodel-compose-1.0.0-alpha05.aar",
          "size": 8133,
          "sha512": "96dd392f48614514ad22656fc83f883f895e5bb98a96881ee6237fc2e568ebecafec2e3bf335db5de50aef8607bcd466b6953fa5a4620b4d1afef41de33f1420",
          "sha256": "43561f3fb6963c0cfe385d85c5908eeaf91f029d7d9ff845cc4517db61dcedcd",
          "sha1": "79060c0369d57850641fb1381879d713870be65b",
          "md5": "d7030a7536da6e5d8a7df1e05d5054f4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta07"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-beta07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-1.0.0-alpha05.aar",
          "url": "lifecycle-viewmodel-compose-1.0.0-alpha05.aar",
          "size": 8133,
          "sha512": "96dd392f48614514ad22656fc83f883f895e5bb98a96881ee6237fc2e568ebecafec2e3bf335db5de50aef8607bcd466b6953fa5a4620b4d1afef41de33f1420",
          "sha256": "43561f3fb6963c0cfe385d85c5908eeaf91f029d7d9ff845cc4517db61dcedcd",
          "sha1": "79060c0369d57850641fb1381879d713870be65b",
          "md5": "d7030a7536da6e5d8a7df1e05d5054f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-1.0.0-alpha05-sources.jar",
          "url": "lifecycle-viewmodel-compose-1.0.0-alpha05-sources.jar",
          "size": 2916,
          "sha512": "6da7c39492afbbdc4a878e2f812d714582d95036ec80c45640236f87aab3eb5eaa96423107c04bb0ce96d461fd3653f07dafb353ec9c1911b9c8527ee3b9ee77",
          "sha256": "c683ca62862124133f170c4add1488faf07f9958257659e7cbf0cd0040ebba79",
          "sha1": "04b95044c2925265d7acf1fb092919497e530a36",
          "md5": "3637b5d0853181d4a2e8ecf5c069bfb8"
        }
      ]
    }
  ]
}
