{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.3.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.0-alpha08"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.0-alpha08.aar",
          "url": "activity-ktx-1.3.0-alpha08.aar",
          "size": 32172,
          "sha512": "37ae4e26dbef153f9885e6e4e0c35e9ec5eaba5fbf2981fccdf460da3d66bc15ea9d00b547a3767e1fec8231d27890cb351cc25934cbeab1dde0b5675b4e87a3",
          "sha256": "97756ea61edd225359b50b72535a12016507dc4810dc62314c8e44da72258156",
          "sha1": "64aba98ac5d23a4bf6fb523c442b9285f15caf74",
          "md5": "74882e3d1cecb350ed2bfcd974effb6f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.0-alpha08"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.0-alpha08.aar",
          "url": "activity-ktx-1.3.0-alpha08.aar",
          "size": 32172,
          "sha512": "37ae4e26dbef153f9885e6e4e0c35e9ec5eaba5fbf2981fccdf460da3d66bc15ea9d00b547a3767e1fec8231d27890cb351cc25934cbeab1dde0b5675b4e87a3",
          "sha256": "97756ea61edd225359b50b72535a12016507dc4810dc62314c8e44da72258156",
          "sha1": "64aba98ac5d23a4bf6fb523c442b9285f15caf74",
          "md5": "74882e3d1cecb350ed2bfcd974effb6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.3.0-alpha08-sources.jar",
          "url": "activity-ktx-1.3.0-alpha08-sources.jar",
          "size": 7750,
          "sha512": "f10f4d426d8972e12ea1d1be324878712e012eb904523c577623ddcc6173bce84b7118187fd401b99934aece7449fa59bdde20f4c28c7310f07c27b1584565c5",
          "sha256": "3de7a02ea69a75c95e5b381409464e2ea56194bacf73dc28ecd529fb2d22af0f",
          "sha1": "b61bb9e9dca1b4c0efb31a2b91ef39afabdbcbd7",
          "md5": "e5c7c1eb5829e19494a9bd19c6617cf7"
        }
      ]
    }
  ]
}
