{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.4.1.aar",
          "url": "lifecycle-runtime-testing-2.4.1.aar",
          "size": 8448,
          "sha512": "6980fa0a50165bea31e90dd36944eaafa4e73ab6f175dcdc8009f2ba7ccfcdb8b081fed524179c398392eacc6a780886123b1993995061b8929f6d3a5d68f8de",
          "sha256": "beecf55519377567bfbc341544e2b3ca73cffffb08d5cad1f194720e98891d90",
          "sha1": "f1e69ad524cbf923eb328e5b52b3ad57d82343b7",
          "md5": "31d13123f4591896b631db65ef4cceaa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.4.1.aar",
          "url": "lifecycle-runtime-testing-2.4.1.aar",
          "size": 8448,
          "sha512": "6980fa0a50165bea31e90dd36944eaafa4e73ab6f175dcdc8009f2ba7ccfcdb8b081fed524179c398392eacc6a780886123b1993995061b8929f6d3a5d68f8de",
          "sha256": "beecf55519377567bfbc341544e2b3ca73cffffb08d5cad1f194720e98891d90",
          "sha1": "f1e69ad524cbf923eb328e5b52b3ad57d82343b7",
          "md5": "31d13123f4591896b631db65ef4cceaa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.4.1-sources.jar",
          "url": "lifecycle-runtime-testing-2.4.1-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}
