{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7119694"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-alpha01.aar",
          "url": "activity-1.3.0-alpha01.aar",
          "size": 68076,
          "sha512": "1d45901a9724798c249f17910b21130ece50b4e8f74d49709289b3c6317c06b6d0438504b745527fcd25e58defde405d75642d26de33c36420d940cfa8a30e88",
          "sha256": "e74d273a8e48ce4a1145c1efb9fd34ac7809d68690ff6f147e6e5ecf42effb8e",
          "sha1": "c9324ca41f5f8a3a85424ff660f2fe12cdc1e4ad",
          "md5": "fb9cc3f4c833021e86d3882646c28fa2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-alpha01.aar",
          "url": "activity-1.3.0-alpha01.aar",
          "size": 68076,
          "sha512": "1d45901a9724798c249f17910b21130ece50b4e8f74d49709289b3c6317c06b6d0438504b745527fcd25e58defde405d75642d26de33c36420d940cfa8a30e88",
          "sha256": "e74d273a8e48ce4a1145c1efb9fd34ac7809d68690ff6f147e6e5ecf42effb8e",
          "sha1": "c9324ca41f5f8a3a85424ff660f2fe12cdc1e4ad",
          "md5": "fb9cc3f4c833021e86d3882646c28fa2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.3.0-alpha01-sources.jar",
          "url": "activity-1.3.0-alpha01-sources.jar",
          "size": 35507,
          "sha512": "d48334da6bc0fdbb8e99a94e0c684d57e09d9085085971f72d87b05659b29e7b659b7bc3835f4262b67f707fd3a4b783cf4741daa238bcbfba0a2aea2b0b18b2",
          "sha256": "b89b706a10bec6ce41ceb42a3618a76bfaa50b08bc3e750e2b486bf12831dccc",
          "sha1": "813d294feb840319a7210060dda904d285cc8a02",
          "md5": "b71ada3451dc9929355071ee001aa909"
        }
      ]
    }
  ]
}
