{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-compiler",
    "version": "2.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.6.0-alpha05.jar",
          "url": "lifecycle-compiler-2.6.0-alpha05.jar",
          "size": 49872,
          "sha512": "985957a8806c1c7997d9d75c620793d9689a792cc8234b0a2086e05933f8c1c0c2b9d4b83974eb3995b319618a4dd3a252a7652f3cac0a6f30616323e18c8844",
          "sha256": "4fef712e91ddf788c43b1063b90d082543607470b693b0ab9cf2099887c292e6",
          "sha1": "6c050d385b2404d84887c25ed166eb7ca842547d",
          "md5": "03c7b4cb9b415077c0871615c7e57eaf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-compiler-2.6.0-alpha05.jar",
          "url": "lifecycle-compiler-2.6.0-alpha05.jar",
          "size": 49872,
          "sha512": "985957a8806c1c7997d9d75c620793d9689a792cc8234b0a2086e05933f8c1c0c2b9d4b83974eb3995b319618a4dd3a252a7652f3cac0a6f30616323e18c8844",
          "sha256": "4fef712e91ddf788c43b1063b90d082543607470b693b0ab9cf2099887c292e6",
          "sha1": "6c050d385b2404d84887c25ed166eb7ca842547d",
          "md5": "03c7b4cb9b415077c0871615c7e57eaf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.6.0-alpha05-sources.jar",
          "url": "lifecycle-compiler-2.6.0-alpha05-sources.jar",
          "size": 18983,
          "sha512": "c8e653923ebf52a8cebd372f576845edd9e7eb910a6fd5c34fb981b8b7af29c8907041ca3aaffcf070602e5d1e2c4f796cbfc4b8fe57aaaba8c2500c2d5247b0",
          "sha256": "cf0bc1b22e6aab15c842a58b43e571f3e981bd79e7a1bd3707b9001af80a3f98",
          "sha1": "77cdcc094c8395f6aeabe104109299851a931b77",
          "md5": "3b8351edae46f3fbe3fef1b2a63c7ee8"
        }
      ]
    }
  ]
}