{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.3.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7017154"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.3.0-rc01.aar",
          "url": "lifecycle-livedata-2.3.0-rc01.aar",
          "size": 10659,
          "sha512": "da7c67b99637793f0e704b8b18dc11d38698988edf12be14f6d8f3ea72ba97e25425c509d81d21e02ca4dfec02da4938e53772c7b8a023c3f32d149d7062ad9d",
          "sha256": "53f9f11d7fd1bffd6de0ca32b4e38e386519b650da165ebc6c54ec48720f7b69",
          "sha1": "22343f15edb8987bbfd2fefcce6aac162b0fd0ea",
          "md5": "0de137935c03f27b8c4115413b0f9d7d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.3.0-rc01.aar",
          "url": "lifecycle-livedata-2.3.0-rc01.aar",
          "size": 10659,
          "sha512": "da7c67b99637793f0e704b8b18dc11d38698988edf12be14f6d8f3ea72ba97e25425c509d81d21e02ca4dfec02da4938e53772c7b8a023c3f32d149d7062ad9d",
          "sha256": "53f9f11d7fd1bffd6de0ca32b4e38e386519b650da165ebc6c54ec48720f7b69",
          "sha1": "22343f15edb8987bbfd2fefcce6aac162b0fd0ea",
          "md5": "0de137935c03f27b8c4115413b0f9d7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.3.0-rc01-sources.jar",
          "url": "lifecycle-livedata-2.3.0-rc01-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
