{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-compose",
    "version": "2.6.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.6.0-alpha04.aar",
          "url": "lifecycle-runtime-compose-2.6.0-alpha04.aar",
          "size": 11702,
          "sha512": "ed53ae937552d55cfdd39f795ef1fa1b370b0070ca3a0e87850202ab41733be7c7fb344bc2ebcc6c79f23e68fa4b60eed031562c9e205c8f26474f0a03728ecf",
          "sha256": "675264a68d1b86c60cd4885b0f12c4e934649ddce14f167c637e11fc260ed2cb",
          "sha1": "be1c5f2babd8f72a8be879b8675c159742233336",
          "md5": "03809262dfba18188c8e9569837f85d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.6.0-alpha04.aar",
          "url": "lifecycle-runtime-compose-2.6.0-alpha04.aar",
          "size": 11702,
          "sha512": "ed53ae937552d55cfdd39f795ef1fa1b370b0070ca3a0e87850202ab41733be7c7fb344bc2ebcc6c79f23e68fa4b60eed031562c9e205c8f26474f0a03728ecf",
          "sha256": "675264a68d1b86c60cd4885b0f12c4e934649ddce14f167c637e11fc260ed2cb",
          "sha1": "be1c5f2babd8f72a8be879b8675c159742233336",
          "md5": "03809262dfba18188c8e9569837f85d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.6.0-alpha04-sources.jar",
          "url": "lifecycle-runtime-compose-2.6.0-alpha04-sources.jar",
          "size": 2157,
          "sha512": "10ac2fd95ba549e3a1684facaf6caae2248ff24541681aa23db2aa13d1b6d76e62f14c180865a84836007cda8f865146b1118d90c99b29b35c7cb2ec77cde361",
          "sha256": "dc61e56cf83fda48b6116e89f21846ec63d768d2e800ac0fe6993289c6dbe926",
          "sha1": "7f01a3a02a438ea53e95a9922ee61da155d4355a",
          "md5": "107d8a6aa18818fc9a42e3217acef789"
        }
      ]
    }
  ]
}