{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-compose-samples",
    "version": "2.6.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-alpha04.aar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-alpha04.aar",
          "size": 9674,
          "sha512": "c547bf1526cb45d40711ba2c83e4dcb48a73f9c385c35d5d778bbb64fd9274db6c75d1aea6c6c773f5505dfe25e681298872d1c5653b9767bce7103b8ca97129",
          "sha256": "96bc3155bd646e3702683708ece1828af6f65aef557070ef8cb49887cd38cc04",
          "sha1": "7c7297d13fd32fb9819d489e3bc0b450d163d342",
          "md5": "c81797dab8fed504b9a6e6532abaad18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-alpha04.aar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-alpha04.aar",
          "size": 9674,
          "sha512": "c547bf1526cb45d40711ba2c83e4dcb48a73f9c385c35d5d778bbb64fd9274db6c75d1aea6c6c773f5505dfe25e681298872d1c5653b9767bce7103b8ca97129",
          "sha256": "96bc3155bd646e3702683708ece1828af6f65aef557070ef8cb49887cd38cc04",
          "sha1": "7c7297d13fd32fb9819d489e3bc0b450d163d342",
          "md5": "c81797dab8fed504b9a6e6532abaad18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-alpha04-sources.jar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-alpha04-sources.jar",
          "size": 1695,
          "sha512": "6b7c33ed90518314fee86c5c196986c42bc1fd965e75abab33607256fd49b942f5cf46a41cd0f731cda7d8352aecb59dff83d9c69fb2e4db11cc7328769d255a",
          "sha256": "9c3611e02a386c84b38c6711d16008c69c54f1f594e24493a561f5de1241f7e0",
          "sha1": "5de57691b2ad2b85a7e59bfe2913b05d9e404281",
          "md5": "5552d4402a66cb165bfbcabb7de21974"
        }
      ]
    }
  ]
}