{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.5.0-alpha01.aar",
          "url": "activity-ktx-1.5.0-alpha01.aar",
          "size": 28291,
          "sha512": "e38ec660239494d6e144133adc374976e243836a27d32b39a8996832866ef614a1a8e85cf8a194ede1d91efbcb5ff359aa035ac8ea13215ce162f40e8b828b38",
          "sha256": "b34e35f82d2e43deb67077b260588af1987dca7cff2231eed744c3df72220e42",
          "sha1": "ff9a7b3fe6b9083b6fc9b5545f4255176801b304",
          "md5": "18dc2b2a7fff0432e3ccdf6d6f071baa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.5.0-alpha01.aar",
          "url": "activity-ktx-1.5.0-alpha01.aar",
          "size": 28291,
          "sha512": "e38ec660239494d6e144133adc374976e243836a27d32b39a8996832866ef614a1a8e85cf8a194ede1d91efbcb5ff359aa035ac8ea13215ce162f40e8b828b38",
          "sha256": "b34e35f82d2e43deb67077b260588af1987dca7cff2231eed744c3df72220e42",
          "sha1": "ff9a7b3fe6b9083b6fc9b5545f4255176801b304",
          "md5": "18dc2b2a7fff0432e3ccdf6d6f071baa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.5.0-alpha01-sources.jar",
          "url": "activity-ktx-1.5.0-alpha01-sources.jar",
          "size": 7796,
          "sha512": "52d7ad83a8b1e86c3c918f01851b3f5eba1f5419c4458e6bcf1308a7391703b9dd608449712b4b64ec42e5d2d2312fa97713dc944cce54ae0356d041cdb6f99c",
          "sha256": "18a3edbb0477ea00564499dd808f553ffdfe1ddcc864ccb7d310705a74b774d3",
          "sha1": "b951dde497e2eabcbd35ae7c8336046a5265a5d2",
          "md5": "0deabfdaf04c8934c64224afe215c559"
        }
      ]
    }
  ]
}
