{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "2.6.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.6.0-alpha04.aar",
          "url": "lifecycle-viewmodel-compose-2.6.0-alpha04.aar",
          "size": 22034,
          "sha512": "2a532423a946e49977bc0b5ed7df85c30f9adb12ef07612c6585c9d49eb4fb959dd5568f9528a3f09a691d0083f6f999e8472414b046ed0cd24051f62752badc",
          "sha256": "5de258eeeadefb7a43f2948cc84018054487ea899a1d114d9c933bfef4d6739f",
          "sha1": "01e87afd23fbee29e49d1eee641f7ede1e5d9e42",
          "md5": "e2e7b83c8ddbb463f568fbc391ea796e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.6.0-alpha04.aar",
          "url": "lifecycle-viewmodel-compose-2.6.0-alpha04.aar",
          "size": 22034,
          "sha512": "2a532423a946e49977bc0b5ed7df85c30f9adb12ef07612c6585c9d49eb4fb959dd5568f9528a3f09a691d0083f6f999e8472414b046ed0cd24051f62752badc",
          "sha256": "5de258eeeadefb7a43f2948cc84018054487ea899a1d114d9c933bfef4d6739f",
          "sha1": "01e87afd23fbee29e49d1eee641f7ede1e5d9e42",
          "md5": "e2e7b83c8ddbb463f568fbc391ea796e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-2.6.0-alpha04-sources.jar",
          "url": "lifecycle-viewmodel-compose-2.6.0-alpha04-sources.jar",
          "size": 6396,
          "sha512": "3daf843d45c2ca38e13c4b9a30ba1e9da43c7e1742ec9c30a00f3087b80a81b2a60a330827cfdb3f14b07d1c9550bc1f62bcf6f4a583b84c7d357064232ce3dc",
          "sha256": "436f1ace1326d46a682d18e274c5057afbf72f31f787d99611856b4223926bb0",
          "sha1": "e967730b764be6a1452aa6bbd5685da8fd1f2f94",
          "md5": "2790832ad6cde8783467b159a24678c0"
        }
      ]
    }
  ]
}