{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7104547"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.3.0.aar",
          "url": "lifecycle-service-2.3.0.aar",
          "size": 3832,
          "sha512": "2e2ed656da1e8c247c97a865f0bcf7477d36f5dcd7a42e115eb88f3967e63640ad2753858c9ded6b88b06080deced33218e1309830e95fabe05c0f1eca78cd92",
          "sha256": "cf8659567e245e18bc3aaff0f6e4e5b81ea123536df9481ec7f46a2133fb81e7",
          "sha1": "8e30677cd54dd62004c51d9a8234654995f3f872",
          "md5": "7dfdc8dea2a09c2e3494125b6468ed9a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.3.0.aar",
          "url": "lifecycle-service-2.3.0.aar",
          "size": 3832,
          "sha512": "2e2ed656da1e8c247c97a865f0bcf7477d36f5dcd7a42e115eb88f3967e63640ad2753858c9ded6b88b06080deced33218e1309830e95fabe05c0f1eca78cd92",
          "sha256": "cf8659567e245e18bc3aaff0f6e4e5b81ea123536df9481ec7f46a2133fb81e7",
          "sha1": "8e30677cd54dd62004c51d9a8234654995f3f872",
          "md5": "7dfdc8dea2a09c2e3494125b6468ed9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.3.0-sources.jar",
          "url": "lifecycle-service-2.3.0-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
