{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7137781"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-alpha02.aar",
          "url": "activity-1.3.0-alpha02.aar",
          "size": 68092,
          "sha512": "5e6c56f4f5fddf1d4818d783893f76665ef7599e8ff8217ddc9c33749aee94a51716574fd16ca5872823a3e7c77243bb5bf904e3249133b617529cae92401058",
          "sha256": "c97b4435f64f40e64fefd549c2716dd8e3cff552c1952bb5469af96a60992869",
          "sha1": "f50bff934c38d49be4913113e4f6927a9ecead63",
          "md5": "fa191db758fdb237ed5fd4cc05559ee3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-alpha02.aar",
          "url": "activity-1.3.0-alpha02.aar",
          "size": 68092,
          "sha512": "5e6c56f4f5fddf1d4818d783893f76665ef7599e8ff8217ddc9c33749aee94a51716574fd16ca5872823a3e7c77243bb5bf904e3249133b617529cae92401058",
          "sha256": "c97b4435f64f40e64fefd549c2716dd8e3cff552c1952bb5469af96a60992869",
          "sha1": "f50bff934c38d49be4913113e4f6927a9ecead63",
          "md5": "fa191db758fdb237ed5fd4cc05559ee3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.3.0-alpha02-sources.jar",
          "url": "activity-1.3.0-alpha02-sources.jar",
          "size": 35507,
          "sha512": "d48334da6bc0fdbb8e99a94e0c684d57e09d9085085971f72d87b05659b29e7b659b7bc3835f4262b67f707fd3a4b783cf4741daa238bcbfba0a2aea2b0b18b2",
          "sha256": "b89b706a10bec6ce41ceb42a3618a76bfaa50b08bc3e750e2b486bf12831dccc",
          "sha1": "813d294feb840319a7210060dda904d285cc8a02",
          "md5": "b71ada3451dc9929355071ee001aa909"
        }
      ]
    }
  ]
}
