{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6684396"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.3.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-alpha06.aar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-alpha06.aar",
          "size": 2127,
          "sha512": "86a62ef23b73a5c0a8e7fece2711a74215751e07c4a47de9950cfa18cd134223248a0d4f417129c26e0a018dcfa216ce07706398bca7e7b4ebd543ce22f7eadd",
          "sha256": "800dc2becee7febfae5f81952d360868dfdc06222dbcbe0b8d85da26a7eff598",
          "sha1": "7297892d0915de69bcd593d8fef3a59f65f21cb8",
          "md5": "8b4b27c33a0113e3b3204388baf543b2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.3.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-alpha06.aar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-alpha06.aar",
          "size": 2127,
          "sha512": "86a62ef23b73a5c0a8e7fece2711a74215751e07c4a47de9950cfa18cd134223248a0d4f417129c26e0a018dcfa216ce07706398bca7e7b4ebd543ce22f7eadd",
          "sha256": "800dc2becee7febfae5f81952d360868dfdc06222dbcbe0b8d85da26a7eff598",
          "sha1": "7297892d0915de69bcd593d8fef3a59f65f21cb8",
          "md5": "8b4b27c33a0113e3b3204388baf543b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-alpha06-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-alpha06-sources.jar",
          "size": 1260,
          "sha512": "9855fea967e2e3e524d04ecf0d9838f1c96fd94b80c348dc612c69bd42ca82ce4779cf587cc833a4dde819b94f2e92589cc478ab28b31638de1e1b32d7a61c36",
          "sha256": "36ab72c2b848531aed3a416c5d0636c24cc64463b3685b0825eab17924b0aa4e",
          "sha1": "f1045318682f7dbef230a3cf1ce0ed2377d14903",
          "md5": "173bdd2cae36a9dc56a58e4f5482488d"
        }
      ]
    }
  ]
}
