{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.5.0-alpha05.aar",
          "url": "lifecycle-viewmodel-2.5.0-alpha05.aar",
          "size": 34727,
          "sha512": "0e5014ecd047fff8c4a515d0c78b85374ed0871e48b02ae69822c86b464e0cd1ff5dae6eba625b441462afb5e358023a31f4c9ef066ea11afda1f7918a8e3b03",
          "sha256": "df37291b1c18611cda03e49740a9cf85a37515e82c5f3eb002ad7402793b7daf",
          "sha1": "75233d902423598766b8a253a5c0e33e82b69142",
          "md5": "347d2b991ddf3c31aa0bfa594b14e032"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.5.0-alpha05.aar",
          "url": "lifecycle-viewmodel-2.5.0-alpha05.aar",
          "size": 34727,
          "sha512": "0e5014ecd047fff8c4a515d0c78b85374ed0871e48b02ae69822c86b464e0cd1ff5dae6eba625b441462afb5e358023a31f4c9ef066ea11afda1f7918a8e3b03",
          "sha256": "df37291b1c18611cda03e49740a9cf85a37515e82c5f3eb002ad7402793b7daf",
          "sha1": "75233d902423598766b8a253a5c0e33e82b69142",
          "md5": "347d2b991ddf3c31aa0bfa594b14e032"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-2.5.0-alpha05-sources.jar",
          "url": "lifecycle-viewmodel-2.5.0-alpha05-sources.jar",
          "size": 17215,
          "sha512": "66b5c4f4b7eb6a33613049c1756099e1cd681ff59578261742c9ce65f07fbfd3784e18acb5e1dd27d1ce4250d6dde6915d5fccc512c298534b8c1c2a63d85c70",
          "sha256": "ecf61b1e024365f4cc442ceb8c5f8a6d20054d87e2e10bf474f0ffb1a504ae8e",
          "sha1": "e93529c8f5b5e27af696681dfb4dc7561ac6e849",
          "md5": "d66a9bf927a8461f1be3f3fd3de32587"
        }
      ]
    }
  ]
}