{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.6.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.6.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.6.0-alpha03.aar",
          "url": "lifecycle-reactivestreams-ktx-2.6.0-alpha03.aar",
          "size": 3644,
          "sha512": "9494da743a45929452980beaa88ba73f121ace1769488922073e7a8846dcbb3e15e0d75e3fa8cbbd9aceb7dcddef6556fe4c5d0ab45da3943a1f3f3b8499cdf2",
          "sha256": "6b344b513370beb214f5f29a45e5f8a2e15be2839df1407237a6221f35526504",
          "sha1": "3168b8641bde81a968e9f6d314d843090362fc9d",
          "md5": "3cbccce39619dd5aba2c199c653f7378"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.6.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.6.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.6.0-alpha03.aar",
          "url": "lifecycle-reactivestreams-ktx-2.6.0-alpha03.aar",
          "size": 3644,
          "sha512": "9494da743a45929452980beaa88ba73f121ace1769488922073e7a8846dcbb3e15e0d75e3fa8cbbd9aceb7dcddef6556fe4c5d0ab45da3943a1f3f3b8499cdf2",
          "sha256": "6b344b513370beb214f5f29a45e5f8a2e15be2839df1407237a6221f35526504",
          "sha1": "3168b8641bde81a968e9f6d314d843090362fc9d",
          "md5": "3cbccce39619dd5aba2c199c653f7378"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.6.0-alpha03-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.6.0-alpha03-sources.jar",
          "size": 1261,
          "sha512": "bb0f402ed24247b2fd8e5ecbfec147427d84a8f18bf21cb5857c1fee5746e2a97febac326c894484fe6e86a515fe1bfd05c3b1538eb3f0f1cce712f280a76861",
          "sha256": "c50b9f047a5b5d5ee5d330b3e2dc45f4ae8deca41f607d1d495792c89e731048",
          "sha1": "23c53fd2626cac61baac62c95dec1c49046e0261",
          "md5": "5d68075becef226fa5ce3a00a8721ea7"
        }
      ]
    }
  ]
}