{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-process",
    "version": "2.3.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7017154"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.3.0-rc01.aar",
          "url": "lifecycle-process-2.3.0-rc01.aar",
          "size": 8927,
          "sha512": "185b046efbb26d3ffd46744d1b3a32942f3413f3d4518013ba95204f7b27f45fc528037b7ca9dc70b97be9546f32da1db234dfa1f52699a1ffc8a35fadc400fb",
          "sha256": "68ac6d6b505064635997a9515418810757a5d42166ddb6ba2139fab7c44e12cc",
          "sha1": "66c1b371393f22b908b5525c4b3661c200303cda",
          "md5": "14cf12905678cc05fe52bb0ea30f5761"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.3.0-rc01.aar",
          "url": "lifecycle-process-2.3.0-rc01.aar",
          "size": 8927,
          "sha512": "185b046efbb26d3ffd46744d1b3a32942f3413f3d4518013ba95204f7b27f45fc528037b7ca9dc70b97be9546f32da1db234dfa1f52699a1ffc8a35fadc400fb",
          "sha256": "68ac6d6b505064635997a9515418810757a5d42166ddb6ba2139fab7c44e12cc",
          "sha1": "66c1b371393f22b908b5525c4b3661c200303cda",
          "md5": "14cf12905678cc05fe52bb0ea30f5761"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-process-2.3.0-rc01-sources.jar",
          "url": "lifecycle-process-2.3.0-rc01-sources.jar",
          "size": 5779,
          "sha512": "8b0aebfa4a7182c1b8cd1aa6c2aeaa7d6f87fe0612bcafd186bf992ae55d0bfe9e7e716e00da6976b2a7e50477cdbc126186dbdd9a5339b2a380f0eb44efbfdb",
          "sha256": "34247e6a4c63d14f59c37f0e1780f0b64329e52316f22b53c9a6e0975db030dd",
          "sha1": "47344d875a6f6b0db710194fc03b511ddc8b13cf",
          "md5": "3a273ea3c91f35168e08dd4540ac309b"
        }
      ]
    }
  ]
}
