{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7183123"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.2.1.aar",
          "url": "activity-ktx-1.2.1.aar",
          "size": 19771,
          "sha512": "112faa9d3c85c763d1ec6988ceb873f88817d70ed70b19a4836924b6c5f36ed273b1832db50af6b99720216142ede2566d42adbf276f8345ba59cf435a35501f",
          "sha256": "bf0cf2cab85e2de09986eadd42238e745749419b4eae8bdf5c07235e82c472bf",
          "sha1": "cd109ab6f89ed541aec23ad2671863b313b67527",
          "md5": "609d86fcda581f4a12fa682b642d5f30"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.2.1.aar",
          "url": "activity-ktx-1.2.1.aar",
          "size": 19771,
          "sha512": "112faa9d3c85c763d1ec6988ceb873f88817d70ed70b19a4836924b6c5f36ed273b1832db50af6b99720216142ede2566d42adbf276f8345ba59cf435a35501f",
          "sha256": "bf0cf2cab85e2de09986eadd42238e745749419b4eae8bdf5c07235e82c472bf",
          "sha1": "cd109ab6f89ed541aec23ad2671863b313b67527",
          "md5": "609d86fcda581f4a12fa682b642d5f30"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.2.1-sources.jar",
          "url": "activity-ktx-1.2.1-sources.jar",
          "size": 6129,
          "sha512": "c200adb95b52aa1e21baa37cc4a09ba40c7953e5b9d976af27d341358120aa6fcff35820566e852c698600379ff4421927b7defe72b39664709c6cf1ff1c9bb6",
          "sha256": "efaf9cabd37472c01a222864f955218fb43dfe1a8f0ceddf7bf99bae11000af3",
          "sha1": "827664f9421e56e79f9eed7223ba4a5d67d941c2",
          "md5": "df582cf41df416363a854f5a5cede6ca"
        }
      ]
    }
  ]
}
