{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-ktx",
    "version": "2.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.4.0-beta01.aar",
          "url": "lifecycle-livedata-ktx-2.4.0-beta01.aar",
          "size": 41309,
          "sha512": "56821d25b02d483800752da77bf62e30e4af19dc53331c18306cc5dc4fc6c919e6290e29b826ce2d924d95b13a4c508f9cc92921ebfa0132a988f7e574fec857",
          "sha256": "fb5e4c6f97b841dfc0556ced6853285cdd21d2407dfa6ce2a449b1bcb185daf1",
          "sha1": "c0e898427716b03c7a3b9450feea5b0cc4ce4a3d",
          "md5": "6d0f4e0867071ee42a2bb8086ae5ea18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.4.0-beta01.aar",
          "url": "lifecycle-livedata-ktx-2.4.0-beta01.aar",
          "size": 41309,
          "sha512": "56821d25b02d483800752da77bf62e30e4af19dc53331c18306cc5dc4fc6c919e6290e29b826ce2d924d95b13a4c508f9cc92921ebfa0132a988f7e574fec857",
          "sha256": "fb5e4c6f97b841dfc0556ced6853285cdd21d2407dfa6ce2a449b1bcb185daf1",
          "sha1": "c0e898427716b03c7a3b9450feea5b0cc4ce4a3d",
          "md5": "6d0f4e0867071ee42a2bb8086ae5ea18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.4.0-beta01-sources.jar",
          "url": "lifecycle-livedata-ktx-2.4.0-beta01-sources.jar",
          "size": 8605,
          "sha512": "bf68a5fa3b3dcf7107cfcf168327bd0868a9e751043900fb9c03cf24194555b8aeed044a6ec016d75b01f41d5b8cba14a94dcf463eb0cc0827697224f2a0abda",
          "sha256": "2fec6a303d980782a936f0d50dee895daf3526501e94dfad6bfd901b944bf1e1",
          "sha1": "4aa2db934fc7bfa0f648f1ddee7fd2a436d7712c",
          "md5": "0385e246a505d01919242329d23e562e"
        }
      ]
    }
  ]
}
