{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.4.0.aar",
          "url": "lifecycle-runtime-testing-2.4.0.aar",
          "size": 8448,
          "sha512": "d03673c499b8725efb5cc98b5c52eec5ab8e88b728ca5e689ffb71eb2444bb595e173d2eb119fbe488a0bf5d70a155d331702b58512385f43bacfd1cdfb25d37",
          "sha256": "54eca2efa255ad749613ff927fa95710140338c296984d88e6d1dc1378a81c27",
          "sha1": "4dc261abeb0b6d9b0659518a9b9c4787ecdd36f1",
          "md5": "29472ecebae8fc67c3d13cb193bbe121"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.4.0.aar",
          "url": "lifecycle-runtime-testing-2.4.0.aar",
          "size": 8448,
          "sha512": "d03673c499b8725efb5cc98b5c52eec5ab8e88b728ca5e689ffb71eb2444bb595e173d2eb119fbe488a0bf5d70a155d331702b58512385f43bacfd1cdfb25d37",
          "sha256": "54eca2efa255ad749613ff927fa95710140338c296984d88e6d1dc1378a81c27",
          "sha1": "4dc261abeb0b6d9b0659518a9b9c4787ecdd36f1",
          "md5": "29472ecebae8fc67c3d13cb193bbe121"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.4.0-sources.jar",
          "url": "lifecycle-runtime-testing-2.4.0-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}
