{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-beta01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.8.0-alpha01.aar",
          "url": "activity-ktx-1.8.0-alpha01.aar",
          "size": 26468,
          "sha512": "e9ef6e11f1dcdbbf4f2ade38b5f4c9e37555d59a3e6be2629efb15d8794cae40c655052cf5ccab7191d7817ea4c532ff25c7f2b4e2701a80bc7b0e2fff69a717",
          "sha256": "419dc8cf5c3e0699fc10c80f75cce4d73930c35aed28a35675a115d9fe75b95c",
          "sha1": "6466a71fe1ec43bcd9a94ac72af0aaa25f2177fa",
          "md5": "5b66cba35cb44c96577f3ea832068d68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-beta01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.8.0-alpha01.aar",
          "url": "activity-ktx-1.8.0-alpha01.aar",
          "size": 26468,
          "sha512": "e9ef6e11f1dcdbbf4f2ade38b5f4c9e37555d59a3e6be2629efb15d8794cae40c655052cf5ccab7191d7817ea4c532ff25c7f2b4e2701a80bc7b0e2fff69a717",
          "sha256": "419dc8cf5c3e0699fc10c80f75cce4d73930c35aed28a35675a115d9fe75b95c",
          "sha1": "6466a71fe1ec43bcd9a94ac72af0aaa25f2177fa",
          "md5": "5b66cba35cb44c96577f3ea832068d68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.8.0-alpha01-sources.jar",
          "url": "activity-ktx-1.8.0-alpha01-sources.jar",
          "size": 5891,
          "sha512": "0ab223f5f772f37a5e9d647b10c1e1addc94a60bd1cc23067b0fb4b10d1c035df41326f1ffbaac47d33acb338d9c2eb76288a1acd104c9713eff54de9735024c",
          "sha256": "aa0efa1286eca31f19921e14807731242ac606ddcc8588c1b10550f2293dd6c6",
          "sha1": "303ffe73fa85353c185e2281d60fb8fc65be8bc8",
          "md5": "c6e340fecd1713a2be35815d65373ff0"
        }
      ]
    }
  ]
}