{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.6.0-alpha01.aar",
          "url": "lifecycle-viewmodel-2.6.0-alpha01.aar",
          "size": 35367,
          "sha512": "ba8771c3f5249e7fba82c3d3749f452b0c84f997bbf3118f196de6b498afc83d21cc3e17f4d8cfe536cf297c05b90ab84fea01bab38a6dced70f1aedab154630",
          "sha256": "a88ad1f9edfc267d455673a54770c3eda82757b70cf8318f20f42df1dbaa1218",
          "sha1": "8d74d6e90f5a05836b5cb2e3ef265fd3a87ee879",
          "md5": "74b2d76a4ad54d29a03cf359fc1302cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.6.0-alpha01.aar",
          "url": "lifecycle-viewmodel-2.6.0-alpha01.aar",
          "size": 35367,
          "sha512": "ba8771c3f5249e7fba82c3d3749f452b0c84f997bbf3118f196de6b498afc83d21cc3e17f4d8cfe536cf297c05b90ab84fea01bab38a6dced70f1aedab154630",
          "sha256": "a88ad1f9edfc267d455673a54770c3eda82757b70cf8318f20f42df1dbaa1218",
          "sha1": "8d74d6e90f5a05836b5cb2e3ef265fd3a87ee879",
          "md5": "74b2d76a4ad54d29a03cf359fc1302cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-2.6.0-alpha01-sources.jar",
          "url": "lifecycle-viewmodel-2.6.0-alpha01-sources.jar",
          "size": 17318,
          "sha512": "ac9ccc0e1beab18ba30352b006a6874d91960927ac92b153736743ab71e0a824786394256b684f8c28cfd9a30de1690fddea11b97e2b71138250f6af4afa8d47",
          "sha256": "e5b85791cc624ad3df72be77cc35a736c29e8161cf8085367fdc4e8d912ad7ec",
          "sha1": "e4f5125d80cf6fd0822a581848be527086ca32f1",
          "md5": "495918920a884dfc7669f1e81802e43a"
        }
      ]
    }
  ]
}