{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-alpha03.aar",
          "url": "lifecycle-runtime-testing-2.5.0-alpha03.aar",
          "size": 8531,
          "sha512": "5eb81ab64e90c94d6d3732c496084ccd36d2a740a17f744fdf6962751e06db8199e052adf731e61b157bd9d10a8eb1e4ca33457f46be93688cc97e8cdb69afb7",
          "sha256": "ea0760fa212457d712c0467199a6cd6278581b206e78213aa28e69107505b57a",
          "sha1": "2b633fd4d98da19eb75a45813ce6377abdae9d08",
          "md5": "e77baaf3881a658268117a10e76ac898"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-alpha03.aar",
          "url": "lifecycle-runtime-testing-2.5.0-alpha03.aar",
          "size": 8531,
          "sha512": "5eb81ab64e90c94d6d3732c496084ccd36d2a740a17f744fdf6962751e06db8199e052adf731e61b157bd9d10a8eb1e4ca33457f46be93688cc97e8cdb69afb7",
          "sha256": "ea0760fa212457d712c0467199a6cd6278581b206e78213aa28e69107505b57a",
          "sha1": "2b633fd4d98da19eb75a45813ce6377abdae9d08",
          "md5": "e77baaf3881a658268117a10e76ac898"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-alpha03-sources.jar",
          "url": "lifecycle-runtime-testing-2.5.0-alpha03-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}
