{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-ktx",
    "version": "2.5.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.5.0-alpha06.aar",
          "url": "lifecycle-livedata-ktx-2.5.0-alpha06.aar",
          "size": 40776,
          "sha512": "6855af0cf3b5cf759858526504ad478762cae166f70e439091f533ad2a7ae799d7fdce6ee32fd662a9b47a32a7bbb09ed4b42bcbea0110bc7163edc7d1019f05",
          "sha256": "7be59c6db8c4d32d3e8902ebb73db4f52231ab528d5e0ffea47f3b9189b0fff7",
          "sha1": "7bdec8c146a5a8fa15a5c6503bdb16eba2716ef0",
          "md5": "920e8f524c143a9dcbd3b7d670e721e5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.5.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.5.0-alpha06.aar",
          "url": "lifecycle-livedata-ktx-2.5.0-alpha06.aar",
          "size": 40776,
          "sha512": "6855af0cf3b5cf759858526504ad478762cae166f70e439091f533ad2a7ae799d7fdce6ee32fd662a9b47a32a7bbb09ed4b42bcbea0110bc7163edc7d1019f05",
          "sha256": "7be59c6db8c4d32d3e8902ebb73db4f52231ab528d5e0ffea47f3b9189b0fff7",
          "sha1": "7bdec8c146a5a8fa15a5c6503bdb16eba2716ef0",
          "md5": "920e8f524c143a9dcbd3b7d670e721e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.5.0-alpha06-sources.jar",
          "url": "lifecycle-livedata-ktx-2.5.0-alpha06-sources.jar",
          "size": 8725,
          "sha512": "821c6091de18f97dcb9e34631e9fa9f04886992595f01391ffe88a30401bafe2c26d03f6c6514a86d38f722ec3d6448d71275075753e6deb1e7999f63b33d89e",
          "sha256": "93b88aed20951cf9ffdc604ae665414bca0811c069986c339d0d1991861fa956",
          "sha1": "9017d4f6a545e0fd90d4a40bef15b517fa32fbcb",
          "md5": "edf93d3aa22eb5d1ac37890a66fb05a6"
        }
      ]
    }
  ]
}