{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-compiler",
    "version": "2.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.5.0-alpha01.jar",
          "url": "lifecycle-compiler-2.5.0-alpha01.jar",
          "size": 49133,
          "sha512": "fe985f720c41df56282d745a32ff1571c279c3a2b56d9f5d5724fa7a240212a8813c4881a388a77ed0be90b8e5f73f4506eb192d7fbea56f63232614789294a7",
          "sha256": "15869dafbdd729d41e909eb12e4b4e949dbb30580e18125a56909af947596746",
          "sha1": "c22d285860ff1afed7d05c7428e2a19800bb8fbe",
          "md5": "1175cdae9524da91d365cc1126f7ff63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-compiler-2.5.0-alpha01.jar",
          "url": "lifecycle-compiler-2.5.0-alpha01.jar",
          "size": 49133,
          "sha512": "fe985f720c41df56282d745a32ff1571c279c3a2b56d9f5d5724fa7a240212a8813c4881a388a77ed0be90b8e5f73f4506eb192d7fbea56f63232614789294a7",
          "sha256": "15869dafbdd729d41e909eb12e4b4e949dbb30580e18125a56909af947596746",
          "sha1": "c22d285860ff1afed7d05c7428e2a19800bb8fbe",
          "md5": "1175cdae9524da91d365cc1126f7ff63"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.5.0-alpha01-sources.jar",
          "url": "lifecycle-compiler-2.5.0-alpha01-sources.jar",
          "size": 18983,
          "sha512": "ca17efe01b105646b8c4e6ab80a94aa11e08d9a0294813b4d8b4c237368fe3340f2ead7a1daaaff4311e97e7109a4155e65b308686570d1d2bb6f782fa341cf8",
          "sha256": "cbf9618ee4cb0170a7030bffd2480507261af831552bacd101db3bce319622d2",
          "sha1": "aa8485e5b4ed1777938edf2ff3d96b89ba07c51c",
          "md5": "787146ee536af428776a9fa21a83fa4a"
        }
      ]
    }
  ]
}
