{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-compose-samples",
    "version": "2.6.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-alpha02.aar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-alpha02.aar",
          "size": 9857,
          "sha512": "8eadbcd9cf8d5f4ae64b85ed3404de0724b544fe66447540b48ef532f52f523b9cc43ac6050bdd7d5c850b138ee8264c2f6d298ca4d8a6e3e971b99de7f66587",
          "sha256": "e1bef688877be8b034b4962044d9badfcde45b2142b9c893741656b8d6415246",
          "sha1": "5de18a2a3105f1c534c98c764fc861071aa7c8b5",
          "md5": "c11172f8e4c4d15325162a734a8d2b57"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-alpha02.aar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-alpha02.aar",
          "size": 9857,
          "sha512": "8eadbcd9cf8d5f4ae64b85ed3404de0724b544fe66447540b48ef532f52f523b9cc43ac6050bdd7d5c850b138ee8264c2f6d298ca4d8a6e3e971b99de7f66587",
          "sha256": "e1bef688877be8b034b4962044d9badfcde45b2142b9c893741656b8d6415246",
          "sha1": "5de18a2a3105f1c534c98c764fc861071aa7c8b5",
          "md5": "c11172f8e4c4d15325162a734a8d2b57"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-alpha02-sources.jar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-alpha02-sources.jar",
          "size": 1731,
          "sha512": "f32a32a12973855c0eab98d590f8ab6a0043e7640f01f32e0d6d4278252fd89bbbf9cdbfc9674ac086eecde7c1d93a8262e0ee334bbd0e78c2cabf952dd36f52",
          "sha256": "ef6d4ceecbf1088ff696b4a6d673133df23ab41f025fb27f881b62ab43d15d6c",
          "sha1": "9f69512e7023d6927160997f98484e79c8694fc5",
          "md5": "9515fd8b08da901770d198ce6eb0b15a"
        }
      ]
    }
  ]
}