{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.5.0-alpha01.aar",
          "url": "activity-1.5.0-alpha01.aar",
          "size": 91689,
          "sha512": "1dc98279bd9dd779ac20d10be7f2c255a92973c7fcbbe5c1c901e156ad77c121d0074fa946a71b201ff878fdfdde56c744ef291d321d878a5cd96ab212622a9d",
          "sha256": "d15d2c3613e5502cfd42d70b1c9ede0fdd27c5d18a04bb5177951f2c7e82e459",
          "sha1": "5a7cc4e1d0deb1522772ae4cf407eba9b3f89823",
          "md5": "adaf7d86145d655bd882075b3337c7b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.5.0-alpha01.aar",
          "url": "activity-1.5.0-alpha01.aar",
          "size": 91689,
          "sha512": "1dc98279bd9dd779ac20d10be7f2c255a92973c7fcbbe5c1c901e156ad77c121d0074fa946a71b201ff878fdfdde56c744ef291d321d878a5cd96ab212622a9d",
          "sha256": "d15d2c3613e5502cfd42d70b1c9ede0fdd27c5d18a04bb5177951f2c7e82e459",
          "sha1": "5a7cc4e1d0deb1522772ae4cf407eba9b3f89823",
          "md5": "adaf7d86145d655bd882075b3337c7b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.5.0-alpha01-sources.jar",
          "url": "activity-1.5.0-alpha01-sources.jar",
          "size": 39460,
          "sha512": "348bb4e4a80a5608ac7a323cae729d87773f94e9f4c3536ebe74a4f7b0d7b3bd0ec1fdf961098f87eb9039419692d90be9c240d0193dede947d301eea230774c",
          "sha256": "c97eeec131834debfb5aba200fb253f7fe2871bec1249d1c892558f1afe3764a",
          "sha1": "3f2d5a7de4119b2502ac7c98f50a8e8e62a3ddf5",
          "md5": "2504d4e0c4bf7b813e9ce6e7eecd05fe"
        }
      ]
    }
  ]
}
