{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.4.0-rc01.aar",
          "url": "activity-1.4.0-rc01.aar",
          "size": 83373,
          "sha512": "4534868a8308f55032e51b937bf972d82949491033e740e01fd9c257ecd7c06daa78e9f0ae6e679bf043a481ad876f5d3c348885a193496f9fb5b1e550270d46",
          "sha256": "b654a35bf53113173542ab814938a7b23e16cfefdba9511cd6ef8a8cddfe4caa",
          "sha1": "e4ac9f2dc9ef1005adb93478f39c329deefba493",
          "md5": "bcc643d0696bd83cadfc03f29b7c1180"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.4.0-rc01.aar",
          "url": "activity-1.4.0-rc01.aar",
          "size": 83373,
          "sha512": "4534868a8308f55032e51b937bf972d82949491033e740e01fd9c257ecd7c06daa78e9f0ae6e679bf043a481ad876f5d3c348885a193496f9fb5b1e550270d46",
          "sha256": "b654a35bf53113173542ab814938a7b23e16cfefdba9511cd6ef8a8cddfe4caa",
          "sha1": "e4ac9f2dc9ef1005adb93478f39c329deefba493",
          "md5": "bcc643d0696bd83cadfc03f29b7c1180"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.4.0-rc01-sources.jar",
          "url": "activity-1.4.0-rc01-sources.jar",
          "size": 36385,
          "sha512": "d1e46522803c15b78515e3398f48dbca18f9426754bc0aad06b09b8c168fd4bec72dd8bdf24ac7af20927909e24f18df7a1e80926b27dbce2b33a2810ff8c64e",
          "sha256": "560d6da5f09de62d26c71169cfca29c7cb24f867073053776fb172074aaa76f0",
          "sha1": "a4f631154eaacd9b2391773c349a58000639ac7d",
          "md5": "95aa11c0cfbf3f023f32223f605eea9e"
        }
      ]
    }
  ]
}
