{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.5.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-rc02.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-rc02.aar",
          "size": 19631,
          "sha512": "c98a47a6d2ac53a07b4aa4cc558e0cae4ebde39de59d2c1d8dcd106f0f3afdb361ead883d556587479f3e52327b2d370f90f1ea060c577e5d0c62120b3ee0827",
          "sha256": "a956023bbccf4ac3b0ebcef4005ee915816e961d6beecf128d6253046d1b4816",
          "sha1": "4b0aaa367b25d89ac506549330f57fb94178436b",
          "md5": "ae17c6d2b4c04d1d412492cdf3508d35"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-rc02.aar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-rc02.aar",
          "size": 19631,
          "sha512": "c98a47a6d2ac53a07b4aa4cc558e0cae4ebde39de59d2c1d8dcd106f0f3afdb361ead883d556587479f3e52327b2d370f90f1ea060c577e5d0c62120b3ee0827",
          "sha256": "a956023bbccf4ac3b0ebcef4005ee915816e961d6beecf128d6253046d1b4816",
          "sha1": "4b0aaa367b25d89ac506549330f57fb94178436b",
          "md5": "ae17c6d2b4c04d1d412492cdf3508d35"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.5.0-rc02-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.5.0-rc02-sources.jar",
          "size": 1631,
          "sha512": "aec27370748b879276405755e63a377e08307bfe2f370687ee18fa5c43cb5e203fe5e3bcc9cda40390c872bf279e96bc2bae2f0a9e2ee631f861b2ad0e54c0ae",
          "sha256": "b7a2a7c66a58440b0ba30c68abe17074836f217123fb6ea728279834641a7c77",
          "sha1": "0ec507705520b7ddccce7da52bbf5abd9ecd1808",
          "md5": "c552138cfc58a3f4d73c8acbb66e4a86"
        }
      ]
    }
  ]
}