{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-compiler",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.5.0.jar",
          "url": "lifecycle-compiler-2.5.0.jar",
          "size": 49119,
          "sha512": "1ff3ba227d57f1b3f799a8307897095f3ed0f61cc031cd0bb2f8a354d1ff5615abe51f2529bbbded5d598cfc1cf7a53366da987f9521b0c6710a7262b557caa8",
          "sha256": "6f7fe4db9f8404363efcb89d6d7b2bfc810bc33cba205e601730efc527ed08b8",
          "sha1": "1d36fa846d1ffa7235a91fed54e3c5704c56eb00",
          "md5": "26527d090ea1ec4d902a319f908de89b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-compiler-2.5.0.jar",
          "url": "lifecycle-compiler-2.5.0.jar",
          "size": 49119,
          "sha512": "1ff3ba227d57f1b3f799a8307897095f3ed0f61cc031cd0bb2f8a354d1ff5615abe51f2529bbbded5d598cfc1cf7a53366da987f9521b0c6710a7262b557caa8",
          "sha256": "6f7fe4db9f8404363efcb89d6d7b2bfc810bc33cba205e601730efc527ed08b8",
          "sha1": "1d36fa846d1ffa7235a91fed54e3c5704c56eb00",
          "md5": "26527d090ea1ec4d902a319f908de89b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.5.0-sources.jar",
          "url": "lifecycle-compiler-2.5.0-sources.jar",
          "size": 18983,
          "sha512": "ca17efe01b105646b8c4e6ab80a94aa11e08d9a0294813b4d8b4c237368fe3340f2ead7a1daaaff4311e97e7109a4155e65b308686570d1d2bb6f782fa341cf8",
          "sha256": "cbf9618ee4cb0170a7030bffd2480507261af831552bacd101db3bce319622d2",
          "sha1": "aa8485e5b4ed1777938edf2ff3d96b89ba07c51c",
          "md5": "787146ee536af428776a9fa21a83fa4a"
        }
      ]
    }
  ]
}