{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.5.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-rc02.aar",
          "url": "lifecycle-livedata-core-2.5.0-rc02.aar",
          "size": 10083,
          "sha512": "356ad26e3f7218a4c08bf475db224bb9597d25ab10708568083e7f735d06294c0b46a16aa5bca46591aafce3c05f1f95303b0cfb45429685c410f0d37a49836e",
          "sha256": "30bf3a7e9bbf26d743b2eaae69c191b48ffb71931a0d7f0fe700abcf8231fe32",
          "sha1": "03c1fdf64f38dc559ed9d45146e497233a6248d3",
          "md5": "cc61425f291d2a21e208c353150c1ff2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-rc02.aar",
          "url": "lifecycle-livedata-core-2.5.0-rc02.aar",
          "size": 10083,
          "sha512": "356ad26e3f7218a4c08bf475db224bb9597d25ab10708568083e7f735d06294c0b46a16aa5bca46591aafce3c05f1f95303b0cfb45429685c410f0d37a49836e",
          "sha256": "30bf3a7e9bbf26d743b2eaae69c191b48ffb71931a0d7f0fe700abcf8231fe32",
          "sha1": "03c1fdf64f38dc559ed9d45146e497233a6248d3",
          "md5": "cc61425f291d2a21e208c353150c1ff2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-rc02-sources.jar",
          "url": "lifecycle-livedata-core-2.5.0-rc02-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}