{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-ktx",
    "version": "2.3.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6558100"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.3.0-alpha04.aar",
          "url": "lifecycle-livedata-ktx-2.3.0-alpha04.aar",
          "size": 40507,
          "sha512": "3aaf12c23513de9fee7bc3b3aea39ae75b58a7eb74e8dd4578e07ac85336a0897276e639297aee09d61db66b2d243d194f6c515e7a2a242541a83ea24e39e618",
          "sha256": "4675e7c7121e3ac936cfe2d6cf9cd84e426c507ddc0db33d569cac7d7567430a",
          "sha1": "7f941b3ac89235d09cec934502e7e58bf658f40c",
          "md5": "e69d046e855dd054ad3456070d2076ad"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.3.0-alpha04.aar",
          "url": "lifecycle-livedata-ktx-2.3.0-alpha04.aar",
          "size": 40507,
          "sha512": "3aaf12c23513de9fee7bc3b3aea39ae75b58a7eb74e8dd4578e07ac85336a0897276e639297aee09d61db66b2d243d194f6c515e7a2a242541a83ea24e39e618",
          "sha256": "4675e7c7121e3ac936cfe2d6cf9cd84e426c507ddc0db33d569cac7d7567430a",
          "sha1": "7f941b3ac89235d09cec934502e7e58bf658f40c",
          "md5": "e69d046e855dd054ad3456070d2076ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.3.0-alpha04-sources.jar",
          "url": "lifecycle-livedata-ktx-2.3.0-alpha04-sources.jar",
          "size": 8201,
          "sha512": "1607196926547b6c2e33590d8d9a4048fd343049bdfc736e643bb7e8f083462e2a02fecd16c2a4c924b793b22811a98dd76869ef6ec804cbaaaee607189292b6",
          "sha256": "41aa31144a473c4025d6cf5f55eb68c109399c806e9772c6d00bfb9c5e149ef2",
          "sha1": "3e104f0a8f35e9a17c5b6bc2ccc8450bec99a2e9",
          "md5": "d73a2d79278c9c357fabbd0f7ad7e646"
        }
      ]
    }
  ]
}
