{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.7.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-rc01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.0-rc01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-samples",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-lint",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-lint",
          "version": {
            "requires": "1.7.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.7.0-beta02.aar",
          "url": "activity-ktx-1.7.0-beta02.aar",
          "size": 26409,
          "sha512": "5f1be91d287bd011c49ff5ac0970273aac769d308204a208ebe2b4f7920a30114d3c484e0a4e49d7d43650a44bb01272cc5d515b4f1700da780e7e87a62df9c7",
          "sha256": "8f9024d85e51445eb87b5f4f2ee03d53e08ffe703ed8fe6c7395c90806d9e0d5",
          "sha1": "28ab8061a94f5d103518ad5a51f5f16bd70dd63e",
          "md5": "fa4f14783cd631d1fdaa02374daba600"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-rc01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.0-rc01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-samples",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-lint",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-lint",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.7.0-beta02.aar",
          "url": "activity-ktx-1.7.0-beta02.aar",
          "size": 26409,
          "sha512": "5f1be91d287bd011c49ff5ac0970273aac769d308204a208ebe2b4f7920a30114d3c484e0a4e49d7d43650a44bb01272cc5d515b4f1700da780e7e87a62df9c7",
          "sha256": "8f9024d85e51445eb87b5f4f2ee03d53e08ffe703ed8fe6c7395c90806d9e0d5",
          "sha1": "28ab8061a94f5d103518ad5a51f5f16bd70dd63e",
          "md5": "fa4f14783cd631d1fdaa02374daba600"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-samples",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-lint",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-lint",
          "version": {
            "requires": "1.7.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.7.0-beta02-sources.jar",
          "url": "activity-ktx-1.7.0-beta02-sources.jar",
          "size": 5891,
          "sha512": "0ab223f5f772f37a5e9d647b10c1e1addc94a60bd1cc23067b0fb4b10d1c035df41326f1ffbaac47d33acb338d9c2eb76288a1acd104c9713eff54de9735024c",
          "sha256": "aa0efa1286eca31f19921e14807731242ac606ddcc8588c1b10550f2293dd6c6",
          "sha1": "303ffe73fa85353c185e2281d60fb8fc65be8bc8",
          "md5": "c6e340fecd1713a2be35815d65373ff0"
        }
      ]
    }
  ]
}