{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.6.0-alpha01.aar",
          "url": "lifecycle-viewmodel-savedstate-2.6.0-alpha01.aar",
          "size": 35672,
          "sha512": "b73438d451c59fe1688128e9ff8703700d0afba64d22c2a4c6f790cf0664d52af1aa7299dc3728ffe1d2fd99c833c71d9c0e3bb8453544e783c92346c495e277",
          "sha256": "18325853f219a765ea7c0be5134f4c1c5b6c102da2e6471e212b0b2e2bdc06db",
          "sha1": "1c48fae026a3266b613b8843ef29e8a192c63269",
          "md5": "b74ca7622a478d7eec928c448928584e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.6.0-alpha01.aar",
          "url": "lifecycle-viewmodel-savedstate-2.6.0-alpha01.aar",
          "size": 35672,
          "sha512": "b73438d451c59fe1688128e9ff8703700d0afba64d22c2a4c6f790cf0664d52af1aa7299dc3728ffe1d2fd99c833c71d9c0e3bb8453544e783c92346c495e277",
          "sha256": "18325853f219a765ea7c0be5134f4c1c5b6c102da2e6471e212b0b2e2bdc06db",
          "sha1": "1c48fae026a3266b613b8843ef29e8a192c63269",
          "md5": "b74ca7622a478d7eec928c448928584e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.6.0-alpha01-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-2.6.0-alpha01-sources.jar",
          "size": 15813,
          "sha512": "1259b4b87e5a1f195e60c9ae54d9a044385adb5f72e6cbd57c69ca9f10bc3b406b880848c367adb9f29ebfe193d79c44a22a001e77ca0b3ed11f6e0ca44be14e",
          "sha256": "5cf43d3c8f67295f0f8330d9442ab0d871bef16d12f47817ecb517c373bbd980",
          "sha1": "011f7a8fab7793634b9cc07891180c35fbf4315c",
          "md5": "11e134c252cf46c84114a198fc48e3e2"
        }
      ]
    }
  ]
}