{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.0-alpha03.aar",
          "url": "lifecycle-service-2.4.0-alpha03.aar",
          "size": 4304,
          "sha512": "5bac0ee18e31546a77bcc89496d5110f592a9f01434021c82fc2f637ffca5f36f890bed7b52820e844fbad7d871ffa61a43fe12a188ce804dbccfaadcd3e9c17",
          "sha256": "dc69dbe8ca723c20fc6a77a57f0678f6ef21e486013807ea30abaf79b2d16546",
          "sha1": "2fd4c561d4e8e58bf1ed4a87687f06c63831f123",
          "md5": "538f750e54fc1ce400813b9e82c7c2fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.0-alpha03.aar",
          "url": "lifecycle-service-2.4.0-alpha03.aar",
          "size": 4304,
          "sha512": "5bac0ee18e31546a77bcc89496d5110f592a9f01434021c82fc2f637ffca5f36f890bed7b52820e844fbad7d871ffa61a43fe12a188ce804dbccfaadcd3e9c17",
          "sha256": "dc69dbe8ca723c20fc6a77a57f0678f6ef21e486013807ea30abaf79b2d16546",
          "sha1": "2fd4c561d4e8e58bf1ed4a87687f06c63831f123",
          "md5": "538f750e54fc1ce400813b9e82c7c2fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.4.0-alpha03-sources.jar",
          "url": "lifecycle-service-2.4.0-alpha03-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
