{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-compiler",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.4.1.jar",
          "url": "lifecycle-compiler-2.4.1.jar",
          "size": 49549,
          "sha512": "3b2f687d4f17f6f3b21d794155a298a3bef85db32b175a4976ef05fb5082cda0c6195735b8f600f327c1d94a34c46a5c5cffaf2713894b8721821bde160f30d8",
          "sha256": "e763338d93727ef71fd92a50cd613be523466d4adebafe1e7aecbe798d3647e0",
          "sha1": "b0a171bd13fa7665ff9cd098a2c5b60310420278",
          "md5": "d4265b1b38a1aad1c3b7b50083ccf756"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-compiler-2.4.1.jar",
          "url": "lifecycle-compiler-2.4.1.jar",
          "size": 49549,
          "sha512": "3b2f687d4f17f6f3b21d794155a298a3bef85db32b175a4976ef05fb5082cda0c6195735b8f600f327c1d94a34c46a5c5cffaf2713894b8721821bde160f30d8",
          "sha256": "e763338d93727ef71fd92a50cd613be523466d4adebafe1e7aecbe798d3647e0",
          "sha1": "b0a171bd13fa7665ff9cd098a2c5b60310420278",
          "md5": "d4265b1b38a1aad1c3b7b50083ccf756"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.4.1-sources.jar",
          "url": "lifecycle-compiler-2.4.1-sources.jar",
          "size": 18983,
          "sha512": "ca17efe01b105646b8c4e6ab80a94aa11e08d9a0294813b4d8b4c237368fe3340f2ead7a1daaaff4311e97e7109a4155e65b308686570d1d2bb6f782fa341cf8",
          "sha256": "cbf9618ee4cb0170a7030bffd2480507261af831552bacd101db3bce319622d2",
          "sha1": "aa8485e5b4ed1777938edf2ff3d96b89ba07c51c",
          "md5": "787146ee536af428776a9fa21a83fa4a"
        }
      ]
    }
  ]
}
