{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-alpha01.aar",
          "url": "lifecycle-runtime-testing-2.5.0-alpha01.aar",
          "size": 8461,
          "sha512": "e031da2a335b51996fede5c3359938a9147968017e5c4bddf15b82a288c7eb2c8e2dec5a3de9955e26ce73899fa432898b5228a1bfdf8d7424336afbe8a206f9",
          "sha256": "6297531a9740424ac08764775d32ed8e0b305986f04d2a04eaec3bd5a79a45ea",
          "sha1": "6aa57bc921be2013176178673898cfdc0ca28b9f",
          "md5": "21f909ec04d3820e43e975c94f950fc1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-alpha01.aar",
          "url": "lifecycle-runtime-testing-2.5.0-alpha01.aar",
          "size": 8461,
          "sha512": "e031da2a335b51996fede5c3359938a9147968017e5c4bddf15b82a288c7eb2c8e2dec5a3de9955e26ce73899fa432898b5228a1bfdf8d7424336afbe8a206f9",
          "sha256": "6297531a9740424ac08764775d32ed8e0b305986f04d2a04eaec3bd5a79a45ea",
          "sha1": "6aa57bc921be2013176178673898cfdc0ca28b9f",
          "md5": "21f909ec04d3820e43e975c94f950fc1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.5.0-alpha01-sources.jar",
          "url": "lifecycle-runtime-testing-2.5.0-alpha01-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}
