{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.5.0-alpha02.aar",
          "url": "activity-1.5.0-alpha02.aar",
          "size": 92516,
          "sha512": "7770642116b987d4cf347949e194a9ea5da73f53475eeca9841a821a5b339954ab6219f49a3f986c4a13494265267896b486dc018b8a1735df1bbf96c8b5f82f",
          "sha256": "a940fff05b1a4a9659a9be71d86f0fdf9572e715d3af0d33a4bc3bd791acb8af",
          "sha1": "ed64e2fb44783a8a4656f68642c738c60fef9884",
          "md5": "e7c8b39d9f7f41fec2d86ed338614bfe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.5.0-alpha02.aar",
          "url": "activity-1.5.0-alpha02.aar",
          "size": 92516,
          "sha512": "7770642116b987d4cf347949e194a9ea5da73f53475eeca9841a821a5b339954ab6219f49a3f986c4a13494265267896b486dc018b8a1735df1bbf96c8b5f82f",
          "sha256": "a940fff05b1a4a9659a9be71d86f0fdf9572e715d3af0d33a4bc3bd791acb8af",
          "sha1": "ed64e2fb44783a8a4656f68642c738c60fef9884",
          "md5": "e7c8b39d9f7f41fec2d86ed338614bfe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.5.0-alpha02-sources.jar",
          "url": "activity-1.5.0-alpha02-sources.jar",
          "size": 39882,
          "sha512": "5bbc4be483800fe8c511d7a825c93680245cced0ae09ac6b28f02a9d1dce0cc5bcd5fc56855e4f8a982d085eb75cf486eb027522ccdff5d45e7f7a9d699b4936",
          "sha256": "aed2b7301cb9a94e9c340be6df927294969282db4f0e094b98d6ca9dfede8778",
          "sha1": "7ff0d8176dc874ddcc1015e27db0fe9697557935",
          "md5": "22ed71abec21c2f8b0ce0e514e63d233"
        }
      ]
    }
  ]
}
