{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.4.0-rc01.aar",
          "url": "lifecycle-reactivestreams-ktx-2.4.0-rc01.aar",
          "size": 2874,
          "sha512": "e953050e694478060e122a5be9916def9b13365a554a8496d560934d57165427cc7042bb3d35d6144230c6fee508c7e7bba7b44b89d2668b99475faa0d10df05",
          "sha256": "4fd0e4a9bc16ca69d9e7d682d5231b3855f6826a8d5176cc07c2adcda5cb9814",
          "sha1": "fc4f3ba94015f05cdc6fb6f8935590c812906d9f",
          "md5": "628861ac14f24c3e546442d39214af8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.4.0-rc01.aar",
          "url": "lifecycle-reactivestreams-ktx-2.4.0-rc01.aar",
          "size": 2874,
          "sha512": "e953050e694478060e122a5be9916def9b13365a554a8496d560934d57165427cc7042bb3d35d6144230c6fee508c7e7bba7b44b89d2668b99475faa0d10df05",
          "sha256": "4fd0e4a9bc16ca69d9e7d682d5231b3855f6826a8d5176cc07c2adcda5cb9814",
          "sha1": "fc4f3ba94015f05cdc6fb6f8935590c812906d9f",
          "md5": "628861ac14f24c3e546442d39214af8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.4.0-rc01-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.4.0-rc01-sources.jar",
          "size": 1261,
          "sha512": "bb0f402ed24247b2fd8e5ecbfec147427d84a8f18bf21cb5857c1fee5746e2a97febac326c894484fe6e86a515fe1bfd05c3b1538eb3f0f1cce712f280a76861",
          "sha256": "c50b9f047a5b5d5ee5d330b3e2dc45f4ae8deca41f607d1d495792c89e731048",
          "sha1": "23c53fd2626cac61baac62c95dec1c49046e0261",
          "md5": "5d68075becef226fa5ce3a00a8721ea7"
        }
      ]
    }
  ]
}
