{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-compose-samples",
    "version": "2.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-alpha05.aar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-alpha05.aar",
          "size": 9810,
          "sha512": "5b79fc36277cc6d9a469d1fddd9a5ae8924d8d08df9fd55bd88bf23ba883c1e152917c9be1c612143a8763a8af09a7d1bdbafaa4bd8566c81bc43472a94f137b",
          "sha256": "94d9e5738b1aae7b7341797778da180419e7e1eebac48c3006936fe32e99fbef",
          "sha1": "4655f4c84bf011907a6a1324a7930cf7b6ffd2e6",
          "md5": "bcd3f2b443aa84e9365c23c0607fd107"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-alpha05.aar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-alpha05.aar",
          "size": 9810,
          "sha512": "5b79fc36277cc6d9a469d1fddd9a5ae8924d8d08df9fd55bd88bf23ba883c1e152917c9be1c612143a8763a8af09a7d1bdbafaa4bd8566c81bc43472a94f137b",
          "sha256": "94d9e5738b1aae7b7341797778da180419e7e1eebac48c3006936fe32e99fbef",
          "sha1": "4655f4c84bf011907a6a1324a7930cf7b6ffd2e6",
          "md5": "bcd3f2b443aa84e9365c23c0607fd107"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.6.0-alpha05-sources.jar",
          "url": "lifecycle-runtime-compose-samples-2.6.0-alpha05-sources.jar",
          "size": 1695,
          "sha512": "6b7c33ed90518314fee86c5c196986c42bc1fd965e75abab33607256fd49b942f5cf46a41cd0f731cda7d8352aecb59dff83d9c69fb2e4db11cc7328769d255a",
          "sha256": "9c3611e02a386c84b38c6711d16008c69c54f1f594e24493a561f5de1241f7e0",
          "sha1": "5de57691b2ad2b85a7e59bfe2913b05d9e404281",
          "md5": "5552d4402a66cb165bfbcabb7de21974"
        }
      ]
    }
  ]
}