{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId:": "6420846"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.3.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-alpha02.aar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-alpha02.aar",
          "size": 2127,
          "sha512": "c8d76f2aeca8ca5728432a5557f03a3044cde91bb659806e772cfa6a029dd3301d42e4826bd7e8625f8ce507e5a677d69fab315fb0a7c8a839f1b497fc6021e7",
          "sha256": "79ca30a91bc5f7362382eec2a8052ea6dab67dfa910dcf835c46583bf742c90f",
          "sha1": "1ebfc9591f624ce44727147104faf146484653e4",
          "md5": "79882368aec1ad57a3073a505c0535b0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.3.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-alpha02.aar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-alpha02.aar",
          "size": 2127,
          "sha512": "c8d76f2aeca8ca5728432a5557f03a3044cde91bb659806e772cfa6a029dd3301d42e4826bd7e8625f8ce507e5a677d69fab315fb0a7c8a839f1b497fc6021e7",
          "sha256": "79ca30a91bc5f7362382eec2a8052ea6dab67dfa910dcf835c46583bf742c90f",
          "sha1": "1ebfc9591f624ce44727147104faf146484653e4",
          "md5": "79882368aec1ad57a3073a505c0535b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-alpha02-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-alpha02-sources.jar",
          "size": 1260,
          "sha512": "9855fea967e2e3e524d04ecf0d9838f1c96fd94b80c348dc612c69bd42ca82ce4779cf587cc833a4dde819b94f2e92589cc478ab28b31638de1e1b32d7a61c36",
          "sha256": "36ab72c2b848531aed3a416c5d0636c24cc64463b3685b0825eab17924b0aa4e",
          "sha1": "f1045318682f7dbef230a3cf1ce0ed2377d14903",
          "md5": "173bdd2cae36a9dc56a58e4f5482488d"
        }
      ]
    }
  ]
}
