{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId:": "6420846"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha02.aar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha02.aar",
          "size": 7591,
          "sha512": "797da1ba4bb1c37cfb17ccd4b4d1875ac32257d53b9667bd43b1fbf96893ba248b13db1b8129003e6d83bce618fe5b82bdca94b824f94e74d0786ceccfb4353d",
          "sha256": "8fffe9887e3ed6b42d92f49e40be9d46b16b845a23db8401d0a0f88b932489f2",
          "sha1": "7857233fe1ffed52d8f7964064f91fcb43369540",
          "md5": "1ac8be0a3b27ff79b3e5eb8701b978c8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha02.aar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha02.aar",
          "size": 7591,
          "sha512": "797da1ba4bb1c37cfb17ccd4b4d1875ac32257d53b9667bd43b1fbf96893ba248b13db1b8129003e6d83bce618fe5b82bdca94b824f94e74d0786ceccfb4353d",
          "sha256": "8fffe9887e3ed6b42d92f49e40be9d46b16b845a23db8401d0a0f88b932489f2",
          "sha1": "7857233fe1ffed52d8f7964064f91fcb43369540",
          "md5": "1ac8be0a3b27ff79b3e5eb8701b978c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha02-sources.jar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha02-sources.jar",
          "size": 1809,
          "sha512": "85d5e06438ec35aaeee972795ee55b315c3bee5bb5bdbeebdf09785dad5c73c003adad00a94e3cee71b820bd3f1df337f3290e8032e48bfb2a007e89badae94b",
          "sha256": "f97e2b220a76e4c873132978c3cf668e66b9e5299f3ae8fa0f647b85d16150d3",
          "sha1": "7952288ebf7757e9238984e4f927aed0ac5c6b6c",
          "md5": "c66286898d7af679c567208f7f42d3f2"
        }
      ]
    }
  ]
}
