{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose-samples",
    "version": "2.5.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-alpha04.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-alpha04.aar",
          "size": 10831,
          "sha512": "2127635be2cb7e9493151f7a41c380f0646f90a6b690c1dc3ceb5c503aa96aa69bdfcb8e60fb9aa13f2dc9f81c87b8a388ab76d30d87a45dd0cf5fe9b28da400",
          "sha256": "02ee0ee1ca1f8377cb286fe01ea372b59c319fd8429a703ef0301c06a6a4cbe6",
          "sha1": "ff334b7ae98604a5a12aadcb8fddc7d2be22d469",
          "md5": "b3dad99336a3d09f16b7abef872814bc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-alpha04.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-alpha04.aar",
          "size": 10831,
          "sha512": "2127635be2cb7e9493151f7a41c380f0646f90a6b690c1dc3ceb5c503aa96aa69bdfcb8e60fb9aa13f2dc9f81c87b8a388ab76d30d87a45dd0cf5fe9b28da400",
          "sha256": "02ee0ee1ca1f8377cb286fe01ea372b59c319fd8429a703ef0301c06a6a4cbe6",
          "sha1": "ff334b7ae98604a5a12aadcb8fddc7d2be22d469",
          "md5": "b3dad99336a3d09f16b7abef872814bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.5.0-alpha04-sources.jar",
          "url": "lifecycle-viewmodel-compose-samples-2.5.0-alpha04-sources.jar",
          "size": 2461,
          "sha512": "6e4fd93e0e6398d39eb55c2074747669612fd012a887747e6509ce49245c5cbd5792a01b7030bad3c65804246b1761de979fa46bc9c1327960be4f89494785bc",
          "sha256": "031442d4389134af208369ce647168d884c3313ac1a75e6978ca5caf20b385e5",
          "sha1": "56124041cb26f8231262b3ebf2fff3dccc60cf48",
          "md5": "622a355fc3a790e31908b8ce6512071e"
        }
      ]
    }
  ]
}
