{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.0-beta02.aar",
          "url": "activity-ktx-1.3.0-beta02.aar",
          "size": 30067,
          "sha512": "fad19343b18d700c455e006bd1a6833535a1084adb2dc7219cf9f632fb6894c17df2b44bfb33ebd9fa3200f6d0ba37b3a1b0e0eabe21a3bca80cb1c4ba0ea54b",
          "sha256": "ddfaaa0a91b5a82f9e1b81dc7ea8a27398e3d113458f64822b8da4ca432c1b3a",
          "sha1": "fe96a53888ffc690697e72ca369529cf679f325f",
          "md5": "b9fcc5451c4a87d4028a69afb2772274"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.0-beta02.aar",
          "url": "activity-ktx-1.3.0-beta02.aar",
          "size": 30067,
          "sha512": "fad19343b18d700c455e006bd1a6833535a1084adb2dc7219cf9f632fb6894c17df2b44bfb33ebd9fa3200f6d0ba37b3a1b0e0eabe21a3bca80cb1c4ba0ea54b",
          "sha256": "ddfaaa0a91b5a82f9e1b81dc7ea8a27398e3d113458f64822b8da4ca432c1b3a",
          "sha1": "fe96a53888ffc690697e72ca369529cf679f325f",
          "md5": "b9fcc5451c4a87d4028a69afb2772274"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.3.0-beta02-sources.jar",
          "url": "activity-ktx-1.3.0-beta02-sources.jar",
          "size": 7769,
          "sha512": "804afefb365825fba128fb90e94e2a52c592f086d4829c379113a6dff9541f59fba14d174ed54808d3d218fa67d8c7b0d13b46fbf21d5fa37289f20712888cf2",
          "sha256": "e9203b000c2790d6f867dd642380f820cf97ba9a821e96daadac8b7dba19e0b3",
          "sha1": "370e20946dad67d9ce26dbe3f33034ddf84600c4",
          "md5": "eafcc6f70cc644f6a4d16ba2482a3c1b"
        }
      ]
    }
  ]
}
