{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-common",
    "version": "3.0.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6860046"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-3.0.0-alpha07.jar",
          "url": "paging-common-3.0.0-alpha07.jar",
          "size": 659349,
          "sha512": "cfbd19b4119be648abacbfa27ba1b9aa10ebe239669cad6eee7b84fc5374997d412e3323b6bbd062d3e3fab28f3fe2a3e10384836e3f84e49249b96d183b807a",
          "sha256": "95e61b193b4331b14bdedac81ee3caed5e42128a864bbf012307cf5aeaa26d38",
          "sha1": "25b9657fb117413da5859d67950ff8daec29fd85",
          "md5": "dd5aebb670a8179f445648dba025a2e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-3.0.0-alpha07.jar",
          "url": "paging-common-3.0.0-alpha07.jar",
          "size": 659349,
          "sha512": "cfbd19b4119be648abacbfa27ba1b9aa10ebe239669cad6eee7b84fc5374997d412e3323b6bbd062d3e3fab28f3fe2a3e10384836e3f84e49249b96d183b807a",
          "sha256": "95e61b193b4331b14bdedac81ee3caed5e42128a864bbf012307cf5aeaa26d38",
          "sha1": "25b9657fb117413da5859d67950ff8daec29fd85",
          "md5": "dd5aebb670a8179f445648dba025a2e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-common-3.0.0-alpha07-sources.jar",
          "url": "paging-common-3.0.0-alpha07-sources.jar",
          "size": 122893,
          "sha512": "35bf53f2a7c2dda07ab341a2d6249a993b82b240eec512a36fabbc60f19994abb86a15eca3f26658b23e2b93f57af6be73a77fbeb7496100a6dfe5ba94081a01",
          "sha256": "c28e18c367adda4a3fba72c82ce7b3845462fc85302d02dc84c38eaa08b355d4",
          "sha1": "0d33f58d67e4e71969d6e3d731f5b4b949f63f66",
          "md5": "55d2ee00cee99d840f97a3af811ec195"
        }
      ]
    }
  ]
}
