{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-ktx",
    "version": "2.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.5.0-rc01.aar",
          "url": "lifecycle-runtime-ktx-2.5.0-rc01.aar",
          "size": 79846,
          "sha512": "d974a5412d4e2070c100df1e551e92ffff7571dc2d8bcf7806de471ff229ad755e9d3daea533d0fe9f17d677f030a2dccdfffdc74600502f96479e19f893fae1",
          "sha256": "29285cccd5e60f80bf718e1575eb39b4193e1c110667747694bf52880aaf770b",
          "sha1": "fbe24520d32d132b34d62bb67d5931f8b212fd65",
          "md5": "beda5151e6ea1786797c2cdb42ab28b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.5.0-rc01.aar",
          "url": "lifecycle-runtime-ktx-2.5.0-rc01.aar",
          "size": 79846,
          "sha512": "d974a5412d4e2070c100df1e551e92ffff7571dc2d8bcf7806de471ff229ad755e9d3daea533d0fe9f17d677f030a2dccdfffdc74600502f96479e19f893fae1",
          "sha256": "29285cccd5e60f80bf718e1575eb39b4193e1c110667747694bf52880aaf770b",
          "sha1": "fbe24520d32d132b34d62bb67d5931f8b212fd65",
          "md5": "beda5151e6ea1786797c2cdb42ab28b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.5.0-rc01-sources.jar",
          "url": "lifecycle-runtime-ktx-2.5.0-rc01-sources.jar",
          "size": 14828,
          "sha512": "e970319d029eab328f11c9cf9f263f8aae0b958f2be8a6c6ee5fdc8e785a1ef8caf4de5e5a42e32394437d77605ebfa74d9018acba18287ecf12cdf5da809802",
          "sha256": "9c1d28b751c500263b5d4d81caf6bd541944d91e295df85273b09e7b7d0baed3",
          "sha1": "6d338022f8fa82c24121d5d249fe5daeeb297742",
          "md5": "6bd895cc45fa4ff72bfb62dfa2cc7602"
        }
      ]
    }
  ]
}