{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.3.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-rc01.aar",
          "url": "activity-1.3.0-rc01.aar",
          "size": 69723,
          "sha512": "814c9350b77e2ee2af0071627460e15ad70d6894378ddf2ffbdbefbc7bf2bbcb1d5032ccc9810b97fe32e4c6ba1f17d9078bb49f4dfba8acae0174a53aa40a8b",
          "sha256": "d3d2c592464f6097b193c95ad2416548ae010c00c8d16077c588f7144e5800b4",
          "sha1": "12af4ccf5f01bebf85f68aac7ace7b62ff07230e",
          "md5": "000db00e418056f0fcf3e6582e00c589"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.3.0-rc01.aar",
          "url": "activity-1.3.0-rc01.aar",
          "size": 69723,
          "sha512": "814c9350b77e2ee2af0071627460e15ad70d6894378ddf2ffbdbefbc7bf2bbcb1d5032ccc9810b97fe32e4c6ba1f17d9078bb49f4dfba8acae0174a53aa40a8b",
          "sha256": "d3d2c592464f6097b193c95ad2416548ae010c00c8d16077c588f7144e5800b4",
          "sha1": "12af4ccf5f01bebf85f68aac7ace7b62ff07230e",
          "md5": "000db00e418056f0fcf3e6582e00c589"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.3.0-rc01-sources.jar",
          "url": "activity-1.3.0-rc01-sources.jar",
          "size": 35864,
          "sha512": "9894e3b290eb4d521df8860a7ccb6fc6aaa68d7120173487867df621ee7a3c4ea48203621791e91f47fdd5c2b5f1c135c1633a0136fbd53bc3db2c3b96fe2670",
          "sha256": "e7ab45663cbd2727e9f5fefda4ff857c0742639597edeafc826412b41a2f8da0",
          "sha1": "fd2a77bacd72443b40a79855dd7b5bd78b7ef4c3",
          "md5": "e903b4be8d7256d92b6f91c9ea480ea4"
        }
      ]
    }
  ]
}
