{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.6.0-alpha01.aar",
          "url": "activity-1.6.0-alpha01.aar",
          "size": 95622,
          "sha512": "b33f485ab9ec03943ea8216786eb95c2ef1e0afb6e15973afdc43530ff2a41d1705f235e8f7ff3b45a4722b95b31d7bfeed5556dc313b684e6a7d6df2439abf3",
          "sha256": "9a3e2e8c596e5189f19ff9f5ee693c65f1c2280117b9f6defa24cf67cc805d8d",
          "sha1": "da05edb2e2272f3f8d8c534bb90ff13841b74210",
          "md5": "2126896068710febd5b1827bb37c11fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.6.0-alpha01.aar",
          "url": "activity-1.6.0-alpha01.aar",
          "size": 95622,
          "sha512": "b33f485ab9ec03943ea8216786eb95c2ef1e0afb6e15973afdc43530ff2a41d1705f235e8f7ff3b45a4722b95b31d7bfeed5556dc313b684e6a7d6df2439abf3",
          "sha256": "9a3e2e8c596e5189f19ff9f5ee693c65f1c2280117b9f6defa24cf67cc805d8d",
          "sha1": "da05edb2e2272f3f8d8c534bb90ff13841b74210",
          "md5": "2126896068710febd5b1827bb37c11fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.6.0-alpha01-sources.jar",
          "url": "activity-1.6.0-alpha01-sources.jar",
          "size": 40852,
          "sha512": "1ce4f8de64ac55aaa19f68a8737f8d45a335d197d06aafc528e00d29f988561eed6111d698c6570e12b034ffdb9b1a7fdc94d49460d90248b14e2832ac95502d",
          "sha256": "6cb5f43e32324c1dbb4fb248ee93baffaec39a4fdba3cb7f5ea23634cd20926e",
          "sha1": "2d3168ef6b69674f4d3004247f41d7532e6f97a5",
          "md5": "87a8d8c9e4637c650da16fbd9e8005cd"
        }
      ]
    }
  ]
}