{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-alpha03.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-alpha03.aar",
          "size": 2942,
          "sha512": "6c540e467b9fea13343228bd9241a627ecf916cde2cad841c0f8749cc5af138e932cf8a025bfdd55810fb107bbc750d5c90b0105d7fcf8cdf7d2746fe49cd24f",
          "sha256": "476527d4efd78150dd93fe2ad83ff468776d16ab2572f945e00788aca7eab716",
          "sha1": "8af9ec0e53fa3782017bfb092788a01df09d5d71",
          "md5": "bbd3d196a2260ee4915b084a61a815d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-alpha03.aar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-alpha03.aar",
          "size": 2942,
          "sha512": "6c540e467b9fea13343228bd9241a627ecf916cde2cad841c0f8749cc5af138e932cf8a025bfdd55810fb107bbc750d5c90b0105d7fcf8cdf7d2746fe49cd24f",
          "sha256": "476527d4efd78150dd93fe2ad83ff468776d16ab2572f945e00788aca7eab716",
          "sha1": "8af9ec0e53fa3782017bfb092788a01df09d5d71",
          "md5": "bbd3d196a2260ee4915b084a61a815d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.5.0-alpha03-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.5.0-alpha03-sources.jar",
          "size": 1261,
          "sha512": "bb0f402ed24247b2fd8e5ecbfec147427d84a8f18bf21cb5857c1fee5746e2a97febac326c894484fe6e86a515fe1bfd05c3b1538eb3f0f1cce712f280a76861",
          "sha256": "c50b9f047a5b5d5ee5d330b3e2dc45f4ae8deca41f607d1d495792c89e731048",
          "sha1": "23c53fd2626cac61baac62c95dec1c49046e0261",
          "md5": "5d68075becef226fa5ce3a00a8721ea7"
        }
      ]
    }
  ]
}
