{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha02.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha02.aar",
          "size": 10047,
          "sha512": "fc24c1d6fb074d81663bd1359283c62b97689edf534fcbca58d7aa2361861c12f1c688c448c142c63b101a0864ce3a2c677fbceefed6d850d2dea3ad525cfe43",
          "sha256": "d20358355ac30e8f2b03fd2fb56cfa46072441fe4080d9538c18025dd46c63b6",
          "sha1": "4073341faab8eeab5b68bc61025b08cdb6a08c99",
          "md5": "274bfd78354ea5a70ee7498dbce197f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha02.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha02.aar",
          "size": 10047,
          "sha512": "fc24c1d6fb074d81663bd1359283c62b97689edf534fcbca58d7aa2361861c12f1c688c448c142c63b101a0864ce3a2c677fbceefed6d850d2dea3ad525cfe43",
          "sha256": "d20358355ac30e8f2b03fd2fb56cfa46072441fe4080d9538c18025dd46c63b6",
          "sha1": "4073341faab8eeab5b68bc61025b08cdb6a08c99",
          "md5": "274bfd78354ea5a70ee7498dbce197f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha02-sources.jar",
          "url": "lifecycle-livedata-core-2.5.0-alpha02-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}
