{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7262094"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.0-alpha06.aar",
          "url": "activity-ktx-1.3.0-alpha06.aar",
          "size": 20431,
          "sha512": "e1d15ecf0397192610fd2ae11517a5766e9c870f552c21acd8a17121a2ff883073a5be664d1e3b0bacd946e295883df6fed7e69213b45feba0fd7bf0d8b03920",
          "sha256": "af1553df796b9eb0e5013866ae2490550f3f0100db899ab75e93b748a24ee344",
          "sha1": "d2a1d4447ff6c5b5eb6c3f4655af2ab129ec30b4",
          "md5": "be648c95ea36aca0aaa3734a973abfb8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.0-alpha06.aar",
          "url": "activity-ktx-1.3.0-alpha06.aar",
          "size": 20431,
          "sha512": "e1d15ecf0397192610fd2ae11517a5766e9c870f552c21acd8a17121a2ff883073a5be664d1e3b0bacd946e295883df6fed7e69213b45feba0fd7bf0d8b03920",
          "sha256": "af1553df796b9eb0e5013866ae2490550f3f0100db899ab75e93b748a24ee344",
          "sha1": "d2a1d4447ff6c5b5eb6c3f4655af2ab129ec30b4",
          "md5": "be648c95ea36aca0aaa3734a973abfb8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.3.0-alpha06-sources.jar",
          "url": "activity-ktx-1.3.0-alpha06-sources.jar",
          "size": 6133,
          "sha512": "a5266f324c627f8819af1667fb4f31e61196fc118c691c07570487ee2eb7584d5415faa8a85eecd06e810f4448d893a8ddddd32e9e229b514466ad0f7f81c5d9",
          "sha256": "4d8c5ae5ebb411cf3770fc3546a93c527a20819762b4807fec8ea1c7521ce06e",
          "sha1": "8de8463662d207920c11530ec0e76af3005f0061",
          "md5": "7f56f8cdd73c71afc49702017eb9408b"
        }
      ]
    }
  ]
}
