{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-reactivestreams-ktx",
    "version": "2.3.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6602655"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-alpha05.aar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-alpha05.aar",
          "size": 2128,
          "sha512": "77510145477dbe571e7282363814999d8131ebfe87e63b322722a5c44397d436578dcc52e32f96c4ef5399b9f49f20724cc0163331ec07858f641ebb8f7ecd7c",
          "sha256": "7586368864a57f13e5f56b9a6b4a6fa2f5432b0bc6800d3add62d7e993bed85d",
          "sha1": "0167ee9c2f1fefa1eae3211f127727726a86e008",
          "md5": "5e0f4bc311c0110f76adcbd9411e61a8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-alpha05.aar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-alpha05.aar",
          "size": 2128,
          "sha512": "77510145477dbe571e7282363814999d8131ebfe87e63b322722a5c44397d436578dcc52e32f96c4ef5399b9f49f20724cc0163331ec07858f641ebb8f7ecd7c",
          "sha256": "7586368864a57f13e5f56b9a6b4a6fa2f5432b0bc6800d3add62d7e993bed85d",
          "sha1": "0167ee9c2f1fefa1eae3211f127727726a86e008",
          "md5": "5e0f4bc311c0110f76adcbd9411e61a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-reactivestreams-ktx-2.3.0-alpha05-sources.jar",
          "url": "lifecycle-reactivestreams-ktx-2.3.0-alpha05-sources.jar",
          "size": 1260,
          "sha512": "9855fea967e2e3e524d04ecf0d9838f1c96fd94b80c348dc612c69bd42ca82ce4779cf587cc833a4dde819b94f2e92589cc478ab28b31638de1e1b32d7a61c36",
          "sha256": "36ab72c2b848531aed3a416c5d0636c24cc64463b3685b0825eab17924b0aa4e",
          "sha1": "f1045318682f7dbef230a3cf1ce0ed2377d14903",
          "md5": "173bdd2cae36a9dc56a58e4f5482488d"
        }
      ]
    }
  ]
}
