{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-compiler",
    "version": "2.6.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.6.0-alpha04.jar",
          "url": "lifecycle-compiler-2.6.0-alpha04.jar",
          "size": 49374,
          "sha512": "89a1cebbd3712c4907e7558c9753892c26e684fb523e3bbcc25d20f8bd67714be7b7073d2a1d85892a9cd3ea18e48f91cb0f26d03102cc8ac421c31a1d467c90",
          "sha256": "6bf0439e84df712b82a21e908de33b4f0da249866239c5dfdb502ca4b1a3d3e4",
          "sha1": "1247096708b0206432039deac62cefffa7a733fe",
          "md5": "8c431f2b1bedbe67597fa97663b8b8e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha04"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-compiler-2.6.0-alpha04.jar",
          "url": "lifecycle-compiler-2.6.0-alpha04.jar",
          "size": 49374,
          "sha512": "89a1cebbd3712c4907e7558c9753892c26e684fb523e3bbcc25d20f8bd67714be7b7073d2a1d85892a9cd3ea18e48f91cb0f26d03102cc8ac421c31a1d467c90",
          "sha256": "6bf0439e84df712b82a21e908de33b4f0da249866239c5dfdb502ca4b1a3d3e4",
          "sha1": "1247096708b0206432039deac62cefffa7a733fe",
          "md5": "8c431f2b1bedbe67597fa97663b8b8e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-compiler-2.6.0-alpha04-sources.jar",
          "url": "lifecycle-compiler-2.6.0-alpha04-sources.jar",
          "size": 18983,
          "sha512": "c8e653923ebf52a8cebd372f576845edd9e7eb910a6fd5c34fb981b8b7af29c8907041ca3aaffcf070602e5d1e2c4f796cbfc4b8fe57aaaba8c2500c2d5247b0",
          "sha256": "cf0bc1b22e6aab15c842a58b43e571f3e981bd79e7a1bd3707b9001af80a3f98",
          "sha1": "77cdcc094c8395f6aeabe104109299851a931b77",
          "md5": "3b8351edae46f3fbe3fef1b2a63c7ee8"
        }
      ]
    }
  ]
}