{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.3.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7017154"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-rc01.aar",
          "url": "lifecycle-runtime-testing-2.3.0-rc01.aar",
          "size": 7735,
          "sha512": "b99e8d23cff5bfa91087f1bcb1079bb2e099487d83ae92f89ec7fce3e2c28489fe2bd829672924da78b6c23bebee7d712365a03186382dc8c08a2255ad67b761",
          "sha256": "324759bbb824654f0621186d6ee30b7421ddf8af5cd18301e5a0f3b4b4714809",
          "sha1": "3fabb42f02d6119053c70961bfc2f5c2c8566c38",
          "md5": "4238a49a02307a4083240e199d83cd2e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-rc01.aar",
          "url": "lifecycle-runtime-testing-2.3.0-rc01.aar",
          "size": 7735,
          "sha512": "b99e8d23cff5bfa91087f1bcb1079bb2e099487d83ae92f89ec7fce3e2c28489fe2bd829672924da78b6c23bebee7d712365a03186382dc8c08a2255ad67b761",
          "sha256": "324759bbb824654f0621186d6ee30b7421ddf8af5cd18301e5a0f3b4b4714809",
          "sha1": "3fabb42f02d6119053c70961bfc2f5c2c8566c38",
          "md5": "4238a49a02307a4083240e199d83cd2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-rc01-sources.jar",
          "url": "lifecycle-runtime-testing-2.3.0-rc01-sources.jar",
          "size": 1889,
          "sha512": "a557326aa26fd9cb2b0e5d98da770fc972d2a82e36219e3ba88252a2d9500680d51f4a9320f732406209aa6c0bc12ef8af6c586562404a868d617047e6ff170f",
          "sha256": "94dd6f635cd1f9c1104846c4cdec976ed00aa41c2b3889d1c7da9402e4bea50d",
          "sha1": "95f9d77a6ffb70df17d728b6ed513302c8056275",
          "md5": "d2e33c99240fd9042286ec457f34c1d3"
        }
      ]
    }
  ]
}
