{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.0-alpha02.aar",
          "url": "lifecycle-service-2.4.0-alpha02.aar",
          "size": 4369,
          "sha512": "ddc7c47cd3d9ede01ed77be7e4025e54a2e6da3840e84461febf05eec3cecc6782bf02efb65246c72aa2a7d709952ead181e06fa6343e5c088fb83bd75d7521b",
          "sha256": "6048a65dd8a5c9b36b3a1c31c3c9e2354d3b4ee2cf1d09bdc4200b99956b48aa",
          "sha1": "353222a11c7a54b84dc7e72b385fd8eff6a9bdb0",
          "md5": "9386d04ec761fe1cd352f2681b9ee271"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.0-alpha02.aar",
          "url": "lifecycle-service-2.4.0-alpha02.aar",
          "size": 4369,
          "sha512": "ddc7c47cd3d9ede01ed77be7e4025e54a2e6da3840e84461febf05eec3cecc6782bf02efb65246c72aa2a7d709952ead181e06fa6343e5c088fb83bd75d7521b",
          "sha256": "6048a65dd8a5c9b36b3a1c31c3c9e2354d3b4ee2cf1d09bdc4200b99956b48aa",
          "sha1": "353222a11c7a54b84dc7e72b385fd8eff6a9bdb0",
          "md5": "9386d04ec761fe1cd352f2681b9ee271"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.4.0-alpha02-sources.jar",
          "url": "lifecycle-service-2.4.0-alpha02-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
