{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-ktx",
    "version": "2.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.5.0-alpha02.aar",
          "url": "lifecycle-runtime-ktx-2.5.0-alpha02.aar",
          "size": 80178,
          "sha512": "20cab5a853535ef36cc8acc2357af60d35fce2e2622596ee7b2a6826a773342b89793180fc6c9e6eb6128bd09e4546c11d89606ced2b9f9269247204d76b9d58",
          "sha256": "a68829b51bddab6bf9959cc08333fdade6f6d10a3e427fb25fa52d78d73f6681",
          "sha1": "1dfafde13f87a5bcecf777bc168cce5a0d1d7138",
          "md5": "c2034aa9a7eb03e7a1fbdcf763de5a6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.5.0-alpha02.aar",
          "url": "lifecycle-runtime-ktx-2.5.0-alpha02.aar",
          "size": 80178,
          "sha512": "20cab5a853535ef36cc8acc2357af60d35fce2e2622596ee7b2a6826a773342b89793180fc6c9e6eb6128bd09e4546c11d89606ced2b9f9269247204d76b9d58",
          "sha256": "a68829b51bddab6bf9959cc08333fdade6f6d10a3e427fb25fa52d78d73f6681",
          "sha1": "1dfafde13f87a5bcecf777bc168cce5a0d1d7138",
          "md5": "c2034aa9a7eb03e7a1fbdcf763de5a6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.5.0-alpha02-sources.jar",
          "url": "lifecycle-runtime-ktx-2.5.0-alpha02-sources.jar",
          "size": 14828,
          "sha512": "e970319d029eab328f11c9cf9f263f8aae0b958f2be8a6c6ee5fdc8e785a1ef8caf4de5e5a42e32394437d77605ebfa74d9018acba18287ecf12cdf5da809802",
          "sha256": "9c1d28b751c500263b5d4d81caf6bd541944d91e295df85273b09e7b7d0baed3",
          "sha1": "6d338022f8fa82c24121d5d249fe5daeeb297742",
          "md5": "6bd895cc45fa4ff72bfb62dfa2cc7602"
        }
      ]
    }
  ]
}
