{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.0-beta01.aar",
          "url": "lifecycle-service-2.4.0-beta01.aar",
          "size": 4307,
          "sha512": "6eb6d88cd9d2ff5f567d93b5743b873459883d826339abd8a2afa1ebb8fb8f7e282e729a87638f370a2004c8dcb8d9f8af68606663f8a90d651cf588c1dfff6f",
          "sha256": "eeb54e22d6ad40de5cfbfcb5a993f8f88dba92b23ac0c002d320d4a88bbd2fd5",
          "sha1": "d45e3c2060dfd190ab9a9c65f3df512e65bcaec4",
          "md5": "8744a05b44f1b6242aedc668095143d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.0-beta01.aar",
          "url": "lifecycle-service-2.4.0-beta01.aar",
          "size": 4307,
          "sha512": "6eb6d88cd9d2ff5f567d93b5743b873459883d826339abd8a2afa1ebb8fb8f7e282e729a87638f370a2004c8dcb8d9f8af68606663f8a90d651cf588c1dfff6f",
          "sha256": "eeb54e22d6ad40de5cfbfcb5a993f8f88dba92b23ac0c002d320d4a88bbd2fd5",
          "sha1": "d45e3c2060dfd190ab9a9c65f3df512e65bcaec4",
          "md5": "8744a05b44f1b6242aedc668095143d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.4.0-beta01-sources.jar",
          "url": "lifecycle-service-2.4.0-beta01-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
