{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate",
    "version": "2.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.4.0-rc01.aar",
          "url": "lifecycle-viewmodel-savedstate-2.4.0-rc01.aar",
          "size": 15795,
          "sha512": "9fc9f30d35f171be10e396cfe45f174701f6ec7cd9a060146ed84fdcf5b197a150ec0567c012a814471795f125cc8a54ce7e344bc67d5693dcf582d65eb3e9b8",
          "sha256": "c801ccb09249d9496858f59be5768ffb17f522e98830e89723fd5d5b1caa695d",
          "sha1": "aa4bf0be45b249cb5da63bb03ebb6a301743c351",
          "md5": "ca82446aabb40c95a91cc02177f08b52"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.4.0-rc01.aar",
          "url": "lifecycle-viewmodel-savedstate-2.4.0-rc01.aar",
          "size": 15795,
          "sha512": "9fc9f30d35f171be10e396cfe45f174701f6ec7cd9a060146ed84fdcf5b197a150ec0567c012a814471795f125cc8a54ce7e344bc67d5693dcf582d65eb3e9b8",
          "sha256": "c801ccb09249d9496858f59be5768ffb17f522e98830e89723fd5d5b1caa695d",
          "sha1": "aa4bf0be45b249cb5da63bb03ebb6a301743c351",
          "md5": "ca82446aabb40c95a91cc02177f08b52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.4.0-rc01-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-2.4.0-rc01-sources.jar",
          "size": 10391,
          "sha512": "cb7875ae19b6607458d6eee746e0d7f0163620c93e7c4a0a19153bf9ec98cc52b2e31cb2bbe37927d3fd1e18f9dd21a32c35d380fe5c56ab202a815a18fc7c62",
          "sha256": "53dee368efb419a0029948568a20151e8ef7e63a6e9bda72f3202a225c750704",
          "sha1": "ec4f5df6c28e3c7a892dccdc6c1f682234bb021c",
          "md5": "8dd8063dc95ce2c054d0f1b5343918fd"
        }
      ]
    }
  ]
}
