{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-ktx",
    "version": "2.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6860046"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.3.0-beta01.aar",
          "url": "lifecycle-livedata-ktx-2.3.0-beta01.aar",
          "size": 40558,
          "sha512": "0e6307ff2073d79d830e0f4fa7d3f7f1ce11d211dc5866fa0cb74ac8302c8cf93dbb2af20577e8779d1b5be55274786c8c780cf3b0d655c84a64bf42cc635f33",
          "sha256": "1e98bf4769d7def9d8a795aa425d16c4ce31f65c35209ab6256aa659dc33e084",
          "sha1": "cc14b7b45a5563ded9ce55b7b941c4d1fc6e8d68",
          "md5": "fec15c7dd3a566dace9d636cb6f8de97"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.3.0-beta01.aar",
          "url": "lifecycle-livedata-ktx-2.3.0-beta01.aar",
          "size": 40558,
          "sha512": "0e6307ff2073d79d830e0f4fa7d3f7f1ce11d211dc5866fa0cb74ac8302c8cf93dbb2af20577e8779d1b5be55274786c8c780cf3b0d655c84a64bf42cc635f33",
          "sha256": "1e98bf4769d7def9d8a795aa425d16c4ce31f65c35209ab6256aa659dc33e084",
          "sha1": "cc14b7b45a5563ded9ce55b7b941c4d1fc6e8d68",
          "md5": "fec15c7dd3a566dace9d636cb6f8de97"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.3.0-beta01-sources.jar",
          "url": "lifecycle-livedata-ktx-2.3.0-beta01-sources.jar",
          "size": 8559,
          "sha512": "f5b0d9f4e9f3c6c0e109d0bd376f3a4e1d4f186ea4122be1933864d961aad8377bbf428b4d980d7c9ecaf964179813e880a37649d7ca58549e973bfd88c16070",
          "sha256": "cf40b747751b4c16b6c417920b46611c1c7de15caa648766225327b1886d8d3f",
          "sha1": "71dbb9853b749d65c3018fca483e22efe24998c9",
          "md5": "c0b598dc1db964986d410105dd2f7fc6"
        }
      ]
    }
  ]
}
