{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-process",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.5.0-beta01.aar",
          "url": "lifecycle-process-2.5.0-beta01.aar",
          "size": 10560,
          "sha512": "44c2966509fda7d7ca35bf6f064f844715a167cf1b412cf5c40e4e4db1290e15d6946284ec5483779ae66a6c28ef78ce1943c196fb0c32b33b2e2af7a6bd670d",
          "sha256": "20b190d07b1922f5993ef0a02f7b3941e71e70e65cb15ab245eafe5f3e1e2498",
          "sha1": "39c0aba2ebf41385a60ea635ae00997b1e05d816",
          "md5": "547a857fff957453d6ae92196aa8a070"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.5.0-beta01.aar",
          "url": "lifecycle-process-2.5.0-beta01.aar",
          "size": 10560,
          "sha512": "44c2966509fda7d7ca35bf6f064f844715a167cf1b412cf5c40e4e4db1290e15d6946284ec5483779ae66a6c28ef78ce1943c196fb0c32b33b2e2af7a6bd670d",
          "sha256": "20b190d07b1922f5993ef0a02f7b3941e71e70e65cb15ab245eafe5f3e1e2498",
          "sha1": "39c0aba2ebf41385a60ea635ae00997b1e05d816",
          "md5": "547a857fff957453d6ae92196aa8a070"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-process-2.5.0-beta01-sources.jar",
          "url": "lifecycle-process-2.5.0-beta01-sources.jar",
          "size": 5906,
          "sha512": "ce90d34c102d83719416317ec6329e10256c3a646f88afedab555f0a4957704876f8f13e086e78e5a4d734e5d1606b1e328c961e7418cfb3d0457d9c78fe7736",
          "sha256": "b40b16492aa34faed4e34fb19f8d12afb79715eeb8ef098df4c5713647cd1a42",
          "sha1": "8fccf25901f65172f1380c9abc6cbbabe809fe6a",
          "md5": "53d76930af8c714cd452d8736b32f67b"
        }
      ]
    }
  ]
}