{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-compose",
    "version": "2.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.6.0-alpha05.aar",
          "url": "lifecycle-runtime-compose-2.6.0-alpha05.aar",
          "size": 11850,
          "sha512": "20f6a475e72cb66b16aea5e093a1010d0b70a0410384151f415a6dc8e913487f9dce80ac5b37f3ddfc7d3cdc98e2fd977c79f8d23437d027332b286eaaa0054d",
          "sha256": "199cb2de58eec6f0418b69e2671798e63548abb1e736c756fea998b37e183f19",
          "sha1": "47b2c87e22487d553874a4555981568cd7b642f5",
          "md5": "7cd361376a3b255d14eef29d91b84bf6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.6.0-alpha05.aar",
          "url": "lifecycle-runtime-compose-2.6.0-alpha05.aar",
          "size": 11850,
          "sha512": "20f6a475e72cb66b16aea5e093a1010d0b70a0410384151f415a6dc8e913487f9dce80ac5b37f3ddfc7d3cdc98e2fd977c79f8d23437d027332b286eaaa0054d",
          "sha256": "199cb2de58eec6f0418b69e2671798e63548abb1e736c756fea998b37e183f19",
          "sha1": "47b2c87e22487d553874a4555981568cd7b642f5",
          "md5": "7cd361376a3b255d14eef29d91b84bf6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.6.0-alpha05-sources.jar",
          "url": "lifecycle-runtime-compose-2.6.0-alpha05-sources.jar",
          "size": 2157,
          "sha512": "10ac2fd95ba549e3a1684facaf6caae2248ff24541681aa23db2aa13d1b6d76e62f14c180865a84836007cda8f865146b1118d90c99b29b35c7cb2ec77cde361",
          "sha256": "dc61e56cf83fda48b6116e89f21846ec63d768d2e800ac0fe6993289c6dbe926",
          "sha1": "7f01a3a02a438ea53e95a9922ee61da155d4355a",
          "md5": "107d8a6aa18818fc9a42e3217acef789"
        }
      ]
    }
  ]
}