{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-compose",
    "version": "2.6.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.6.0-alpha02.aar",
          "url": "lifecycle-runtime-compose-2.6.0-alpha02.aar",
          "size": 12331,
          "sha512": "cd961e7ba86566bcdcc7dff9c7ad92254d71b11bf199373f5684eaee2ecbe63a4bbf71e20d3b6c1224f1906f7a1d0e58d69917e616a2e2d117284a660bafd6e5",
          "sha256": "c4c11059ae2e5be932b038725e1677be23127f60827b7f08d0cba0b9bf4a25f2",
          "sha1": "c58e0b7f5b63106b66bcb3cd7bc208cb37bca7e5",
          "md5": "3073bd544bec2f98f39ec00a81eed361"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "{androidx.LibraryVersions.LIFECYCLE}"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.6.0-alpha02.aar",
          "url": "lifecycle-runtime-compose-2.6.0-alpha02.aar",
          "size": 12331,
          "sha512": "cd961e7ba86566bcdcc7dff9c7ad92254d71b11bf199373f5684eaee2ecbe63a4bbf71e20d3b6c1224f1906f7a1d0e58d69917e616a2e2d117284a660bafd6e5",
          "sha256": "c4c11059ae2e5be932b038725e1677be23127f60827b7f08d0cba0b9bf4a25f2",
          "sha1": "c58e0b7f5b63106b66bcb3cd7bc208cb37bca7e5",
          "md5": "3073bd544bec2f98f39ec00a81eed361"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.6.0-alpha02-sources.jar",
          "url": "lifecycle-runtime-compose-2.6.0-alpha02-sources.jar",
          "size": 2893,
          "sha512": "480014d95a8c3eb4b4e2dd19dd26151bd35b54afff2966572ee13ece336362985cb48739fe1e6f32c805d2bdb82214b88eb24111431f65681370cce289be24e7",
          "sha256": "fbab6be35ba514d7d4ffe06a93744aab184633c481a889cde1a8003bfd1480d8",
          "sha1": "06fb45fc1344c9377520820d8879e9dab0a60e1d",
          "md5": "87f6f0cb4545c27d5cfaa045db75f169"
        }
      ]
    }
  ]
}