{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-ktx",
    "version": "2.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.4.0-beta01.aar",
          "url": "lifecycle-viewmodel-ktx-2.4.0-beta01.aar",
          "size": 3958,
          "sha512": "1103efb28ce541365a4e091f4e9d2997043866ad22ee8f5f7e4c8ec2e884e422e5d47c525a5edbbdaac54589bf4b926978e07eefdeb84b3e5dcb4b6c4fcd13d8",
          "sha256": "29c7be9bdbe5bfe8626c42a300245cf2bc1b6d43215ff968788a4d9b6f89d687",
          "sha1": "47051e7388fe57946069ea8e10abaeff25dc16cd",
          "md5": "46c3cf86931aa32386de965d33c59bb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.4.0-beta01.aar",
          "url": "lifecycle-viewmodel-ktx-2.4.0-beta01.aar",
          "size": 3958,
          "sha512": "1103efb28ce541365a4e091f4e9d2997043866ad22ee8f5f7e4c8ec2e884e422e5d47c525a5edbbdaac54589bf4b926978e07eefdeb84b3e5dcb4b6c4fcd13d8",
          "sha256": "29c7be9bdbe5bfe8626c42a300245cf2bc1b6d43215ff968788a4d9b6f89d687",
          "sha1": "47051e7388fe57946069ea8e10abaeff25dc16cd",
          "md5": "46c3cf86931aa32386de965d33c59bb3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.4.0-beta01-sources.jar",
          "url": "lifecycle-viewmodel-ktx-2.4.0-beta01-sources.jar",
          "size": 1410,
          "sha512": "bfe6372c5910f626e7b41bb6468d62612d1f1bde9b3c767caaa7eb7c07e93cf00d047d8e909b7c47f2985f42ffa554a82888f83e712473cee8756407fcc09548",
          "sha256": "8af8f2ac694742fe8ae133067dfdec6a193a738f46ba80c59b3e8a4ab36703f3",
          "sha1": "a900dc99643d8638beb02bd809a495f772d457e7",
          "md5": "43d89db66da712ab2560a41753632946"
        }
      ]
    }
  ]
}
