{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.1.0/kotlinx-serialization-json-1.1.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "u4iezisfpff7hc4f62xtsv27vi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.1.0.jar",
          "url": "kotlinx-serialization-json-jvm-1.1.0.jar",
          "size": 157490,
          "sha512": "2a67868418e06d8d841df6bbdf1c417a9fa5ee035dd98cef2a9da9679c76d454e37e913f25d6be17ccf62fb76dde8b2ed342a298fff2e5635e3bb4b4c91b8a31",
          "sha256": "cea6836d3a3990b7ac59f61a9534a0bf1c8d3932bd206080a3a13622ec7587d1",
          "sha1": "086c26030512eb057e02c9bfcfdfd9e2fbb82201",
          "md5": "7d91ba71192225347c9292cf41213d72"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.1.0.jar",
          "url": "kotlinx-serialization-json-jvm-1.1.0.jar",
          "size": 157490,
          "sha512": "2a67868418e06d8d841df6bbdf1c417a9fa5ee035dd98cef2a9da9679c76d454e37e913f25d6be17ccf62fb76dde8b2ed342a298fff2e5635e3bb4b4c91b8a31",
          "sha256": "cea6836d3a3990b7ac59f61a9534a0bf1c8d3932bd206080a3a13622ec7587d1",
          "sha1": "086c26030512eb057e02c9bfcfdfd9e2fbb82201",
          "md5": "7d91ba71192225347c9292cf41213d72"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json/1.1.0/kotlinx-serialization-json-1.1.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json",
        "version": "1.1.0"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json/1.1.0/kotlinx-serialization-json-1.1.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json",
        "version": "1.1.0"
      }
    }
  ]
}
