{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.3.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6558100"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha04.aar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha04.aar",
          "size": 7591,
          "sha512": "6a4ea4f56b9b72c2ad7bda12cae5c25eac51f8afe50b3083e8a56e754d4e84a387f2d3128931a46c85a32034cb651f8b475ff5dff29a650635d17721467b6f35",
          "sha256": "e4d33f96c97bb295b5ec59d2d39fdb2d7394ddf094aa5fb4c04234d1b03a9238",
          "sha1": "024705965cd7f5a24382e143454198d6a18585fb",
          "md5": "1954f1dce8e1a8a311d84abf8ef4c148"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha04.aar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha04.aar",
          "size": 7591,
          "sha512": "6a4ea4f56b9b72c2ad7bda12cae5c25eac51f8afe50b3083e8a56e754d4e84a387f2d3128931a46c85a32034cb651f8b475ff5dff29a650635d17721467b6f35",
          "sha256": "e4d33f96c97bb295b5ec59d2d39fdb2d7394ddf094aa5fb4c04234d1b03a9238",
          "sha1": "024705965cd7f5a24382e143454198d6a18585fb",
          "md5": "1954f1dce8e1a8a311d84abf8ef4c148"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.3.0-alpha04-sources.jar",
          "url": "lifecycle-runtime-testing-2.3.0-alpha04-sources.jar",
          "size": 1809,
          "sha512": "85d5e06438ec35aaeee972795ee55b315c3bee5bb5bdbeebdf09785dad5c73c003adad00a94e3cee71b820bd3f1df337f3290e8032e48bfb2a007e89badae94b",
          "sha256": "f97e2b220a76e4c873132978c3cf668e66b9e5299f3ae8fa0f647b85d16150d3",
          "sha1": "7952288ebf7757e9238984e4f927aed0ac5c6b6c",
          "md5": "c66286898d7af679c567208f7f42d3f2"
        }
      ]
    }
  ]
}
