{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.5.0-beta01.aar",
          "url": "lifecycle-viewmodel-savedstate-2.5.0-beta01.aar",
          "size": 34939,
          "sha512": "5f8bbbc2b9b90e85bcea154794737c23b58fd9893f5bc5aea9422bee1f7ffcb5aabf5ccc104d9a848af8fc952ff20886b677098a11128052a28e1a56ebeaa85c",
          "sha256": "e4a7732034f500aff161370e9d584af05138bcea0dd9b46ff787745eee468fc6",
          "sha1": "9a3d94574ffd471f4570725a02f1978bd72e147a",
          "md5": "b5f69f5d10e1e365749dcee7d4a49def"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.5.0-beta01.aar",
          "url": "lifecycle-viewmodel-savedstate-2.5.0-beta01.aar",
          "size": 34939,
          "sha512": "5f8bbbc2b9b90e85bcea154794737c23b58fd9893f5bc5aea9422bee1f7ffcb5aabf5ccc104d9a848af8fc952ff20886b677098a11128052a28e1a56ebeaa85c",
          "sha256": "e4a7732034f500aff161370e9d584af05138bcea0dd9b46ff787745eee468fc6",
          "sha1": "9a3d94574ffd471f4570725a02f1978bd72e147a",
          "md5": "b5f69f5d10e1e365749dcee7d4a49def"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.5.0-beta01-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-2.5.0-beta01-sources.jar",
          "size": 15813,
          "sha512": "1259b4b87e5a1f195e60c9ae54d9a044385adb5f72e6cbd57c69ca9f10bc3b406b880848c367adb9f29ebfe193d79c44a22a001e77ca0b3ed11f6e0ca44be14e",
          "sha256": "5cf43d3c8f67295f0f8330d9442ab0d871bef16d12f47817ecb517c373bbd980",
          "sha1": "011f7a8fab7793634b9cc07891180c35fbf4315c",
          "md5": "11e134c252cf46c84114a198fc48e3e2"
        }
      ]
    }
  ]
}