{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.6.0-alpha05.aar",
          "url": "lifecycle-runtime-2.6.0-alpha05.aar",
          "size": 21795,
          "sha512": "0511d3fae14094fb04e46a2cfb20fe9ad9d4d3774f8d8a530a23b8ef67fbde2a701ddaa431988c9d9796730a6a57bbe2a5228396757b89d9772301307b7b9604",
          "sha256": "034e1f6b46309c6e92a0cc3d53e98308c450d3a30977477981b86685c1c6d92d",
          "sha1": "b0f365ab8fdc5621be283ba33633366519d2441e",
          "md5": "32b3e257973cb0f3a32ff5f744d4ef24"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0-beta01"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.2.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.6.0-alpha05.aar",
          "url": "lifecycle-runtime-2.6.0-alpha05.aar",
          "size": 21795,
          "sha512": "0511d3fae14094fb04e46a2cfb20fe9ad9d4d3774f8d8a530a23b8ef67fbde2a701ddaa431988c9d9796730a6a57bbe2a5228396757b89d9772301307b7b9604",
          "sha256": "034e1f6b46309c6e92a0cc3d53e98308c450d3a30977477981b86685c1c6d92d",
          "sha1": "b0f365ab8fdc5621be283ba33633366519d2441e",
          "md5": "32b3e257973cb0f3a32ff5f744d4ef24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.6.0-alpha05-sources.jar",
          "url": "lifecycle-runtime-2.6.0-alpha05-sources.jar",
          "size": 8601,
          "sha512": "6063b882107bcf76e6280797ce65e860274a97fb32de8cd8c2a4e356f2a35313436dbe1b1cb254070a1c0820089c31e7ad93bd42f80b49d6a160d1d7600cb17f",
          "sha256": "07129c61c68a7c4333aeabe1712827c33677f973db29bc11b99044463899b13d",
          "sha1": "f653a171fc041d7062a83c81458c12f0201bcd6f",
          "md5": "40db71daf9d0b4f55bfa265236a651fa"
        }
      ]
    }
  ]
}