{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.4.0-rc01.aar",
          "url": "activity-ktx-1.4.0-rc01.aar",
          "size": 30003,
          "sha512": "59a49061da3eda908a9d5f51e34b2a816b0d1c6c05d2f795a86925e72f69d02d2f2a1a604c7c598adf10ce574cad141c4ae0dfea9efbe78dc2493f0a27f619ac",
          "sha256": "bd117936ec27aa33052348cbfcefd2fd5449dbad02daed919623870f890a2dcb",
          "sha1": "e24cd52186bc10b8b12074e6f0e50281141c606c",
          "md5": "5018b9a9ae8e9da3ea5f96648a945d23"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.4.0-rc01.aar",
          "url": "activity-ktx-1.4.0-rc01.aar",
          "size": 30003,
          "sha512": "59a49061da3eda908a9d5f51e34b2a816b0d1c6c05d2f795a86925e72f69d02d2f2a1a604c7c598adf10ce574cad141c4ae0dfea9efbe78dc2493f0a27f619ac",
          "sha256": "bd117936ec27aa33052348cbfcefd2fd5449dbad02daed919623870f890a2dcb",
          "sha1": "e24cd52186bc10b8b12074e6f0e50281141c606c",
          "md5": "5018b9a9ae8e9da3ea5f96648a945d23"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.4.0-rc01-sources.jar",
          "url": "activity-ktx-1.4.0-rc01-sources.jar",
          "size": 7767,
          "sha512": "5d813443ac6d811e43d27cb20da46ca2b00d8ae2b67d7afe0c1d8cc0426401fa3fa3931d18398dbffd4a802b1e7e00015f105fff8d06c3664081807d86ae3122",
          "sha256": "c82f0974410b4442695d84c4504cd93efb45adfce625ea469c8134e8679f0c7a",
          "sha1": "3906b867d26e0c0c6e60215a0925e3d2f0c016e2",
          "md5": "89fc20347b040f6cc077ac6fc9e9ff34"
        }
      ]
    }
  ]
}
