{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-ktx",
    "version": "2.6.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.6.0-beta01.aar",
          "url": "lifecycle-runtime-ktx-2.6.0-beta01.aar",
          "size": 61621,
          "sha512": "9a39f2c59494671457eba70b03ac4c5bd3bc138cc1d6f77f20ca8ad9562762b9c86c62d773d698f153e36e635192d3f5a0ca4fb884042d363644846737f75ab4",
          "sha256": "31dc5f1c8a1a1258709a21d768a7e649e19464660077da9313b73fbe94070fd0",
          "sha1": "335c33a73668eaf3458ee8d80eb1e9c1f5f30a17",
          "md5": "a0a52b4dc32ba206f91836013fa642ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.6.0-beta01.aar",
          "url": "lifecycle-runtime-ktx-2.6.0-beta01.aar",
          "size": 61621,
          "sha512": "9a39f2c59494671457eba70b03ac4c5bd3bc138cc1d6f77f20ca8ad9562762b9c86c62d773d698f153e36e635192d3f5a0ca4fb884042d363644846737f75ab4",
          "sha256": "31dc5f1c8a1a1258709a21d768a7e649e19464660077da9313b73fbe94070fd0",
          "sha1": "335c33a73668eaf3458ee8d80eb1e9c1f5f30a17",
          "md5": "a0a52b4dc32ba206f91836013fa642ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.6.0-beta01-sources.jar",
          "url": "lifecycle-runtime-ktx-2.6.0-beta01-sources.jar",
          "size": 7211,
          "sha512": "100fd52d3422a2b8d95ebcf26ea99ce1c8eeafc5ef6676fb37a030b35b36da617e45c56748c41d7f5b2061ff78735a29573b63715e66fdf82443e2a51b03b4b5",
          "sha256": "8503ed85cf65d200b9079e660a2b2c645cb322d74558034b08d364f0e349662a",
          "sha1": "6ad3251adb760573a519eebbdfb90fd2384b185d",
          "md5": "b30c0ae8153c899de498250c2a31db60"
        }
      ]
    }
  ]
}