{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-process",
    "version": "2.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.5.0-alpha05.aar",
          "url": "lifecycle-process-2.5.0-alpha05.aar",
          "size": 10563,
          "sha512": "6e52ef123029273cf9d788fe7cb206220ad99cd9d6863bc1692530bc039f012ec3f27aa967d9c07801a4f9e8d5493bdb211ee26ed42def9c69c2bc3fcdf033e7",
          "sha256": "2094cef33c8fa69961aca04c96637426c22becd5cdd35aaed7fe421d9cd0b515",
          "sha1": "e608ea5a2ab77203479de47675c8ceadaeecda2a",
          "md5": "2166dd7d516faa3ecebed89f12e4ae99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha05"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.5.0-alpha05.aar",
          "url": "lifecycle-process-2.5.0-alpha05.aar",
          "size": 10563,
          "sha512": "6e52ef123029273cf9d788fe7cb206220ad99cd9d6863bc1692530bc039f012ec3f27aa967d9c07801a4f9e8d5493bdb211ee26ed42def9c69c2bc3fcdf033e7",
          "sha256": "2094cef33c8fa69961aca04c96637426c22becd5cdd35aaed7fe421d9cd0b515",
          "sha1": "e608ea5a2ab77203479de47675c8ceadaeecda2a",
          "md5": "2166dd7d516faa3ecebed89f12e4ae99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-process-2.5.0-alpha05-sources.jar",
          "url": "lifecycle-process-2.5.0-alpha05-sources.jar",
          "size": 5906,
          "sha512": "ce90d34c102d83719416317ec6329e10256c3a646f88afedab555f0a4957704876f8f13e086e78e5a4d734e5d1606b1e328c961e7418cfb3d0457d9c78fe7736",
          "sha256": "b40b16492aa34faed4e34fb19f8d12afb79715eeb8ef098df4c5713647cd1a42",
          "sha1": "8fccf25901f65172f1380c9abc6cbbabe809fe6a",
          "md5": "53d76930af8c714cd452d8736b32f67b"
        }
      ]
    }
  ]
}