{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose-samples",
    "version": "2.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.4.0-beta01.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.4.0-beta01.aar",
          "size": 1768,
          "sha512": "7c8797d87e25e326b0d4ff27289c7b170d8c332ca671849a5b39b82cfe88dd21fd38be561a58fd88374f8539d99cbbd05020ad24369179037462318678ab2c0f",
          "sha256": "3f0cc372c939aa0853ff014c3d10f00cc94c270316e496b30893da69f37bb712",
          "sha1": "213a164775453445f808225451b0df63f50b4f4b",
          "md5": "47d85d89d12055519e510a98f3a5b420"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.4.0-beta01.aar",
          "url": "lifecycle-viewmodel-compose-samples-2.4.0-beta01.aar",
          "size": 1768,
          "sha512": "7c8797d87e25e326b0d4ff27289c7b170d8c332ca671849a5b39b82cfe88dd21fd38be561a58fd88374f8539d99cbbd05020ad24369179037462318678ab2c0f",
          "sha256": "3f0cc372c939aa0853ff014c3d10f00cc94c270316e496b30893da69f37bb712",
          "sha1": "213a164775453445f808225451b0df63f50b4f4b",
          "md5": "47d85d89d12055519e510a98f3a5b420"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-samples-2.4.0-beta01-sources.jar",
          "url": "lifecycle-viewmodel-compose-samples-2.4.0-beta01-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
