{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-common",
    "version": "3.0.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6602655"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-3.0.0-alpha02.jar",
          "url": "paging-common-3.0.0-alpha02.jar",
          "size": 618043,
          "sha512": "28366320566362deccd1059fe376ec93e6da82495d403cb263a3e7131d3e8488507fd05437da4386acc87bdbc4e6bda006d9f467f2f8cdeb17e840891ef5080d",
          "sha256": "027650c56fd059e9e78b42e4624ffea5e6a6835d4222ef7a5f3083eee20f00a1",
          "sha1": "e116d91113ee30bd49288e7039ff442af4c33a73",
          "md5": "27f0060ddbc537e9e0b46c165d8ce461"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-3.0.0-alpha02.jar",
          "url": "paging-common-3.0.0-alpha02.jar",
          "size": 618043,
          "sha512": "28366320566362deccd1059fe376ec93e6da82495d403cb263a3e7131d3e8488507fd05437da4386acc87bdbc4e6bda006d9f467f2f8cdeb17e840891ef5080d",
          "sha256": "027650c56fd059e9e78b42e4624ffea5e6a6835d4222ef7a5f3083eee20f00a1",
          "sha1": "e116d91113ee30bd49288e7039ff442af4c33a73",
          "md5": "27f0060ddbc537e9e0b46c165d8ce461"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-common-3.0.0-alpha02-sources.jar",
          "url": "paging-common-3.0.0-alpha02-sources.jar",
          "size": 116247,
          "sha512": "8666ba28fe97fa1fcf8fdeed435ca2548f31e5f1140e946590bdbd70dd2445f8b8b510509a5426f6224f6766403fdedade66d3d6c757e86affb8716e2c7774bf",
          "sha256": "055f0fc7b4e18ad26a0239740a0e25ef22e7b3ccb0693623af6bbc220389fae9",
          "sha1": "a1b31522f862deb63a89870d79fde031ba08c912",
          "md5": "8c566267565a040c94972360cb561ddb"
        }
      ]
    }
  ]
}
