{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate",
    "version": "2.3.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6558100"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.3.0-alpha04.aar",
          "url": "lifecycle-viewmodel-savedstate-2.3.0-alpha04.aar",
          "size": 14889,
          "sha512": "888619d039fa95b984a99ca98a62adf776a34eea5e7269a4417297ecb1b1cadec00a285b5919e7adcd10103f4d102aae8a4c7d34c433dae2b9efefb205cef730",
          "sha256": "73952862a834e494614dfcf80c85721ff232ecb9bcbc4f0ef6fcf47de7a0e489",
          "sha1": "dad7c55ef2ea0c6983affe252b3debacc2768969",
          "md5": "4f1ea4761c248d83abad4818b7f94da2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.3.0-alpha04.aar",
          "url": "lifecycle-viewmodel-savedstate-2.3.0-alpha04.aar",
          "size": 14889,
          "sha512": "888619d039fa95b984a99ca98a62adf776a34eea5e7269a4417297ecb1b1cadec00a285b5919e7adcd10103f4d102aae8a4c7d34c433dae2b9efefb205cef730",
          "sha256": "73952862a834e494614dfcf80c85721ff232ecb9bcbc4f0ef6fcf47de7a0e489",
          "sha1": "dad7c55ef2ea0c6983affe252b3debacc2768969",
          "md5": "4f1ea4761c248d83abad4818b7f94da2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.3.0-alpha04-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-2.3.0-alpha04-sources.jar",
          "size": 10268,
          "sha512": "e64538861b106b7289566e8bdb4ab52211a0d644924736e86b039df4202a8762242b0a053d2487aa91a3b47c0f140912c5df20254fac31afaf0097cf10c451e5",
          "sha256": "50c364793b6e7bbedcd23cb643733ea02def11e0f77bcc248eb14975df3e6b28",
          "sha1": "fd25ccd63974838a15015d34aa36b91a12bf8d5b",
          "md5": "eeac832f0b32a836d0406a025f086281"
        }
      ]
    }
  ]
}
